:experimental:
= QALIPSIS GUI

== Overview

The QALIPSIS GUI allows you to create, configure, run, monitor and view results of test campaigns from your browser.
You can configure campaigns and run them immediately, at a future time, or on a recurring schedule.

* You can view in-process campaign results in real time.
* You can view finalized reports of a previous campaign's data on static reports and on an interactive time-series chart.

The QALIPSIS GUI is available via open-source or by purchasing a Cloud subscription.

The open-source version includes the following features:


The Cloud version (via subscription) alows the user access to following additional features:


== Where to start

If you are new to QALIPSIS Cloud, you are encouraged to start by reading and understanding the following sections:

* <<Logging in to QALIPSIS>>
* <<Navigating QALIPSIS>>


== Configuring a running a campaign
The QALISIS GUI alows you to easliy configure andrun a campaign. +


* <<Working with series data and filters>>
* <<Configuring and running a campaign>>
** Creating a  campaign
** Adding scenarios to a campaign
** Running a campaign.
* <<Displaying campaign data>>
* Updating Settings
** Managing users and their permissions
** Creating and managing API Keys
** Managing subscriptions



== Logging in to QALIPSIS
. Navigate to the _QALIPSIS Welcome_ page according to the installation details provided by your administrator.
+
QALIPSIS Cloud is available at https://app.qalipsis.io.
. Enter your Username and Password.
+
If your user profile is eligible for several organizations, select the tenant to use from the drop down box.
+
. Click btn:[Submit] to log into QALIPSIS.

*Notes*::

* If a Tenant selection message is not displayed, you will be logged in to QALIPSIS with the tenant you were using in your most recent login.
* You can can select a different tenant at any time that you are logged into QALIPSIS, using the bottom-left panel.

== Navigating QALIPSIS
When you log into QALIPSIS, the _Home_ page of the GUI and a left sidebar are displayed.

=== Left Sidebar
* Near the top of the sidebar, a menu is displayed. The contents of the menu depends on your profile permissions.
+
From the displayed menu you have several options.

** <<Access campaign information and functions>>
** <<Access Series information and functions>>
// ** <<Access administrative functions>>
+
* Near the bottom of the sidebar, your user name is displayed with your current tenant.
Click  on the your name to display the _Tenant Modal_ window.
+
From the _Tenant Modal_ you have a few options.

** <<Change to a different tenant>>
** <<View/Update Your profile>>
** <<Change your password>>
** <<Logout>>

Note:: The left sidebar remains displayed throughout your session.

=== Change to a different tenant
. Click on your name near the bottom of the sidebar to open the _Tenant Modal_ window.
. Select an available tenant to use for the current session.

=== View/Update Your profile
. Click on your name at the bottom of the left sidebar to open the  _Tenant Modal_ window.
. Click on the `settings` icon.
. Click on `My profile` to open the _My Profile_ page.
. Make changes to your profile and click on `Save` in the top right corner of the screen

=== Change your password
. Click on your name at the bottom of the left sidebar to open the  _Tenant Modal_ window.
. Click on the `settings` icon.
. Click on `My profile` to open the _My Profile_ page.
. Click on `Change password`.
. Enter your new password in the `New Password` and `Comfirm Password` fields.
. Click on `Save changes` to save your new password.

=== Logout 
. Click on your name at the bottom of the left sidebar to open the _Tenant Modal_ window.
. Click on the `settings` icon.
. Click the btn:[Logout] button.
You will be logged out and returned to the _Welcome_ screen.

=== Access campaign information and functions 
The _Campaign_ page is accessible from the left side bar.
From the _Campaign_ page, you can view current or past campaign data and create a new campaign.

Further details are provided later in this documentation.

* <<Configuring and running a campaign>>
* <<Displaying campaign data>>

=== Access Series information and functions
Series are data sets that are preconfigured to monitor and display relevant campaign data.
The _Series_ screen is accessible from the left sidebar.
The _Series_ screen allows the user view current series information, update or duplicate a series, and create a new series.

Further details are provided later in this documentation.

* <<Working with series data and filters>>
* <<Creating a series>>
* <<Updating a series>>

// === Access administrative functions  
// From the left sidebar (if you have `Admin` permissions):

// . Click on *Admin* to display the _Users_ screen.
// . Click on a user's name to open the _Update User_ window.

// From the _Update User_ window, user information can be updated and modified and roles (permissions) set.

// More options will be available from the Admin area of the GUI in the near future.

== Working with series data and filters
Series are data sets that are preconfigured to monitor and display relevant campaign data.

* The logged events and meters can be graphically displayed
* You can create a series if your profile has write permissions.
* You can update a series if one of the following is true.
** You are the owner.
** The owner has shared it in write mode and you have write permissions.

=== Creating a series
From the Tenant sidebar:

. Click on `Series` to open the _Series_ page.
+
The _Series_  page displays a table listing currently defined series.
+
. Click the btn:[+New series] button near the top right corner of the page.
+
The _New series_ modal window opens.
. Enter the required data into the appropriate fields.
+
Note that only numeric fields can be used with an operation. The the other types, only the count of provided values can be configured.

. Click the btn:[Create] button.
+
The following text is displayed in the modal window: '[Series Name] has just been created!'.
. Close the  _New series_ modal window to return to the _Series_ page.
+
The newly created series is displayed in the table.

=== Updating a series
. Click on *Series* in the left sidebar menu.
+
The _Series_ page opens and displays a table listing currently defined series.
. Click on the name of the series you want to update.
+
The _Update series_ modal window opens.
. Enter the required data into the appropriate fields.
. Click the btn:[Update] button.
. Close the _Update series_ modal window to return to the _Series_ page.

== Configuring and running a campaign

. Click the btn:[+Campaign] button near the top right of the _Campaign_ page.
+
The _New Campaign_ window will open displaying the campaign name, a settings icon, a search field, and a table listing scenarios that are available to run in the campaign.


. Optionally, rename the campaign by hovering over the `New Campaign` title and selecting the pen icon to edit the name.

. Select the checkbox to the left of each scenario that you want to include in your campaign.
+
Each scenario has a default configuration.
+
. To configure a scenario to better suit your specific requirements, click the btn:[Configure] button to the right of the scenario.

. Update the fields on the _Scenario Configuration_ window.
. Click  *Apply* and close the window.
+
Scenario changes are saved for the current campaign and do not affect the scenario's default settings.

. Click the btn:[Run immediately] button to start the campaign.
+
Campaign data is displayed in real-time in the _Report_ panel and on the time-series chart.

** Minion count is displayed by default.
** Select one or more series cards to display the generated data for that series.

== Displaying campaign data

. Click on *Campaign* in the left sidebar.
+
A table listing all existing and planned campaigns is displayed.

* Click on any column title to sort the table by ascending/descending order.
* Search for a specific campaign by clicking on the magnifying glass icon near the top right of the screen and entering the name (or partial name) of the campaign.

. Click on the name of a campaign to display the _Campaign details_ page.
+
* A _Report_ panel is displayed at the top of the screen.
+
The top line in the _Report_ panel displays information for the  whole campaign; the following lines display information for each scenario within the campaign.
+
Click on the `Campaign Summary` dropdown filter to select which scenario(s) information to display in the report section.

