= What's new

QALIPSIS is designed with the scalability and simplicity required to perform load, efficiency and end-to-end verification on both distributed and stand-alone systems

With QALIPSIS:

* You can create scenarios with different branches and running with many minions.
* You can use its many native steps and plugins to fire load on your system and feed QALIPSIS with data to verify load strength.

QALIPSIS can run in embedded, standalone and distributed modes. It has the capability to log and save a history of events and metrics using various tools such as Elasticsearch, Graphite, TimescaleDB and InfluxDB.

In future QALIPSIS releases, you can expect an expansion of plugins, an increase in load injection steps and verification processes and various other improvements.

Feedback on this release, including bugs and suggested enhancements, is welcome and may be sent to the QALIPSIS team at https://github.com/qalipsis[Github, window=\"_blank\"].

== Version history

v0.15.a — Aug 2025: Initial release of QALIPSIS with support for distributed load testing and enhanced performance metrics.