= Configuration

QALIPSIS is extremely powerful and configurable.

To make it easy and fast to use, it comes with a default set of configuration, that might not exactly meet your requirements.

There are really many things you can configure, but do not be afraid.

We will get through this section and discover how easy it is to customize the execution of QALIPSIS.

By the way, have you already read the section about xref:installation/installation.adoc[Installing QALIPSIS]? Perhaps you should start up there...

Here is a small overview of the different parts composing this section:

- xref:configuration/basics.adoc[Basics] explains the principles of configurability in QALIPSIS and the most important parameters.
- xref:configuration/dependency-injection.adoc[Dependency injection] is rather for advanced user, and explains how to use the principles of configuration and injection of dependency (aka IoC) in your scenarios.
- xref:configuration/monitoring-test-campaigns.adoc[Monitoring test campaigns] will guide you through the steps required to store and use  analytics data generated the tests.

