= Introduction

== Overview
QALIPSIS is an enterprise-grade load and performance-testing tool especially designed for distributed systems. It is a step above other load test applications that merely evaluate your system internally.

* QALIPSIS is developer-centric with a low learning curve that makes it easy to use and extremely efficient.
* QALIPSIS is developed in Kotlin to gain the benefits of the Java ecosystem and provide seamless system performance.
* The basic out-of-the box QALIPSIS tool is completely free of charge.
+
Commercial-licensed-based plugins, the cloud-based application, and other premium extensions are not included in the basic out-of-the box QALIPSIS tool.
* QALIPSIS is designed to test the performance of distributed and monolith systems.
* QALIPSIS collects data from operating systems, databases, and monitoring tools.
* QALIPSIS cross-checks system metrics and performs data verification to ensure that the test systems is performing as expected. 

== Features
=== User-friendly interface
The QALIPSIS Graphical User Interface (GUI) allows users, depending on their role, to configure and run load tests with capabilities including, but not limited to:

* Start/Stop
* Configure the Load Distribution
* Increase/Decrease the Number of Simulated Users
* View Reports
* Schedule a Test 

=== Automation friendly performance verification
Using the Command Line Interface (CLI) or the Gradle plugin, you can automatically and repeatedly verify the condition and performance of your system.

=== Developer friendly plug-ins
Downloading a ready-to-use project for your IDE is made easier on QALIPSIS, consequently integrating with popular DevOps tools to test your software and track the impact of recent changes.

=== Aggregated assertions
Aggregated assertions allow you to verify the overall results on a scenario. You can define thresholds to make a test succeed or fail and immediately get insights about the performance and consistency of your tested system. 

=== Testing, performance, and geographical distribution
* QALIPSIS can test distributed systems.
* QALIPSIS can perform as a distributed system.
* QALIPSIS can simulate load from several geographic locations to run comparisons based on location. 
 
=== Live results 
QALIPSIS events and meters provide extended details of load-test operations, providing users with various options for accessing the results. The results visualizations and dashboards, with details of each test-case execution, provide valuable insight for identifying the bottlenecks in your applications and uncovering the components and conditions of failures.

=== Concurrent load simulations
QALIPSIS simulates the load from thousands to millions of users (e.g., website visitors, connected IoT devices, etc.) and cross-verifies successive values from different sources including requests, responses, infrastructure metrics, messaging platforms and databases.

=== Operating system independent
QALIPSIS load and performance testing can be performed from any operating system supporting Java with the same impressive results.

== Benefits
QALIPSIS was designed with distributed systems and current developer practices in mind. It provides a testing framework to allow developers to work in a real-world environment, writing and running load tests without a steep learning curve.

=== For developers 
QALIPSIS empowers developers to:

* Choose their own testing tools and preferred programming language for writing load-test scenarios.
* Cross-verify data from different sources: bring responses to requests, infrastructure metrics, middleware events and database records in the same port to compare them and verify that they match your expectations.
* Unlock the full power of the Java ecosystem by making use of any library, protocol or system.
* Reuse pieces of their own software to faster develop scenarios.
* Simulate users, third-party software and IoT devices.
* Simulate real-user and device behavior to make load tests more relevant.
* Generate detailed and relevant results by using distributed tracing markers to follow the complete execution workflow from end to end.
* Customize reports and dashboards.
* Perform tests on development machines, containers and virtual machines with excellent results.
* Integrate their standard DevOps workflow for performance testing before the deployment of health checks on production environments.
* Create a scenario in just a few minutes by enabling utilization of any Java library of choice (such as JUnit, Hamcrest, AssertJ) or pieces of software or proprietary libraries.
* Test non-http technologies using numerous plug-ins, such as databases and messaging platforms.

=== For IT operations teams
QALIPSIS provides IT Operations teams solutions to:

* Monitor how deployments and other IT operations can affect the availability and overall performance of the system.
* Expose bottlenecks and find correlations between load and resource consumption by unifying the verification of load-test and infrastructure metrics.
* Identify issues before users and customers do by verifying the size and configuration of the system's infrastructure.
* Examine how the system performs during normal and peak loads by running load tests from different geographic locations at varying times.
* Generate exceptional results on virtual engines, containers and conventional development machines.
* Allow for implementation and integration of verifications in their standard DevOps workflow.


