== Introduction

QALIPSIS is an open-source, enterprise-grade load and performance-testing tool especially designed for distributed systems.

QALIPSIS is a step above other load test applications that merely evaluate your system internally.

* QALIPSIS is developer-centric with a low learning curve that makes it easy to use and extremely efficient.

* QALIPSIS is developed in Kotlin to gain the benefits of the Java ecosystem and provide seamless system performance.

* QALIPSIS's open-source version is completely free of charge.
(Plugins, the cloud-based application, and other premium extensions are not included in the open-source version.)

* QALIPSIS is designed to test the performance of distributed and monolith systems.

* QALIPSIS collects data from operating systems, databases, and monitoring tools.

* QALIPSIS cross-checks system metrics and performs data verification to ensure that your systems is performing as expected. 

 
=== Features

==== User-friendly Interface
  
The QALIPSIS Graphical User Interface (GUI) allows users to drive straight forward test runs: start and stop, change the load distribution, and increase or decrease the number of simulated users.


==== Automation Friendly Performance Verification
Using the CLI or the Gradle plugin, you can automatically and repeatedly verify the condition and performance of your system.

==== Developer Friendly Plug-ins

Downloading a ready-to-use project for your IDE is made easier on QALIPSIS, consequently integrating with popular DevOps tools to test your software and track the impact of recent changes.

==== Aggregated Assertions
Aggregated assertions allow you to verify the overall results on a scenario. You can define thresholds to make a test succeed or fail and immediately get insights about the performance and consistency of your tested system. 

Testing, Performance, and Geographical Distribution

* QALIPSIS can test distributed systems.
* QALIPSIS can perform as a distributed system.
* QALIPSIS can simulate load from several geographic locations to run comparisons based on location. 
 
==== Live Results 
 
QALIPSIS events and meters provide extended details of load-test operations, providing users with various options for accessing the results. The results visualizations and dashboards, with details of each test-case execution, provide valuable insight for identifying the bottlenecks in your applications and uncovering the components and conditions of failures.

==== Concurrent Load Simulations

QALIPSIS simulates the load from thousands to millions of users (e.g., website visitors, connected IoT devices, etc) and cross-verifies successive values from different sources including requests, responses, infrastructure metrics, messaging platforms and databases.


==== Operating System Independent
QALIPSIS load and performance testing can be performed from any operating system supporting Java with the same impressive results.


=== Benefits

QALIPSIS was designed with distributed systems and current developer practices in mind. It provides a testing framework to allow developers to work in a real-world environment, writing and running load tests without a steep learning curve.

==== For Developers 
QALIPSIS empowers developers to:

* Choose their own testing tools and preferred programming language for writing load-test scenarios.

* Cross-verify data from different sources: bring responses to requests, infrastructure metrics, middleware events and database records in the same port to compare them and verify that they match your expectations.

* Unlock the full power of the Java ecosystem by making use of any library, protocol or system.

* Reuse pieces of their own software to faster develop scenarios.
* Simulate users, third-party software and IoT devices.
* Simulate real-user and device behavior to make load tests more relevant.
* Generate detailed and relevant results by using distributed tracing markers to follow the complete execution workflow from end to end.
* Customize reports and dashboards.
* Perform tests on development machines, containers and virtual machines with excellent results.
* Integrate their standard DevOps workflow for performance testing before the deployment of health checks on production environments.

* Create a scenario in just a few minutes by enabling utilization of any Java library of choice (such as JUnit, Hamcrest, AssertJ) or pieces of software or proprietary libraries.

* Test non-http technologies using numerous plug-ins, such as databases and messaging platforms.

==== For IT Operations Teams
QALIPSIS provides IT Operations teams solutions to:

* Monitor how deployments and other IT operations can affect the availability and overall performance of the system.
* Expose bottlenecks and find correlations between load and resource consumption by unifying the verification of load-test and infrastructure metrics.
* Identify issues before users and customers do by verifying the size and configuration of the system's infrastructure.
* Examine how the system performs during normal and peak loads by running load tests from different geographic locations at varying times.
* Generate exceptional results on virtual engines, containers and conventional development machines.
* Allow for implementation and integration of verifications in their standard DevOps workflow.



=== Core Concepts
Boasting a high degree of flexibility, QALIPSIS allows users to configure and execute seamless campaigns that test specific features of their system. 

To achieve this, QALIPSIS brings the following core concepts together: 

* Scenarios - The single largest components of a QALIPSIS load test.

* Steps - The central atomic components within each scenario. 

* Assertions - Steps that perform cross-checks of data, execution states and durations from different sources. 

* Minions - Virtual actors simulating website users, IoT devices, or other systems that interact with the test system to inject load and verify behavior performance.
 
* Head - The component of a cluster that is responsible for orchestration and reporting.

* Factories - The distributed components of a cluster which host the minions to execute the load tests and assertions. 
 
These concepts are discussed in detail in the Qalipsis Core Concepts Section. Add a link!!!!

Once you have a minimal understanding of the core concepts, you will be ready to create a QALIPSIS "Hello World" scenario to  verify that your software is performing as expected.
