
== QALIPSIS Core Concepts and Operators
=== Core Concepts

The aim of QALIPSIS is to execute actions that inject load into IT systems to monitor and validate their behaviors (latency, failure rates, availability, and data consistency.

The actions are performed by minions that are injected into a system and then run through a preconfigured scenario consisting of steps and assertions. If running QALIPSI on a distributed system, you can create clusters with Head and Factory nodes to inject load.

Before attempting to configure QALIPSIS to run on your system, it is important to understand the core concepts of the tool:

* Minions
* Scenarios
* Steps
* Assertions
* Head
* Factory
 

==== Minions
Minions are simulations of website users, IoT devices, or other systems. They each perform a complete scenario.


Any number of minions can act on a scenario. The minion count for a scenario is set during scenario configuration (refer to _<Scenario Configuration>_ or at runtime (refer to _<QALIPSIS Configuration>_.  If a minion count is entered at runtime, that count overrides the minion count set during scenario configuration.
   

==== Scenarios

A QALIPSIS scenario is the single largest component of a load test. It contains steps with a detailed description of all the operations to accomplish, their dependencies, as well as assertions to ensure everything performs as expected.

A simple scenario configuration includes the following:

. *Call the scenario function.* 
+

* Mandatory 

* QALIPSIS Signature:  _@Scenario_


. *Assign the scenario a name.*
+
* Mandatory
* Value: alphanumeric string
* QALIPSIS Signature:  _val myScenario = scenario("scenario name")_

. *Define the total # of minions to be executed.*
+

* Optional
* numeric string
* Value: positive number
* Default = 1; Minimum = 0
* QALIPSIS Signature: _minionsCount = xxxxx_


. *Define the ramp-up strategy.*
+

* Mandatory
* QALIPSIS Signature: _rampUP {strategy( )}_


. *Define the tree where the load will be injected.*
+
* Mandatory
* QALIPSIS Signature: _start()_

. *Call Scenario dependencies.*
+
* Mandatory
* QALIPSIS Signature: 
[source,kotlin,linenumbers]
import com.github.jengelman.gradle.plugins.shadow.tasks ShadowJar 
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

. *Call Scenario plugins.*
+
* Mandatory
* QALIPSIS Signature: 
[source,kotlin,linenumbers]
plugins {
application kotlin("jvm") kotlin("kapt")
id("com.github.johnrengelman.shadow") version "6.0.0" 
 }
. *Add steps to your scenario.*


==== Steps

Steps are the central components for working with QALIPSIS and can be developed in Kotlin, Groovy or Java, using either JUnit-like classes or the fluent API. 

Steps depend on data sources, results of other steps or assertions to execute or use their data.

There are two ways of configuring a step specification: 

* The step receives the configuration closure as a parameter. 
* You can call configure after a step to configure it:
 
Each step has a unique configuration depending on the purpose of the step. Steps are configured using core operators:

* Assertions
* Timing
* Creating
* Conditional
* Converting
* Error Handling
* Filtering
* Joining
* Mathematical/Aggregate
* Transforming
* Utility
* User-defined

Refer to <Operators>  

==== Assertions (needs Work)
Assertions perform cross-checks within the scenario by:
* Providing validation of data persistence, message exchanges, and requests to remote systems. 
* Setting and testing durations to verify the system’s overall responsiveness.


There are several types of assertions, the most common being:

* A precondition assertion that is placed at the beginning of a section of code and determines the set of states under which the programmer expects the code to execute.

* A postcondition assertion that is placed at the end of a section of code and describes the expected state at the end of execution. 

* A static assertion???


Assertion parameters include: 

 * Duration  - set and tested in order to verify the overall responsiveness of the system.

 

==== Node
A node is a redistribution point or a communication endpoint within a QALIPSIS cluster. QALIPSIS nodes are designated as either a Head or a Factory.

===== Head
The head is a node of a QALIPSIS cluster that is responsible for orchestration and reporting.

===== Factory
The factory is a node of a QALIPSIS cluster that hosts the minions to execute the load tests and assertions. 

=== Operators
QALIPSIS provides operators to either create or configure a scenario or a step. Some operators are provided for common use cases; plugins bring other operators to extend the scope of the features you can use.

QALIPSIS operators can be grouped by type:

* Creating
* Conditional
* Converting
* Error Handling
* Filtering
* Joining
* Mathematical/Aggregate
* Transforming
* Utility

[cols="1,1,2,2,2"]
|===
|*Operator*
|*Type*
|*Function*
|*QALIPSIS Signature*
|*Example*

|Configure
|Creating
|
|
|

|Iterate
|Creating
|Repeats
|_iterate(Minions Count, Duration.ofMillis())_
|Injects 200 minions every 2 ms:
_iterate(200, Duration.ofMillis(2))_

|Interval
|Creating
|
|
|

|Scenario
|Creating
|Calls a scenario
|@scenario
|

|FlatMap
|Transforming
|
|
|

|map
|Transforming
|
|
|

|Delay
|Utility
|
|
|



