
== QALIPSIS Core Concepts 

Once you have a minimal understanding of the core concepts, you will be ready to create a QALIPSIS "Hello World" scenario to  verify that your software is performing as expected.


The aim of QALIPSIS is to execute actions that inject load into IT systems to monitor and validate their behaviors (latency, failure rates, availability, and data consistency.

The actions are performed by minions that are injected into a system and then run through a preconfigured scenario consisting of steps and assertions. If running QALIPSI on a distributed system, you can create clusters with Head and Factory nodes to inject load.

Before attempting to configure QALIPSIS to run on your system, it is important to understand the core concepts of the tool:

* Minions
* Scenarios
* Steps
* Assertions
* Head
* Factory
 

=== Minions
Minions are simulations of website users, IoT devices, or other systems. They each perform a complete scenario.


Any number of minions can act on a scenario. The minion count for a scenario is set during scenario configuration (refer to _<Scenario Configuration>_ or at runtime (refer to _<QALIPSIS Configuration>_.  If a minion count is entered at runtime, that count overrides the minion count set during scenario configuration.
   

=== Scenarios

A QALIPSIS scenario is the single largest component of a load test. It contains steps with a detailed description of all the operations to accomplish, their dependencies, as well as assertions to ensure everything performs as expected.
A simple scenario configuration includes the following:

. Call to the scenario function.

** Mandatory
** QALIPSIS Signature: `@Scenario`

. Assign the scenario a name.
** Mandatory
** Value: alphanumeric string
** QALIPSIS Signature: `val myScenario = scenario("scenario name")`

. Define the total # of minions to be executed.
** Optional
** Value: positive number
** Default = 1; Minimum = 0
** QALIPSIS Signature: `minionsCount = xxxxx`
. Define the ramp-up strategy.
** Mandatory
** QALIPSIS Signature: `rampUP {strategy( )}`

. Define the tree where the load will be injected.
** Mandatory
** QALIPSIS Signature: `start()`

. Call Scenario dependencies.
** Mandatory
** QALIPSIS Signature:
+
`import com.github.jengelman.gradle.plugins.shadow.tasks ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile`

. Call Scenario plugins.
** Mandatory
** QALIPSIS Signature: 
+
`plugins {
 application kotlin("jvm") kotlin("kapt")
id("com.github.johnrengelman.shadow") version "6.0.0"
 }`

. Add steps to your scenario.



=== Steps

Steps are the central components for working with QALIPSIS and can be developed in Kotlin, Groovy or Java, using either JUnit-like classes or the fluent API. 

Steps depend on data sources, results of other steps or assertions to execute or use their data.

There are two ways of configuring a step specification: 

* The step receives the configuration closure as a parameter. 
* `.configure` is called after the step parameters are set.

Refer to <Steps-> Configuring Step Specifications> for more details.  

 
Each step has a unique configuration depending on the purpose of the step:

Steps are configured using core operators:

* Assertions
* Timing
* Creating
* Conditional
* Converting
* Error Handling
* Filtering
* Joining
* Mathematical/Aggregate
* Transforming
* Utility
* User-defined

Refer to <Steps-> Operators>  

=== Assertions 
Assertions perform cross-checks within the scenario by:

* Providing validation of data persistence, message exchanges, and requests to remote systems. 
* Setting and testing durations to verify the system’s overall responsiveness.


There are several types of assertions, the most common being:

* A precondition assertion is placed at the beginning of a section of code and determines the set of states under which the programmer expects the code to execute.
* A postcondition assertion is placed at the end of a section of code and describes the expected state at the end of execution.
* A static assertion checks if a condition (a constant expression) is true when the code is compiled. If the condition is not true, the compiler issues an error message and stops the compiling process. 



=== Node
A node is a redistribution point or a communication endpoint within a QALIPSIS cluster. QALIPSIS nodes are designated as either a Head or a Factory.

==== Head
The head is a node of a QALIPSIS cluster that is responsible for orchestration and reporting.

==== Factory
The factory is a node of a QALIPSIS cluster that hosts the minions to execute the load tests and assertions. 

