
= QALIPSIS Project Deployment 

== Overview

There are several ways to install, operate and use QALIPSIS, depending on your use case, load needs and IT-landscape complexity.

This section discusses different approaches, including the benefits and consequences of each approach.

If you find yourself in a situation that requires professional support to assist in the preparation, installation and operation phases, do not hesitate to contact our team at https://qalipsis.io/#contact. 

== Embedded
It is extremely simple to use QALIPSIS as an embedded service into your existing JVM applications.

Using QALIPSIS as an embedded service is convenient for execute campaigns in your tests (JUnit or others) or to create your own applications that can trigger campaigns.

It requires only three steps:

. Add the dependencies to run QALIPSIS and develop your scenario.
+
[source,kotlin,linenumbers]
----
dependencies {
    implementation(platform("io.qalipsis:qalipsis-platform:<version>"))
    kapt("io.qalipsis:api-processors")
    
    runtimeOnly("io.qalipsis:head")
    runtimeOnly("io.qalipsis:factory")
    implementation(test"io.qalipsis:runtime")
    
    // Examples of plugins
    implementation("io.qalipsis.plugin:cassandra")
    implementation("io.qalipsis.plugin:jackson")
}
----

. Develop your scenario.
+
[source,kotlin,linenumbers]
----
import io.qalipsis.api.annotations.Scenario
...

class My Scenario {

    @Scenario("do-something-useful") // Do not forget the annotation!
    fun doSomethingUseful() {
        scenario {
            minionsCount = 10_000
            profile {
                stages {
                  ...
                }
            }
        }.start()
        ....
    }
}
----
. Start QALIPSIS in your application:
+
[source,kotlin,linenumbers]
----
Qalipsis.main("-s", "do-something-useful", "-c", "myconfig=thevalue", "my-other-args")
----
Alternately, you can use the following method:
.. Import the test fixtures module for the runtime
+
[source,kotlin,linenumbers]
----
dependencies {
    implementation(platform("io.qalipsis:qalipsis-platform:<version>"))
    kapt("io.qalipsis:api-processors")

    runtimeOnly("io.qalipsis:head")
    runtimeOnly("io.qalipsis:factory")
    implementation(test"io.qalipsis:runtime")
    implementation(testFixtures("io.qalipsis:runtime")) // Here is the additional dependency.
    
    // Examples of plugins
    implementation("io.qalipsis.plugin:cassandra")
    implementation("io.qalipsis.plugin:jackson")
}
----

.. Use the builder to start QALIPSIS
+
[source,kotlin,linenumbers]
----
QalipsisTestRunner.withScenarios("do-something-useful")
    .withConfiguration("myconfig=thevalue")
    .execute("my-other-args")
----

== Ephemeral

Ephemeral installations of QALIPSIS are designed to be directly embedded into third-party tools or for use in continuous integration/continuous deployment (CI/CD) applications.

However, the ease of build and lightness of an ephemeral installation makes it a very portable alternative for verifying test systems and performing demos. 
 
The QALIPSIS Gradle Plugin provides the task `package-ephemeral` to create an archive of your project.

To configure an ephemeral installation for project deployment:

* In your QALIPSIS project, execute the task `package-ephemeral` which will assemble your project and create an archive file: `build/install/your-project-name-your-version-qalipsis.jar`.
+ 
The .jar file is a self-executable archive that contains your scenario, classes, and all required dependencies to execute your QALIPSIS project. 

* Check that Java Runtime Environment 11+ is installed on your system as it is required to execute the archive.
* Move the archived file to your folder of choice; navigate to that folder.
* If operating on a Windows system, run `java -jar your-project-name-your-version-qalipsis.jar --autostart`. 
* If operating on a Linux, Unix or Mac system:
. Run `chmod +x your-project-name-your-version-qalipsis.jar` 
. Run `java -jar your-project-name-your-version-qalipsis.jar --autostart`

* QALIPSIS starts, executes the scenario(s) in the project, and quits. 
* The results of the project are displayed on the console but are not saved to QALIPSIS.
* To save the results, export them to a file(s) using any of our exporters such as JUnit.

If you want to tweak the configuration, create and include in your project a `qalipsis.yml` or `config/qalipsis.yml` file that contains the part of the configuration that you want to overwrite. 

Note that the `config/qalipsis.yml` file has precedence over the `qalipsis.yml` if both are present in the configuration.

If any of your use cases includes data that you want to retain in QALIPSIS for comparison, regression testing, or other use, you should use QALIPSIS in a non-persistent standalone installation.  

== Transient
=== Overview
Transient installations of QALIPSIS are designed for operations that do not need to keep a history of data. The most often used cases for transient installations include:

* Continuous integration/continuous deployment (CI/CD) workflows where only the success or failure of the execution determines if the data passes through the quality gates.
* End-to-end testing that does not require a history of data.

A transient installation is not a long-live process.

* QALIPSIS starts a campaign execution on demand and stops immediately after the campaign's completion. 
* To keep external logs of the campaign execution, export the results as a file or to a third-party platform.

If any of your use cases includes data that you want to retain in QALIPSIS for comparison, regression testing, or other use, you should use QALIPSIS in a non-persistent standalone installation.  

=== Configuring a transient installation for project deployment
 
The QALIPSIS Gradle Plugin provides tasks to create an installable archive from your project. It proposes a unique task to create a ZIP archive and a TAR.GZ archive. The installation is similar whether using a ZIP archive or a TAR.GZ archive; installation using a ZIP archive are described in this section.

In your QALIPSIS project, execute the task `package-standalone` which will assemble your project and create a ZIP file: `build/install/qalipsis-your-project-name.zip`.

The ZIP archive contains your scenario, classes, and all required dependencies to execute your QALIPSIS project.

* Add the ZIP archive to your installation folder of choice and extract the compressed files: `unzip qalipsis-your-project-name.zip`. 

* Navigate to the QALIPSIS folder on your system:

 ** Linux, Unix or Mac systems:`/your/installation/folder/qalipsis-your-project-name` 
 ** Windows systems:`C:\your\installation\folder\qalipsis-your-project-name on Windows`

* Start QALIPSIS:
** On Linux, Unix or Mac systems: 

. Run `chmod +x -R`
. Run `./qalipsis.sh --autostart`

** On Windows systems:
. Run `qalipsis.bat --autostart`

An additional argument is not required, as the transient, non-persistent execution, is the default.

* QALIPSIS starts, executes the scenario(s) in the project, and quits.

* The results of the project are displayed on the console but are not saved to QALIPSIS.

* To save the results, export them results to a file(s) using an exporter such as JUnit.

If you want to tweak the configuration, create and include in your project a `qalipsis.yml` or `config/qalipsis.yml` file that contains the part of the configuration that you want to overwrite.

Note that the `config/qalipsis.yml` file has precedence over the `qalipsis.yml` if both are present in the configuration.

If any of your use cases includes data that you want to retain in QALIPSIS for comparison, regression testing, or other use, you should use QALIPSIS in a non-persistent standalone installation.

== Standalone

=== Overview
Standalone installations of QALIPSIS are designed for low to normal load operations that require data tracking. They allow you to tweak the deployment configuration to track the history of executions. 

A standalone installation:
* Executes all QALIPSIS components as in a transient installation.
* Provides durability in data and history tracking.
* Provides REST endpoints to interact with QALIPSIS.

QALIPSIS stores the master data and the time-series data generated by the scenario (events, meters) in separate databases. The master data requires transactional consistency and the time-series data requires high throughput and strong calculation capabilities. Separate databases allow for the different requirements.  

For sake of simplicity, this guide will use http://postgresql.org[PostgreSQL] for both groups of data.  

If you want to configure a different database for the time-series data, refer to the applicable plugin section for details (`elasticsearch`, `influxDB`, `timescaleDB`, and `graphite` are currently supported).
 
This section will guide you through the configuration of a <<Transient>> installation to a persistent standalone installation.

While this installation requires the installation of a PostgreSQL database, we will not go into those details which are provided in the official http://postgresql.org[PostgreSQL] documentation.

=== Prepare the installation
Execute the following steps as for a <<Transient>> installation:

* In your QALIPSIS project, execute the task `package-standalone` to create a ZIP file: `build/install/qalipsis-your-project-name.zip`.

* Add the ZIP archive to your installation folder of choice and extract the compressed files: `unzip qalipsis-your-project-name.zip`. 

=== Prepare the database
* Install your PostgreSQL database
* Create a user with the name `qalipsis`. 
* Create a database with the name `qalipsis`. 
* Connect to the database `qalipsis` with your admin user (generally `postgres`).
* Execute the following:
+
[example,kotlin, linenumbers]
----
CREATE SCHEMA qalipsis_liquibase IF NOT EXISTS;
ALTER SCHEMA qalipsis_liquibase OWNER TO qalipsis;
CREATE SCHEMA qalipsis IF NOT EXISTS;
ALTER SCHEMA qalipsis OWNER TO qalipsis;

CREATE SCHEMA events AUTHORIZATION qalipsis;
GRANT ALL ON SCHEMA events TO qalipsis;

CREATE SCHEMA meters AUTHORIZATION qalipsis;
GRANT ALL ON SCHEMA meters TO qalipsis;
---- 

=== Configure the database for the master data
* Navigate to your installation folder where the  `qalipsis.sh` and `qalipsis.bat` files are located.
* Create a `qalipsis.yml` file to configure access to the database for the master data:
+
[source,kotlin, linenumbers]
----
datasources:
  default:
    url: jdbc:postgresql://your-database-host:5432/qalipsis <1>
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    maximumPoolSize: 4      <2>
    minimumIdle: 2
----
<1> Replace the `host`, `port`, `username`, and `password` values with the appropriate values for you configuration.
<2> The `maximumPoolSize` and `minimumIdle` are the REST endpoints and depend on your number of users. Increase the value of `maximumPoolSize` if you observe errors or a high latency when using the REST endpoints.

=== Configure the database for the events and meters
The connection to PostgreSQL for events and meters is provided by the timescale plugin, which is embedded by default in all the head, transient and standalone installation you will build with the QALIPSIS Gradle plugin.

In the file qalipsis.yml add the following details:

[source,kotlin,linenumbers]
----
events: 
  export.timescaledb:  <1>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters

  provider.timescaledb: <2>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters
    
meters:
  export.timescaledb: <3>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters

  provider.timescaledb: <4>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters
----
<1> Export the events to PostgreSQL.
<2> Render the events from PostgreSQL.
<3> Export the meters to PostgreSQL.
<4> Render the meters from PostgreSQL.

=== Start QALIPSIS

Navigate to the QALIPSIS folder on your system:

* Linux, Unix or Mac systems:`/your/installation/folder/qalipsis-your-project-name`

* Windows systems:`C:\your\installation\folder\qalipsis-your-project-name on Windows`

Start QALIPSIS:

* On Linux, Unix or Mac systems: 
. Run `chmod +x -R`
. Run `./qalipsis.sh --autostart`

* On Windows systems:
+
Run `qalipsis.bat --autostart`

QALIPSIS will start and provide REST endpoints on port 5432.

Open source QALIPSIS OSS does not support native security. For a native secured installation, we encourage you to https://qalipsis.io/#contact[contact] the QALIPSIS team to request a license for QALIPSIS Enterprise. 

== Cluster Installations 
=== Overview
Clusters provide a scalable and durable installation of QALIPSIS, allowing increased load needs, more scenarios and more users. 

In a cluster, QALIPSIS is split into several components which collaborate using third-parties systems to exchange data.

Heads are the components users use to interact with QALIPSIS.
Factories are hidden and inaccessible to users. Factories only initiate outbound connections which allows them to securely run behind firewalls without limitation.

Heads should remain active permanently to provide the best user experience. 
Factories can remain active or come and go on demand without limiting the campaign results analysis.

Clusters can also be deployed in https://kubernetes.io/docs/concepts/security/[Kubernetes] or https://www.redhat.com/en/technologies/cloud-computing/openshift[OpenShift] or in a hybrid system with some factories on physical machines and others on virtual machines.

The following sections describe how to install QALIPSIS as clusters of different forms that provide different levels of scalability and availability.

=== Light cluster
A light cluster requires minimal effort for installation; however, it is limited in terms of load capability.

The main advantage of a light cluster installation is to provide a secure geographical/network-based distribution of load and data consumption for private networks.

A light cluster consists of:

* One instance of a head.
* Several instances of factories.
* A PostgreSQL database.
* A Redis instance (or a Redis cluster) to host shared data and exchange messages between the QALIPSIS head and factories.

=== High-load cluster
A high-load cluster requires significant effort for installation and operation; however, it is extremely scalable.

NOTE::
A high-load cluster is only possible for enterprise installations.  If you are interested in deploying a  high-load cluster, https://qalipsis.io/#contact[contact] the QALIPSIS team to request a license for QALIPSIS Enterprise.

A high-load cluster consists of:

* One instance of a head.
* Several instances of factories.
* A PostgreSQL database.
* One or more clusters of databases for the time-series data.
* A Redis cluster to host shared data.
* A Kafka cluster to exchange messages between the QALIPSIS head and factories.


== Amendable installations
The purpose of an amendable installation is to allow you to add scenarios to the installation without having to rebuild a new installation archive after each change.

As a prerequisite, you need to install QALIPSIS as described in the <<Transient installations,`transient`>>, <<Standalone Installations,`standalone`>> or <<Cluster Installations,`cluster`>> installation sections. 

When packaging an installation, you do not need to create a scenario for the project. An "empty" installation is a valid installation. Executing QALIPSIS on an "empty" installation will return an exit code different from 0 and a `no scenario found` warning.

When your QALIPSIS installation is complete:

. Create a new QALIPSIS project using the QALIPSIS Gradle plugin
. Create a scenario in your project. 
. Add implementation or runtime dependencies to your Gradle project, as you would with any Gradle project.
. Execute the task `package-scenario` on your Gradle module, which will assemble your project and create a ZIP file:
+
`build/scenario/qalipsis-scenario-your-project-name.zip`
+
This archive contains your scenario and all the non-QALIPSIS dependencies you have manually added to your Gradle project.
. Copy and paste the archive to a folder with an existing installation of QALIPSIS transient, standalone or factory of a cluster.
. Extract the compressed files: `unzip qalipsis-scenario-your-project-name.zip`.
. Copy each file in the expanded folder into the folder with scenarios of your existing installation.
. If it is still running, restart QALIPSIS to load the new scenarios.

:warning: WARNING
Different scenarios might require different dependencies; pay attention to the conflict of versions when you overwrite existing files in an existing installation.

To avoid conflicts, use the same versions of dependencies across all scenarios/projects deployed in the same installation.

== Containers
Docker images from QALIPSIS work like prepared installations that you can amend with your own scenarios and configuration.

Three images are available on the Docker hub free to all QALIPSIS users: 

* `qalipsis-oss:<version|latest>` to start a container as a transient or standalone application.

* `qalipsis-oss-head:<version|latest>` contains only the components to execute a head in a cluster.

* `qalipsis-oss-factory:<version|latest>` contains only the components to execute a factory in a cluster.

=== Prepare the images
While the images available on the Docker hub are ready to use, empty standalone and factory images cannot do much for you.

You can add your own scenarios and dependencies as prepared for an <<Amendable installations,Amendable installation>> with the following Docker file:

[example,kotlin, linenumbers]
----
from qalipsis-oss:latest

ADD build/scenario/qalipsis-scenario-your-project-name.zip /opt/qalipsis
----
=== Where can you use the images?
All of the images are tested to run as https://www.docker.com/[Docker], https://kubernetes.io/[Kubernetes] or https://www.redhat.com/en/technologies/cloud-computing/openshift[OpenShift] containers and can be configured with additional program arguments or a mounted configuration file.

You can refer to the official documentation for each platform to learn how to attach a configuration file and arguments to the execution of QALIPSIS.


 

 


