== Quickstart


This section will guide you through:

* Downloading and installing QALIPSIS 1.0 on your system.
* Creating a new project.
* Settiing up your IDE.
* Creating and configuring a QALIPSIS scenario.
* Specifing the load injection point 
* Adding steps to your scenario
* Running yours Scenario


NOTE: Before getting started, confirm that you have Java 11 (or above) SDK installed on your workstation. 

=== Downloading and Installing QALIPSIS to your system.

The first step, of course,  is to download and unpack the current version of QALIPSIS.


=== Creating a Project

Once Qalipsis is installed on your system,  create a project for Gradle with your IDE, using the Kotlin DSL.


Import the QALIPSIS executable file:
[source,kotlin,linenumbers]
----
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar 
//The QALIPSIS executable file  is packaged as a "fat JAR'; it uses the shadow plugin and contains all all of the dependencies required to run QALIPSIS and your scenario.//
----
Import the Kotlin Compiler:
[source,kotlin,linenumbers]
----
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile //Kotlin Compiler//
----
Import QUALIPSIS plugins:
[source,kotlin,linenumbers]
----
plugins {
    application //provide description//
    kotlin("jvm") //provide description//
    kotlin("kapt") //provide description//
    id("com.github.johnrengelman.shadow") version "6.0.0" //provide description//
}
----
Assign your project a name:
[source,kotlin,linenumbers]
----
description = "QALIPSIS  Quickstart" 
// replace _QALIPSIS Quickstart_ with "your project name"//
----
Configure compileKotlin and compileTestKotlin:
[source,kotlin,linenumbers]
----
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.majorVersion
        javaParameters = true
    }
}
----
Call Scenario  dependencies:
[source,kotlin,linenumbers]
----
dependencies {
    implementation(kotlin("stdlib")) 
    //required to develop scenarios with Kotlin//
   
    implementation("io.qalipsis:api-dsl:{revnumber}") 
    //required to develop scenarios for QALIPSIS, indepenent of language//

    implementation("com.willowtreeapps.assertk:assertk:2.0.3") 
    implementation("com.willowtreeapps.assertk:assertk-jvm:2.0.3") 
    //assertion libraries required to verify data in a scenarion; use JUnit, AssertJ or AssertK, Hamcrest, or any other library you are familiar with.//


    runtimeOnly("io.qalipsis:runtime:{revnumber}") 
    //required to execute QALIPSIS, either as a head or factory.//

    kapt("io.qalipsis:api-processors:{revnumber}") 
    //required to perform the annotation processing at compile time.//
}
----

Optionally, import the default configuration of the application (requuired to test locally): 

[source,kotlin,linenumbers]
----
application { 
    
       mainClassName = "io.qalipsis.runtime.Qalipsis"
    applicationDefaultJvmArgs = listOf("-noverify", "-XX:TieredStopAtLevel=1", "-Dcom.sun.management.jmxremote",
            "-Dmicronaut.env.deduction=false")
    this.ext["workingDir"] = projectDir 
    
}
----

Add a classifier to distinguish the "fat JAR" package froma a "normal JAR":
[source,kotlin,linenumbers]
----
tasks { 
    
    named<ShadowJar>("shadowJar") {
        mergeServiceFiles()
        archiveClassifier.set("qalipsis")
    }
}
----
Include the creation of the "fat JAR" in the standard build workflow:
[source,kotlin,linenumbers]
----
tasks { 
    
    build {
        dependsOn(shadowJar)
    }
}
----
If you are using a snapshot version of QALIPSIS, add `https://oss.sonatype.org/content/repositories/snapshots` as a dependency repository.

=== Setting Up Your IDE
NOTE: While it is possible to develop a complete scenario with a text editor, it is recommended that you use a suitable IDE such as IntelliJ or Eclipse.

QALIPSIS relies on annotation processing at compile time to prepare the executable code and to list the scenarios to later execute.

Furthermore, QALIPSIS relies on the Micronaut IoC framework, which requires that you setup your IDE following the instrutions provided in the https://docs.micronaut.io/latest/guide/index.html[Micronaut User Guide].

==== IntelliJ

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#ideaSetup[IntelliJ IDEA] section of the Micronaut User Guide.

==== Eclipse

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#eclipseSetup[Eclipse] section of the Micronaut User Guide.


==== Visual Studio Code

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#vsCodeSetup[Visual Studio Code] section of the Micronaut User Guide.


=== Creating a scenario

In this sections, you will create a simple scenario specification that injects 1000 minions, 50 msec aparts, to write a message on the console.

Scenarios can be created in classes or as Kotlin objects or as a Kotlin function.  The name you give the scenario does not matter; however, it is necessary to annotate the creation method (i.e., class, Kotlin object, or Kotlin function). 

[source,kotlin,linenumbers]
----
package my.example //???//

import io.qalipsis.api.annotations.Scenario//import the Qalipsis plug-in for scenario creation methods//

class HelloWorldScenario {
//creation method is class, scenario nane is HelloWorld//
    @Scenario
    fun myScenario() {
//the sceanrio will be configured and devloped here (refer to <Configuring a Scenario>//
    }

}
----
=== Configuring the Scenaerio
IMPORTANT: Due to the incremental compilation not yet fully taken into account in QALIPSIS annotation processor, you should clean the output/build directory when you delete or rename the package or class containing a scenario method. The risk is to have a scenario listed to be executed at runtime, which no longer exists.

NOTE: You can create several methods with the `@Scenario` annotation in the same class/object.


In the annotated method, create a new scenario and configure it:

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    scenario("hello-world") { // <1>
        minionsCount = 1000 // <2>
        rampUp {
            regular(1000, 50) // <3>
        }
    }
}
----
<1> Creates a new scenario called "hello-world" (see <<Scenario>> for more details)
<2> Defines the default number of minions to execute, which you can change at runtime (see <<Runtime configuration>> for more details), they are the number of simulated users or systems that generate load: the more the minions, the more the load
<3> Defines the strategy to start the minion, which you can make faster or slower at runtime (see <<Runtime configuration>> for more details)

=== Specify where the load should be injected

Consider the scenario as a directed graph joining the steps/actions to execute. Within the scenario, it is possible to have:

* several roots
* two branches joining the same step (like a Y)
* one step distributing two branches (like a ⅄)

In eack of the branches, you will need to identify when the load should be injected.

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 1000
        rampUp {
            regular(1000, 50)
        }
    }
    .start() // <1>
}
----
<1> The `start()` statement locates the root of the tree, receiving the load of all the minions at runtime.

=== Add steps to your scenario

Now you can add all the steps you want!
Let's go further in our "hello world" scenario.

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 1000
        rampUp {
            regular(1000, 50)
        }
    }
    .start()
    .returns<String> { context -> // <1>
        "Hello World! I'm the minion ${context.minionId}"
    }
    .shelve { mapOf("started at" to System.currentTimeMillis()) } // <2>
    .map { str -> str!!.toUpperCase() } // <3>
    .unshelve<String, Long>("started at") // <4>
    .verify { // <5>
        assertThat(it).all {
            prop(Pair<String, Long?>::first).startsWith("HELLO")
            prop(Pair<String, Long?>::second).isNotNull().isPositive()
        }
    }
    .execute<Pair<String, Long?>, Unit> { ctx -> // <6>
        val input = ctx.receive()
        println("${input.first} and finished after ${input.second!! - start} ms")
    }
    .configure {
        iterate(2, 1000) // <7>
    }
}
----
<1> You declare the first step as root of the tree on the scenario, and is generally responsible for generating data to be used in the rest of the tree.
<2> Data can be cached for later use.
<3> Transforms the record.
<4> Retrieves a value previously added to the cache.
<5> Verifies the records using your assertion library of choice, here assertk.
<6> Executes a totally free operation on the step context: you can do whatever you want here, such as printing the "Hello world" message in the console with the start time.
<7> And if you like it, you can repeat it several times with an interval.

Et voila! You've just created your first scenario. It is not really useful, but you went through the most important concepts of creating a scenario.

Now you are ready to go further in the documentation and create scenarios that are really relevant for your system.
