== Quickstart


This section will guide you through:

* Downloading and installing QALIPSIS 1.0 on your system.
* Creating a new project.
* Setting up your IDE.
* Creating and configuring a QALIPSIS scenario.
* Specifying the load injection point.
* Adding steps to your scenario.
* Running your scenario.


NOTE: Before getting started, confirm that you have Java 11 (or above) SDK installed on your workstation. 

=== Downloading and Installing QALIPSIS to your system.

The first step, of course,  is to download and unpack the current version of QALIPSIS.
*_Instructions needed here_*


=== Creating a Project

In order to create a project for Gradle with your IDE, using the Kotlin DSL, you need to take the following steps:


. Import the QALIPSIS executable file:
[source,kotlin,linenumbers]
+
----
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar 
//The QALIPSIS executable file  is packaged as a "fat JAR'; it uses the shadow plugin and contains all of the dependencies required to run QALIPSIS and your scenario.//
----
. Import the Kotlin Compiler:
+
[source,kotlin,linenumbers]
----
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile //Kotlin Compiler//
----
. Import QUALIPSIS plugins:
+
[source,kotlin,linenumbers]
----
plugins {
    application //provide description//
    kotlin("jvm") //Java plugin//
    kotlin("kapt") //Maven plugin//
    id("com.github.johnrengelman.shadow") version "6.0.0" //QALIPSIS Shadow JAR plugin//
}
----
. Give your project a name:
+
[source,kotlin,linenumbers]
----
description = "QALIPSIS  Quickstart" 
// replace _QALIPSIS Quickstart_ with "your project name"//
----
. Configure compileKotlin and compileTestKotlin:
+
[source,kotlin,linenumbers]
----
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.majorVersion
        javaParameters = true
    }
}
----
. Call the scenario dependencies:
+
[source,kotlin,linenumbers]
----
dependencies {
    implementation(kotlin("stdlib")) 
    //required to develop scenarios with Kotlin//
   
    implementation("io.qalipsis:api-dsl:{revnumber}") 
    //required to develop scenarios for QALIPSIS, indepenent of language//

    implementation("com.willowtreeapps.assertk:assertk:2.0.3") 
    implementation("com.willowtreeapps.assertk:assertk-jvm:2.0.3") 
    //assertion libraries required to verify data in a scenarion; use JUnit, AssertJ or AssertK, Hamcrest, or any other library you are familiar with.//


    runtimeOnly("io.qalipsis:runtime:{revnumber}") 
    //required to execute QALIPSIS, either as a head or factory.//

    kapt("io.qalipsis:api-processors:{revnumber}") 
    //required to perform the annotation processing at compile time.//
}
----

. Optionally, import the default configuration of the application (requuired to test locally): 
+

[source,kotlin,linenumbers]
----
application { 
    
       mainClassName = "io.qalipsis.runtime.Qalipsis"
    applicationDefaultJvmArgs = listOf("-noverify", "-XX:TieredStopAtLevel=1", "-Dcom.sun.management.jmxremote",
            "-Dmicronaut.env.deduction=false")
    this.ext["workingDir"] = projectDir 
    
}
----

. Add a classifier to distinguish the "fat JAR" package from a "normal JAR":
+
[source,kotlin,linenumbers]
----
tasks { 
    
    named<ShadowJar>("shadowJar") {
        mergeServiceFiles()
        archiveClassifier.set("qalipsis")
    }
}
----
. Include the creation of the "fat JAR" in the standard build workflow:
+
[source,kotlin,linenumbers]
----
tasks { 
    
    build {
        dependsOn(shadowJar)
    }
}
----
. If you are using a snapshot version of QALIPSIS, add `https://oss.sonatype.org/content/repositories/snapshots` as a dependency repository.

=== Setting Up Your IDE
NOTE: While it is possible to develop a complete scenario with a text editor, it is recommended that you use a suitable IDE such as IntelliJ or Eclipse.

QALIPSIS relies on annotation processing at compile time to prepare the executable code and to list the scenarios to later execute.

Furthermore, QALIPSIS relies on the Micronaut IoC framework, which requires that you setup your IDE following the instrutions provided in the https://docs.micronaut.io/latest/guide/index.html[Micronaut User Guide].

==== IntelliJ

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#ideaSetup[IntelliJ IDEA] section of the Micronaut User Guide.

==== Eclipse

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#eclipseSetup[Eclipse] section of the Micronaut User Guide.


==== Visual Studio Code

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#vsCodeSetup[Visual Studio Code] section of the Micronaut User Guide.


=== Creating  a Scenario

Scenarios can be created in classes or as Kotlin objects or as a Kotlin function.  The name you give the scenario does not matter; however, it is necessary to annotate the creation method (i.e., class, Kotlin object, or Kotlin function). 

In this section, you will create and configure a simple scenario that injects 1000 minions, 50 msec apart, to write a message on the console and then stop.

. Import the package to be used:
+
[source,kotlin,linenumbers]
----
package my.example 
----
. Import the Qalipsis annotation processor:
+
[source,kotlin,linenumbers]
----
import io.qalipsis.api.annotations.Scenario
----
. Annotate the scenario as _class_ and name it _HelloWorld_:
+
[source,kotlin,linenumbers]
----
class HelloWorldScenario {}
----
. Configuring the Scenario
+

IMPORTANT: Due to the incremental compilation not yet fully taken into account in QALIPSIS annotation processor, you should clean the output/build directory when you delete or rename the package or class containing a scenario method. The risk is to have a scenario listed to be executed at runtime, which no longer exists.

NOTE: You can create several methods with the `@Scenario` annotation in the same class/object.


Using the _fun_ method, create a new scenario named "hello-world" and configure it with a default minions cout of 1000:

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario()// {
    scenario("hello-world") { 
        //creates a new scenario and names it _hello-world_>//
        minionsCount = 1000 
        //sets the default minion count to 1000//
        rampUp {
            regular(1000, 50) //defines the strategy for injecting minions:  to 1 every 50 ms until 1000 have benn injected//
        }
    }
}
----


=== Specify where the load should be injected

Consider the scenario as a directed graph joining the steps/actions to execute. Within the scenario, it is possible to have:

* several roots
* two branches joining the same step (like a Y)
* one step distributing two branches (like a ⅄)

In eack of the branches, you will need to identify when the load should be injected.

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 1000
        rampUp {
            regular(1000, 50)
        }
    }
    .start() // <1>
}
----
<1> The `start()` statement locates the root of the tree, receiving the load of all the minions at runtime.

=== Add steps to your scenario

Now you can add all the steps you want!
Let's go further in our "hello world" scenario.

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 1000
        rampUp {
            regular(1000, 50)
        }
    }
    .start()
    .returns<String> { context -> // <1>
        "Hello World! I'm the minion ${context.minionId}"
    }
    .shelve { mapOf("started at" to System.currentTimeMillis()) } // <2>
    .map { str -> str!!.toUpperCase() } // <3>
    .unshelve<String, Long>("started at") // <4>
    .verify { // <5>
        assertThat(it).all {
            prop(Pair<String, Long?>::first).startsWith("HELLO")
            prop(Pair<String, Long?>::second).isNotNull().isPositive()
        }
    }
    .execute<Pair<String, Long?>, Unit> { ctx -> // <6>
        val input = ctx.receive()
        println("${input.first} and finished after ${input.second!! - start} ms")
    }
    .configure {
        iterate(2, 1000) // <7>
    }
}
----
<1> You declare the first step as root of the tree on the scenario, and is generally responsible for generating data to be used in the rest of the tree.
<2> Data can be cached for later use.
<3> Transforms the record.
<4> Retrieves a value previously added to the cache.
<5> Verifies the records using your assertion library of choice, here assertk.
<6> Executes a totally free operation on the step context: you can do whatever you want here, such as printing the "Hello world" message in the console with the start time.
<7> And if you like it, you can repeat it several times with an interval.

Et voila! You've just created your first scenario. It is not really useful, but you went through the most important concepts of creating a scenario.

Now you are ready to go further in the documentation and create scenarios that are really relevant for your system.
