= Quickstart Guide: Testing an HTTP Server with Qalipsis

In this quickstart guide, you will learn how to test a very simple echo-like HTTP service using QALIPSIS.

== Before You Get Started
Before starting, you need:

* A general understanding of the link:02a_core-concepts.adoc[QALIPSIS Core Concepts].
* Java 11 or above SDK installed on your system.
* Docker installed on your system.

== What This Guide Covers 
 
This guide provides a step-by-step process for testing an HTTP server.
Following this guide, you will:
. Start the HTTP server and the docker environment for the project. 
. Generate a project archive. 
. Open the downloaded archive and configure the scenario skeleton.
. Add steps to the scenario.
.. An `HTTP` step to send requests to the server.
.. An `assertion` step to verify the server's responses.
.. An `HTTP WITH` step that reuses the HTTP connection.
.. A second `assertion` step to verify the server's responses.
. Execute the scenario using https://docs.gradle.org/current/userguide/what_is_gradle.html[Gradle] and view the report.
. Create a Java archive of your project so that you can easily transport it as needed.  
. Enable event logging to allow you to view reporting errors. 

== Start the HTTP Server
. Create a file named `docker-compose.yml` in the root (c:\) directory with the following content:
+
[source,kotlin,linenumbers]
----
version: '3.5'
services:
  http-punching-ball:
    image: aerisconsulting/http-punching-ball
    command:
      - "--https=true"
      - "--ssl-key=http-server.key"
      - "--ssl-cert=http-server.crt"
    ports:
      - "18080:8080"
      - "18443:8443"   
----

. Start the docker environment with the file `docker-compose.yml` with the command `docker compose up -d`.

== Create a Project
. In your browser, open the website https://launch.qalipsis.io[Launch QALIPSIS].
. Verify that your system has the pre-requisites listed on the https://launch.qalipsis.io[Launch QALIPSIS] page.
. In the "Name" field, enter "Quickstart".
. In the "plugins" menu, select `netty`.
. In the assertions libraries menu, select `Kotest`.
. Click `Generate`. An archive containing a skeleton of the project is proposed for download.
. Download the proposed project archive. 

[ insert graphic/screenshot of the Launch QALLIPSIS page ]

== Prepare a Scenario

=== Edit the Downloaded Scenario Skeleton

. Open the downloaded project archive in your IDE. 
. Edit the file `src/main/kotlin/Quickstart.kt`.
The scenario skeleton should be displayed:

[source,kotlin,linenumbers]
----
package quickstart
import io.qalipsis.api.annotations.Scenario
class Quickstart{
    @Scenario
    fun quickstart() {
        scenario("quickstart-http") {
            minionsCount = 1
            rampUp {     
            }
        }
    .start()
    }
}
----

=== Configure the Scenario Basics

Configure the scenario to inject 10,000 minions at a rate of 100 minions every 500 ms.
[source,kotlin,linenumbers ]
----
        scenario("quickstart-http") {
            minionsCount = 10000
            rampUp {
                regular(periodMs = 500, minionsCountProLaunch = 100)
            }
        }
        .start()
----

=== Add Steps to the Scenario.
Add and configure steps within the scenario that will send an HTTP request to the server and verify that the server's response is as expected.

==== Send an HTTP Request
Create an HTTP step to send a POST request to the server. After the `start()` statement that specifies the starting point of load injection, access the `netty` namespace and call the `http` operator:

1. Give your step a name.
2. Configure the connection to the server.
3. Configure the HTTP request to send: HTTP method, path and body.
4. Enable the reporting of errors for the step.

[source,kotlin,linenumbers ]
----
        .start()
        .netty()
        .http {
            name = "quickstart-http-post"
            connect {
                url("http://localhost:18080")
                version = HttpVersion.HTTP_1_1
            }
            request { _,_ ->
                    SimpleHttpRequest(HttpMethod.POST, "/echo").body(
                    "Hello World!",
                    HttpHeaderValues.TEXT_PLAIN
                    )
            }
            report {
                reportErrors = true
            }
        }
----

Execute your scenario using Gradle: `./gradlew run`. This allows you to observe requests logged by the HTTP server. However, it does not verify that the server's is returning what you expect.

[ insert screen shot here of the report]

==== Verify the Server's Response
In order to verify that the server is returning what you expect, add a `verify` step to the scenario, just after the `http` step. This steps allow you to verify that:

* The HTTP status of the response is OK (we are using `io.netty.handler.codec.http.HttpResponseStatus`)
* The body of the response contains the string we sent in the request.

[source,kotlin,linenumbers ]
----
        .start()
        .netty()
        .http {
            // ...
        }
        .verify { result ->
            assertSoftly {
                result.asClue {
                    it.response shouldNotBe null
                    it.response!!.asClue { response ->
                        response.status shouldBe HttpResponseStatus.OK
                        response.body shouldContainOnlyOnce "Hello World!"
                        response.body shouldContainOnlyOnce "POST"
                    }
                    it.meters.asClue { meters ->
                        meters.timeToFirstByte!! shouldBeLessThanOrEqualTo Duration.ofSeconds(1)
                        meters.timeToLastByte!! shouldBeLessThanOrEqualTo Duration.ofSeconds(2)
                    }
                }
            }
        }.configure {
            name = "verify-post"
        }
----
Execute your updated scenario.  This time you will observe the HTTP status of the response and verify that server is returning the string you sent.

[ *insert screen shot here of results* ]

==== Reuse the HTTP Connection
To strengthen the relevance of your test, create a step that reuses the first HTTP connection (`quickstart-http-post`)
to provide  that the minions will be injected in.  [*needs reworked*]

To do so, add a new `netty http` step after the validation, called `httpWith`, where we specify the name of the
step that holds the connection: in our case `quickstart-http-post`, which is the first HTTP step of our scenario.

You can note that there is logically no need to specify anything about the connection, since the one from `quickstart-http-post` was kept active and is automatically closed after that new step.

For convenience purpose, we also add a new verification step.
----
 import java.time.Duration.configure {
                name = "verify-post"
            }
            .netty()
            .httpWith("quickstart-http-post") {
                report {
                    reportErrors = true
                }
                request { _, _ ->
                    SimpleHttpRequest(HttpMethod.PATCH, "/echo").body(
                        "Hello World!",
                        HttpHeaderValues.TEXT_PLAIN
                    )
                }
            }.verify { result ->
                assertSoftly {
                    result.asClue {
                        it.response shouldNotBe null
                        it.response!!.asClue { response ->
                            response.status shouldBe HttpResponseStatus.OK
                            response.body shouldContainOnlyOnce "Hello World!"
                            response.body shouldContainOnlyOnce "PATCH"
                        }
                        it.meters.asClue { meters ->
                            meters.timeToFirstByte!! shouldBeLessThanOrEqualTo Duration.ofMillis(100)
                            meters.timeToLastByte!! shouldBeLessThanOrEqualTo Duration.ofMillis(200)
                        }
                    }
                }
            }.configure {
                name = "verify-patch"
            }
----
=== Execute Your Scenario

You can now  execute your scenario as a Gradle project.
After a couple of seconds, you will see the following report on your console:

```
============================================================
=====================  CAMPAIGN REPORT =====================
============================================================   

Campaign...........................quickstart-http-4fb6244cd3
Start..............................2022-03-30T16:41:02.597973Z
End................................2022-03-30T16:41:53.411602Z
Duration...........................50 seconds 
Configured minions.................10000
Completed minions..................10000
Successful steps executions........39832
Failed steps executions............42
Status.............................FAILED
   
        

=====================  SCENARIO REPORT =====================
Scenario...........................quickstart-http
Start..............................2022-03-30T16:41:02.597973Z
End................................2022-03-30T16:41:53.411602Z
Duration...........................50 seconds 
Configured minions.................10000
Completed minions..................10000
Successful steps executions........39832
Failed steps executions............42
Status.............................FAILED
Messages:
- ERROR:  step 'quickstart-http-post' - "Success: 9958, Execution errors: 42"
- INFO:   step 'verify-post' - "Success: 9958, Failures (verification errors): 0, Errors (execution errors): 0"
- INFO:   step '_622niod959' - "Success: 9958, Execution errors: 0"
- ERROR:  step 'verify-patch' - "Success: 9926, Failures (verification errors): 32, Errors (execution errors): 0"
        
```
You can note the information of the whole campaign as well as scenario by scenario.
There were errors, which explains why the execution failed. Do you want to know which errors? Go to the section
related to the events logging.

=== Create an Archive of your scenario
Execute the statement `./gradlew assemble`.

A JAR archive ending with `-qalipsis.jar` is created in the folder `build/libs`.
This archive contains all the dependencies and is self-sufficient to execute your scenario on any machine with
a Java Runtime Environment installed.

To execute it, open a terminal and go to the folder where your JAR archive is stored - move it out from the `build`
folder to avoid it to be deleted by mistake.

Execute the command `java -jar quickstart-<your-version>-qalipsis.jar`.

=== Enable Event Logging 

to know the details of the failures
In current directory, create a folder called `config`.
In this new folder, create a file called `qalipsis.yml` with the following content:

```yaml
events:
  root: warn
  export:
    slf4j:
      enabled: true
```

This enables the logging of the events with severity WARN and upper to a file called `qalipsis-events.log`.

Execute your scenario again, the events file is created and contains the details of the individual failed assertions:

2022-03-31T06:33:55.937Z  WARN --- step.assertion.failure;io.qalipsis.plugins.netty.tcp.ConnectionAndRequestResult@1e869276
MetersImpl(timeToSuccessfulConnect=null, timeToFailedConnect=null, timeToSuccessfulTlsConnect=null, timeToFailedTlsConnect=null, bytesCountToSend=85, sentBytes=85, timeToFirstByte=PT0.10696475S, timeToLastByte=PT0.1163375S, receivedBytes=394)
PT0.10696475S should be <= PT0.1S;campaign=quickstart-campaign-4d39026fd7,minion=quickstart-http-62qr1n87xx,scenario=quickstart-http,dag=dag-1,step=verify-patch,context-creation=2022-03-31T06:33:55.730Z,parent-step=_629qthims5,_ step-type=Verification,iteration=0,attempts-after-failure=0,isExhausted=true,isTail=true,isCompleted=true_
2022-03-31T06:33:56.916Z  WARN --- step.assertion.failure;io.qalipsis.plugins.netty.tcp.ConnectionAndRequestResult@19a03b37
MetersImpl(timeToSuccessfulConnect=null, timeToFailedConnect=null, timeToSuccessfulTlsConnect=null, timeToFailedTlsConnect=null, bytesCountToSend=85, sentBytes=85, timeToFirstByte=PT0.128673083S, timeToLastByte=PT0.128737375S, receivedBytes=394)
PT0.128673083S should be <= PT0.1S;campaign=quickstart-campaign-4d39026fd7,minion=quickstart-http-62sqemkv8j,scenario=quickstart-http,dag=dag-1,step=verify-patch,context-creation=2022-03-31T06:33:56.735Z,parent-step=_629qthims5,_ step-type=Verification,iteration=0,attempts-after-failure=0,isExhausted=true,isTail=true,isCompleted=true_


Essentially, you want to view the following pertinent parts of the message:
```
2022-03-31T06:33:55.937Z ... PT0.10696475S should be <= PT0.1S ... campaign=quickstart-campaign-4d39026fd7,... scenario=quickstart-http,... step=verify-patch
```

* The exact instant when the failed assertion occurred:
+
2022-03-31T06:33:55 (March 31, 2022 at 06:33:55)in the example above.


* The reason for the failure:
+
PT0.10696475S should be <= PT0.1S
* 
The campaign (quickstart-campaign-4d39026fd7), scenario (quickstart-http) and verification step (verify-patch) where the failed assertion occurred 

== Next steps

* Discover how to push log file events to a database, making them easier to view and understand.
* Work through other QALIPSIS Quickstart Guides:
** quickstart 1
** quickstart 2

