== Quick Start

This section will guide you through:

* Creating a project.
* Setting up your IDE.
* Creating and configuring a QALIPSIS scenario.
* Specifying the load injection point.
* Adding steps to your scenario.
* Executing your scenario.

NOTE: Before getting started, confirm that you have Java 11 (or above) SDK installed on your workstation. 

=== QALIPSIS Workflow

NOTE: This workflow assumes that you have a general understanding of the QALIPSIS Core concepts and that you have Java 11 or above SDK installed on your workstation.

. Create a project:
.. Download a QALIPSIS project skeleton.
.. Give your project a name.
. Set up your IDE:
. Create a scenario:
.. Call the Scenario function (initiates a new scenario).
.. Assign the scenario a name.
.. Declare the package (directory) where the scenario will
be stored.
.. Import the QALIPSIS annotation processor.
. Configure the Scenario Specification.
.. Declare the root of the tree.
.. Declare the # of minions (Optional, default = 1).
.. Declare the ramping strategy.
. Add Steps to your Scenario.
.. Configure steps depending on their function.
.. Add step specifications as applicable.
. Repeat steps 3-5 to create, configure, and add steps to as many scenarios that you intend to run within your project. 
. Start QALIPSIS.  
.. Select scenario(s) to run.
.. Enter load factor for each scenario.
.. Enter speed factor for each scenario.
.. Enter minion count for each scenario.
.. Enter ramping strategy for each scenario.
. Monitor the results.

[example]
Insert Workflow graphic here

=== Creating a Project
. Import a QALIPSIS skeleton project from the _QALIPSIS Launch_ website:
[source,kotlin,linenumbers]
+
----
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar 
----
The project skeleton includes a Gradle plugin that generates a "fat JAR" that includes all required project and scenario: 
 * Compilers and their configurations.
 * Dependencies.
*  Plugins .

. Give your project a name:
+
[source,kotlin,linenumbers]
----

// Replace "QALIPSIS Quickstart" with your project name.
----

=== Setting Up Your IDE
NOTE: While it is possible to develop a complete scenario with a text editor, it is recommended that you use a suitable IDE such as IntelliJ or Eclipse.

QALIPSIS relies on annotation processing at compile time to prepare the executable code and to list the scenarios to later execute.

QALIPSIS also relies on the Micronaut IoC framework, which requires that you setup your IDE following the instructions provided in the https://docs.micronaut.io/latest/guide/index.html[Micronaut User Guide].

==== IntelliJ
Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#ideaSetup[IntelliJ IDEA] section of the Micronaut User Guide.

==== Eclipse
Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#eclipseSetup[Eclipse] section of the Micronaut User Guide.

==== Visual Studio Code
Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#vsCodeSetup[Visual Studio Code] section of the Micronaut User Guide.

=== Creating a Scenario
Scenarios can be created in classes, as Kotlin objects or as a Kotlin function.  The name you give the class or function does not matter; however, it is necessary to annotate the function that builds the scenario. 

In this section, you will create and configure a simple scenario that injects 500 minions, 35 ms apart, to write a message on the console and then stop.

. Declare the package/directory where the scenario can be found:
+
[source,kotlin,linenumbers]
----
package my.example 
----
. Import the Qalipsis annotation processor:
+
[source,kotlin,linenumbers]
----
import io.qalipsis.api.annotations.Scenario
----
. Declare the name for the Scenario class as _HelloWorldScenario_:
+
[source,kotlin,linenumbers]
----
class HelloWorldScenario {}
----
. Configure the Scenario
+
IMPORTANT: Due to the incremental compilation not yet fully taken into account by the QALIPSIS annotation processor, you should clear the output/build directory when you delete or rename the package or class containing a scenario method. The risk of not doing so is to have a scenario listed to be executed at runtime, which no longer exists.

NOTE: You can create several methods with the `@Scenario` annotation in the same class/object.

Using the _fun_ keyword, create a function that declares a new scenario named "hello-world" and configure it with a default minions count of 500:
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    scenario("hello-world") { 
        minionsCount = 500 
                rampUp {
            regular(35, 50) 
            // Defines the strategy to inject 50 minions
            every 35 ms until 500 minions have been injected.
        }
    }
}
----

=== Specify where the load should be injected
Consider the scenario as a directed graph joining the steps/actions to execute. Within the scenario, it is possible to have:

* Several roots.
* Two branches joining the same step (like a Y)
* One step distributing to two branches (like a ⅄)

You need to identify the branch that is to receive the load using the _(start ()_ operator.
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
    minionsCount = 500
        rampUp {
            regular(35, 50)
        }
    }
 .start() // Declares the root of the tree to receive the load of all the minions at runtime.
----

=== Adding Steps to Your Scenario
You can now add steps to your scenario.
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 500
        rampUp {
            regular(35, 50)
        }
    }
 .start() // Declares the root of the tree to receive the load of all the minions at runtime.
 
    // Add steps here.
----
. Add a step to generate data to be used in the rest of the tree:
[source,kotlin,linenumbers]
+
----
    .returns<String> { context -> 
        "Hello World! I'm the minion ${context.minionId}"
    }
----
. Add a step to indicate where data is cached for later use:
+
[source,kotlin,linenumbers]
----
    .shelve { mapOf("started at" to System.currentTimeMillis()) } 
    .map { str -> str!!.toUpperCase() } 
    // Transforms the record to an Upper Case string.
    .unshelve<String, Long>("started at") 
    // Retrieves a value previously added to the cache.
    .verify {// Verifies the records using your assertion library of choice, assertk in this scenario.
        assertThat(it).all {
            prop(Pair<String, Long?>::first).startsWith("HELLO")
            prop(Pair<String, Long?>::second).isNotNull().isPositive()
        }
    }
----
=== Configuring the Scenario Execution

[source,kotlin,linenumbers]
----
        .execute<Pair<String, Long?>, Unit> { ctx -> // Executes a totally free operation on the step context: you can do whatever you want here, such as printing the "Hello world" message in the console with the start time.
        val input = ctx.receive()
        println("${input.first} and finished after ${input.second!! - start} ms")
    }
    .configure {
        iterate(4, Duration.ofMillis(2)) // Repeat the execution 4 times with a delay of 2 msec.
    }
}
----
You've just created your first scenario. 

Now you are ready to create scenarios that are relevant for your system.
