== Quick Start


This section will guide you through:

* Downloading required QALIPSIS files to your system.
* Creating a new project.
* Setting up your IDE.
* Creating and configuring a QALIPSIS scenario.
* Specifying the load injection point.
* Adding steps to your scenario.
* Running your scenario.


NOTE: Before getting started, confirm that you have Java 11 (or above) SDK installed on your workstation. 

=== Downloading required QALIPSIS files to your system.

The first step is to confirm that you have configured and downloaded a project skeleton from the _QALIPSIS Launch_ website. Follow the instructions located at <https:\\QALIPSIS.com>



=== Creating a Project

In order to create a project for Gradle with your IDE, using the Kotlin DSL, you need to take the following steps:

. Import the QALIPSIS executable file:
[source,kotlin,linenumbers]
+
----
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar 
//The QALIPSIS executable file  is packaged as a "fat JAR"; it uses the shadow plugin and contains all of the dependencies required to run QALIPSIS and your scenario.//
----
. Import the Kotlin Compiler:
+
[source,kotlin,linenumbers]
----
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile 
----
. Call the following plugins:
+
[source,kotlin,linenumbers]
----
plugins {
    application 
    //prepares JARs tp execute the application locally//
    kotlin("jvm") 
    //kotlin for the JAVA Virtual machines//
    kotlin("kapt") //Kotlin Annotation Processor Tool//
    id("com.github.johnrengelman.shadow") version "6.0.0" // creates the Jar that includes everything to setup the classpath//
}
----
. Give your project a name:
+
[source,kotlin,linenumbers]
----
description = "QALIPSIS  Quickstart" 
// replace "QALIPSIS Quickstart" with your project name//
----
. Configure compileKotlin and compileTestKotlin:
+
[source,kotlin,linenumbers]
----
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.majorVersion
        javaParameters = true
    }
}
----
. Call the scenario dependencies:
+
[source,kotlin,linenumbers]
----
dependencies {
    implementation(kotlin("stdlib")) 
    //the required kotlin components in the compilation and execution classpaths//
   
    implementation("io.qalipsis:api-dsl:{revnumber}") 
    //the kotlin DSL library required to develop scenarios for QALIPSIS//

    implementation("com.willowtreeapps.assertk:assertk:2.0.3") 
    implementation("com.willowtreeapps.assertk:assertk-jvm:2.0.3") 
    //assertion libraries required to verify data in a scenario; use JUnit, AssertJ or AssertK, Hamcrest, or any other library you are familiar with//


    runtimeOnly("io.qalipsis:runtime:{revnumber}") 
    //required to execute QALIPSIS, either as a head or factory//

    kapt("io.qalipsis:api-processors:{revnumber}") 
    //required to perform the annotation processing at compile time//
}
----

. Optionally, import the default configuration of the application (required to test locally): 
+

[source,kotlin,linenumbers]
----
application { 
    
       mainClassName = "io.qalipsis.runtime.Qalipsis"
    applicationDefaultJvmArgs = listOf("-noverify", "-XX:TieredStopAtLevel=1", "-Dcom.sun.management.jmxremote",
            "-Dmicronaut.env.deduction=false")
    this.ext["workingDir"] = projectDir 
    
}
----

. Add a classifier to distinguish the "fat JAR" package from a "normal JAR":
+
[source,kotlin,linenumbers]
----
tasks { 
    
    named<ShadowJar>("shadowJar") {
        mergeServiceFiles()
        archiveClassifier.set("qalipsis")
    }
}
----
. Include the creation of the "fat JAR" in the standard build workflow:
+
[source,kotlin,linenumbers]
----
tasks { 
    
    build {
        dependsOn(shadowJar)
    }
}
----
. If you are using a snapshot version of QALIPSIS, add `https://oss.sonatype.org/content/repositories/snapshots` as a dependency repository.

=== Setting Up Your IDE
NOTE: While it is possible to develop a complete scenario with a text editor, it is recommended that you use a suitable IDE such as IntelliJ or Eclipse.

QALIPSIS relies on annotation processing at compile time to prepare the executable code and to list the scenarios to later execute.

QALIPSIS also relies on the Micronaut IoC framework, which requires that you setup your IDE following the instructions provided in the https://docs.micronaut.io/latest/guide/index.html[Micronaut User Guide].

==== IntelliJ

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#ideaSetup[IntelliJ IDEA] section of the Micronaut User Guide.

==== Eclipse

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#eclipseSetup[Eclipse] section of the Micronaut User Guide.


==== Visual Studio Code

Follow the instructions provided in the https://docs.micronaut.io/latest/guide/index.html#vsCodeSetup[Visual Studio Code] section of the Micronaut User Guide.


=== Creating  a Scenario

Scenarios can be created in classes or as Kotlin objects or as a Kotlin function.  The name you give the scenario does not matter; however, it is necessary to annotate the creation method (i.e., class, object, or fun). 

In this section, you will create and configure a simple scenario that injects 500 minions, 35 ms apart, to write a message on the console and then stop.

. Declare the package/directory where the scenario can be found:
+
[source,kotlin,linenumbers]
----
package my.example 
----
. Import the Qalipsis annotation processor:
+
[source,kotlin,linenumbers]
----
import io.qalipsis.api.annotations.Scenario
----
. Declare the name for the Scenario class as _HelloWorldScenario_:
+
[source,kotlin,linenumbers]
----
class HelloWorldScenario {}
----
. Configure the Scenario
+

IMPORTANT: Due to the incremental compilation not yet fully taken into account in the QALIPSIS annotation processor, you should clean the output/build directory when you delete or rename the package or class containing a scenario method. The risk is to have a scenario listed to be executed at runtime, which no longer exists.

NOTE: You can create several methods with the `@Scenario` annotation in the same class/object.


Using the _fun_ method, create a new scenario named "hello-world" and configure it with a default minions count of 500:

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario()// {
    scenario("hello-world") { 
        minionsCount = 500 
                rampUp {
            regular(35, 50) 
            //defines the strategy to inject 50 minions
            every 35 ms until 500 minions have been injected//
        }
    }
}
----


=== Specify where the load should be injected

Consider the scenario as a directed graph joining the steps/actions to execute. Within the scenario, it is possible to have:

* several roots
* two branches joining the same step (like a Y)
* one step distributing to two branches (like a ⅄)

In each of the branches, you will need to identify when the load should be injected.

[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") 
    {minionsCount = 500
        rampUp {
            regular(35, 50)
        }
    }
.start() //Sets the root of the tree to receive
     the load of all the minions at runtime//
     
----

----
    
----

=== Adding steps to your scenario
You can now add steps to your scenario.
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 500
        rampUp {
            regular(35, 50)
        }
    }
    //Add steps here//
----
. Declare the first step as the root of the tree:
[source,kotlin,linenumbers]
+
----
    .start()
----

. Add a step to generate data to be used in the rest of the tree:
[source,kotlin,linenumbers]
+
----
    .returns<String> { context -> 
        "Hello World! I'm the minion ${context.minionId}"
    }
----
. Add a step to indicate where data is cached for later use:
[source,kotlin,linenumbers]
----
    .shelve { mapOf("started at" to System.currentTimeMillis()) } 
----
    .map { str -> str!!.toUpperCase() } 
    // transforms the record//
    .unshelve<String, Long>("started at") 
    // Retrieves a value previously added to the cache.//
    .verify { // Verifies the records using your assertion library of choice, assertk in this scenario//
        assertThat(it).all {
            prop(Pair<String, Long?>::first).startsWith("HELLO")
            prop(Pair<String, Long?>::second).isNotNull().isPositive()
        }
    }
    .execute<Pair<String, Long?>, Unit> { ctx -> // executes a totally free operation on the step context: you can do whatever you want here, such as printing the "Hello world" message in the console with the start time.//
        val input = ctx.receive()
        println("${input.first} and finished after ${input.second!! - start} ms")
    }
    .configure {
        iterate(2, 1000) // repeat the execution every 2 msec,1000 times//
    }
}
----


 You've just created your first scenario. 

Now you are ready to create scenarios that are relevant for your system.
