= Scenario specification

A scenario specification is the total of all of the steps required to configure the scenario and to execute it at run-time.

In order to provide maximum flexibility for configuring a scenario and the best performance while executing it, QALIPSIS splits its configuration from its execution.

* In the configuration phase, you develop specifications for the scenario.
* In the execution phase, you set the runtime parameters for the scenario(s) you are executing.

This section focuses on scenario configuration.  Details on scenario execution are provided in link:06_configuration.adoc[QALIPSIS Configuration]. 

== Configuring a Scenario Specification
A scenario specification is made up of several parts.

. Calling the Scenario function:
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario()
----
. Assigning the scenario a name (_hello world_):
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario(){
val myScenario = scenario("hello-world")
----
. Configuring the scenario.
.. Assume the default configuration parameters: 
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario()
 val myScenario = scenario("hello-world"){ // Scenario default parameter values
    }
----
The default parameters include:
* minionCount = 1
* retryPolicy = no retry
..  Include a defined parameters within the configuration, as in the following example: 
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario(){
 val myScenario = scenario("hello-world"){ 
    minionsCount = 1000
     retryPolicy(instanceOfRetryPolicy)
     rampUp {
        regular(1000, 50)
    }
}
----
. Identifying the root of the (load-injected) tree receiving all the minions.
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario(){
 val myScenario = scenario("hello-world"){ 
    minionsCount = 1000
     retryPolicy(instanceOfRetryPolicy)
     rampUp {
        regular(1000, 50)
    }
}
.start()\\Root of the load injected tree.
----
. Adding step specifications to the tree:
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario(){
 val myScenario = scenario("hello-world"){ 
    minionsCount = 1000
     retryPolicy(instanceOfRetryPolicy)
     rampUp {
        regular(1000, 50)
    }
}
.start() // Add step specifications here.
----
== Default Scenario Configuration
Every scenario has a default configuration.

=== Number of Minions
* Optional
* Default to 1*

Whether you want to simulate users, IoT devices or third-party systems, each simulation is identified with a unique minion.
The more minions, the more load.
Minions execute concurrently and through all trees.
You can specify their default number (1000 in the following example ):
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 1000 
    }
}
----
Load-injected trees receive all the minions; non-load injected trees receive only one minion. 

=== Ramping Strategies
* Mandatory
* There is no default

Once you have specified the number of minions to be injected into your scenario, you need to specify how they will be injected.

You can use an out-of-the-box strategy or create your own.

In the following sections we will explain how to use a few of the out-of-the-box ramping strategies. 

* Accelerated Ramping Strategies
+
An accelerating ramping strategy injects either a set number of minions at an accelerated pace or an accelerated number of minions at a set pace.
+
. Accelerated pace using `faster`.
+
The following example injects 10 minions every 2000 ms, then 10 minions every 1333 (2000 / 1.5) ms, then 10 minions every 888 (2000 / 1.5 / 1.5) ms, continuing until the interval reaches 200 ms.
+
At that point, 10 minions are started every 200 ms, until they all are active.
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        rampUp {
            faster(2000, 1.5, 200, 10)
        }
    }
}
----
+
The speed-factor at runtime will be applied to the multiplication factor: a speed factor of 2 will reduce the interval twice faster.

. Accelerated number of minions using `more`.
+
The following example starts minions every 200 ms: first 10, then 20 minions after 200 ms, 40 new minions after 200 ms, to the limit of 1000 minions every 200ms until they all are active.
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        rampUp {
            more(200, 10, 2.0, 1000)
        }
    }
}
----
+
The speed-factor at runtime will be applied to the multiplication factor: a speed factor of 2 will increase the number of minions at each shot twice faster.

* `regular` Ramping Strategy
+
A regular ramping strategy sets the injection of a set amount of minions at a set pace.
+
The following example sets the execution of 200 minions every 10 ms.
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        rampUp {
            regular(200, 10)
        }
    }
}
----
+
The speed-factor at runtime will be applied to the interval: a speed factor of 2 will divide the interval by 2.
* `Timeframe` Ramping Strategy
+
A time frame ramping strategy injects an equal number of minions at an equal interval within a set timeframe.
+
The following example starts an equal number of minions every 20 ms, so that they all are active after 40000 ms.
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        rampUp {
            timeframe(20, 40000)
        }
    }
}
----
+
The speed-factor at runtime will be applied to the interval: a speed factor of 2 will divide the interval by 2.

* User Defined Ramping Strategies
+
A user-defined ramping strategy is totally open to the developer's creativity or needs. It consists of returning a `MinionsStartingLine` considering the previous period in milliseconds, the total number of minions to start and the speed factor to apply.
+
The following example first releases 1/100th of all the minions after 1000 ms, then apply different rules depending on the past interval:

* If the previous interval was longer than 2 seconds, 100th of all the minions are released after 100ms;
* Otherwise, a random interval is calculated applying the speed factor to reduce it, in order to start 10th of all the minions.
+
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        rampUp {
            define { pastPeriodMs, totalMinions, speedFactor ->
                when {
                    pastPeriodMs == 0L -> MinionsStartingLine(totalMinions / 100, 1000)
                    pastPeriodMs > 2000 -> MinionsStartingLine(totalMinions / 10, 100)
                    else -> MinionsStartingLine(totalMinions / 10,
                        ((1000 + pastPeriodMs * Math.random()) / speedFactor).toLong().coerceAtLeast(200))
                }
            }
        }
    }
}
----
+
Whatever definition you choose: 
+
* The maximum number of minions launched cannot be more than the `totalMinions`.
*  Generating a negative interval results in an immediate start.
+
* When calling the first iteration of a user-defined strategy, the initial value of `pastPeriodMs` is 0. 

=== Retry policy
* Optional
* Default = no retry

Execution of steps can fail for a variety of reasons, including, but not limited to, an unreachable remote host or invalid data. 

When a step execution fails, it may be retried if a retry policy has been set within the scenario configuration or the step configuration.

Once all attempts are executed per the defined `retryPolicy`, the step execution context is marked as exhausted and only link:05_steps.adoc[Error Processing Steps] are executed.
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        retryPolicy(instanceOfRetryPolicy)
    }
}
----
== Load-injected Tree
A scenario is a combination of directed acyclic graphs, joined by steps.

There might be several graphs starting concurrently at the scenario root, but only one graph (the specified load-injected branch) is visited by all the minions injected into the scenario.

Other graphs are considered non-injected or "side-trees" and perform data verification for when the branches rejoin.

`_myScenariostart().doSomething()_` identifies which graph is the root receiving the load of all the minions at runtime.

`_myScenario.doSomething()_` identifies a second graph visited by a unique minion and generally consisting of iterative operations such as polling of data sources.
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world") {
        minionsCount = 1000
        rampUp {
            regular(1000, 50)
        }
    }
    myScenario.start() // Root branch receiving all minions.
        .returns<String>{ "My input" }
    myScenario // Second branch visited by a unique minion.
        .returns<String>{ "My other input" }
}
----
Note that only one use of `.start()` is permitted and only one step after it.
 
To create two load-injected branches, you can use the `.split` command.

`.split` provides the output of a unique step to several steps by initiating the divergence of two load-injected branches, both running concurrently and receiving all the minions. 

In the following example, two branches are diverging: one with the step `.map{}` and a second with `flatten().filterNotNull()`.  Both run concurrently after `.split`.
[source,kotlin,linenumbers]
----
@Scenario
fun myScenario() {
    val myScenario = scenario("hello-world"){
    .start()
        .split { 
             .map {
             .returns<String>{ "My other input"
             }
            flatten() {
                .filterNotNull() 
            .returns<String>{ "My other input" }
            }
        }
    }
}
----

== Singleton Step
A singleton step is designed to be executed only once by one minion. Its purpose is to gather data to provide to the other minions as they pass through it.  The minions can use the data to feed other steps or verify expected results in the tested system.

Examples of a singleton step include:

* A database poller.
* A message consumer.

While the singleton step is executed only once, it provides provides data to all the minions passing through it.

A singleton step does not defer from other steps. It is executed using one minion, which looks like any other minion. Even if the singleton step is created on a load-injected branch, it remains aside and is proxied.

The proxy will be executed by all the minions going through the branch, while the singleton step will only have its own one, only aiming at triggering its operation: polling, reading a file, starting a message consumer, etc.

The singleton step and its proxy are connected by a topic, which actually defines the way the polled/read/ consumed records are provided to the minions.

== Data Distribution from the Singleton Step to the Load Minions
For convenience purpose, QALIPSIS proposes three different modes of distributing records out of a singleton step:

* Loop
* Unicast/Forward Once
* Broadcast

Note: You can develop your own singleton step by creating a plugin for it; refer to <<Create your own plugin>> for details.

QALIPSIS provides all required statements out-of-the-box.

=== Loop

When the number of records emitted by the singleton step is finite (such as a file), you might want to loop in the whole set of data to be sure there will always be data for the minions.

[example]
Create and insert singleton loop graphic here

All minions receive all the records.
When there is no more data for a minion, it receives the same data again from the beginning and loops on the whole set of records as long as it needs new ones.

=== Unicast/Forward Once

Each minion receives the next unused record emitted from the step. Once there are no more records to provide, all the minions remain blocked in the step.

[example]
Create and insert singleton-unicast graphic here

In the example, each of the 3 minions receives a record fairly: the first asking is served. However, since the buffer
is only 2, the first records are just lost, keeping only a buffer of 2 until the first minion requests a value.

=== Broadcast

All the minions receive all the records from the beginning. Once there are no more records to provide, all of the minions, having already received all available records, remain blocked in the step.

If the size of the buffer is limited, minions landing in the step for the first time will not receive everything from the beginning, but only from the size of the buffer.

[example]
Create and insert broadcast graphic here

In the example, the all 3 minions receive all the records in the correct order. However, since the buffer
is only 2, each newly requesting minion can only receive two records in the past at the earliest.