== Step specifications

=== Defining and Configuring a Step Specification

A step's specification is defined, depending on their nature and function, as either: 

* The root of a scenario (the first step after .start()).
+
or
* The successor of a previous step.

In the example below, `*_my-tcp_*` is the root step; `*_reuse-tcp_*` is a successor step.

[source,kotlin,linenumbers]

----
scenario("hello-netty-udp-world") {
        minionsCount = 100
        rampUp {
            
            regular(100, minionsCount)//Start all at once.
        }
    }
    .start()
    .netty()

    .tcp { //This step is the root of the Scenario.
        name = "my-tcp"
        connect {
            address("localhost", availableTcpPort)
            noDelay = true
        }
        request { tcpRequest1 }
        metrics { connectTime = true }
        events { connection = true }
    }

    .reuseTcp("my-tcp") {

        name = "reuse-tcp" //This step is a successor of the previos step and receives the previos step's output as its input.
        iterate(20, Duration.ofMillis(100))
        request { tcpRequest2 }
    }
----

A step's specification is configured so that either:

* The step receives the configuration closure {} as a parameter (as in `*_.tcp_*` and `*_.reuse-tcp_*` in the example above).
+
or
* `*_configure_*` is called after the step (as in the example below):


[source,kotlin,linenumbers]
----
    reuseTcp("my-tcp") {
        request { tcpRequest2 }
    }.configure {
        name = "reuse-tcp" 
        iterate(20, Duration.ofMillis(100)) 

        retryPolicy(instanceOfRetryPolicy) 

        timeout(2000) 
    }

----
=== Step Context

A step's context:

* Transports the data received from the previous step as its input and passes the data through the current step to its output to be forwarded to the next step.

* Transports prior errors through the step.


=== Common Load Distribution Steps

==== Fan-out

When you want to split a branch and add two concurrent steps as successors, you can execute a `*_.split_*`.

In the example below, `*_execute_*` receives the output of the previous step and provides it as input to both the _map_ and the _flatten_ steps which each do something different with the data.

[source,kotlin,linenumbers]
----

    execute { }
        .split { 
            map { ... } // <2>
                .validate{ ... }

            flatten() // <3>
                .filterNotNull()

        }
----

Here is the graphical representation:
[example]
include fan-out graphic here


NOTE: Both branches run concurrently, in no defined execution order.

WARNING: If the entity returned by `anyStep` is mutable, take care of not altering it in one branch, because this would have side-effects on the other.
Prefer creating deep clones.

==== Fan-in / Joins

Because you split a scenario into different branches or you want to verify data from different sources, you may need to join the branches.

You can join the branches in one of two ways:

* Use the name of a concurrent step.
* Create a step directly in the join.

The following example uses the name of a concurrent step:

[source,kotlin,linenumbers]
----

    execute { } //Provides an output of type `EntityWithKey`, with a field `key` being an Integer
        .innerJoin<EntityWithKey, EntityWithId>(
            on = { "${it.key}" }, //The calculation of the key from the left side is converted to a string.
            with = "my-datasource-poll-step", //The step `my-datasource-poll-step` is declared in a parallel branch (or earlier in the same branch) and provides an output of type `EntityWithId` with a field `id` being a string.>
            having = { it.id } //Closure to extract the key from the right side, which is a string.
        )
        .map { } //The result is a `Pair<EntityWithKey, EntityWithId>` where string representation of `key` of the `EntityWithKey` equals to the field `id` of the `EntityWithId`.
----


Records coming from the right side are kept in a cache until one comes from the left side with the same key. Once used, they are evicted from the cache.

When a flow comes from the left side but has no corresponding record yet coming from the right, it waits until the defined timeout on the step.
Refer to <<Configuring a Step Specification>> for more details.

The step context after the join inherits from the one coming from the left. Below is the graphical representation:

[example]
insert operators-inner-join graphic here


The following example creates a step directly in the join:

[source,kotlin,linenumbers]
----

    execute { }
        .innerJoin<EntityWithKey, EntityWithId>(
            on = { "${it.key}" },
            with = { 
                r2dbc().poll{
                    
                }
            },
            having = { it.id }
        )
        .map {}
----
This method is similar to naming a concurrent step except that a step is created in the join. The receiver of the `with` is the scenario.

==== Error processing steps

When an error occurs when executing a step, after all the potential retries, the step context being carried from top to bottom is marked as "exhausted".

From that point of the process, only the steps relevant for error processing are executed, the others are simply bypassed.

The steps relevant for error processing include:

* `catchError`: takes the collection of errors as parameter to process them.
* `catchExhaustedContext`: takes the full exhausted step context as parameter, where you can also set the `isExhausted` flag to `false` in order execute next steps.


=== Operators

QALIPSIS provides default operators to tweak the execution of your scenario, that do not require the addition of plugins to your classpath.

The list of operaters available for QALIPSIS steps is infinite.  Some of them let you transform the data, filter the data, verify the data, alter the behavior of the data, etc. You can also define your own operators.

Some of the commonly used operators are defined in this section.

==== Timing operators

* `*delay*` adds a constant delay before executing the next step, keeping the same execution pace as previous step.

[example]
insert delay graphic here

* `*pace*` ensures that the next step is executed at an expected pace, whatever the pace of the input is. The calculation applies independently to each minion.

* `*acceleratingPace*` reduces the waiting interval for at each iteration; to slow down the pace, use an accelerator lower than 1.


[example]
insert acceleratingPace graphic here

* `*constantPace*` applies a constant pace to execute the step after.

[example]
insert constantPace graphic here

=== Filter operators

* `*_filter_*` removes the step contexts having an input not matching the filter specification. Filter is a silent equivalent of validate; it does not generate an error and does not mark the step context as exhausted.

[example]
insert `*_filter(is even)_*` graphic here


* `*_validate_*` validates the input. When errors are returned, the step context is marked as exhausted and can then only be processed by error processing steps.

[example]
insert `*_validate(is even)_*` graphic here

* `*_verify_*` validates assertions rather than the input data quality/safety validated by _validate_.

[example]
insert verify(assetThat(it).isEven()) graphic here


=== Transformation operators

* `*_flatMap_*` converts a collective input into single element in the output, using a user-defined strategy.

[example]
insert verify(assetThat(it).isEven()) graphic here

* _flatten_ converts a collective input into single element in the output, for a known collective type (array, iterable).

[example]
insert verify(assetThat(it).isEven()) graphic here

* _map_ converts each element into another in the output.

* _mapWithContext_ provides the same capability as _map_ with the step context as an additional argument.

image:operators/map.svg[operators-map]

* _onEach_ executes one or several statements on each element of the input, and forwards them unchanged to the output.

image:operators/onEach.svg[operators-onEach]

=== Caching operators

* _shelve_ caches the provided values in a shared cache.
+
When using a distributed architecture, make sure the cached value
can be serialized by the used implementation of shared state registry.The ID of the minion is automatically added to
the key to avoid collusion.

* _unshelve_ fetches one or more records from the shared state registry, previously shelved with the provided keys for the same minion.

=== Utility operators

* _tube_ simply forwards the input to the output.

image:operators/tube.svg[operators-tube]

* _blackHole_ consumes the input and provides no output.

image:operators/blackHole.svg[operators-blackHole]

* _stage_ groups a linear graph of steps.
+
Stages are not mandatory in a scenario, but provide a convenient way to iterate, waiting for the last step to be completed before looping back as in the following example:

[source,kotlin,linenumbers]
----

    stage("my-stage") {
        map { it * 3 }.map { arrayOf(it, it + 100) }.flatten()
    }.configure { 
        iterate(5)
    }
----

=== Combining operators

* _collect_ collects inputs across all the minions and releases them as a list, within the latest received step context.
This operator can be seen as the opposite of the `flatten`.

image:operators/collect.svg[operators-collect]


