== Configuration

=== Starting QALIPSIS in different modes

Two modes of QALIPSIS configuration are currently supported:

* Interactive
* Scenario Selection

==== Interactive

 . Execute QALIPSIS with the option `--prompt` or `-p`.
as in the following example:
+
[source,bash]
----
java -jar my-scenario-qalipsis.jar --prompt
----

. When prompted, enter the load factor (# of minions), speed factor, rampUp strategy, etc. 

==== Scenario Selection

. Execute QALIPSIS with the `--scenarios` or `-s` as in the following example:
+
[source,bash]
----
java -jar my-scenario-qalipsis.jar --scenarios "my-first-scenario, ?y-*-s*n?rio"
----
+
The value is a comma-separated list of an exact value of a scenario, a pattern of the scenario, or both. The pattern may contain wildcards (* or ?) as in the example above.


=== Runtime configuration

==== Command-line arguments

This section provides a overview and example of the command-line arguments that are available at runtime.

Not that all command-line arguments can be provided in a file, as explained in <<External Property Sources>>.

. Number of Minions by Scenario.
+
This command defines how many minions should be used in the load-injected tree. It is not compliant with `campaign.minions-factor`.
+
Following is an example of the command to set the number of minions:
+
[source,bash]
----
campaign.minions-count-per-scenario=#ofMinions
----
+
where `# ofMinions` is an integer and the default value is the `minionCount` set during configuration of the scenario.

+

. Load Factor.
+
The load factor command multiplies the number of minions set during scenario configuration by the provided value. It is not compliant with `campaign.minions-count-per-scenario`.
+
* If the value is set between 0 and 1, the `minionCount` is reduced.

* If the value is set to greater than one (or `double`,`triple`, `quadruple`, etc)  the `minionCount` is increased. 

* The default value is always set to `1`.
+
Following is an example of the command to set the load factor:
+
[source,bash]
----
campaign.minions-factor, double, default to 1
----

+
. Speed Factor.

The speed factor command is applied on the ramp-up to accelerate or slow down the pace of the minions to be started.

For example:

[source,bash]
----
`campaign.speed-factor`, double, default to 1
----

The value for the speed factor are defined the same as for load factor.




==== External Property Sources

QALIPSIS uses Micronaut's runtime underneath.
Hence, you can use its mechanism of https://docs.micronaut.io/latest/guide/index.html#propertySource[externalized configuration with property sources].

You can overwrite the default configuration and add your own properties by creating a file called `application-config.yml` either in the class path or in the working directory.

You can also specify additional environments using the parameter `--environments` (shorthand `-e`) and the required list:

[source,bash]
----
java -jar my-scenario-qalipsis.jar -e my-scenario,production
----

When overwriting the default configuration file and specifying additional environments, the following  configuration files are applied:

*  `application-my-scenario.{extension}`

* `application-production.{extension}` 

where `{extension}` can be `.properties`, `.json` or `.yml`.

=== Injecting configuration in a scenario

You can inject values into your scenario or its declaring class using the annotation `@io.qalipsis.api.annotations.Property` as in the following example:
[source,kotlin]
----
class EcommercePurchase(@Property("ecommerce-purchase.load") private val numberOfMinions: Int) {

    @Scenario
    fun fromLoginToCheckout(@Property("ecommerce-purchase.action-pace") actionPaceDuration: Duration) {
        scenario("login-select-and-checkout"){
            minionsCount = numberOfMinions
        }
        .constantPace(actionPaceDuration.toMillis())
        
    }
}
----
