= Plugins

== Introduction
A plugin is a technical extension designed to extend the core capabilities of QALIPSIS.

Plugins: 

* Tackle the complexity implied by the multiplicity of technologies and use cases to support in the tool.
* Reduce the coupling between the technical elements, keeping them safer and easier to maintain.

The main advantages of using plugins are:

* A drastic reduction in the footprint of required libraries to run a scenario.
* A better user/developer experience, including:
**  The ability to focus on what is absolutely relevant to the user/developer.
** Having a smaller list of proposals when using auto-completion.
** Faster compilation and start times.
** Smaller artifacts to store, transport and share.

By nature, a plugin is an optional component of QALIPSIS. It allows you to include only what you need while ignoring components and libraries that do not serve your your present concerns.

While a certain number of plugins are proposed by the community to cover the most common use cases and technologies, a plugin can also be an extension only for yourself and remain private.

== Plugin Functionality
A plugin contains one or several technical functionalities of the software that are not part of the core. The most common functionalities that a plugin might implement are:

* A step to perform an action, such as:
** Executing requests on a remote system using a specific protocol.
** Polling data from a source.
** Transforming data.
* An events logger.
* A meter registry.
 
Default implementations of the above functionalities are part of the QALIPSIS core. However, the default implementations may not be suited for your scenario (e.g., if productive testing or constant monitoring are requirements). QALIPSIS plugins enhance the above functionalities by providing related implementations.

== Plugin Integration
To create a test scenario, a tiny Gradle project is required. The plugin is simply added as a dependency to the class path of the project. You can read more about scenario configuration within the <<Quickstart Guide: Testing an HTTP Server with Qalipsis>>.

If the development of a scenario requires the plugin to compile (when using a step, for example), the dependency to the plugin artifact must be added to the `implementation` dependencies.

If the plugin delivers functionalities that you only need at runtime, add it to the `runtimeOnly` dependencies.

== Using QALIPSIS Plugins
QALIPSIS provides several plugins targeting different technologies, systems and protocols.

To use a plugin, add the related dependency to your project:

Gradle - Groovy DSL:
[source,groovy,subs="normal"]
----
implementation group:'io.qalipsis', name: 'plugin-XXX', version: '{revnumber}'
----
Gradle - Kotlin DSL:
[source,kotlin,subs="normal"]
----
implementation("io.qalipsis:plugin-XXX:{revnumber}")
----

== QALIPSIS Available Plugins

In this section, documentation is provided for currently available plugins that can be used with your QALIPSIS project.

This section will be updated as more plugins are available.

Note: Before using a plugin, confirm that the related dependency has been added to your project:

* Gradle - Groovy DSL:
+
`implementation group:'io.qalipsis', name: 'plugin-XXX', version: '{revnumber}`

* Gradle - Kotlin DSL:
+
`implementation("io.qalipsis:plugin-XXX:{revnumber}")`

[cols="1,3"]
|===

|  *Name*
|  *Description*

|link:#_cassandra-plugin[cassandra]
|Connects QALIPSIS to https://cassandra.apache.org/index.html[APACHE Cassandra].

|link:#_elasticsearch-plugin[elasticsearch]
|Connects QALIPSIS to https://www.elastic.co/[Elasticsearch].

|link:#_graphite-plugin[graphite]
|Waiting on info...

|link:#_influxdb-plugin[influxdb]
|Connects QALIPSIS to https://www.influxdata.com/[InfluxDB].

|link:#_jackson-plugin[jackson]
|Supports reading a file https://github.com/FasterXML/jackson[(JSON, XML or CSV)], converting the data to an object, and pushing the object to the next step.

|link:#_jms-plugin[jms]
|Connects QALIPSIS to a messaging platform that supports https://www.oracle.com/java/technologies/java-message-service.html[JMS] (for example, https://activemq.apache.org/[ActiveMQ]).

|link:#_kafka-plugin[kafka]
|Connects QALIPSIS to an https://kafka.apache.org/[Apache Kafka] cluster.

|link:#_mongodb-plugin[mongodb]
|Connects QALIPSIS to https://mongodb.com/[MongoDb].

|link:#_netty-plugin[netty]
|Supports https://datatracker.ietf.org/doc/html/rfc793[TCP], https://datatracker.ietf.org/doc/html/rfc768[UDP], https://httpwg.org/[HTTP] and https://mqtt.org/[MQTT] clients

|link:#_r2dbc-jasync-plugin[r2dbc-jasync]
|Connects connects QALIPSIS to https://mariadb.org/[MariaDB], https://www.mysql.com[MySQL] and https://www.postgresql.org/[PostgreSQL].

|link:#_rabbitmq-plugin[rabbitmq]
|Connects QALIPSIS to https://www.rabbitmq.com/[RabbitMQ].

|link:#_redis-lettuce-plugin[redis-lettuce]
|Connects QALIPSIS to https://redis.io/[Redis].
|===


<<<<

include::{includedir}/sections/plugins/08b_cassandra.adoc[]

<<<<

include::{includedir}/sections/plugins/08c_elasticsearch.adoc[]

<<<<

include::{includedir}/sections/plugins/08d_graphite.adoc[]

<<<<

include::{includedir}/sections/plugins/08e_influxdb.adoc[]

<<<<

include::{includedir}/sections/plugins/08f_jackson.adoc[]

<<<<

include::{includedir}/sections/plugins/08g_jms.adoc[]

<<<<

include::{includedir}/sections/plugins/08h_kafka.adoc[]

<<<<

include::{includedir}/sections/plugins/08i_mongodb.adoc[]

<<<<

include::{includedir}/sections/plugins/08j_netty.adoc[]

<<<<

include::{includedir}/sections/plugins/08l_r2dbc-jasync.adoc[]

<<<<

include::{includedir}/sections/plugins/08m_rabbitmq.adoc[]

<<<<

include::{includedir}/sections/plugins/08n_redis-lettuce.adoc[]
