= Available Plugins

== Overview
In this section, documentation is provided for currently available plugins that can be used with your QALIPSIS project.

This section will be updated as more plugins are available.

Note: Before using a plugin, confirm that the related dependency has been added to your project:

* Gradle - Groovy DSL: 
+
`implementation group:'io.qalipsis', name: 'plugin-XXX', version: '{revnumber}`

* Gradle - Kotlin DSL: 
+ 
`implementation("io.qalipsis:plugin-XXX:{revnumber}")`

[cols="1,3"]
|===

|  *Name* 
|  *Description*

|<<cassandra Plugin,cassandra>>
|Waiting on info

|<<elasticsearch Plugin,elasticsearch>>
|Connects Qalipsis to Elasticsearch using the REST client and a query.

|<<graphite Plugin,graphite>>
|Waiting on info...

|<<influxdb Plugin,influxdb>>
|Connects Qalipsis to InfluxDB using InfluxDbClientKotlin with Flux v.2.0.

|<<jackson Plugin,jackson>>
|Waiting on info... 

|<<jms Plugin,jms>>
|Connects Qalipsis to ActiveMQ using jms.

|<<kafka Plugin,kafka>>
|Connects Qalipsis to the Kafka broker.

|<<mongodb Plugin,mongodb>>
|Connects Qalipsis to MongoDb using the mongodb-driver-sync
driver from org.mongodb

|<<netty Plugin,netty>>
|Supports TCP, UDP, HTTP and MQTT using the non blocking Netty plugin

|<<r2dbc Plugin,r2dbc>>
|Waiting on info...

|<<rabbitmq Plugin,rabbitmq>>
|Connects Qalipsis to the RabbitMQ broker.

|<<r2dbc-jasync Plugin,r2dbc-jasync>>
|Connects Qalipsis to MariaDB, MySQL and PostgreSQL using the R2DBC drivers from jasync-sql.

|<<redis-lettuce Plugin,reddis-lettuce>>
|Connects Qalipsis to Redis using the Lettuce client.
|===


== cassandra Plugin
The `cassandra` plugin ......


== elasticsearch Plugin
The `elasticsearch` plugin connects Qalipsis to Elasticsearch using the REST client and a query.

Technology Addressed::
Elasticsearch: https://www.elastic.co/

Dependency::
`_io.qalipsis:plugin-elasticsearch_`

Namespace in Scenario::
`_elasticsearch()_`

Client Library::
To configure a connection to Elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html

Supported Steps::
* <<Poll Step (elasticsearch),Poll>>: polls newest data periodically.
* <<Save Step (elasticsearch),Save>>: saves a batch of records generated from the input and step context.
* <<Search Step (elasticsearch),Search>>: searches records, building a query from the input and step context.

=== Poll Step (elasticsearch)
The `poll` step within the `elasticsearch` plugin periodically polls data from Elasticsearch. The output is a list of [ElasticsearchDocument]and contains maps of column names to values. 

This step is generally used in conjunction with a left join to assert data or inject them in a workflow

Ancestor::
Scenario or Step

Functionality::
* The selected query is created by the scenario developer once and used as called in the scenario. 
* The query requires at least one sorting field (known as SF below) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for the SF is known as the tiebreaker which  filters out the values already received directly from the database.
However, we apply a strategy of “delivered at least once” and cannot avoid the records at the boundaries (having their value of SF equal to the tiebreaker) to be delivered several times.
* The output is a list of [ElasticsearchDocument] that contains maps of column names to values. When [flatten] is called, the records are provided one by one to the next step, otherwise each poll batch remains complete

Example::
+
[source,kotlin,linenumbers]
----
elasticsearch().poll {
  index("building-moves")
  client {
        RestClient.builder(HttpHost("localhost", esPort, "http")).build()
  }
   query {
       """{
           "query": {
               "term": {
                   "action": "IN"
               }
           },
           "size": 2,
           "sort":["timestamp","username"]
       }""".trimIndent()
   }
   pollDelay(Duration.ofSeconds(1))
}
----
Notable Parameters::
* To configure the connection: provide the port, build the REST client, and create an index.
* `_client_`: configures the REST client to connect to Elasticsearch.
* `_query_`:  the builder for the JSON query to perform the first poll.
+ 
Behind the scene we use Elasticsearch capability for "search after" and the tie-breaker is extracted from the sort clauses. 
+
Default sorts to all the documents in the target are sorted by `_id_`.
+
Refer to the <https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after[elasticsearch documentation]> for an explanation of the limitations.
* `_index()_`: sets the elasticsearch indices to use for the queries. The default vaule is `_all_`.
* `_queryParameters_` (optional):adds query parameters.
 See the [official documentation] for the values: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params
* `_mapper_`: configures the JSON Mapper to deserialize the records.
* `_pollDelay_` (required): specifies the delay between two executions of the query

=== Save Step (elasticsearch)
The `_save_` step within the `_elasticsearch_` plugin persists a batch of records into Elasticsearch using a document.

Ancestor::
Step

Functionality::
 The input and step context are used to generate the list of Documents which are  forwarded to the Elasticsearch 


Example::
+
[source,kotlin,linenumbers]
----
elasticsearch().save {
             documentsFactory = documentsFactory
            client{
                 RestClient.builder(HttpHost("localhost", esPort, "http")).build()
            }
	monitoring {
	  events = false
                meters = true
            }
}
----

Notable Parameters::
To configure the connection, provide the port, build the REST client, and create the index.
* `_client_` configures the REST client to connect to Elasticsearch.
* `_documents_` defines the statement to execute when saving.
* `_monitoring_` configures the monitoring of the save step.
* `_mapper_` configures the JSON Mapper to deserialize the records.

The `_save_` is extremely flexible; values may depend on the context and input value received from the previous step.
 
=== Search Step (elasticsearch)
The `_search_` step within the `_elasticsearch_` plugin searches records in the Elasticsearch using a search query. Refer to the current
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html[elasticsearch documentation].

 Ancestor::
 Step
 
Functionality::
 The input and step context are used to generate a Documentt and the values to complete it; the batch of results is then forwarded to the next steps.

Example::
+
[source,kotlin,linenumbers]
----
elasticsearch().search {
           client(clientBuilder)
           mapper(mapperConfigurer)
           index(indicesFactory)
           query(queryFactory)
           queryParameters(paramsFactory)
           monitoring {
                  all()
           }
         fetchAll()

----
 
Notable Parameters::
 · To configure the connection, provide the port, build the REST client, and create the index.
* `_client_`: configures the REST client to connect to Elasticsearch.
* `_query_` is a builder for the JSON query to perform for first poll. Behind the scene we use Elasticsearch capability for "search after" and the tie-breaker is extracted from the sort clauses. Defaults to all the documents in the target sorted by `_id_`.
See the [official documentation] to know the limitations: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after
* `_index_`: sets the elasticsearch indices to use for the queries; defaults to `_all_`.
* `_queryParameters_`: (optional): adds parameters to the query.
 See the [official documentation] for the values: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params
* `_mapper_` configures the JSON Mapper to deserialize the records.
 * `_monitoring_`: configures the monitoring of the search step.
 * `_fetchAll_`: specifies that all the documents have to be fetched, even over the result-sized window. 
  +
 `_fetchAll_` has to be combined with either a scroll activation or a sorting definition in the query.
  +
 The latter case will use search after to page all the data, meaning that new data coming between two requests will be fetched. The requests stop when the number of fetched documents reaches the total hits of the latest response.

== graphite Plugin
The `_graphite_` plugin connects or supports...

== influxdb Plugin
The `_influxdb_` plugin connects Qalipsis to InfluxDB using InfluxDbClientKotlin with Flux v.2.0.

Technologies Addressed::
* InfluxDB: https://www.influxdata.com/ 
* Flux: https://docs.influxdata.com/flux/v0.x/  

Dependency::
`_io.qalipsis:plugin-influxdb_`

Namespace in Scenario::
`_influxdb()_`

Client Library::
`_influxdb-client-kotlin_` is an asynchronous database client for InfluxDb written in Kotlin
https://github.com/influxdata/influxdb-client-java/tree/master/client-kotlin[influxdb-client-java/client-kotlin/]

Supported Steps::
* <<Poll Step (influxdb),Poll>>: polls the newest data periodically.
* <<Save Step (influxdb),Save>>: saves a batch of records generated from the input and step context.
* <<Search Step (influxdb),Search>>: searches records, building a query from the input and step context.

=== Poll Step (influxdb)
The `_poll_` step within the `_influxdb()_` plugin polls the newest records from a database table.

Ancestor::
Scenario or Step

Functionality::
* The select query is created once by the scenario developer and used throughout the scenario as called.
* It requires at least one sorting field (known as SF below) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for the SF is known as the tiebreaker which filters out the values already received directly from the database.
* Poll uses a strategy of “delivered at least once” that cannot avoid the records at the boundaries (with an  SF equal to the tiebreaker) from being delivered several times.

Example::
+
[source,kotlin,linenumbers]
----
iinfluxdb().poll {
            name = "poll.in"
            connect {
                   server("http://localhost:8080", BUCKET, ORGANIZATION)
                   basic("user", "passpasspass")
             }
            query("from(bucket: \"$BUCKET\") |> range(start: 0) |> filter(fn: (r) => (r[\"tag\"] == \"IN\") |> sort([\”_time\”], desc: false")
            pollDelay(Duration.ofSeconds(1))
}
----

Notable Parameters::
* To configure the connection, provide the URL, organization name, bucket, and token for this method. The token can be automatically created using your password and username.
* query (required) specifies a query respecting the requirements of the Flux v.2.0  https://docs.influxdata.com/flux/v0.x/  
* tieBreaker (required) repeats the first field used for sorting and comparison: <= or >= depends on the ascending or descending order
* parameters (optional) binds values to the clauses of the prepared query
* pollDelay (required) specifies the delay to wait between two executions of the query

Tip::
Use the poll step with a join operator to verify the values that the tested system saves to the database.

=== Save Step (influxdb)
The save step within the `_influxdb()_` plugin persists a batch of records into the influxdb bucket using a specific `_points_` class.

Ancestor::
Step

Functionality::
The input and step context are used to generate the bucket, the list of Points with their measurement, tags and fields, which are all combined and forwarded to the database

Example::
+
[source,kotlin,linenumbers]
----
influxdb().save {
          connect {
                    server(
                            url = "http://localhost:8080",
                            bucket = "test", 
                            org = "testtesttest"
                            )
                   basic(
                             user = "user", 
                             password  = "passpasspass"
                             )
          }
          query {
                   bucket = bucketName
                   organization = orgName
                   points = pointSupplier
          }
          monitoring {
                   events = true
                   meters = false
          }
}
----

Notable Parameters::
* To configure the connection, provide the URL, organization name, bucket, and token for this method. Token automatically can be created using your password and username.
* The step is extremely flexible: bucket, tags, measurement and fields might depend on the context and input value received from the previous step.

Tip::
Use this step after a `_collect()_` step to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the tested system.


=== Search Step (influxdb)
The `_search_` step within the `_influxdb_` plugin searches the records in the database.

Ancestor::
Step

Functionality::
The input and step context are used to generate a Point and the values to complete it; the batch of results is then forwarded to the next steps.

Example::
+
[source,kotlin,linenumbers]
----
influxdb().search {
          connect {
                    server(
                            url = "http://localhost:8080",
                            bucket = "test", 
                            org = "testtesttest"
                            )
                   basic(
                             user = "user", 
                             password  = "passpasspass"
                             )
          }
          query {
                   bucket = bucketName
                   organization = orgName
                   points = pointSupplier
          }
           parameters { ctx, input -> listOf("ENTERING") }
          monitoring {
                   events = true
                   meters = false
          }
}
----

Notable Parameters::
* To configure the connection, provide the URL, organization name, bucket, and token for this method. The token can automatically be created with your password and username.
* query: generates points from the context and input.
* parameters: generates a list of values to bind onto the query parameters identified.

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load the scenario generates on it.

== jackson Plugin
The `jackson` plugin connects or supports...

== jms Plugin
The `jms` plugin Connects Qalipsis to ActiveMQ using jms.

Technology Addressed::
ActiveMQ: https://activemq.apache.org/components/artemis/documentation/latest/using-jms.html

Dependency::
io.qalipsis:plugin-jms

Namespace in Scenario::
 jms()
 
 Client Library::
 The Java Message Service (JMS) API provides a common way for Java programs to create, send, receive and read an enterprise messaging system's messages.
Refer to https://docs.oracle.com/javaee/7/api/javax/jms/package-summary.html[Java Interface Summary] for more information.

 
Supported Steps::
* <<Consume Step (jms),Consume>>: consumes data from activeMq  queues and topics
* <<Produce Step (jms),Produce>>: produces messages into activeMQ

 
=== Consume Step (jms)
The `consume` step within the `jms` plugin consumes records from ActiveMQ.
 
Ancestor::
Scenario or Step
 
Functionality::
The developer provides the connection, the consumer and the deserializer for the data
 
Example::
+
[source,kotlin,linenumbers]
----
.jms()
            .consume {
                queues("queue-1")
                queueConnection { ActiveMQConnectionFactory().createQueueConnection() }
                monitoring {
                    events = true
                    meters = true
                }
                metrics {
                    bytesCount = true
                    recordsCount = true
                }
            }.deserialize(JmsJsonDeserializer(User::class))

----
 
Notable Parameters::

* To configure a connection, provide using the java activeMq connection for either queues (QueueConnection) or topics(TopicConnection)

* If the connection is a queueConnection use queues; oOtherwise use topics.
* To deserialize a json text use JmsJsonDeserializer and provide the desired class to use in the deserialization. In the case of a deserialize just a string, use JmsStringDeserialize
 
=== Produce Step (jms)
The `_produce_` step within the jms plugin produces records in ActiveMQ using JMS.
 
Ancestor::
Step
 
Functionality::
The developer provides the connection, and a list of records to be produced into one or more JMS destinations. The values could be provided by previous steps.
 
Example::
+
[source,kotlin,linenumbers]
----
.jms().produce {
                records { ctx, input ->
                    listOf(
                        JmsProducerRecord(
                            destination = ActiveMQQueue().createDestination("queue-1"),
                            messageType = JmsMessageType.TEXT,
                            value = "hello-queue"
                        ),
                        JmsProducerRecord(
                            destination = ActiveMQQueue().createDestination("queue-1"),
                            messageType = JmsMessageType.AUTO,
                            value = "another message".toByteArray()
                        )
                    )
                }
               connect { ActiveMQConnectionFactory().createQueueConnection() }
                monitoring {
                    events = true
                    meters = true
                }
                metrics {
                    bytesCount = true
                    recordsCount = true
                }
----

 Notable Parameters::
* To configure the connection, provide using the java activeMq connection for either queues (QueueConnection) or topics(TopicConnection)
* JmsMessageType possible values are: TEXT, AUTO, BYTES, OBJECT. Use AUTO if the type of the value is not known, as it will try to infer the type and produce the message

== kafka Plugin
The `kafka` plugin connects Qalipsis to the Kafka broker.
 
Technology Addressed::
 Kafka: https://kafka.apache.org/

Dependency::
 `io.qalipsis:plugin-kafka`

Namespace in Scenario::
 `kafka()`

Client Library::
 Kafka is open-source stream-processing software for collecting, processing, storing, and analyzing data. Refer to https://kafka.apache.org/[APACHE KAFKA].

Supported Steps::
* <<Consume Step (kafka),Consume>>: polls data from topics of an Apache Kafka cluster.
* <<Produce Step (kafka),Produce>>: pushes data onto topics of a Kafka broker.

=== Consume Step (kafka)
The `consume` step within the `kafka` plugin polls data from topics of an Apache Kafka cluster and forwards the data to the next step, either in batches or individually.

This step is generally used in conjunction with a left join to assert data or inject data into a workflow.

The `consume` step supports multithreading (concurrent consumers) using the `concurrency` property.

 Ancestor::
 Scenario or Step.
 
Functionality::
 * The topic name or pattern used for subscribtion. 
 * KafkaConsumer start polling loop for client
with the certain groupId. When new records appear, consumer poll them and send to the next step. 
* After recieving the records consumer Close the polling loop for this certain client


Example::
+
[source,kotlin,linenumbers]
----
kafka().consume {
   name = "kafka-consumer"
   bootstrap(bootstrap)
   topics(testProducerTopic)
   groupId("kafka-left")
   pollTimeout(100)
   offsetReset(OffsetResetStrategy.EARLIEST)
}
----
 
Notable Parameters::
 * To configure the consumer, consult the documentation of kafka: 
 https://kafka.apache.org/[APACHE KAFKA].
* `bootstrap` configures the bootstrap hosts of the Kafka cluster; defaults to localhost:9092.
* `topics` defines the list of topics to consume, exclusive with [topicsPattern].
* `pollTimeout` defines the consumer poll timeout to wait for records; defaults to 1 second.
* `offset` defines the strategy to apply when the consumer group is not known from the cluster; defaults to [OffsetResetStrategy.LATEST].
* `maxPolledRecords` defines the maximum number of records returned in a unique poll batch;default value is 500.
* `groupId` defines the consumer group.

Tip::
   Use this step with a left join to assert data or inject data into a workflow.

=== Produce Step (kafka)
The `produce` step within the `_kafka_` plugin pushes data onto topics of the Kafka broker and forwards the input to the next step.

Ancestor::
 Scenario or Step
 
Functionality::
 The input and step context are used to generate the values to complete the step. The batch of results or a single result is then forwarded to the next step.

Example::
+
[source,kotlin,linenumbers]
----
kafka().produce(
   Serdes.ByteArray().serializer(),
   Serdes.String().serializer()
) {
   name = "kafka-producer"
   bootstrap(bootstrap)
   clientName("producer")
   records { _, input ->
       listOf(
           KafkaProducerRecord(
               topic = producerTopic,
               value = "Produced ${input.record.value!!}"
           )
       )
   }
       monitoring {
                   events = true
                   meters = false
          }
}
----
 
Notable Parameters::
 * To configure the producer, consult the documentation of kafka: 
 https://kafka.apache.org/[APACHE KAFKA].
* `bootstrap` configures the bootstrap hosts of the Kafka cluster; default is set to localhost:9092.
* `clientName` defines the name of the client used in the kafka client
* `properties` configures additional properties for the producer, as documented in https://kafka.apache.org/documentation/#producerconfigs[Kafka Producer Configs].
* `records` defines the records to be published, it receives the context and the output from previous step that can be used when defining the records.
* `monitoring` configures the monitoring of the produce step.

== mongodb Plugin
The `mongodb` plugin connects Qalipsis to MongoDb using the mongodb-driver-sync
driver from https://javadoc.io/doc/org.mongodb/mongodb-driver-sync/latest/index.html[mongodb.org].

Technology Addressed::
MongoDB: https://www.mongodb.com/



Dependency::
`_io.qalipsis:plugin-mongodb_`

Namespace in Scenario::
`_mongodb()_`

Client Library::
mongodb-driver-sync is the synchronous Java driver:
https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync


Supported Steps::
* <<Poll Step (mongodb),Poll>>: polls newest data periodically
* <<Save Step (mongodb),Save>>: saves a batch of records generated from the input and step context
* <<Search Step (mongodb),search>>: searches records, building a query from the input and step context

=== Poll Step (mongodb)
The `_poll_` step within the `_mongodb_` plugin polls the newest records from a database table, with a delay between each execution.

Ancestor::
Step or scenario

Functionality::
* The select query is created once by the scenario developer used throughout the scenario as called.
* The query requires at least one sorting field (known as SF in the example) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for the SF is known as the tiebreaker which  filters out the values already received directly from the database.
* Poll uses a strategy of “delivered at least once” that cannot avoid the records at the boundaries (with an  SF equal to the tiebreaker) from being delivered several times.

Example::
+
[source,kotlin,linenumbers]
----
mongodb().poll {
        connect { MongoClients.create("mongodb://localhost:${mongoDbPort}/?streamType=netty") 
        }
        search {
            database = "the-db"
            collection = "moves"
            query = Document().append("action", "IN")
            sort = linkedMapOf("timestamp" to Sorting.ASC)
            tieBreaker = "timestamp"
          }
          pollDelay(Duration.ofSeconds(1))
}
----

Notable Parameters::
* To configure the connection, provide the port, database name  and collection name.
* query (required) specifies a Document respecting the requirements of the target database
* tieBreaker (required) repeats the first field used for sorting
* parameters (optional) binds values to the clauses of the prepared statements
* pollDelay (required) specifies the delay to wait between two executions of the query

Tip::
Use this step with a join operator when you need to verify the values saved by your tested system in the database


=== Save Step (mongodb)
The `_save_` step within the _mongodb_` plugin persists a batch of records into MongoDB using a document.

Ancestor::
Step

Functionality::
The input and step context are used to generate the table, the list of columns and their values, which are all combined and forwarded to the database

Example::
+
[source,kotlin,linenumbers]
----
mongodb().save {
    connect {
      MongoClients.create()
    }
    query {
      database = databaseName
      collection = collectionName
      records = recordSupplier
    }
	  monitoring {
	    events = false
      meters = true
    }
}
----

Notable Parameters::
* To configure the connection, provide the port, database name  and collection name.
* The step is extremely flexible: table, columns and values might depend on the context and input value received from the previous step

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.

=== Search Step (mongodb)
The `_search_` step within the `_mongodb_` plugin searches records in the database.

Ancestor::
Step

Functionality::
The input and step context are used to generate a document and the values to complete it; the batch of results is then forwarded to the next steps

Example::
+
[source,kotlin,linenumbers]
----
mongodb().search {
	connect {
    MongoClients.create()
  }
  search {
    database = { _, _ -> "db" }
    collection = { _, _ -> "col" }
    query = { _, _ -> Document() }
    sort = { _, _ -> linkedMapOf("asc" to Sorting.ASC, "desc" to Sorting.DESC) }
  }
  monitoring {
	  events = false
    meters = true
  }
}
----

Notable Parameters::
* To configure the connection, provide the port, database name  and collection name.
* query (required) specifies a Document respecting the requirements of the target database

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.

== netty Plugin
The `netty` plugin supports TCP, UDP, HTTP and MQTT using the non blocking Netty plugin.

Technologies Addressed::
* HTTP/1.1: https://datatracker.ietf.org/doc/html/rfc2616
* HTTP/2: https://datatracker.ietf.org/doc/html/rfc7540
* MQTT: https://mqtt.org/
* TCP (Transmission Control Protocol): https://datatracker.ietf.org/doc/html/rfc793
* UDP (User Datagram Protocol): https://datatracker.ietf.org/doc/html/rfc768

Dependency::
`_io.qalipsis:plugin-netty_`

Namespace in Scenario::
`_netty()_`

Client Library::
Netty: https://netty.io/

Supported Steps::
* <<HTTP Step (netty),HTTP>>: client for HTTP 1.1 and HTTP 2.0.
* <<HTTP WITH Step (netty),HTTP WITH>>: executes a HTTP request reusing the HTTP connection created by precedent step.
* <<CLOSE HTTP Step (netty),CLOSE HTTP>>: closes the HTTP connection created by a precedent step.
* <<MQTT Publish Step (netty),MQTT Publish>>: sends data to an MQTT server.
* <<MQTT Subscribe Step (netty),MQTT Subscribe>>: consumes data from an MQTT server.
* <<TCP Step (netty),TCP>>: client to exchanges data with a TCP server
* <<TCP WITH Step (netty),TCP WITH>>: exchanges data reusing the TCP connection created by precedent step
* <<CLOSE TCP Step (netty),CLOSE TCP>>: closes the TCP connection created by a precedent step
* <<UDP Step (netty),UDP>>: client to exchanges data with UDP

=== HTTP Step (netty)
The `_HTTP_` step within the `_netty_` plugin is a client for HTTP 1.1 and HTTP 2.0

Ancestor::
Step or Scenario

Functionality::
* An HTTP connection is established with the server using either a pool of connections or an individual connection for each minion. 
* In the latter case, the connection is maintained until the latest execution for the minion was performed, including the ones from related steps HTTP WITH (see below).
* When the step is kept open without limit, a later step CLOSE HTTP should be executed to properly close the connections and avoid a saturation of the system.
+

Be aware that the number of connections that can be concurrently maintained open depend on the configuration of your operating system. Among others, you should consider adapting the limits for file descriptors.

Example::
+
[source,kotlin,linenumbers]
----
netty().http {
   request { context, input -> SimpleHttpRequest(HttpMethod.HEAD, "/head") }
   connect {
       url("https://my-website.com:8080/test")
       connectTimeout = Duration.ofMinutes(1)
       inflate()
       charset(Charsets.ISO_8859_1)
       maxContentLength(123)
       followRedirections(15)
       noDelay = false
       keepConnectionAlive = false
       tls {
           disableCertificateVerification = true
       }
       proxy {
           type = HttpProxyType.SOCKS5
           address("my-proxy", 9876)
       }
       followRedirections(5)
   }
   pool {
       size = 143
       checkHealthBeforeUse = true
   }
   monitoring {
       events = true
       meters = true
   }
}.deserialize(String::class)

----

Notable Parameters::
* request: a factory to create the request to exchange, using the step context and the input as arguments
* connect: configures the connection to the remote endpoint
** version: version of the HTTP protocol to use: HTTP_1_1 or HTTP_2_0, defaults to HTTP_1_1
** url: the root URL, the path of the request is appended to it
connectTimeout: limit duration to fully establish the connection, defaults to 10 seconds
** readTimeout: limit duration to receive a response and read it totally after a request, defaults to 10 seconds
** shutdownTimeout: limit duration to close a connection, defaults to 10 seconds
** sendBufferSize: the size of the buffer used to prepare the data to send, defaults to 1024 bytes
** receiveBufferSize: the size of the buffer to receive the data of the response, defaults to 1024 bytes
** nettChannelOptions: overwrites the options of the Netty channel, use with care
** noDelay: disables the Nagle Algorithm, defaults to true
** keepConnectionAlive: when set to true, the HTTP header Connection is set to Keep-Alive and the client connection is kept open until closeHttp() is called
** tls: configuration for SSL/TLS
*** disableCertificationVerification: set it to true when the certificate on server should not be verified (for example for a self-signed certificate)
*** protocols: supported protocols (defaults to the default ones of Netty for the related HTTP version)
*** ciphers: supported cipher algorithms (defaults to the default ones of Netty for the related HTTP version)
** proxy: configuration to exchange HTTP data via a proxy, defaults to no configuration
*** address: the host and port of the proxy
*** type: type of the proxy to use: HTTP, SOCKS5, default to HTTP
*** authenticate: username and optional password to authenticate to the proxy, if it supports and requires it
** charset: character encoding of the HTTP requests, 
** maxContentLength: maximal expected size of a request, in bytes, defaults to 1048576, which is the minimum allowed
** inflate: enables the acceptance of compressed response. Compression of the request is not supported.
** followRedirections: when the server returns a HTTP status 3xx (redirection) in the response, the client will resend the request to the provided location. Otherwise, the response is kept as this. The argument maxRedirections provides the maximal number of redirections to follow and defaults to 10. By default, the redirections are not followed at all. Note that following a redirections makes the request to be sent there, exactly as it is (same method and content).
* pool: configuration of the pool of connections (the pool is disabled by default)
** size: number of constants connections maintained in the pool
** checkHealthBeforeUse: verifies the health of the connection when polled from the pool and before it is used
* deserialize: specifies the class to use to deserialize the body of the response

=== HTTP WITH Step (netty)
The `_HTTP WITH_` step within the `_netty_` plugin executes an HTTP request reusing the HTTP connection created by precedent step

Ancestor::
Step

Functionality::
* The HTTP WITH step is a direct or indirect follower of an HTTP step. HTTP WITH specifies the name of the step that owns the connection, and reuses a connection from that step, as it was created (either from a pool or the connection attached to the minion).
* HTTP WITH cannot configure the connection differently than the HTTP step.

Example::
[source,kotlin,linenumbers]
----
nnetty().httpWith("name-of-a-previous-HTTP-step") {
   request { context, input -> SimpleHttpRequest(HttpMethod.HEAD, "/head") }
   monitoring { all() }
}.deserialize(String::class)
----

Notable Parameters::
* request: a factory to create the request to exchange, using the step context and the input as arguments
* deserialize: specifies the class to use to deserialize the body of the response


=== CLOSE HTTP Step (netty)
The `_CLOSE HTTP_` step within the `_netty_` plugin closes the HTTP connection attached to the minion, and created by a direct or indirect ancestor step, when the tail of the minion workflow is received. 

It is always a best practice to use such a step when reusing a HTTP connection across several steps without a pool of connections. 


Ancestor::
Step

Functionality::
The `_CLOSE HTTP_` step is a direct or indirect follower of an `_HTTP_` step, which keeps the connection open.  It simply forwards the input it receives to the next steps.

Example::
[source,kotlin,linenumbers]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

Notable Parameters::
This step only accepts the name of an HTTP step as argument. 

=== MQTT Publish Step (netty) 
The `_MQTT Publish_` step within the `_netty_` plugin sends data to an MQTT server.

Ancestor::
 
 
Functionality::
 
Example::
+
[source,kotlin,linenumbers]
----
----
 
Notable Parameters::
 
Tip::
tip

=== MQTT Subscribe Step (netty)
* The `_MQTT Subscribe Step_` within the `_netty_` plugin consumes data from an MQTT.

Ancestor::
 
 
Functionality::
 
Example::
+
[source,kotlin,linenumbers]
----
----
 
Notable Parameters::
 
Tip::

=== TCP Step (netty)

The `_TCP_` step within the `_netty_` plugin is a client for TCP.
 
Ancestor::
Step or Scenario

Functionality::
A TCP connection is established with the server using either a pool of connections or an individual connection for each minion. 
+
In the latter case, the connection is maintained until the latest execution for the minion was performed, including the ones from related steps TCP WITH (see example below). 
+
When the step is kept open without limit, a CLOSE TCP step should be executed to properly close the connections and avoid a saturation of the system.
+
Be aware that the number of connections that can be concurrently maintained open depends on the configuration of your operating system. Consider adapting limits for file descriptors.

Example::
+
[source,kotlin,linenumbers]
----
netty().tcp {
   request { context, input -> input.encodeToByteArray() }
   connect {
       address("remote-server.acme.com", 9000)
       connectTimeout = Duration.ofMinutes(1)
       noDelay = false
       keepConnectionAlive = false
       tls {
           disableCertificateVerification = true
       }
       proxy {
           type = HttpProxyType.SOCKS5
           address("my-proxy", 9876)
       }
   }
   pool {
       size = 143
       checkHealthBeforeUse = true
   }
   monitoring {
       events = true
       meters = true
   }
}
----
Notable Parameters::
* `_request_`: a factory to create the request to exchange, using the step context and the input as arguments; the request is an array of bytes.
* `_connect_`:configures the connection to the remote endpoint.
*** `_address_`:hostname or IP address and port of the remote server.
** `_connectTimeout_`: limit duration to fully establish the connection; defaults to 10 seconds.
** `_readTimeout_`:limit duration to receive and read a response after a request; defaults to 10 seconds.
** `_shutdownTimeout_`:limit duration to close a connection, defaults to 10 seconds
** `_sendBufferSize_`: the size of the buffer used to prepare the data to send, defaults to 1024 bytes
** `_receiveBufferSize_`: the size of the buffer to receive the data of the response, defaults to 1024 bytes
** `_nettyChannelOptions_`: overwrites the options of the Netty channel, use with care
** `_noDelay_`: disables the Nagle Algorithm, defaults to true
** `_tls_`: configuration for SSL/TLS
*** `_disableCertificationVerification_`: set to true if the certificate on the server should not be verified (for example for a self-signed certificate).
*** protocols: supported protocols (defaults to the default ones of Netty)
*** ciphers: supported cipher algorithms (defaults to the default ones of Netty)
** proxy: configuration to exchange data via a proxy, defaults to no configuration
*** address: hostname or IP address and port of the proxy server
*** type: type of the proxy to use: SOCKS4, SOCKS5, default to SOCKS4
*** authenticate: username and optional password to authenticate to the proxy, if it supports and requires it
* pool: configuration of the pool of connections (the pool is disabled by default)
** size: number of constants connections maintained in the pool
** checkHealthBeforeUse: verifies the health of the connection when polled from the pool and before it is used

=== TCP WITH Step (netty)
The `_TCP WITH step_` within the `_netty_` plugin sends a TCP payload reusing the connection created by a precedent step.

Ancestor::
Step

Functionality::
* The TCP WITH step should be a direct or indirect follower of a TCP  step. TCP WITH accepts the name of the step that owns the connection, and reuses a connection from that step, as it was created: either from a pool or the connection attached to the minion.
* TCP WITH cannot configure any detail of the connection differently from the TCP step


Example::
+
[source,kotlin,linenumbers]
----
netty().tcpWith("name-of-a-previous-HTTP-step") {
   request { context, input -> input.encodeToByteArray() }
   monitoring { all() }
}
----
Notable Parameter::
request: a factory to create the request to exchange, using the step context and the input as arguments.

=== CLOSE TCP Step (netty)
The `_CLOSE TCP_` step within the `_netty_` plugin closes the TCP connection, attached to a minion and created by a direct or indirect ancestor step, when the tail of the minion workflow is received. 

It is best practice to use a _CLOSE TCP_` step when reusing a TCP connection across several steps without a pool of connections.

Ancestor::
Step

Functionality::
The `_CLOSE TCP_` step should be a direct or indirect follower of a HTTP step, which keeps the connection open. 


Example::
+
[source,kotlin,linenumbers]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

Notable Parameter::
The `_CLOSE TCP_` step only accepts the name of an HTTP step as an argument.
 
=== UDP Step (netty)
The `_UDP_` step within the `_netty_` plugin is a client for UDP.

It is best practice to use such a step when reusing a TCP connection across several steps without pool of connection.

Ancestors:
Step or Scenario

Functionality::
The UDP step within the plugin creates a UDP Datagram packet from the request and sent to the remote endpoint, waiting for a response.  

Example::
+
[source,kotlin,linenumbers]
----
netty().udp {
   request { context, input -> input.encodeToByteArray() }
   connect {
       address("remote-server.acme.com", 9000)
       connectTimeout = Duration.ofMinutes(1)
   }
   pool {
       size = 143
       checkHealthBeforeUse = true
   }
   monitoring {
       events = true
       meters = true
   }
}
----

Notable Parameters::
* request: a factory to create the request to exchange, using the step context and the input as arguments, the request is an array of bytes
* connect: configures the connection to the remote endpoint
** address: hostname or IP address and port of the remote endpoint
** connectTimeout: limit duration to fully establish the connection, defaults to 10 seconds
** readTimeout: limit duration to receive a response and read it totally after a request, defaults to 10 seconds
** shutdownTimeout: limit duration to close a connection, defaults to 10 seconds
** sendBufferSize: the size of the buffer used to prepare the data to send, defaults to 1024 bytes
** receiveBufferSize: the size of the buffer to receive the data of the response, defaults to 1024 bytes
** nettChannelOptions: overwrites the options of the Netty channel, use with care

== r2dbc Plugin
The `r2dbc` plugin connects or supports...

== r2bc-jasync Plugin
The `r2bc-jasync` plugin connects Qalipsis to MariaDB, MySQL and PostgreSQL using the R2DBC drivers from jasync-sql.

Technologies Addressed::
* MariaDB: https://mariadb.org/

* MySQL: https://www.mysql.com

* PostgreSQL: https://www.postgresql.org/

Dependency::
`_io.qalipsis:plugin-r2dbc-jasync_`

Namespace in Scenario::
`_r2dbcJasync()_`

Client Library::
`jasync-sql` is an asynchronous database driver for PostgreSQL and MySQL written in Kotlin; refer to https://github.com/jasync-sql/jasync-sql.

Supported Steps::
* <<Poll Step (r2bc-jasync),Poll>>: Polls newest data periodically.
* <<Save Step (r2bc-jasync),Save>>: Saves a batch of records generated from the input and step context.
* <<Search Step (r2bc-jasync),Search>>: Searches records and builds a query from the input and step context.

=== Poll Step (r2bc-jasync)
The `_poll_` step within the `_r2bc-jasync_` plugin polls the newest records from a database table, respecting a delay between each execution of a select query.

Ancestor::
Scenario or Step.

Functionality::
* The poll query is created by the scenario developer once and then used throughout the scenario as called.
* The query requires at least one sorting field (known as SF in the example) to filter only the newest results so as not to fetch the same records repeatedly.
* The last known value for the SF is known as the tiebreaker which filters out the values already received directly from the database.
* Poll uses a strategy of “delivered at least once” that cannot avoid the records at the boundaries (with an  SF equal to the tiebreaker) from being delivered several times.

Example::
[source,kotlin]
----
	r2dbcJasync().poll {
		protocol(Protocol. POSTGRESQL)
		connection {
 			port = 5432
 			username = "dbuser"
			password = "dbpassword"
			database = "thedatabase"
	}
`
		query("""select username, "timestamp" from buildingentries where action = ? order by "timestamp"""")
		tieBreaker("timestamp", true)
		parameters("ENTERING")
		pollDelay(Duration.ofSeconds(1))
		monitoring {
			events = false
            meters = true
            }
}
----

Notable Parameters::
Note: To configure the connection, consult the documentation of jasync-sql:
https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections].
* query (required): specifies a query respecting the requirements of the target database (MariaDB, MySQL or PostgreSQL)
* tieBreaker (required): repeats the first field used for sorting as well as its strict comparison: true for strict filtering (< or >) and false otherwise (⇐ or >=)
* parameters (optional): binds values to the clauses of the prepared statements
* pollDelay (required): specifies the delay to wait between two executions of the query

Tip::
Use this step with a join operator when you need to verify the values saved by your tested system in the database.

=== Save Step (r2bc-jasync)
The `_save_` step within the `_r2bc-jasync_` plugin persists a batch of records into an SQL table using a prepared statement.

Ancestor::
Step

Functionality::
The input and step context are used to generate the table, the list of columns and their values, which are combined and forwarded to the database.

Example::
+
[source,kotlin]
----
r2dbcJasync().save {
	protocol(Protocol. POSTGRESQL)
	connection {
 		port = 5432
 		username = "dbuser"
		password = "dbpassword"
		database = "thedatabase"
	}
	tableName{ ctx, input -> "my_table" }
	columns{ ctx, input -> listOf("firstname", "surname", "registration") }
	values{ ctx, input -> list(
                     JasyncSaveRecord("john", "doe", "265edfg2g5"),
                     JasyncSaveRecord("alice", "foo", "3763gdw8"),
                     JasyncSaveRecord("bob", "bar", "627twh762")
              ) }

	monitoring {
	  events = false
                meters = true
            }
}
----
Notable Parameters::
* To configure the connection, consult the documentation of jasync-sql: https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections.
* The step is extremely flexible: table, columns and values might depend on the context and input value received from the previous step

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.

=== Search Step (r2bc-jasync)
The `_search_` step within the `_r2bc-jasync_` plugin searches records in the database.

Ancestor::
Step

Functionality::
The input and step context are used to generate a prepared statement and the values to complete it, the batch of results is then forwarded to the next steps

 Example::
+
[source,kotlin]
----
r2dbcJasync().search {
	protocol(Protocol. POSTGRESQL)
	connection {
 		port = 5432
 		username = "dbuser"
		password = "dbpassword"
		database = "thedatabase"
	}
	query { ctx, input -> """select username, "timestamp" from buildingentries where action = ? order by "timestamp"""" }
	parameters { ctx, input -> listOf("ENTERING") }

	monitoring {
	  events = false
                meters = true
            }
}
----

Notable Parameters::
* To configure the connection, consult the documentation of jasync-sql: https://github.com/jasync-sql/jasync-sql/wiki[Configuring and Managing Connections]
* query generates a prepared statement from the context and input
* parameters generates a list of values to bind onto the query parameters identified by ?; the order matters.

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.

== rabbitmq Plugin
The `rabbitmq` plugin connects Qalipsis to the RabbitMQ broker.

Technology Addressed::
 RabbitMQ: https://www.rabbitmq.com/

Dependency::
 io.qalipsis:plugin-rabbitmq
 
Namespace in Scenario::
 rabbitmq()

Client Library::
 RabbitMQ is lightweight and easy to deploy open source software for collecting, processing, storing, and analyzing data
https://www.rabbitmq.com/

Supported Steps::
* <<Consume Step (rabbitmq),Consume>>: polls data from a RabbitMQ broker
* <<Produce Step (rabbitmq),Procuce>>: push data to a RabbitMQ broker
 
=== Consume Step (rabbitmq)
The `consume` step within the `rabbitmq` plugin consumes data from queues of the RabbitMQ broker and forwards the data to the next step. 

This step is generally used in conjunction with `join` to assert data or inject data into a workflow. 

You can learn more on the https://www.rabbitmq.com/#getstarted[RabbitMQ website].

The `consume` step supports multithreading concurrent consumers using  the `concurrency()` property.

 
Ancestor::
 Step or Scenario
 
Functionality::
Rabbitmq Consumer start polling loop for connection with the certain queueName. When new records appear, consumer poll them and send to the next step. After recieving the records consumer close the polling loop for connection.
 
Example::
+
[source,kotlin,linenumbers]
----
rabbitmq().
   consume {
        queue("user")
        connection {
          host = hostContainer
          port = portContainer
          password = "defaultpass"
          username = "user"
      }
      concurrency(2)
       prefetchCount (11)
}
----
 
Notable Parameters::
To configure the consumer, consult the https://www.rabbitmq.com/documentation.html[rabbitMQ documentation].
 
* `connection` configures the connection to the rabbitMQ broker; defaults to localhost:5672.
* `queue` defines the name of the queue to consume.
* `concurrency` defines the number of concurrent channels producing messages to RabbitMQ; defaults to 1.
* `prefetchCount` defines the prefetch count value, defaults to 10. 
For more information, refer to https://www.rabbitmq.com/consumer-prefetch.html)[RabbitMQ Consumer Prefetch].
* `monitoring` configures the monitoring of the producer step.

Tip::
Use the `consume` step with `join`  to assert data or inject data into a workflow.

=== Produce Step (rabbitmq)
The `produce` step within the `rabbitmq` plugin provides messages to the RabbitMQ broker using a query and then forwards the messages as input to the next step.
 
Ancestor::
Scenario or Step
 
Functionality::
The input and step context are used to generate the values to complete it; results  are then forwarded to the next steps

Example::
+
[source,kotlin,linenumbers]
----
rabbitmq().
     produce {
         name = "my-producer-step"
          concurrency(10)
          connection {
                 host = "anotherhost"
                 port = 5673
                 password = "pass"
                username = "test"
                virtualHost = "/guest"
                clientProperties = mapOf("t" to "test")
                 }
        records(recordSupplier)
        monitoring {
                   events = true
                   meters = false
          }
}
----
 
Notable Parameters::
 To configure the producer, consult the https://www.rabbitmq.com/documentation.html[rabbitMQ documentation].
* `connection` configure the connection to the rabbitMQ broker; defaults to localhost:5672.
* `records` generatse a list of RabbitMqProducerRecord
* `concurrency` defines the number of concurrent channels producing messages to RabbitMQ; defaults to 1.
* `monitoring` configures the monitoring of the `produce` step.

== redis-lettuce Plugin
The `redis-lettuce` plugin connects Qalipsis to Redis using the Lettuce client.

Technology Addressed::
_Redis: https://redis.io/_

Dependency::
`_io.qalipsis:plugin-redis-lettuce_`

Namespace in Scenario::
`_redisLettuce()_`

Client Library::
Lettuce is a scalable Redis client for building non-blocking Reactive applications: https://lettuce.io/

Supported steps::
* <<Poll Step (redis-lettuce),Poll>>: polls newest data periodically.
* <<Save Step (redis-lettuce),Save>>: saves a batch of records generated from the input and step context.
* <<Consume Step (redis-lettuce),Consume>>: consumes data from Redis streams.
* <<Produce Step (redis-lettuce),Produce>>: produces messages into Redis streams.

=== Poll Step (redis-lettuce)
The `_poll_` step within the `_redis-lettuce_` plugin Polls the newest records from a Redis key, with a delay between each execution of polling.

Ancestor::
Scenario or Step

Functionality::
* The select query is created once by the scenario developer and used throughout the scenario as called.
* The developer must provide the key or pattern that is going to be used in the poll and also the command, being valid values: SCAN, SSCAN, HSCAN, ZSCAN.
* For each one of them is called the native Redis command through Lettuce using the pattern provided.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
        .pollHscan {
          name = "poll.hscanacl"
          connection {
            nodes = “localhost:6379”
            database = 0
            authPassword = "pass"
            authUser = "user"
          }
          keyOrPattern("hscan-test-acl")
          pollDelay(Duration.ofSeconds(1))
          monitoring {
            events = false
            meters = false
          }
        }
----

Notable Parameters::
* To configure the connection, provide the type by using either SINGLE, CLUSTER or SENTINEL. These are the types of connections supported. 
* In the case of SENTINEL, the parameter masterId is necessary, see here for more information: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]
* The step supports different Redis commands: SCAN, SSCAN, HSCAN, ZSCAN.
* keyOrPattern (required): pattern or key that will be polled after each pollDelay.
* pollDelay (required): specifies the delay to wait between two executions of the query.

Tip::
Use this step with a join operator when you need to verify the values saved by your tested system in the database.

=== Save Step (redis-lettuce)
The `_save_` step within the `_redis-lettuce_` plugin persists a batch of records into Redis.

Ancestor::
Step

Functionality::
The input and step context are used to generate a valid Redis command and the values to complete it; the batch of results is then forwarded to the next steps

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce().save {
        name = "save"
        connection {
          nodes = “localhost:6379”
          database = 0
          redisConnectionType = RedisConnectionType.SINGLE
          authPassword = "password"
          authUser = "user"
       }
        records { _, _ ->
          listOf(
            ValueRecord(
              key = "key",
              value = "value"
          ),
          HashRecord(
            key = "hash",
            value = mapOf("key" to "value")
          )
        )
      }
      monitoring {
        events = true
        meters = true
      }
    }
----

Notable Parameters::
* To configure the connection, indicate the connection type as `_SINGLE_`, `_CLUSTER_` or `_SENTINEL_`.
+
If the connection type is set to `_SENTINEL_`, the parameter masterId is necessary. For more information, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]
* Records (required): the step supports different Redis commands: SET, SADD, HSET, ZADD and the provided values might depend on the context and input value received from the previous step.

Tip::
Different types of commands can be inserted in the same step.

=== Consume Step (redis-lettuce)
The `_consume_` step within the `_redis-lettuce_` plugin records from Redis streams.

Ancestor::
Scenario or Step

Functionality::
The developer provides the connection, the consumer group name and the concurrency level to create a consumer group in a Redis stream key.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
      .streamsConsume {
        name = "consumer"
        connection {
          nodes = “localhost:6379”
          database = 0
          redisConnectionType = RedisConnectionType.CLUSTER
          authPassword = "password"
          authUser = "user"
        }
        concurrency(5)
        group("consumer-test-1")
        streamKey("test")
        offset(“FROM_BEGINNING”)
        monitoring {
          events = false
          meters = false
       }
     }
----

Notable Parameters::
* To configure the connection, indicate the type of connection as `_SINGLE_`, `_CLUSTER_` or `_SENTINEL_`.  
+
In the case of `_SENTINEL_`, the parameter masterId is necessary.  For more information, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]
* `_concurrency_`: configures the level of coroutines consuming the Redis streams.
* `_Offset_`: sets the offset value to `_FROM_BEGINNING_`, `_LAST_CONSUMED_` or `_LATEST_` for each topic and consumer group.

=== Produce Step (redis-lettuce)
The `_produce_` step within the `_redis-lettuce_` plugin produce records into the Redis streams.

Ancestor::
Step

Functionality::
The developer provides the connection, and a batch of records to be produced into one or more Redis streams topics. The values could be provided by previous steps.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce().streamsProduce {
        name = "producer"
        connection {
          nodes = “localhost:6379”
          database = 0
          redisConnectionType = RedisConnectionType.CLUSTER
          authPassword = "password"
          authUser = "user"
       }
        records { _, input ->
          listOf(
            LettuceStreamsProduceRecord(
              key = "producer.test",
              value = mapOf("test" to input.value.values.first())
            )
         )
      }
      monitoring {
        events = true
        meters = true
      }
    }
----

Notable Parameters::
* To configure the connection, provide the type by using either SINGLE, CLUSTER or SENTINEL. These are the types of connections supported. 
* In the case of SENTINEL, the parameter masterId is necessary, see here for more information: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]
* Records (required) the combination of key and values to be produce, can be used the values from previous steps.



