= elasticsearch Plugin
The `elasticsearch` plugin connects Qalipsis to Elasticsearch using the REST client and a query.

Technology Addressed::
Elasticsearch: https://www.elastic.co/

Dependency::
`_io.qalipsis:plugin-elasticsearch_`

Namespace in Scenario::
`_elasticsearch()_`

Client Library::
To configure a connection to Elasticsearch, refer to the
https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html[Important Elasticsearch configuration
] documentation.


Supported Steps::
* <<Poll Step,Poll>>: polls newest data periodically.
* <<Save Step,Save>>: saves a batch of records generated from the input and step context.
* <<Search Step,Search>>: searches records, building a query from the input and step context.

== Poll Step
The `poll` step within the `elasticsearch` plugin periodically polls data from Elasticsearch. The output is a list of [ElasticsearchDocument]and contains maps of column names to values. 

This step is generally used in conjunction with a left join to assert data or inject them in a workflow

Ancestor::
Scenario or Step

Functionality::
The poll step is created only once in a scenario; it is used throughout the scenario as called.
 * The query parameter requires at least one sorting field (SF) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for the SF is known as the tiebreaker which  filters out the values already received directly from the database.
* `_poll_` uses a strategy of “delivered at least once” that cannot avoid the records at the boundaries (with an  SF equal to the tiebreaker) from being delivered several times.
* The output of the `_poll_` step is a list of [ElasticsearchDocument] that contains maps of column names to values. If `_flatten_` is called, the records are provided one by one to the next step; otherwise each poll batch remains complete

Example::
+
[source,kotlin,linenumbers]
----
elasticsearch().poll {
  index("building-moves")
  client {
        RestClient.builder(HttpHost("localhost", esPort, "http")).build()
  }
   query {
       """{
           "query": {
               "term": {
                   "action": "IN"
               }
           },
           "size": 2,
           "sort":["timestamp","username"]
       }""".trimIndent()
   }
   pollDelay(Duration.ofSeconds(1))
}
----
Notable Parameters::
* `_client_`: configures the REST client to connect to Elasticsearch.
* `_query_`:  the builder for the JSON query to perform the first poll.
+ 
Elasticsearch capability for "search after" is used and the tie-breaker is extracted from the sort clauses; `_sort_` defaults to all; the documents in the target are sorted by `_id_`.
+
Refer to the https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after[elasticsearch documentation] for an explanation of the limitations.
* `_index()_`: sets the elasticsearch indices to use for the queries; defaults to `_all_`.
* `_queryParameters_` (optional): adds query parameters. Refer to
 https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params[Elasticsearch Query Parameters] for more information on valid parameters.
* `_mapper_`: configures thefer to JSON Mapper to deserialize the records.
* `_pollDelay_` (required): specifies the delay between two executions of the query

== Save Step 
The `_save_` step within the `_elasticsearch_` plugin persists a batch of records into Elasticsearch using a document.

Ancestor::
Step

Functionality::
 The input and step context are used to generate the list of documents that are forwarded to Elasticsearch.

Example::
+
[source,kotlin,linenumbers]
----
elasticsearch().save {
             documentsFactory = documentsFactory
            client{
                 RestClient.builder(HttpHost("localhost", esPort, "http")).build()
            }
	monitoring {
	  events = false
                meters = true
            }
}
----

Notable Parameters::
* `_client_` configures the REST client to connect to Elasticsearch.
* `_documents_` defines the statement to execute when saving.
* `_monitoring_` configures the monitoring of the save step.
* `_mapper_` configures the JSON Mapper to deserialize the records.

The `_save_` step is extremely flexible; values may depend on the context and input value received from the previous step.
 
== Search Step
The `_search_` step within the `_elasticsearch_` plugin searches records in Elasticsearch database using a search query. Refer to the current
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html[elasticsearch documentation].

 Ancestor::
 Step
 
Functionality::
The search step’s input and step context are used to generate a Document and the values to complete it; the batch of results is then forwarded to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
elasticsearch().search {
           client(clientBuilder)
           mapper(mapperConfigurer)
           index(indicesFactory)
           query(queryFactory)
           queryParameters(paramsFactory)
           monitoring {
                  all()
           }
         fetchAll()

----
 
Notable Parameters::
* `_client_`: configures the REST client to connect to Elasticsearch.
* `_query_` is a builder for the JSON query to perform for first poll. Behind the scene we use Elasticsearch capability for "search after" and the tie-breaker is extracted from the sort clauses; defaults to `_all_` documents in the target sorted by `_id_`.
Refer to  the https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after[Elasticsearch Reference] to learn more about the limitations.
* `_index_`: sets the elasticsearch indices to use for the queries; defaults to `_all_`.
* `_queryParameters_`(optional): adds parameters to the query.
 Refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params[Elasticsearch Query Parameters] for more information on valid parameters.
* `_mapper_` configures the JSON Mapper to deserialize the records.
 * `_monitoring_`: configures the monitoring of the search step.
 * `_fetchAll_`: specifies that all the documents have to be fetched, even over the result-sized window. 
  +
 `_fetchAll_` has to be combined with either a scroll activation or a sorting definition in the query.
  +
 The latter case uses search after to page all the data. New data coming between two requests will be fetched. The requests stops when the number of fetched documents reaches the total hits of the latest response.
