= jackson Plugin
The jackson plugin supports reading a file (JSON, XML or CSV), converting the data to an object, and pushing the object to the next step.

Technologies Addressed::
 https://github.com/FasterXML/jackson[Class JsonMapper]

Dependency::
 `io.qalipsis:plugin-jackson`

Namespace in Scenario::
 `jackson()`

Client Library::
 JsonMapper: refer to http://fasterxml.github.io/jackson-databind/javadoc/2.11/com/fasterxml/jackson/databind/json/JsonMapper.html[FasterXML].

Supported Steps::
 * link:++ csvToMap, csvToObject++,[csvToMap, csvToObject]
: reads a CSV file, and converts the data to a MAP (or Object).
 * link:++jsonToMap, jsonToObject"++,[jsonToMap, jsonToObject]: reads a JSON file and converts the data to a MAP (or Object) .
 * <<XmlToObject,xmlToObject>>: reads an XML file, converts the data to an object,

== csvToMap, csvToObject
The `csvToMap` and `csvToObject` steps within the jackson plugin read a CSV resource (file, classpath resource, URL) and returns each item as an instance of an object or Map.
 
Ancestor::
 Step
 
Functionality::
The `csvToMap` and `csvToObject` step Specification has a `targetClass` property to which the output lines should be mapped.
The step reads a CSV file, convert the data to an object (or Map)  and push the object (or Map) to the next step.

Example::
+
[source,kotlin,linenumbers]
----
 jackson().csvToMap {
   classpath(file)
   header {
       escapeChar('E')
       quoteChar('"')
       columnSeparator(';')
       withHeader()
       allowComments()

       column("1st value").double()
       column("2th value").string().array(",")
       column("3rd value").string(true)
       column("4th value").string(true)
   }
}

jackson().csvToObject(PojoForTest::class) {
   classpath(file)
}
----
 
Notable Parameters::
 * `classpath(path)`: reads the data from a class path resource. The parameter path is the path to the resource, the leading slash is ignored.
* `file(path)`: reads the data from from a plain file on the file system. Parameter path is the path to the file, either absolute or relative to the current working directory.
* `url(url)`: reads the data from a URL. Parameter url is the url to access to the data resource.
* `mapper`: configures the JSON Mapper to deserialize the records.
· `pollDelay` (required): specifies the delay between two executions of the query.

== XmlToObject
The `XmlToObject` step within the `jackson` plugin reads an XML resource (file, classpath resource, URL) and returns each item as an instance of object of the specified class.

Ancestor::
 Step
 
Functionality::
The `XmlToObject` step specification has a property `targetClass` to which the output lines should be mapped.
The `XmlToObject` step reads an XML file, convert the data to an object  and pushes the object to the next step.

Example::
+
[source,kotlin,linenumbers]
----
 jackson().xmlToObject(PojoForTest::class) {
   classpath(file)
}
----
 
Notable Parameters::
 * `classpath(path)`: reads the data from a class path resource. Parameter path is the path to the resource, the leading slash is ignored.
* `file(path)`: reads the data from from a plain file on the file system. The parameter `path` is the path to the file, either absolute or relative to the working directory.
* `url(url)`: reads the data from a URL. Parameter url is the url to access to the data resource.

== jsonToMap, jsonToObject
The `jsonToMap` and `jsonToObject` step within the `jackson` plugin reads a JSON resource (file, classpath resource, URL) and returns each item as an instance of `Map` or the specified type.
 
Ancestor::
 Step
 
Functionality::
 The step specification has a property `targetClass` to which the output lines should be mapped;  the step reads a JSON file, converts the data to an object (or Map) and pushes the object (or Map) to the next step.

Example::
+
[source,kotlin,linenumbers]
----
 jackson().jsonToObject(PojoForTest::class) {
   classpath(file)
}
jackson().jsonToMap() {
   classpath(file)
}
----
 
Notable Parameters::
 * `classpath(path)`: reads the data from a class path resource. The parameter `path` is the path to the resource; the leading slash is ignored.
* `file(path)`: reads the data from from a plain file on the file system. The parameter `path` is the path to the file, either absolute or relative to the working directory.
* `url(url)`: reads the data from a URL. The parameter `url` is the url to access to the data resource.
