= jms Plugin

== Overview
The `jms` plugin connects QALIPSIS to a messaging platform that supports https://www.oracle.com/java/technologies/java-message-service.html[JMS].

Technology Addressed::
JMS: https://www.oracle.com/java/technologies/java-message-service.html[]

Dependency::
`io.qalipsis:plugin-jms`

Namespace in Scenario::
jms()
 
Client Library::
JMS API: refer to 
https://docs.oracle.com/javaee/7/api/javax/jms/package-summary.html[Java Interface Summary].

Supported Steps::
* <<Consume Step,`consume`>>: consumes data from a messaging platform supporting JMS.
* <<Produce Step,`produce`>>: pushes data to a messaging platform supporting JMS.

 
== Consume Step 
The `consume` step within the `jms` plugin consumes records from https://activemq.apache.org/[ActiveMQ].
 
Ancestor::
Scenario
 
Functionality::
The `consume` step polls data from the designated https://activemq.apache.org/[ActiveMQ] connection, step context, and the data deserializer.

Example::
+
[source,kotlin,linenumbers]
----
.jms()
    .consume {
        queues("queue-1")
        queueConnection { ActiveMQConnectionFactory().createQueueConnection() }
        monitoring {
            events = true
            meters = true
        }
    }.deserialize(JmsJsonDeserializer(User::class))
----
Notable Parameters::
* `consume`: configures the the https://activemq.apache.org/[ActiveMQ] connection.
** `queues`: specifies the queue(s) for the connection.
** `QueueConnection`: provides the java https://activemq.apache.org/[ActiveMQ] connection for the specified `queues`.
** `topics`: specifies the topic(s) for the connection.
** `TopicConnection`: provides the java https://activemq.apache.org/[ActiveMQ] connection for the specified `topics`.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.
* `deserialize`: specifies the class to use to deserialize the body of the response.

Tips::
* The https://activemq.apache.org/[ActiveMQ] connection can be configured for either `queues` (`QeueConnection`) or `topics` (`TopicConnection`), but not both.
* Refer to the  https://www.oracle.com/java/technologies/java-message-service.html[JMS] documentation for for further parameter and configuration information.
 
== Produce Step
The `produce` step within the `jms` plugin produces records in https://activemq.apache.org/[ActiveMQ] using https://www.oracle.com/java/technologies/java-message-service.html[JMS].
 
Ancestor::
Step
 
Functionality::
The `produce` step produces a batch of records into one or more https://www.oracle.com/java/technologies/java-message-service.html[JMS] `destinations`. The record values may be provided by previous steps.

Example::
+
[source,kotlin,linenumbers]
----
.jms().produce {
    records { ctx, input ->
        listOf(
            JmsProducerRecord(
                destination = ActiveMQQueue().createDestination("queue-1"),
                messageType = JmsMessageType.TEXT,
                value = "hello-queue"
            ),
            JmsProducerRecord(
                destination = ActiveMQQueue().createDestination("queue-1"),
                messageType = JmsMessageType.AUTO,
                value = "another message".toByteArray()
            )
        )
    }
    connect { ActiveMQConnectionFactory().createQueueConnection() }
        monitoring {
            events = true
            meters = true
        }   
}     
----
Notable Parameters::
* `records`: generates and configures a list of produced records.
** `destination`:  defines the destination for each `JmsProducerRecord` as either queues (`QueueConnection`) or topics (`TopicConnection`).
** `messageType`: indicates the `JmsMessageType` as: `TEXT`, `AUTO`, `BYTES`, or `OBJECT`.
** `value`: defines the message to be displayed at the `destination`. 
* `connect`: specifies the connection type for the `JmsProducerRecord`(s).
* `monitoring`(optional): configures the monitoring parameters for the step.

Tips::
* If you are not sure about the `JmsMessageType`, use `AUTO` to allow the system to infer the type and display the result. 
* Refer to the  https://www.oracle.com/java/technologies/java-message-service.html[JMS] documentation for further parameter and configuration information.
