= jms Plugin

The jms plugim connects QALIPSIS to a messaging platform that supports https://www.jcp.org/en/jsr/detail?id=914[JMS].

Technology Addressed::
ActiveMQ: https://activemq.apache.org/

Dependency::
`io.qalipsis:plugin-jms`

Namespace in Scenario::
 jms()
 
 Client Library::
 JMS API: provides a common way for Java programs to create, send, receive and read an enterprise messaging system's messages. 
Refer to 
https://docs.oracle.com/javaee/7/api/javax/jms/package-summary.html[Java Interface Summary] for more information.

Supported Steps::
* <<Consume Step,Consume>>: consumes data from a messaging platform supporting JMS.
* <<Produce Step,Produce>>: into a messaging platform supporting JMS.

 
== Consume Step 
The `consume` step within the `jms` plugin consumes records from ActiveMQ.
 
Ancestor::
Scenario
 
Functionality::
The `consume` step polls data from the designated ActiveMQ connection, step context, and the data deserializer.

 Example::
+
[source,kotlin,linenumbers]
----
.jms()
            .consume {
                queues("queue-1")
                queueConnection { ActiveMQConnectionFactory().createQueueConnection() }
                monitoring {
                    events = true
                    meters = true
                }
                
            }.deserialize(JmsJsonDeserializer(User::class))

----
 
Notable Parameters::

To configure a connection, provide  the java activeMq connection for either queues (`QueueConnection`) or topics (`TopicConnection`).
+
If the connection is a `QueueConnection` use queues; Otherwise use topics.
+
To deserialize a json text use `JmsJsonDeserializer` and provide the desired class to use in the deserialization.
+ If deserialize is a string, use `JmsStringDeserialize`.
 
== Produce Step
The `produce` step within the `jms` plugin produces records in ActiveMQ using JMS.
 
Ancestor::
Step
 
Functionality::
The `produce` step produces a batch of records to be produced into one or more JMS destinations. Note that the record values may be provided by previous steps.

Example::
+
[source,kotlin,linenumbers]
----
.jms().produce {
                records { ctx, input ->
                    listOf(
                        JmsProducerRecord(
                            destination = ActiveMQQueue().createDestination("queue-1"),
                            messageType = JmsMessageType.TEXT,
                            value = "hello-queue"
                        ),
                        JmsProducerRecord(
                            destination = ActiveMQQueue().createDestination("queue-1"),
                            messageType = JmsMessageType.AUTO,
                            value = "another message".toByteArray()
                        )
                    )
                }
               connect { ActiveMQConnectionFactory().createQueueConnection() }
                monitoring {
                    events = true
                    meters = true
                }
                
----

 Notable Parameters::
To configure the connection, provide the java activeMq connection for either queues (QueueConnection) or topics(TopicConnection).
* `JmsMessageType` possible values are: TEXT, AUTO, BYTES, and OBJECT. 
+
Use AUTO if the type of the value is not known.