= jms Plugin

The jms plugin Connects Qalipsis to ActiveMQ using jms.

Technology Addressed::
ActiveMQ: https://activemq.apache.org/components/artemis/documentation/latest/using-jms.html

Dependency::
`_io.qalipsis:plugin-jms_`

Namespace in Scenario::
 jms()
 
 Client Library::
 JMS API: provides a common way for Java programs to create, send, receive and read an enterprise messaging system's messages. 
Refer to 
https://docs.oracle.com/javaee/7/api/javax/jms/package-summary.html[Java Interface Summary] for more information.

Supported Steps::
* <<Consume Step,Consume>>: consumes data from activeMq  queues and topics
* <<Produce Step,Produce>>: produces messages into activeMQ

 
== Consume Step 
The `consume` step within the `jms` plugin consumes records from ActiveMQ.
 
Ancestor::
Scenario
 
Functionality::
The `_consume_` step polls data from the designated ActiveMQ connection, step context, and the data deserializer.

 Example::
+
[source,kotlin,linenumbers]
----
.jms()
            .consume {
                queues("queue-1")
                queueConnection { ActiveMQConnectionFactory().createQueueConnection() }
                monitoring {
                    events = true
                    meters = true
                }
                metrics {
                    bytesCount = true
                    recordsCount = true
                }
            }.deserialize(JmsJsonDeserializer(User::class))

----
 
Notable Parameters::

To configure a connection, provide  the java activeMq connection for either queues (`_QueueConnection_`) or topics (`_TopicConnection_`).
+
If the connection is a `_QueueConnection_` use queues; Otherwise use topics.
+
To deserialize a json text use `_JmsJsonDeserializer_` and provide the desired class to use in the deserialization.
+ If deserialize is a string, use `_JmsStringDeserialize_`.
 
== Produce Step
The `_produce_` step within the `_jms_` plugin produces records in ActiveMQ using JMS.
 
Ancestor::
Step
 
Functionality::
The `_produce_` step produces a batch of records to be produced into one or more JMS destinations. Note that the record values may be provided by previous steps.

Example::
+
[source,kotlin,linenumbers]
----
.jms().produce {
                records { ctx, input ->
                    listOf(
                        JmsProducerRecord(
                            destination = ActiveMQQueue().createDestination("queue-1"),
                            messageType = JmsMessageType.TEXT,
                            value = "hello-queue"
                        ),
                        JmsProducerRecord(
                            destination = ActiveMQQueue().createDestination("queue-1"),
                            messageType = JmsMessageType.AUTO,
                            value = "another message".toByteArray()
                        )
                    )
                }
               connect { ActiveMQConnectionFactory().createQueueConnection() }
                monitoring {
                    events = true
                    meters = true
                }
                metrics {
                    bytesCount = true
                    recordsCount = true
                }
----

 Notable Parameters::
To configure the connection, provide the java activeMq connection for either queues (QueueConnection) or topics(TopicConnection).
* `_JmsMessageType_` possible values are: TEXT, AUTO, BYTES, and OBJECT. 
+
Use AUTO if the type of the value is not known.