== netty Plugin
The `netty` plugin supports TCP, UDP, HTTP and MQTT using the non blocking Netty plugin.

Technologies Addressed::
* HTTP/1.1: https://datatracker.ietf.org/doc/html/rfc2616
* HTTP/2: https://datatracker.ietf.org/doc/html/rfc7540
* MQTT: https://mqtt.org/
* TCP (Transmission Control Protocol): https://datatracker.ietf.org/doc/html/rfc793
* UDP (User Datagram Protocol): https://datatracker.ietf.org/doc/html/rfc768

Dependency::
`_io.qalipsis:plugin-netty_`

Namespace in Scenario::
`_netty()_`

Client Library::
Netty: https://netty.io/

Supported Steps::
* <<HTTP Step (netty),HTTP>>: client for HTTP 1.1 and HTTP 2.0.
* <<HTTP WITH Step (netty),HTTP WITH>>: executes a HTTP request reusing the HTTP connection created by precedent step.
* <<CLOSE HTTP Step (netty),CLOSE HTTP>>: closes the HTTP connection created by a precedent step.
* <<MQTT Publish Step (netty),MQTT Publish>>: sends data to an MQTT server.
* <<MQTT Subscribe Step (netty),MQTT Subscribe>>: consumes data from an MQTT server.
* <<TCP Step (netty),TCP>>: client to exchanges data with a TCP server
* <<TCP WITH Step (netty),TCP WITH>>: exchanges data reusing the TCP connection created by precedent step
* <<CLOSE TCP Step (netty),CLOSE TCP>>: closes the TCP connection created by a precedent step
* <<UDP Step (netty),UDP>>: client to exchanges data with UDP

=== HTTP Step (netty)
The `_HTTP_` step within the `_netty_` plugin is a client for HTTP 1.1 and HTTP 2.0

Ancestor::
Step or Scenario

Functionality::
* An HTTP connection is established with the server using either a pool of connections or an individual connection for each minion. 
* In the latter case, the connection is maintained until the latest execution for the minion was performed, including the ones from related steps HTTP WITH (see below).
* When the step is kept open without limit, a later step CLOSE HTTP should be executed to properly close the connections and avoid a saturation of the system.
+

Be aware that the number of connections that can be concurrently maintained open depend on the configuration of your operating system. Among others, you should consider adapting the limits for file descriptors.

Example::
+
[source,kotlin,linenumbers]
----
netty().http {
   request { context, input -> SimpleHttpRequest(HttpMethod.HEAD, "/head") }
   connect {
       url("https://my-website.com:8080/test")
       connectTimeout = Duration.ofMinutes(1)
       inflate()
       charset(Charsets.ISO_8859_1)
       maxContentLength(123)
       followRedirections(15)
       noDelay = false
       keepConnectionAlive = false
       tls {
           disableCertificateVerification = true
       }
       proxy {
           type = HttpProxyType.SOCKS5
           address("my-proxy", 9876)
       }
       followRedirections(5)
   }
   pool {
       size = 143
       checkHealthBeforeUse = true
   }
   monitoring {
       events = true
       meters = true
   }
}.deserialize(String::class)

----

Notable Parameters::
* request: a factory to create the request to exchange, using the step context and the input as arguments
* connect: configures the connection to the remote endpoint
** version: version of the HTTP protocol to use: HTTP_1_1 or HTTP_2_0, defaults to HTTP_1_1
** url: the root URL, the path of the request is appended to it
connectTimeout: limit duration to fully establish the connection, defaults to 10 seconds
** readTimeout: limit duration to receive a response and read it totally after a request, defaults to 10 seconds
** shutdownTimeout: limit duration to close a connection, defaults to 10 seconds
** sendBufferSize: the size of the buffer used to prepare the data to send, defaults to 1024 bytes
** receiveBufferSize: the size of the buffer to receive the data of the response, defaults to 1024 bytes
** nettChannelOptions: overwrites the options of the Netty channel, use with care
** noDelay: disables the Nagle Algorithm, defaults to true
** keepConnectionAlive: when set to true, the HTTP header Connection is set to Keep-Alive and the client connection is kept open until closeHttp() is called
** tls: configuration for SSL/TLS
*** disableCertificationVerification: set it to true when the certificate on server should not be verified (for example for a self-signed certificate)
*** protocols: supported protocols (defaults to the default ones of Netty for the related HTTP version)
*** ciphers: supported cipher algorithms (defaults to the default ones of Netty for the related HTTP version)
** proxy: configuration to exchange HTTP data via a proxy, defaults to no configuration
*** address: the host and port of the proxy
*** type: type of the proxy to use: HTTP, SOCKS5, default to HTTP
*** authenticate: username and optional password to authenticate to the proxy, if it supports and requires it
** charset: character encoding of the HTTP requests, 
** maxContentLength: maximal expected size of a request, in bytes, defaults to 1048576, which is the minimum allowed
** inflate: enables the acceptance of compressed response. Compression of the request is not supported.
** followRedirections: when the server returns a HTTP status 3xx (redirection) in the response, the client will resend the request to the provided location. Otherwise, the response is kept as this. The argument maxRedirections provides the maximal number of redirections to follow and defaults to 10. By default, the redirections are not followed at all. Note that following a redirections makes the request to be sent there, exactly as it is (same method and content).
* pool: configuration of the pool of connections (the pool is disabled by default)
** size: number of constants connections maintained in the pool
** checkHealthBeforeUse: verifies the health of the connection when polled from the pool and before it is used
* deserialize: specifies the class to use to deserialize the body of the response

=== HTTP WITH Step (netty)
The `_HTTP WITH_` step within the `_netty_` plugin executes an HTTP request reusing the HTTP connection created by precedent step

Ancestor::
Step

Functionality::
* The HTTP WITH step is a direct or indirect follower of an HTTP step. HTTP WITH specifies the name of the step that owns the connection, and reuses a connection from that step, as it was created (either from a pool or the connection attached to the minion).
* HTTP WITH cannot configure the connection differently than the HTTP step.

Example::
[source,kotlin,linenumbers]
----
nnetty().httpWith("name-of-a-previous-HTTP-step") {
   request { context, input -> SimpleHttpRequest(HttpMethod.HEAD, "/head") }
   monitoring { all() }
}.deserialize(String::class)
----

Notable Parameters::
* request: a factory to create the request to exchange, using the step context and the input as arguments
* deserialize: specifies the class to use to deserialize the body of the response


=== CLOSE HTTP Step (netty)
The `_CLOSE HTTP_` step within the `_netty_` plugin closes the HTTP connection attached to the minion, and created by a direct or indirect ancestor step, when the tail of the minion workflow is received. 

It is always a best practice to use such a step when reusing a HTTP connection across several steps without a pool of connections. 


Ancestor::
Step

Functionality::
The `_CLOSE HTTP_` step is a direct or indirect follower of an `_HTTP_` step, which keeps the connection open.  It simply forwards the input it receives to the next steps.

Example::
[source,kotlin,linenumbers]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

Notable Parameters::
This step only accepts the name of an HTTP step as argument. 

=== MQTT Publish Step (netty) 
The `_MQTT Publish_` step within the `_netty_` plugin sends data to an MQTT server.

Ancestor::
 
 
Functionality::
 
Example::
+
[source,kotlin,linenumbers]
----
----
 
Notable Parameters::
 
Tip::
tip

=== MQTT Subscribe Step (netty)
* The `_MQTT Subscribe Step_` within the `_netty_` plugin consumes data from an MQTT.

Ancestor::
 
 
Functionality::
 
Example::
+
[source,kotlin,linenumbers]
----
----
 
Notable Parameters::
 
Tip::

=== TCP Step (netty)

The `_TCP_` step within the `_netty_` plugin is a client for TCP.
 
Ancestor::
Step or Scenario

Functionality::
A TCP connection is established with the server using either a pool of connections or an individual connection for each minion. 
+
In the latter case, the connection is maintained until the latest execution for the minion was performed, including the ones from related steps TCP WITH (see example below). 
+
When the step is kept open without limit, a CLOSE TCP step should be executed to properly close the connections and avoid a saturation of the system.
+
Be aware that the number of connections that can be concurrently maintained open depends on the configuration of your operating system. Consider adapting limits for file descriptors.

Example::
+
[source,kotlin,linenumbers]
----
netty().tcp {
   request { context, input -> input.encodeToByteArray() }
   connect {
       address("remote-server.acme.com", 9000)
       connectTimeout = Duration.ofMinutes(1)
       noDelay = false
       keepConnectionAlive = false
       tls {
           disableCertificateVerification = true
       }
       proxy {
           type = HttpProxyType.SOCKS5
           address("my-proxy", 9876)
       }
   }
   pool {
       size = 143
       checkHealthBeforeUse = true
   }
   monitoring {
       events = true
       meters = true
   }
}
----
Notable Parameters::
* `_request_`: a factory to create the request to exchange, using the step context and the input as arguments; the request is an array of bytes.
* `_connect_`:configures the connection to the remote endpoint.
*** `_address_`:hostname or IP address and port of the remote server.
** `_connectTimeout_`: limit duration to fully establish the connection; defaults to 10 seconds.
** `_readTimeout_`:limit duration to receive and read a response after a request; defaults to 10 seconds.
** `_shutdownTimeout_`:limit duration to close a connection, defaults to 10 seconds
** `_sendBufferSize_`: the size of the buffer used to prepare the data to send, defaults to 1024 bytes
** `_receiveBufferSize_`: the size of the buffer to receive the data of the response, defaults to 1024 bytes
** `_nettyChannelOptions_`: overwrites the options of the Netty channel, use with care
** `_noDelay_`: disables the Nagle Algorithm, defaults to true
** `_tls_`: configuration for SSL/TLS
*** `_disableCertificationVerification_`: set to true if the certificate on the server should not be verified (for example for a self-signed certificate).
*** protocols: supported protocols (defaults to the default ones of Netty)
*** ciphers: supported cipher algorithms (defaults to the default ones of Netty)
** proxy: configuration to exchange data via a proxy, defaults to no configuration
*** address: hostname or IP address and port of the proxy server
*** type: type of the proxy to use: SOCKS4, SOCKS5, default to SOCKS4
*** authenticate: username and optional password to authenticate to the proxy, if it supports and requires it
* pool: configuration of the pool of connections (the pool is disabled by default)
** size: number of constants connections maintained in the pool
** checkHealthBeforeUse: verifies the health of the connection when polled from the pool and before it is used

=== TCP WITH Step (netty)
The `_TCP WITH step_` within the `_netty_` plugin sends a TCP payload reusing the connection created by a precedent step.

Ancestor::
Step

Functionality::
* The TCP WITH step should be a direct or indirect follower of a TCP  step. TCP WITH accepts the name of the step that owns the connection, and reuses a connection from that step, as it was created: either from a pool or the connection attached to the minion.
* TCP WITH cannot configure any detail of the connection differently from the TCP step


Example::
+
[source,kotlin,linenumbers]
----
netty().tcpWith("name-of-a-previous-HTTP-step") {
   request { context, input -> input.encodeToByteArray() }
   monitoring { all() }
}
----
Notable Parameter::
request: a factory to create the request to exchange, using the step context and the input as arguments.

=== CLOSE TCP Step (netty)
The `_CLOSE TCP_` step within the `_netty_` plugin closes the TCP connection, attached to a minion and created by a direct or indirect ancestor step, when the tail of the minion workflow is received. 

It is best practice to use a _CLOSE TCP_` step when reusing a TCP connection across several steps without a pool of connections.

Ancestor::
Step

Functionality::
The `_CLOSE TCP_` step should be a direct or indirect follower of a HTTP step, which keeps the connection open. 


Example::
+
[source,kotlin,linenumbers]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

Notable Parameter::
The `_CLOSE TCP_` step only accepts the name of an HTTP step as an argument.
 
=== UDP Step (netty)
The `_UDP_` step within the `_netty_` plugin is a client for UDP.

It is best practice to use such a step when reusing a TCP connection across several steps without pool of connection.

Ancestors:
Step or Scenario

Functionality::
The UDP step within the plugin creates a UDP Datagram packet from the request and sent to the remote endpoint, waiting for a response.  

Example::
+
[source,kotlin,linenumbers]
----
netty().udp {
   request { context, input -> input.encodeToByteArray() }
   connect {
       address("remote-server.acme.com", 9000)
       connectTimeout = Duration.ofMinutes(1)
   }
   pool {
       size = 143
       checkHealthBeforeUse = true
   }
   monitoring {
       events = true
       meters = true
   }
}
----

Notable Parameters::
* request: a factory to create the request to exchange, using the step context and the input as arguments, the request is an array of bytes
* connect: configures the connection to the remote endpoint
** address: hostname or IP address and port of the remote endpoint
** connectTimeout: limit duration to fully establish the connection, defaults to 10 seconds
** readTimeout: limit duration to receive a response and read it totally after a request, defaults to 10 seconds
** shutdownTimeout: limit duration to close a connection, defaults to 10 seconds
** sendBufferSize: the size of the buffer used to prepare the data to send, defaults to 1024 bytes
** receiveBufferSize: the size of the buffer to receive the data of the response, defaults to 1024 bytes
** nettChannelOptions: overwrites the options of the Netty channel, use with care
