= r2bc-jasync Plugin
The `r2bc-jasync` plugin connects Qalipsis to MariaDB, MySQL and PostgreSQL using the R2DBC drivers from jasync-sql.

Technologies Addressed::
* MariaDB: https://mariadb.org/

* MySQL: https://www.mysql.com

* PostgreSQL: https://www.postgresql.org/

Dependency::
`_io.qalipsis:plugin-r2dbc-jasync_`

Namespace in Scenario::
`_r2dbcJasync()_`

Client Library::
Jasync-sql: https://github.com/jasync-sql/jasync-sql
+
Jasync-sql is an asynchronous database driver for PostgreSQL and MySQL written in Kotlin.

Supported Steps::
* <<Poll Step,Poll>>: Polls newest data periodically.
* <<Save Step,Save>>: Saves a batch of records generated from the input and step context.
* <<Search Step,Search>>: Searches records and builds a query from the input and step context.

== Poll Step 
The `_poll_` step within the `_r2bc-jasync_` plugin polls the newest records from the database, respecting a delay between each execution of a select query.

Ancestor::
Scenario or Step.

Functionality::
The `_poll_` step is created only once in a scenario; it is used throughout the scenario as called.
* The `_query_` parameter requires at least one sorting field (SF) to filter the newest results and not fetch the same records repeatedly.
* The last known value for the SF is known as the tiebreaker which filters out the values already received directly from the database.
* Poll uses a strategy of “delivered at least once” that cannot avoid the records at the boundaries (with an  SF equal to the tiebreaker) from being delivered several times.

Example::
[source,kotlin]
----
	r2dbcJasync().poll {
		protocol(Protocol. POSTGRESQL)
		connection {
 			port = 5432
 			username = "dbuser"
			password = "dbpassword"
			database = "thedatabase"
	}
`
		query("""select username, "timestamp" from buildingentries where action = ? order by "timestamp"""")
		tieBreaker("timestamp", true)
		parameters("ENTERING")
		pollDelay(Duration.ofSeconds(1))
		monitoring {
			events = false
            meters = true
            }
}
----

Notable Parameters::
To configure the connection, refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] within the jasync-sql documentation.
* query (required): specifies a query respecting the requirements of the target database (MariaDB, MySQL or PostgreSQL).
* tieBreaker (required): repeats the first field used for sorting as well as its strict comparison: true for strict filtering (< or >) and false otherwise (⇐ or >=).
* parameters (optional): binds values to the clauses of the prepared statements.
* pollDelay (required): specifies the delay to wait between two executions of the query.

Tip::
Use this step with a join operator when you need to verify the values saved by your tested system in the database.

== Save Step 
The `_save_` step within the `_r2bc-jasync_` plugin persists a batch of records into an SQL table using a prepared statement.

Ancestor::
Step

Functionality::
The input and step context are used to generate the table and the list of columns and their values, which are then combined and forwarded to the database.

Example::
+
[source,kotlin]
----
r2dbcJasync().save {
	protocol(Protocol. POSTGRESQL)
	connection {
 		port = 5432
 		username = "dbuser"
		password = "dbpassword"
		database = "thedatabase"
	}
	tableName{ ctx, input -> "my_table" }
	columns{ ctx, input -> listOf("firstname", "surname", "registration") }
	values{ ctx, input -> list(
                     JasyncSaveRecord("john", "doe", "265edfg2g5"),
                     JasyncSaveRecord("alice", "foo", "3763gdw8"),
                     JasyncSaveRecord("bob", "bar", "627twh762")
              ) }

	monitoring {
	  events = false
                meters = true
            }
}
----
Notable Parameters::
To configure the connection, refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] within the jasync-sql documentation.
+
The `_save_` step is extremely flexible; table, columns and values may  depend on the context and input value received from the previous step.

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.

== Search Step 
The `_search_` step within the `_r2bc-jasync_` plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The search step’s input and step context are used to generate a prepared statement and the values to complete it; the batch of results is then forwarded to the next step(s).

 Example::
+
[source,kotlin]
----
r2dbcJasync().search {
	protocol(Protocol. POSTGRESQL)
	connection {
 		port = 5432
 		username = "dbuser"
		password = "dbpassword"
		database = "thedatabase"
	}
	query { ctx, input -> """select username, "timestamp" from buildingentries where action = ? order by "timestamp"""" }
	parameters { ctx, input -> listOf("ENTERING") }

	monitoring {
	  events = false
                meters = true
            }
}
----

Notable Parameters::
To configure the connection, refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] within the jasync-sql documentation. 
* query: generates a prepared statement from the context and input.
* parameters: generates a list of values to bind onto the query parameters. Note that the order of the list of values is important.

Tip::
Use this step after a collect() step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.
