= rabbitmq Plugin
The `rabbitmq` plugin connects Qalipsis to the RabbitMQ broker.

Technology Addressed::
 RabbitMQ: https://www.rabbitmq.com/

Dependency::
 io.qalipsis:plugin-rabbitmq
 
Namespace in Scenario::
 rabbitmq()

Client Library::
RabbitMQ: https://www.rabbitmq.com/ 
+
RabbitMQ is a lightweight and easy to deploy open-source software for collecting, processing, storing, and analyzing data.

Supported Steps::
* <<Consume Step,Consume>>: polls data from a RabbitMQ broker
* <<Produce Step,Procuce>>: push data to a RabbitMQ broker
 
== Consume Step
The `consume` step within the `rabbitmq` plugin consumes data from queues of the RabbitMQ broker and forwards the data to the next step.

This step is generally used in conjunction with `join` to assert data or inject data into a workflow.

This step supports multithreading concurrent consumers using  the `concurrency()` property.
 
To learn more, visit the https://www.rabbitmq.com/#getstarted[RabbitMQ] website.

Ancestor::
Step or Scenario
 
Functionality::
The `_consume_` step starts a polling loop for connection to the designated queue.  As new records appear, `_consume_` polls them and sends them to the next step. After receiving the records, `_consume_` closes the polling loop for connection.

Example::
+
[source,kotlin,linenumbers]
----
rabbitmq().
   consume {
        queue("user")
        connection {
          host = hostContainer
          port = portContainer
          password = "defaultpass"
          username = "user"
      }
      concurrency(2)
       prefetchCount (11)
}
----
 
Notable Parameters::
To configure the consume step, consult the https://www.rabbitmq.com/documentation.html[rabbitMQ] documentation.
* `connection` configures the connection to the rabbitMQ broker; defaults to `_localhost:5672_`.* `queue` defines the name of the queue to consume.
* `concurrency` defines the number of concurrent channels producing messages to RabbitMQ; defaults to 1.
* `prefetchCount` defines the prefetch count value; defaults to 10. 
* `monitoring` configures the monitoring of the producer step.

Tip::
Use the `consume` step with `join`  to assert data or inject data into a workflow.

== Produce Step 
The `produce` step within the `rabbitmq` plugin provides messages to the RabbitMQ broker using a query; the messages are then forwarded as input to the next step.

Ancestor::
Scenario or Step
 
Functionality::
The `_produce_` step's input and step context are used to generate the values to complete the step; results are then forwarded to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
rabbitmq().
     produce {
         name = "my-producer-step"
          concurrency(10)
          connection {
                 host = "anotherhost"
                 port = 5673
                 password = "pass"
                username = "test"
                virtualHost = "/guest"
                clientProperties = mapOf("t" to "test")
                 }
        records(recordSupplier)
        monitoring {
                   events = true
                   meters = false
          }
}
----
 
Notable Parameters::
 To configure the produc step, consult the https://www.rabbitmq.com/documentation.html[rabbitMQ] documentation.
* `connection` configure the connection to the rabbitMQ broker; defaults to `_localhost:5672_`.
* `records` generatse a list of RabbitMqProducerRecord.
* `concurrency` defines the number of concurrent channels producing messages to RabbitMQ; defaults to `_1_`.
* `monitoring` configures the monitoring of the `produce` step.
