= redis-lettuce Plugin
The redis-lettuce plugin connects QALIPSIS to Redis using the Lettuce client.

Technology Addressed::
_Redis: https://redis.io/_

Dependency::
`io.qalipsis:plugin-redis-lettuce`

Namespace in Scenario::
`redisLettuce()`

Client Library::
Lettuce: https://lettuce.io/
+
Lettuce is a scalable Redis client for building non-blocking Reactive applications.

Supported steps::
* <<Poll Step,Poll>>: polls newest data periodically.
* <<Save Step,Save>>: saves a batch of records generated from the input and step context.
* <<Consume Step,Consume>>: consumes data from Redis streams.
* <<Produce Step),Produce>>: produces messages into Redis streams.

== Poll Step 
The poll  step within the `redis-lettuce` plugin polls the newest records from a Redis key, with a delay between each execution of polling.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is used throughout the scenario as called.
 
* The key or pattern to be used in the poll is set to one of the following valid vaules: SCAN, SSCAN, HSCAN, ZSCAN.

* The native `redis-lettuce`  command is called using the pattern provided.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
        .pollHscan {
          name = "poll.hscanacl"
          connection {
            nodes = “localhost:6379”
            database = 0
            authPassword = "pass"
            authUser = "user"
          }
          keyOrPattern("hscan-test-acl")
          pollDelay(Duration.ofSeconds(1))
          monitoring {
            events = false
            meters = false
          }
        }
----

Notable Parameters::
To configure the connection, indicate the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
+
If the connection type is set to `SENTINEL`, the parameter masterId is necessary. For more information, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel].
+
The step supports different Redis commands: SCAN, SSCAN, HSCAN, ZSCAN.
* keyOrPattern (required): pattern or key that will be polled after each pollDelay.
* pollDelay (required): specifies the delay to wait between two executions of the query.

Tip::
Use this step with a join operator when you need to verify the values saved by your tested system in the database.

== Save Step 
The `save` step within the `redis-lettuce` plugin persists a batch of records into Redis.

Ancestor::
Step

Functionality::
The input and step context are used to generate a valid Redis command and the values to complete it; the batch of results is then forwarded to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce().save {
        name = "save"
        connection {
          nodes = “localhost:6379”
          database = 0
          redisConnectionType = RedisConnectionType.SINGLE
          authPassword = "password"
          authUser = "user"
       }
        records { _, _ ->
          listOf(
            ValueRecord(
              key = "key",
              value = "value"
          ),
          HashRecord(
            key = "hash",
            value = mapOf("key" to "value")
          )
        )
      }
      monitoring {
        events = true
        meters = true
      }
    }
----

Notable Parameters::
* To configure the connection, indicate the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
+
If the connection type is set to `SENTINEL`, the parameter masterId is necessary. For more information, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel].
* Records (required): the step supports different Redis commands: SET, SADD, HSET, ZADD and the provided values might depend on the context and input value received from the previous step.

Tip::
Different types of commands can be inserted in the same step.

== Consume Step
The `consume` step within the `redis-lettuce` plugin records data from Redis streams.

Ancestor::
Scenario 

Functionality::
The `consume` step creates a consumer group in a Redis stream key with the provided connection, consumer group name, and concurrency level.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
      .streamsConsume {
        name = "consumer"
        connection {
          nodes = “localhost:6379”
          database = 0
          redisConnectionType = RedisConnectionType.CLUSTER
          authPassword = "password"
          authUser = "user"
        }
        concurrency(5)
        group("consumer-test-1")
        streamKey("test")
        offset(“FROM_BEGINNING”)
        monitoring {
          events = false
          meters = false
       }
     }
----

Notable Parameters::
To configure the connection, indicate the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
+
If the connection type is set to `SENTINEL`, the parameter masterId is necessary. For more information, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* `concurrency`: configures the level of coroutines consuming the Redis streams.
* `Offset`: sets the offset value to `FROM_BEGINNING`, `LAST_CONSUMED` or `LATEST` for each topic and consumer group.

== Produce Step 
The `produce` step within the `redis-lettuce` plugin produces records into the Redis streams.

Ancestor::
Step

Functionality::
The produce step produces a batch of records to be produced into one or more Redis stream topics. Note that the record values may be provided by previous step(s).

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce().streamsProduce {
        name = "producer"
        connection {
          nodes = “localhost:6379”
          database = 0
          redisConnectionType = RedisConnectionType.CLUSTER
          authPassword = "password"
          authUser = "user"
       }
        records { _, input ->
          listOf(
            LettuceStreamsProduceRecord(
              key = "producer.test",
              value = mapOf("test" to input.value.values.first())
            )
         )
      }
      monitoring {
        events = true
        meters = true
      }
    }
----

Notable Parameters::
To configure the connection, indicate the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
+
If the connection type is set to `SENTINEL`, the parameter masterId is necessary. For more information, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* `records` (required): the combination of keys and values to be produced; the values from previous steps may be used. 
