== Glossary
[cols="1,2"]

|===

|  Term  |  Definition 


|Assertion
|A statement within a step that verifies that the output of the previous step matches expectations. 

|Batch
|A collection of values, as opposed to a single value.


|Campaign
|A single execution of a collection of scenarios, starting at a set time and running for a set period.

|Cluster
|A set of pieces/nodes of the software that are executed in different locations or on different machines. 


|Dependency Injection
a|A technique in which an object receives other objects that it depends on, called dependencies.

Dependency injection involves four objects each having a different role:

 * The service object that is injected into a client.

 * The client object that recieves the injected service.
    
 * The interface object that defines how the client  uses the service.

* The injector object that constructs the services  and injects them into the client.



|Directed Acyclic Graph (DAG)
a|A subpart of a scenario made up of a single continuous sequence of steps, to be executed in the same location by the same minions. 

 * Root DAG: A DAG starting immediately under a scenario
* Frontend DAG: A DAG whose followers execute on a different factory.
 * Backend DAG: A DAG that continues the execution workflow of a DAG hosted in a different factory.
 
  * DAG Underload: A DAG that is executed by the number of minions set on the scenario.
 * Singleton DAG: A DAG that is executed only once and supports infrastructure or optimization operations.

|Directive
|A single instruction published by a head to trigger an action in a factory.


|Event
|A time-stamped snapshot within a step. There are several types of events that can be monitored, including 
the time to respond, the status of the response, the size of the payload to send, etc.


|Feedback
|The factory reply to a directive; the feedback provides status of the directive's progression and/or the result of the expected action.


|Input
|The value set in a step context that is used by a step execution.

|Meter/Step Meter

a|A meter is a value aggregating step of the performance over a short period of time across all the minions.

A step meter is a unique value representing the performance of a unique execution of a step by a minion (e.g., time to response or volume of data saved, etc.)

 |Minion
|A virtual actor simulating a website user, an IoT device, or another system that interacts with the test system to inject load and verify performance.


|Monitoring/Time-series data
|A set of records generated by the execution of a campaign that permit the analysis of the performance of the target system and the generation of dashboards.


|Node
a|A software entity of a QALIPSIS cluster. Nodes communicate with each other to exchange data.

* Head: Node of a QALIPSIS cluster that coordinates and maintains the state of the cluster, orchestrating the factories and the campaigns.

* Factory: Node of a QALIPSIS cluster that executes the scenario to generate load to a target system and verify its behavior.


|Output
|Any data that a step generates, which may be used to verify behavior or generate further load.

|Plugin
|A technical extension designed to extend the core capabilities of QALIPSIS.


|Report
a| * Step report: A consolidated view of the executions of a step.

 * Campaign report: A consolidated view of the step reports.

|Result
|The record returned by a step when executed by a minion.
The result contains values (e.g., records fetched from a database or a response to a request) and the step meters of the execution.
The result is dispatched as output of the step context to the followers.


|Runner
|A component in charge of triggering and orchestrating the flow of data from one step to the next.  The runner is responsible for ensuring that output data from each step is provided as input to the next step as appropriate. Each runner task is assigned to the minion that simulates the user or device executing it.


|Scenario
|Sequence of actions to be executed by minions or to poll data from a remote system.


|Selector
|The Key/Value pair attached to a step to locate its execution in a factory owning the same pair.

|Specification 
|The configuration of a step or a scenario that describes the actions to perform and the sequence in which they are to be performed.

|Step  
a|The central atomic components within each scenario.

 * Error Processing step: A step within a scenario that contains information for handling a failed assertion or execution.

* Proxy step: A step acting as a middle man to forward the step execution to a follower, using convenient strategies.


|Step context
a| * Execution: A set of fields and values representing the single execution of a single minion on a single step.

* Exhausted: After an execution failure, a step context is marked as exhausted, and this state is propagated to its descendants.

 * Tail: A step context that represents the last one in the execution workflow of a single minion.

|Target System
|An IT system that QALIPSIS injects load into in order to verify its ability to scale and support a high volume of users or data.

|===