== Glossary
[cols="1,2"]

|===

|  Term  |  Definition 


|Assertion
|An error processing step  included within a scenario that determines the state of the minion going forward.  

|Batch
|A collection of values, as opposed to a single value.


|Campaign
|A single execution of a collection of scenarios, starting at a set time and running for a set period.

|Cluster
|A set of pieces/nodes of the software that are executed in different locations or on different machines. Clusters allow the factory nodes to verify outputs?????? 


|Dependentcy Injection
a|A technique in which an object receives other objects that it depends on, called dependencies.

Dependency injection involves four objects each having a different role:

 * The service object that is injected into a client.

 * The client object that recieves the injected service.
 
   
 * The interface object that defines how the client  uses the service.

* The injector object that constructs the services  and injects them into the client.



|Directed Acyclic Graph (DAG)
a|A subpart of a scenario made up of a single continuous sequence of steps, having in commom to be executed in the same location by the same minions. 

 * Root DAG: A DAG starting immediately under a scenario
* Frontend DAG: A DAG whose followers execute on a different factory.
 * Backend DAG: A DAG that continues the execution workflow of a DAG hosted in a different factory.
 
  * DAG Underload: A DAG that is executed by the number of minions set on the scenario.
 * Singleton DAG: A DAG that is executed only once and supports infrastructure or optimization operations.

|Directive
|A single instruction published by a head to trigger an action in a factory.


|Event
|A time-stamped snapshot of a statement executed in a step, attached to an information??? A step generally generates several events.

|Feedback
|The factory reply to a directive; the feedack provides staus of the directive's progression and/or the result of the expected action.


|Input
|The value set in a step context that is used by a step execution.

|Meter/Step Meter

a|A meter is a value aggregating step of the performance over a ahort period of tmee  across all the minions.

A step meter is a unique value representing the performance of a unique execution of a step by a minion (e.g., time to response, volume of data saved...)

 |Minion
|A Unique virtual simulated user or device.


|Monitoring/Time-series data
|A set of records generated by the execution of a campaign that permit the analysis of the performance of the target system and the generation of dashboards


|Node
a|A software entity of a QALIPSIS cluster. Nodes communicate with each other to exchange data.

* Head: Node of a Qalipsis cluster that coordinates and maintains the state of the cluster, orchestrating the factories and the campaigns.

* Factory: Node of a QUALIPSI cluster that executes the scenario to generate load to a target system and verify its behavior.


|Output
|The value (result) returned by a step execution into the step context.


|Report
a| * Step report: A consolidated view of the executions of a step.

 * Campaign report: A consolidated view of the step reports.

|Result
|The record returned by a step when executed by a minion.
The result conatins values (e.g., records fetched from a database or a response to a request) and the step meters of the execution.
The result is dispatched as output of the step context to the followers.


|Runner
|A component in charge of triggering the execution of a step onto a minion.

The  Kotlin job??? of step executions  are attached to the minions to maintain its active state.


|Scenario
|Sequence of actions to be executed by minions or to poll data from a remote system.


|Selector
|The Key/Value pair attached to a step to locate its excution in a factory owning the same pair.

|Specification 
|The configuration of a step or a scenario that describes the actions to perform and the sequence in which they are to be performed.

|Step  
a|Atomic action that a minion can execute in a scenario.

 * Error Processing step: A step that is able to execute a step context?? even if exhausted.

* Proxy step: A step acting as a middle-man to forward the step execution to a follower, using convenient strategies.


|Step context
a| * Execution: A set of fields and values representing the single execution of a single minion on a single step.

* Exhausted: After an execution failure, a step context is marked as exhausted and this state is propagated to its to its descendents.

 * Tail: A step context that represents the last one in the execution workflow of a single minion.

|Target System
|An IT system that QALIPSIS injects load into in order to verify its ability to scale and support a high volume of users or data.

|===