= Monitoring a test campaign

== Overview
QALIPSIS aims at giving insights about the behavior of the tested system from a performance perspective.

The insights are provided to users by way of dashboards and detailed values describing the performed operations.

== Definitions 
In QALIPSIS, each step generates different kinds of metadata that supply different levels of detail
about the behavior and performances of the system.

* The highest level of detail is built on <<Meters,meters>>, using the http://micrometer.io[Micrometer Application Monitoring] library. 
+
In essence, meters represent the behavior or performance of a step or operation over a short period of time as defined in  the meter's configuration. 

** The shorter the time period that a meter represents, the more data will be saved into the time-series database.
** The data can only be fetched and reported from the time-series database where they were saved. They are not available  in a QALIPSIS scenario. 
** In QALIPSIS, the Micrometer meters (Counters, Timers, Gauges) are attached to a single campaign and should be created and removed according to the campaign lifecycle. 
+
Refer to <<Meters>> for more information.

* The intermediate level of detail is built on <<Events, events>> that are directly saved into a time-series database.
+
In essence, an event represents an operation to be executed at a given point in time.

** Events can be compared to logs as managed by log4j and logback, and apply a similar concept for configuration. 
** Events are described by a severity, a log name, and values. 
+
Refer to <<Events>> for more information.

* Both meters and events can be tagged to specify the scenario, campaign, and test step that they are related to.

* The highest level of detail is built on <<Step execution meters,step execution meters>>. 
+
In essence, step execution meters are primitive values and Java durations.
+
** Step execution meters are directly provided as an output from one step to another. 
** Step execution meters make it possible to verify the performances and the success of an operation directly in the scenario, in order to decide whether next steps should be executed or not.
+
Refer to <<Step execution meters>> for more more information.

== Meters
=== Overview
Meters are generated using http://micrometer.io[Micrometer Application Monitoring].

* `Micrometer Application Monitoring` allows the test system to generate meters and publish them on a regular basis into a time-series database.
* When the meters are published, the values are aggregated into averages, maximum and minimum. 
* The published meters can be queried from the database or displayed on the dashboards.
* For maximum relevance, the meters have to be linked to the context of their measurement: name of scenario, campaign, step.

=== Creation and destruction of meters
To link meters to the context of their measurement, they have to be created in the start stage of a campaign and stopped in the stop stage.

The name of a meter is a dash-separated string, made of three parts:

* The name of the plugin (cassandra, elasticsearch, redis-lettuce)
* The type of the step (save, search, poll)
* The suffix of the meter, as explained in <<Meter parameters that should be measured>>.

[source,kotlin,line numbers]
----
private val eventPrefix = "cassandra.save" <1>
private val meterPrefix = "cassandra-save"
private var recordsToBeSent: Counter? = null
private var timeToSuccess: Timer? = null
private var timeToFailure: Timer? = null
private var savedDocuments: Counter? = null
private var failedDocuments: Counter? = null
    
override suspend fun start(context: StepStartStopContext) { <2>
    meterRegistry?.apply {
        val tags = context.toMetersTags()
        recordsToBeSent = counter("$meterPrefix-saving-documents", tags)
        timeToSuccess = timer("$meterPrefix-time-to-response", tags)
        timeToFailure = timer("$meterPrefix-time-to-failure", tags)
        savedDocuments = counter("$meterPrefix-saved-documents", tags)
        failedDocuments = counter("$meterPrefix-failed-documents", tags)
    }
}

override suspend fun stop(context: StepStartStopContext) { <3>
    meterRegistry?.apply {
        remove(recordsToBeSent!!)
        remove(timeToSuccess!!)
        remove(timeToFailure!!)
        remove(savedDocuments!!)
        remove(failedDocuments!!)
        recordsToBeSent = null
        timeToSuccess = null
        timeToFailure = null
        savedDocuments = null
        failedDocuments = null
    }
}
----
<1> Configure the meter values and variables.
<2> Start the meter.
<3> stop the meter. 


In the example above, you can see that the meters are nullable and only created when the `meterRegistry` of type `io.micrometer.core.instrument.MeterRegistry` is not null - injected in the step constructor, when converter the specification to a step, only if the configuration flag `meter` is set to true. The tags are passed from the start and stop context onto the identification of the meters to allow their search, aggregation and analysis relatively to different dimensions (step, campaign, scenario). When the step is stopped, the meters have to be removed from the meter registry to avoid them to be further published.

=== Meter parameters that should be measured
==== Request based operations (HTTP, TCP, etc.)

For request based operations, each request must be sent with the suffix `-sending-request`.
You can request to measure the following parameters: 

* The size of each request:  must be sent with the suffix `-sending-bytes`.
* For each request that succeeds responds with the suffix `-successful-request`.
* The size of each request that was successfully sent with the suffix `-sent-bytes`.
* Each request that fails with the suffix `-failed-request`.
* The time to the first byte of the response (when the response starts to be received) with the suffix `-receiving`.
* The time to the last byte of the response (when the response is completely received) with the suffix `-received-response`.
* The size of each response that was successfully received with the suffix `-received-bytes`.
+
Note: :: 
When the connection, handshake, or other preparation??? are part of the operation, more details can be provided via the dashboard and the parameters can be measured as requests are submitted.

==== Records based operations (Database saving, polling, searching).
The  suffixes below are proposed as `-documents`; the suffix that is used depends on the terminology of the developed steps (-records for a SQL database, -documents for Elasticsearch or MongoDB, etc.).

* The number of records to be saved with the suffix `-saving-documents`.
* The number of records actually saved with the suffix `-saved-documents`.
* The number of records that could not be saved with the suffix `-failed-documents.`
* The time to receive a complete successful response with the suffix `-time-to-response`.
* The time to receive a failure with the suffix `-time-to-failure`.
* The number of received records actually saved with the suffix `-received-documents`.
+
Notes: :: 
** When the size in bytes is available for the records or documents, you must also add the relevant counters with the suffixes `-saving-bytes`, `-saved-bytes` and `-received-bytes`.
** When the operation is to push records rather than save them, replace `save` with a more appropriate word, such as `produce` or `push`. 
** When the operation is to pull records rather than save them, replace  `receive` word with a more appropriate word, such as `consume` or `pull`.

== Events
=== Overview
`events` are logged using an instance of `io.qalipsis.api.events.EventsLogger`;  the step - injected in the step constructor, when converter the specification to a step, only if the configuration flag `events` is set to true.

As detailed in <<Creation and destruction of meters>>, the name of a meter is a dot-separated string, made of three parts:

* The name of the plugin (cassandra, elasticsearch, redis-lettuce).
* The type of step (save, search, poll)
* The suffix of the meter.
+
[source,kotlin,line numbers]
----
eventsLogger?.debug("cassandra.save.saving-documents", records.size, tags = contextEventTags)
----

A single event can bring several values of different types that relate to the same thing: 

* The size of a response and the time to receive it
* The time to a failure and the cause of the failure

If an event brings several values those values are passed as an array:
[source,kotlin,line numbers]
----
eventsLogger?.info(
    "cassandra.save.saved-documents",
    arrayOf(savedDocumentsCount, timeToResponse),
    tags = stepContext.toEventTags()
)
----
As with meters, the event context must be provided as tags, which contain the identifiers of the scenario, the campaign, the step as well as the minion, the iteration of the step for that minion and the state of the context (exhausted or not).

=== Event levels 
* `trace`: rarely used, especially in steps; helps to investigate issues in the Qalipsis engine.
* `debug`: used for events before the operation of the step occurs.
* `info`: for information after the operation of the step occurred (time to response, number of records successfully sent or received); generally used to create dashboards and get insights into the the performance of the system.
* `warn` for failures that should not abort the test campaign.
* `error` is extremely rare and only used when the failure is so critical that the test campaign should be aborted.

=== Event parameters that should be measured

==== Request based operations (HTTP, TCP,…)
The preparation of the operation to perform:

When the request is sent at once, each request to be sent with the suffix .sending-request and severity INFO, which must contain the size in bytes of the request

When the request might be chunked or sent in several pieces onto the wire, .sending-request with severity INFO is generated for each request to send and the size of each chunk the suffix .sending-bytes and severity TRACE

When the request is sent at once, each request successfully sent with the suffix .sent-request and severity INFO, which must contain the size in bytes of the request

When the request might be chunked or sent in several pieces onto the wire, .sent-request with severity INFO is generated for each request to send and the size of each chunk the suffix .sent-bytes and severity TRACE

Each request that fails with the suffix .failed-request and severity WARN, with the exception of the failure and the time between the request and the reception of the failure

The time to the first byte of the response (when the response starts to be received) with the suffix .receiving and severity DEBUG

The time to the last byte of the response (when the response starts to be received) and the number of received bytes with the suffix .received-response and severity DEBUG

Note: ::
When the connection, handshake, or other preparation??? are part of the operation, more details can be provided via the dashboard and the parameters can be measured as requests are submitted.


==== Records based operations (Database saving, polling, searching)
Note: the suffixes below are proposed with -documents which has to be adapted to own terminology of the developed steps (record for a SQL database, document for Elasticsearch or MongoDB…)

The number of records to be saved with the suffix .saving-documents and severity DEBUG

The time to receive a complete successful response and the number of records with the suffix .success and severity INFO

If a single request can lead to partial success, the saved records are saved with the suffix .saved-documents and severity INFO and the failed ones with the suffix .failed-documents and severity WARN

The time to receive a failure and the exception with the suffix .failure and severity WARN

The number of actually received records and the time to received all of them  with the suffix .received-documents and severity INFO

When the size in bytes is available for the records or documents, you will also add the relevant counters with the suffices .saving-bytes, .saved-bytes and .received-bytes.

When the operation is not to save but push records, you can replace the save word by a more adequate one, like produce, push,… and the same applies for received. 

== Step execution meters
The step execution meters are directly returned into a wrapper, itself contained in an object transporting the result of the step:

[source,kotlin,line numbers]
----
CassandraSearchResult(
    input = input,
    rows = results,
    meters = CassandraQueryMeters(results.size, timeToResponse)
)
[source,kotlin,line numbers]
data class CassandraQueryMeters(
    var recordsCount: Int,
    var timeToResponse: Duration? = null
)
----
The meters are generally primitive types and Java durations.

Below are suggestions for the names of the fields.

* Timers
** timeToResponse
** timeToFailure
** timeToFirstByte
** timeToLastByte
** timeToSuccesfullConnection
** timeToFailedConnection
** timeToSuccesfullHandshake
** timeToFailedHandshake

* Counters
** recordsToSend, recordsToSave, recordsToProduce
+
Use bytesCount in place of records as needed to to match the plugin terminology.

** sentRecords, savedRecords, producedRecords
+
Use bytesCount in place of records as needed to to match the plugin terminology.
** receivedRecords, consumedRecords
** sentBytes
** receivedBytes

You have the option to propose further details for the step execution meters in order to increase the possibilities for analysis.

=== What should be measured?
See the values in the section Events just above. All the ones you put in the events have to be provided to the next step.

== Configuring monitoring within the step specification.
All the specification should have a function called monitoring, taking a block as parameter:

[source,kotlin,line numbers]
----
fun monitoring(monitoringConfig: StepMonitoringConfiguration.() -> Unit)** <1>
@Spec
data class StepMonitoringConfiguration(
    var events: Boolean = false,
    var meters: Boolean = false (2)
) {
   
    fun all() {
        events = true
        meters = true
    }
}
----
<1> Implementation of io.qalipsis.api.steps.StepMonitoringConfiguration
 * Configuration of the metrics and events to record for a step.
 * @property events when set to true, records the events, defaults to false.
 * @property meters when set to true, records meters, defaults to false.
 
 * @author Eric Jessé
 
 <2> Enables the monitoring of events and meters.
Later, the events logger and meter registry are provided to the step only if the relevant flag is enabled:
[source,kotlin,line numbers]
----
MyStep(
  eventsLogger = supplyIf(spec.monitoringConfig.events) { eventsLogger },
  meterRegistry = supplyIf(spec.monitoringConfig.meters) { meterRegistry }
)
----
 