= Monitoring a test campaign

== Overview
QALIPSIS aims at giving insights about the behavior of the tested system from a performance perspective.

The insights are provided to users by way of dashboards and detailed values describing the performed operations.

== Definitions 
In QALIPSIS, each step generates different kinds of metadata that supply different levels of detail
about the behavior and performances of the system.

* The lowest level of detail is built on meters, using http://micrometer.io[Micrometer Application Monitoring].
** The test system generates meters and publishes them on a regular basis into a time-series database.
** When the meters are published, the values are aggregated into averages, maximum and minimum. 
** The published meters can be queried from the database or displayed on the dashboards.
* For maximum relevance, the meters are linked to the context of their measurement: name of scenario, campaign, step.
+
In essence, meters represent the behavior or performance of a step or operation over a short period of time as defined in the meter's configuration. 

** The shorter the time period that a meter represents, the more data will be saved into the time-series database.
** The data can only be fetched and reported from the time-series database where they were saved. They are not available in a QALIPSIS scenario. 
** In QALIPSIS, the `Micrometer` meters (Counters, Timers, Gauges) are attached to a single campaign and should be created and removed according to the campaign lifecycle. 
+
* The intermediate level of detail is built on events that are directly saved into a time-series database.
+
In essence, an event represents an operation to be executed or the result of an operation at a given point in time.

** Events can be compared to logs as managed by log4j and logback, and apply a similar concept for configuration. 
** Events are described by a severity, a name, and values. 
+
* Both meters and events can be tagged to specify the scenario, campaign, and test step that they are related to.

* The highest level of detail is built on step execution meters. 
+
In essence, step execution meters are primitive values and Java durations.
+
** Step execution meters are directly provided as an output from one step to another. 
** Step execution meters make it possible to verify the performances and the success of an operation directly in the scenario, in order to decide whether next steps should be executed or not.

== Configuring monitoring within the step specification
All step specifications have a monitoring function. 
* Step monitoring is disabled by default to avoid generating unnecessary data.
* Enable step monitoring to monitor events and/or meters:

[source,kotlin,line numbers]
----
    mystep{
        monitoring{
            events = true
            meters = false
        }    
    }
----

Optionally, enable simultaneous monitoring of steps and meters:
[source,kotlin,line numbers]
----
    mystep{
        monitoring{
            all()
        }    
    }
----

 