= Monitoring a Test Campaign

== Overview
QALIPSIS aims at giving insights of the behavior of the tested system, from a performance perspective.

Those insights are provided to the users via dashboards and detailed values describing the performed operations.

== Definitions

* Meters
* Steps
* Step Execution Meters

=== Meters

 Behaviors and Results Reported via the Campaign Dashboard
. Request based operations (HTTP, TCP, etc.)

* Each request to be sent with the suffix -sending-request

* The size of each request to be sent with the suffix -sending-bytes

* Each request that succeeds with the suffix -successful-request

* The size of each request that was successfully sent with the suffix -sent-bytes

* Each request that fails with the suffix -failed-request

* The time to the first byte of the response (when the response starts to be received) with the suffix -receiving

* The time to the last byte of the response (when the response is completely received) with the suffix -received-response

* The size of each response that was successfully received with the suffix -received-bytes

When the connection, handshake or other preparation are part of the operation, more details can be provided, they can also be measured as the requests are.

. Records based operations (Database saving, polling, searching)

Note: the suffices below are proposed with -documents which has to be adapted to own terminology of the developed steps (record for a SQL database, document for Elasticsearch or MongoDB…)

* The number of records to be saved with the suffix -saving-documents

* The number of records actually saved with the suffix -saved-documents

* The number of records that could not be saved with the suffix -failed-documents

* The time to receive a complete successful response with the suffix -time-to-response

* * The time to receive a failure with the suffix -time-to-failure

* The number of received records actually saved with the suffix -received-documents

When the size in bytes is available for the records or documents, you will also add the relevant counters with the suffices -saving-bytes, -saved-bytes and -received-bytes.

When the operation is not to save but push records, you can replace the save word by a more adequate one, like produce, push,… and the same applies received.

=== Events

=== Step Execution Meters
