= Glossary

[cols="1,3"]

|===

|  *Term*  |  *Definition*

|Archive
|A self-executing package containing QALIPSIS components for installation and execution.

|Assertion
|A step within a scenario that compares and validates data and timing information from multiple sources to ensure that expected results are met.  

|Campaign
|A single execution of one or a collection of scenarios, starting at a set time (or immediately), and continuing until completion, a fatal error occurs, or a stop is manually initiated.

|Cluster
|A group of pieces/nodes of the software that are executed on interconnected machines that may or may not be in different locations. 

|Configuration
|Runtime settings to customize the execution of a campaign.

|Data distribution
a|Strategy to distribute data received by a data source step (like polling) to the different minions passing by the step. QALIPSIS data distribution strategies include:

* Loop
* Unicast/forward once
* Broadcast

|Dependency Injection
a|A technique in which an object receives other objects that it depends on, called dependencies. A dependency injection involves four objects each having a different role:

 * The service object that is injected into a client.
 * The client object that receives the injected service.
 * The interface object that defines how the client uses the service.
 * The injector object that constructs the services and injects them into the client.

|Directed Acyclic Graph (DAG)
|A subpart of a scenario made up of a single continuous sequence of steps, to be executed in the same location by the same minions.  The first DAG in a scenario is typically used to initiate the scenario and set up the environment for the other DAGs to execute.

|Directive
|A single instruction published by a head to trigger an action in a factory.

|Event
|A time-stamped snapshot within a step. There are several types of events that can be monitored, including the time to respond, the status of the response, the size of the payload to send, etc.

|Execution profile
a|Settings that define the pace that minions are injected into the system. QALIPSIS out-of-the-box execution profiles include:

* Timeframe
* More
* Faster
* Regular

|Feedback
|The factory response to a directive; the feedback provides the status of the directive's progression and/or the result of the expected action.

|Gradle
|The build automation tool that QALIPSIS uses to compile code, assemble resources, and package and deploy projects.

|Input
|The output of the previous step that is used in the current step's execution.

|Installation
a|The overall strategy for QALIPSIS installation within different environments.
 
* Clusters: Deploying QALIPSIS across multiple locations.
* Amendable: Installing QALIPSIS on existing infrastructures or platforms.
* Containers: Using Docker (or similar) container technology to package and run QALIPSIS. 

|Load-injected tree
|A branch of a scenario that receives load from  all of the minions.

|Meter/Step Meter
a|* A meter is a value aggregating step of the performance over a short period of time across all the minions.
* A step meter is a unique value representing the performance of a unique execution of a step by a minion (e.g., time to response or volume of data saved, etc.)

|Minion
|A virtual actor simulating a website user, an IoT device, or another system that interacts with the test system to inject load and verify performance.

|Monitoring/Time-series data
|A set of records generated by the execution of a campaign that permits the analysis of the performance of the target system and the generation of dashboards.

|Node
a|A software entity of a QALIPSIS cluster. Nodes communicate with each other to exchange data.

* Head: Node of a QALIPSIS cluster that coordinates and maintains the state of the cluster, orchestrating the factories and the campaigns.

* Factory: Node of a QALIPSIS cluster that executes the scenario to generate load to a target system and verify its behavior.

|Operator
|A keyword used in a scenario or step to manipulate or perform calculations on applicable data. 

|Output
|Raw data that a step generates, which may be used as input to the following steps to verify behavior or to generate further load.

|Plugin
|A technical extension designed to extend the core capabilities of QALIPSIS.

|Project deployment
a|A strategy to install and run QALIPSIS on an IT landscape, depending on the requirements for data retention, load and security. QALIPSIS deployment strategies include:

* Embedded
* Ephemeral
* Transient
* Standalone
* Cluster

|QALIPSIS Project
|A set of files that represent QALIPSIS scenarios and the dependencies (libraries) they require.

|Report
a| * A step report is a consolidated view of the executions of a step.
 * A campaign report is a consolidated view of the step reports, organized by scenarios.

|Result
|The record returned by a step when executed by a minion.
The result contains values (e.g., records fetched from a database or a response to a request) and the step meters of the execution. The result is dispatched as the output of the step context to the followers.

|Runner
|A component in charge of triggering and orchestrating the flow of data from one step to the next.  The runner is responsible for ensuring that output data from each step is provided as input to the next step as appropriate. Each runner task is assigned to the minion that simulates the user or device executing it.

|Run-time parameters
|Scenario parameters that are set at run-time or execution of the scenario. 

|Scenario
|Sequence of actions to be executed by minions or to poll data from a remote system.

|Specification 
|The configuration of a step or a scenario that describes the actions to perform and the sequence in which they are to be performed.

|Step  
a|The central atomic components within each scenario. Steps are the challenges minions must complete in order to continue in the scenario.
Each step has a purpose.  There are several step types within QALIPSIS:

* Load steps that generate load or data onto a tested system.

* Error processing steps that contain information for handling a failed assertion or execution.

* Proxy steps that act as middlemen, using convenient strategies to connect steps and facilitate the flow of data and execution requests between them. 

* Operator steps that act on its data input or output before releasing it to the next step.

* Assertion steps that validate incoming or outgoing data.

|Step context
a|A single execution of a single step by a single minion.

* Execution: A set of fields and values representing the single execution of a single minion on a single step.

* Exhausted: After an execution failure, a step context is marked as exhausted, and this state is propagated to its descendants to inform that there will be no more execution with that context.

* Tail: A step context that represents the last one in the execution workflow of a single minion.

|Target system
|An IT system that QALIPSIS injects load into in order to verify its ability to scale and support a high volume of users or data.

|Workflow operators
a|Operators that control the flow of data within a scenario. QALIPSIS workflow operators include:

* Fan-Out: Splits a branch and adds two or more concurrent steps as successors.
* Fan-in/joins: Re-joins split branches of a scenario or verifies data from different sources.
* Error processing steps: Handles errors or unexpected events during execution. 

|===