= Cassandra plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The Cassandra plugin connects QALIPSIS to https://cassandra.apache.org/_/index.html[Apache Cassandra]. 

It enables interaction with Apache Cassandra clusters for testing distributed data storage and retrieval, as well as accessing data generated by the system under test. It provides three key steps: `poll`, `save`, and `search`.

This page explains configuration, important concepts, and provides examples of usage (poll, save, search). 
// It also includes troubleshooting tips.

Technologies addressed::
* Cassandra: https://cassandra.apache.org/_/index.html[Apache Cassandra]
* Cassandra Query Language: https://cassandra.apache.org/doc/latest/cassandra/cql/index.html[The Cassandra Query Language (CQL)]
* DataStax Driver: https://docs.datastax.com/[DataStax].

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-cassandra`

Namespace in scenario::
`cassandra()`

Client library::
DataStax: a modern, feature-rich and highly tunable Java client library for Apache Cassandra using Cassandra’s binary protocol and Cassandra Query Language.
+
See https://docs.datastax.com/[DataStax].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves records generated from the input and step context.
* <<Search step,`search`>>: searches records and builds a query from the input and step context.

Example scenarios are provided later in this <<Example scenarios,section>>.  

== Configuration

=== Sample configuration file

Apache Cassandra configuration settings are configured in a cassandra.yaml file. 

[source,kotlin,linenumbers]
 ----
campaign:
  my-sample-cassandra-campaign
  configuration:
    validation:
      max-execution-duration: PT40S

report:
  export:
    console-live:
      enabled: false
 ----

=== Configuration parameters
Available parameters are described in the table below.

Refer to the https://cassandra.apache.org/doc/latest[Apache Cassandra] documentation for further parameter and configuration information.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `connect`  +
a| Defines the connection parameters to https://cassandra.apache.org[Apache Cassandra]. +
 *Applicable Steps:* Poll, Search, Save +
 *Optional/Required:* Required +
 *Data Type:* Lambda within which connection parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
connect { 
    servers = listOf("localhost:9042") 
    keySpace = "iot" 
    datacenterProfile = DriverProfile.DEFAULT 
    datacenterName = "datacenter1" 
} 
----

| `connect.servers`
a| List of servers available for the connection. +
 *Applicable Steps:* Poll, Search, Save +
 *Optional/Required:* Required +
 *Data Type:* List<String> +
 *Default Value:* localhost:9042 +
 
.Example
[source,kotlin] 
----
connect { 
    servers = listOf("localhost:9042") 
}  
----

| `connect.keyspace`
a| Name of the keyspace to use. A keyspace defines how data is replicated across the cluster (replication strategy and replication factor).  +
 *Applicable Steps:* Poll, Search, Save +
 *Optional/Required:* Required +
 *Data Type:* String +
 *Default Value:* ""  +

.Example
[source,kotlin] 
----
connect {
    keySpace = "iot"
}
----


| `connect.datacenterName`
a| Name of the datacenter where data is stored. +
 *Applicable Steps:* Poll, Search, Save +
 *Optional/Required:* Required +
 *Data Type:* String  +
 *Default Value:* "" +

.Example
[source,kotlin] 
----
connect {
    datacenterName = "datacenter1"
}
----

| `connect.datacenterProfile`
a|  Determines how the DataStax driver selects the Cassandra datacenter to be used for routing requests. +
   Available settings: +
    LOCAL: Use the value of `connect.datacenterName` as the local datacenter. +
    PEER: Application must set datacenter to the peer datacenter you want to target.+
    DEFAULT: Use the driver's default selection policy (i.e don't override the profile's local datacenter selection).+
 *Applicable Steps:* Poll, Search +
 *Optional/Required:* Optional +
 *Data Type:* DriverProfile (enum: LOCAL, PEER, DEFAULT)  +
 *Default Value:* DriverProfile.DEFAULT +

.Example
[source,kotlin] 
----
connect { 
    datacenterProfile = DriverProfile.LOCAL
}
----

| `query`
a| Defines the prepared statement to query or execute. +
 *Applicable Steps:* Poll, Search +
 *Optional/Required:* Required +
 *Data Type:* +
    Poll: String that defines the prepared statement or query to execute. +
    Search: Lambda that takes step context and input to return a string. +
 *Default Value:* N/A +

.Example (Poll)
[source,kotlin] 
----
query ("SELECT deviceid, timestamp, batterylevel FROM battery_state WHERE company = ? ORDER BY timestamp") 
----
.Example (Search)
[source,kotlin] 
----
query { stepContext, input -> 'SELECT * FROM battery_state WHERE company = ? AND deviceid = ? AND timestamp = ?'}
----

| `parameters`
a| Poll: Binds values to the clauses of the prepared query. +
 Search: Computes the list of values bound to the prepared query using the step context and input. +
 *Applicable Steps:* Poll, Search + 
 *Optional/Required:* Optional +
 *Data Type:* +
    Poll: `List<Any>` / `vararg Any` +
    Search: Lambda that takes step context and input and returns `List<Any>`. +
 *Default Value:* `emptyList()` +
    
.Example (Poll)
[source,kotlin] 
----
parameters(listOf(1, "abc")) or parameters(1, "abc") 
----
.Example (Search)
[source,kotlin] 
----
parameters { 
    stepContext, input -> listOf("ACME Inc.") 
} 
----

| `tieBreaker`
a| Configures the tiebreaker column used to track the "last seen" value for polling. +
  *Applicable Step:* Poll +
  *Optional/Required:* Required +
  *Data Type:* Lambda within which tiebreaker parameters are defined. + 
  *Default Value:* N/A +

.Example
[source,kotlin] 
----
tieBreaker {         
    name = "timestamp"
    type = GenericType.INSTANT
}
----

| `tieBreaker.type`
a|Data type to help the datastax driver interpret a value. +
 *Applicable Step:* Poll +
 *Optional/Required:* Required +
 *Data Type:* GenericType (enum) +
 *Default Value:* null +

.Example
[source,kotlin] 
----
    tieBreaker {
        type = GenericType.INSTANT
    }
----


| `tieBreaker.name`
a|Name of the column used as a tiebreaker. +
 *Applicable Step:* Poll +
 *Optional/Required:* Required +
 *Data Type:* String  +
 *Default Value:* "" +

.Example
[source,kotlin] 
----
    tieBreaker {
        name = "timestamp"
    }
----

| `pollDelay`
a| Delay between two polling executions. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration 
 *Default Value:* Duration.ofSeconds(10) 

.Example
[source,kotlin] 
----
 pollDelay(Duration.ofSeconds(1)) 
----

| `table`
a|Computes the output table name using the step context and input. +
 *Applicable Step:* Save +
 *Optional/Required:* Required +
 *Data Type:* Lambda that takes step context and input and returns String. +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
table { stepContext, input -> "batteryState" }
----

| `columns`
a| Computes the list of column names for the output table using the step context and input. + 
 *Applicable Step:* Save +
 *Optional/Required:* Required +
 *Data Type:* Lambda that takes step context and input and returns List<String>.  + 
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
columns { stepContext, input -> listOf("company", "deviceid", "timestamp", "batterylevel") }
----

| `rows`
a| Computes the list of `CassandraSaveRow` to save into the output table using the step context and input. 
 *Applicable Step:* Save +
 *Optional/Required:* Required +
 *Data Type:* Lambda that takes step context and input and returns List<CassandraSaveRow>. + 
 *Default Value:* N/A +

.Examples
[source,kotlin] 
----
CassandraSaveRow (vararg args: Any?) //represent a single row to save into the table. 
----
[source,kotlin] 
----
rows { 
    stepContext, input -> listOf( CassandraSaveRow( "'ACME Inc.'", "'${input.deviceId}'", "'${input.timestamp}'", "'${input.batteryLevel}'" ) ) 
}
----

| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
  Specify one of the strategies directly (not wrapped in a lambda). +
  Available strategies: `sequential`, `broadcast`, `unicast`, `loop`. +

`broadcast(bufferSize, idleTimeout)`:
 sends every polled record to all minions. Records are delivered in order, with the oldest buffered record sent first. In this mode, the singleton behaves like a Pub/Sub broadcaster. 

 `unicast(bufferSize, idleTimeout)`: 
  sends each polled record to exactly one minion. The singleton acts as a FIFO distributor: Records are stored in a buffer until a minion consumes them. The buffer has a fixed size; when it becomes full, the oldest records are dropped to make space for new ones. 

 `loop(bufferSize, idleTimeout)`:
  sends each polled record to all minions, but once the end of the buffer is reached, it loops back to the beginning. This creates a continuous cyclic stream of the buffered records. 

 `sequential()`: 
  disables singleton execution and runs this step within the parent’s workflow. Data distribution is controlled entirely by the parent step. This mode is typically used when you want to process each record from a source from start to finish once, and then stop publishing until new data is available.
   
 Each strategy EXCEPT `sequential` requires `bufferSize` (Int) and `idleTimeout` (Duration); see `singletonConfiguration.bufferSize` and `singletonConfiguration.idleTimeout` definitions below. +

 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* unicast(bufferSize, idleTimeout)

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.bufferSize`
a| Size of the buffer used to store polled records before delivery to minions.+ +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Integer +
 *Default Value:* -1 +

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.idleTimeout`
a| Maximum time to wait before delivering polled records to minions, even if the buffer is not full. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration +
 *Default Value:* Duration.ZERO +

.Example
[source,kotlin] 
---- 
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `broadcast`
a| Specifies the broadcast parameters for a step. +
 *Applicable Step:* Poll
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
broadcast(3, Duration.ofMinutes(1))
----

| `unicast`
a| Specifies the unicast parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
unicast(1, Duration.ofMinutes(3))
----

| `loop`
a| Specifies the loop parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
loop(5, Duration.ofMinutes(2))
----

| `sequential`
a| Specifies the sequential parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
sequential()
----

| `monitoring`
a| Configures the monitoring of the step. +
 *Applicable Steps:* Poll, Save, Search +
 *Optional/Required:* Optional +
 *Data Type:* Lambda within which monitoring parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
monitoring {
    meters = true
    events = true
}
----

| `monitoring.meters`
a| Enables or disables the monitoring by meters for the step.
*Applicable Steps:* Poll, Save, Search +
 *Optional/Required:* Optional +
 *Data Type:* Boolean +
 *Default Value:* false +

.Example
[source,kotlin] 
----
monitoring {
    meters = true
}
----

| `monitoring.events`
a| Enables or disables the monitoring by events for the step.
 *Applicable Steps:* Poll, Save, Search +
 *Optional/Required:* Optional +
 *Data Type:* Boolean +
 *Default Value:* false +

.Example
[source,kotlin] 
----
monitoring {
    events = true
}
----

| `monitoring.all`
a| Enables all monitoring options for the step.
 *Applicable Steps:* Poll, Save, Search +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A

.Example
[source,kotlin] 
----
monitoring {
    all()
}
----
|===

== Examples of Usage

=== Poll step
The `poll` step within the *Cassandra* plugin polls the newest records from the database table.

Ancestor::
Scenario or Step

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario. The `poll` step within the Cassandra plugin uses a strategy of “delivered at least once." That means the same logical record might be delivered more than once (for example, on retries or restarts). +
To correctly and efficiently poll only new data, the plugin uses:
* An ORDER BY clause in the query (for example ORDER BY timestamp).
* A tieBreaker configuration that identifies the column used to compare the "last seen" value (example a timestamp or an increasing id).

Example::
This example demonstrates how to configure a poll step using the timestamp as a tiebreaker.
[source,kotlin,linenumbers]
----
cassandra().poll {
    connect { <1>
        name = "my-poll-step"
        servers = listOf("localhost:9042")
        keyspace = "iot"
        datacenterName = "datacenter1"                           
    }
    query("SELECT deviceid, timestamp, batterylevel FROM batteryState   
       WHERE company = ? ORDER BY timestamp") <2>
    parameters("ACME Inc.") <3>
    tieBreaker {           <4>
        name = "timestamp"
        type = GenericType.INSTANT
    }
    pollDelay(Duration.ofSeconds(1)) <5>
}
----
<1> Define the connection parameters to the cassandra cluster.
<2> Define the prepared statement to execute when polling.
<3> Bind values to the clauses of the prepared query.
<4> Repeat the first column used for sorting and comparison  +
    (`<=` or `>=`, depending on the ascending or descending order)
<5> Specify the delay between query executions.

Tips::
* Use the `poll` step with a left join operator to verify the values saved by your tested system in the database.
* `query` requires at least one sorting field (`tiebreaker` in the example) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for `tiebreaker` is used to filter out values already received from the database.
* Call `flatten()` after the poll step to transform the list of records into a map of column identifier [CQLIdentifier] to values.

Reference documentation::
Refer to the https://cassandra.apache.org/doc/latest[Apache Cassandra] documentation for further parameter and configuration information.

=== Save step
The `save` step within the Cassandra plugin persists records into a cassandra database using the save query with https://cassandra.apache.org/doc/latest/cassandra/cql/index.html[Cassandra Query Language (CQL)].

Ancestor::
 Step

Functionality::
 The `save` step's input and step context are used to generate documents to save into a database.

Example::

[source,kotlin,linenumbers]
----

previousStep.cassandra().save { <1>
    name = "my-save-step"
    connect {   <2> 
        servers = listOf("localhost:9042")
        keyspace = "iot"
        datacenterName = "datacenter1"
    }

    table { _, _ ->   <3>   
        "batteryState"
    }

    columns { _, _ ->  <4>
        listOf(
            "company",
            "deviceid",
            "timestamp",
            "batterylevel"
        )
    }
               
    rows { _, input ->   <5>
        listOf(
            CassandraSaveRow(
                "'ACME Inc.'",
                "'${input.deviceId}'",
                "'${input.timestamp}'",
                input.batteryLevel
            )
        )
    }
}
----
<1> Set a placeholder for any preceding step (e.g. `execute()`, `verify()`, `map()`, etc.)
<2> Define the connection parameters to the cassandra cluster.
<3> Name the output table, that can be resolved from the context and input.
<5> Define column names for the output table, that can be resolved from the context and input.
<5> Define how input fields are extracted and formatted to the output tables, using the step context and input.

Tips::
* Use the `save` step after a `collect` step to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.
* The `save` step is extremely flexible; table, rows, and columns depend on the context and input value received from the previous step.

Reference documentation::
Refer to the https://cassandra.apache.org/doc/latest[Apache Cassandra] documentation for further parameter and configuration information.

=== Search step
The `search` step within the Cassandra plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The `search` step’s input and step context are used to complete the search; the list of results is then forwarded to the next step(s).

Example::

[source,kotlin,linenumbers]
----
previousStep.cassandra().search {
    name = "my-search-step"

    connect {          <1>
        servers = listOf("localhost:9042")
        keyspace = "iot"
        datacenterName = "datacenter1"
    }
    query { _, _ ->   <2>
        "SELECT * FROM batteryState WHERE company= ?  
           AND deviceid = ? AND timestamp = ?"
    }
    parameters { _, input ->            <3>
        listOf("ACME Inc.", input.input.deviceId, input.input.timestamp)
    }
}
----
<1> Define the connection parameters to the cassandra cluster.
<2> Define the query statement, that can be resolved from the context and input.
<3> Define the query parameters, using the step context and input.

Tips::
 * Use the `search` step after a `collect()` step to reduce the number of queries executed onto the database and to reduce the load the scenario generates on the test system.
 * The `query` parameter may contain ordering clauses.

Reference documentation::
 * Refer to the https://cassandra.apache.org/doc/latest[Apache Cassandra] documentation for further parameter and configuration information.

=== CassandraSaveandPoll scenario
This example shows a scenario that saves rows and then polls the table to verify the saved values. It includes a short explanation for each step.

[source,kotlin,linenumbers]
----

@Scenario("cassandra-save-and-poll")
fun scenarioSaveAndPoll() {
    scenario {  <1>
        minionsCount = 20
        profile {
            immediate()
        }
    }
        .start()
        .jackson()      <2>
        .csvToObject(mappingClass = BatteryState::class) {
            classpath(path = "battery-levels.csv") 
            header { <3>
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
            }     
            unicast()
        }
        .map { it.value } <4> 
        .cassandra() <5> 
        .save {

            connect {   <6>
                servers = listOf("localhost:9042")
                keyspace = "iot"
                datacenterName = "datacenter1"
            }

            table { _, _ -> <7>
                "batteryState"
            }

            columns { _, _ -> <8> 
                listOf(
                    "company",
                    "deviceid",
                    "timestamp",
                    "batterylevel"
                )
            }
            rows { _, input ->  <9> 
                listOf(
                    CassandraSaveRow(
                        "'ACME Inc.'",
                        "'${input.deviceId}'",
                        "'${input.timestamp}'",
                        input.batteryLevel
                        )
                    )
                } 
        }           
        .map { it.input }   <10>
        .innerJoin()
        .using { correlationRecord -> correlationRecord.value.deviceId }
        .on {
            it.cassandra().poll {  <11>
                connect {   <12>
                    servers = listOf("localhost:9042")
                    keyspace = "iot"
                    datacenterName = "datacenter1"
                }
                query(queryString = "SELECT deviceid, timestamp, batterylevel 
                  FROM batteryState WHERE company = ? ORDER BY timestamp")  <13>
                parameters("ACME Inc.") <14>
                tieBreaker {
                    name = "timestamp"
                    type = GenericType.INSTANT
                }
                    pollDelay(duration = Duration.ofSeconds(1)) <15>
            }
                .flatten() <16> 
                .map { record ->
                    BatteryState(
                        deviceId = record.value[CqlIdentifier.fromCql("deviceid")] 
                           as String,
                        timestamp = record.value[CqlIdentifier.fromCql("timestamp")] 
                           as Instant,
                        batteryLevel = (record.value[CqlIdentifier.fromCql
                           ("batterylevel")] as Number).toInt()
                    )
                }
        }
        .having { correlationRecord ->  <17>
            correlationRecord.value.deviceId
        }
        .configure {    <18>
            timeout(duration = 5000L)
            report {
                reportErrors = true
            }
        }
        .filterNotNull()
        .verify { result -> <19>
            val savedBatteryState = result.first
            val foundedBatteryState = result.second
            foundedBatteryState.batteryLevel shouldBeExactly 
               savedBatteryState.batteryLevel
        }
}
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file using the +
     csvToObject method to map csv entries to list of utils.BatteryState object.
<3> Define the header of the csv file.
<4> Transform the output of the CSV reader entries to utils.BatteryState.
<5> Start the save step to save data to the database.
<6> Setup the connection to the database.
<7> Define the name of the database.
<8> Define the column names of the database.
<9> Create the list of rows to save to the database.
<10> Transform the output of the save step to get it's input value only.
<11> Initate the poll step.
<12> Define the connection to Cassandra.
<13> Define the query statement.
<14> Define the query parameters.
<15> Set the poll delay.
<16> Define the mapping for the incoming data stream. 
<17> Get the device id for the records.  
<18> Configure the timeout duration and error reporting.
<19> Define the verification parameters. 

=== CassandraSaveandSearch scenario
This example saves a row, performs a search to find it, and verifies values.
[source,kotlin,linenumbers]
----
@Scenario("cassandra-save-and-search")
fun scenarioSaveAndSearch() {
    scenario { <1>
        minionsCount = 20
        profile {
            immediate()
            }
        }
        .start()
        .jackson()  <2>
        .csvToObject(mappingClass = BatteryState::class) {
            classpath(path = "battery-levels.csv")
            header {    <3>
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
            }
            unicast()
        }
        .map { it.value } <4>
        .cassandra() <5>
        .save {
            name = "save"
            connect {   <6>
                servers = listOf("localhost:9042")
                keyspace = "iot"
                datacenterName = "datacenter1"
            }
            table { _, _ ->     <7>
                "batteryState"
            }
            columns { _, _ ->   <8>
                listOf(
                    "company",
                    "deviceid",
                    "timestamp",
                    "batterylevel"
                )
            }
            rows { _, input ->  <9>
                listOf(
                    CassandraSaveRow(
                        "'ACME Inc.'",
                        "'${input.deviceId}'",
                        "'${input.timestamp}'",
                        input.batteryLevel
                    )
                )
            }
        }
        .search {
            name = "search" <10>
            connect {   <11>
                servers = listOf("localhost:9042")
                keyspace = "iot"
                datacenterName = "datacenter1"
            }
            query { _, _ ->     <12>
                "SELECT * FROM batteryState WHERE company = ? 
                   AND deviceid = ? AND timestamp = ?"
            }
            parameters { _, input ->    <13>
                listOf("ACME Inc.", input.input.deviceId, input.input.timestamp)
            }
        }
        .map {      <14>
            it.input.input to it.records.first().let { cassandraRecord ->
                BatteryState(
                    deviceId = cassandraRecord.value[CqlIdentifier.fromCql
                       ("deviceid")] as String,
                    timestamp = cassandraRecord.value[CqlIdentifier.fromCql
                       ("timestamp")] as Instant,
                    batteryLevel = (cassandraRecord.value[CqlIdentifier.fromCql
                       ("batterylevel")] as Number).toInt()
                )
            }
        }
        .verify { result ->     <15>
            val savedBatteryState = result.first
            val foundedBatteryState = result.second
            foundedBatteryState.batteryLevel shouldBeExactly 
               savedBatteryState.batteryLevel
        }
}
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file using the csvToObject method +
    to map csv entries to list of utils.BatteryState object.
<3> Define the header of the csv file.
<4> Transform the output of the CSV reader entries to utils.BatteryState.
<5> Start the save step to save data to the database.
<6> Setup the connection to the database.
<7> Define the name of the database.
<8> Define the column names of the database.
<9> Create the list of rows to save to the database.
<10> Initiate the search step.
<11> Define the connection to Cassandra. 
<12> Define the query statement.
<13> Define the query parameters.
<14> Define the mapping for the incoming data stream. 
<15> Define the verification parameters. 

//== Troubleshooting