= Elasticsearch plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The Elasticsearch plugin connects QALIPSIS to https://www.elastic.co/[Elasticsearch] using the elasticsearch REST client.

*Elasticsearch:*
* Allows QALIPSIS to poll, search, save, and analyze data from your tested system. 
* Can be used to store analytics data from your test campaigns.

Technology addressed::
Elasticsearch: https://www.elastic.co/[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-elasticsearch`

Namespace in scenario::
`elasticsearch()`

Client library::
JAVA API:  refer to
https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.1/connecting.html[Elasticsearch JAVA Client].

Supported steps::
* <<poll step,`poll`>>: polls the newest data periodically.
* <<save step,`save`>>: saves a batch records generated from the input and step context.
* <<search step,`search`>>: searches records and builds a query from the input and step context.

Example scenarios are provided later in this <<Example scenarios,section>>.

== Configuration
`Elasticsearch` configuration settings are configured in an elasticsearch.yaml file. 

=== Sample configuration file

Ealsticsearch configuration settings are configured in a cassandra.yaml file. 

[source,kotlin,linenumbers]
----
campaign:
  name: elasticsearch-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters

Available parameters are described in the table below.

[cols="2,2,1,1,8" options="header"]
|===

| *Parameter*
| *Applicable Step(s)*
| *Optional/*
   *Required* 
| *Default Value*
| *Description/Example Usage*

| `index`
| Poll, Search
| Required
| `all`
| Sets the elasticsearch indices to use for the queries.

    index("battery-state")

| `client`
| Poll, Save, Search
| Required 
| N/A
| Configures the REST client to connect to https://www.elastic.co/[Elasticsearch]

  client { RestClient.builder(HttpHost.create("http://localhost:9200")).build() }
 
| `query`
| Poll, Search
| Required 
| N/A
| Configures the builder for the JSON query to perform the first poll/search.

  query { 
        """{
            "query":{
                "match_all":{}
            },
                "sort" : ["_score"]
            }"""
    }

Search: query { _, input ->
        """{
            "query": {
                "bool": {
                    "must": [
                        { "match": { "deviceId": "${input.input.deviceId}" }},
                        { "term": { "timestamp": ${input.input.timestamp.epochSecond} }}
                    ]
                }
            }
        }"""
    }

| `queryParameters`
|  Poll, Search
|  Optional
|  N/A
|  Adds parameters to the query. +
// neeed Example code here
  

| `pollDelay`
| Poll
| Required
| N/A
| Specifies the delay between query executions.

  pollDelay(Duration.ofSeconds(1)) +
 +
| `broadcast` +
  `unicast` +
  `loop` 

| Poll
| Optional
| N/A
| Specifies the data transfer method. +
 +
  unicast() +
  broadcast() +
  loop()

| `documents`
|  Save
|  Required
|  N/A
| Defines the strategy to create documents to save from the input and step context.
|  documents { _, input ->
        listOf(
            Document(
                index = "battery-state",
                id = input.deviceId,
                source = objectMapper.writeValueAsString(input)
            )
        )
    }
| `broadcast`
|  Poll
|  Optional
|  N/A
| Specifies the broadcast parameters for a step. +
   +
  broadcast(3, Duration.ofMinutes(1))

| `unicast`
|  Poll
|  Optional
|  N/A
| Specifies the unicast parameters for a step. +
   +
   unicast(1, Duration.ofMinutes(3))

| `loop`
|  Poll
|  Optional
|  N/A
| Specifies the loop parameters for a step. +
|  +
   loop(5, Duration.ofMinutes(2))

| `sequential`
|  Poll
|  Optional
|  N/A
| Specifies the sequential parameters for a step. +
  +
  sequential()

| `monitoring`
| Poll, Save, Search
| Optional
| N/A
| Configures the monitoring of the step. +

  monitoring {
    meters = true
    events = true
   }

| `monitoring.meters`
| Poll, Save, Search
| Optional
| false
| Enables or disables the monitoring by meters for the step. +
  +
| meters = true

| `monitoring.events`
| Poll, Save, Search
| Optional
| false
| Enables or disables the monitoring by events for the step. +
  +
  events = true

| `monitoring.all`
| Poll, Save, Search
| Optional
| N/A
| Enables all monitoring options for the step. +
  +
  all()

| `keepResponse`
| Save
| O
| function
| N/A
| when called, keeps the response from Elasticsearch after saving documents and forwards it to the next step.
| keepResponse()

| `fetchAll`
| Search
| O
| function
| N/A
| when called, fetches all results from Elasticsearch even over the result-sized window.
| fetchAll()

| `mapper`
| Search, Poll
| O
| Lambda that receives a JsonMapper to configure
| N/A
| Configures the JSON mapper to use for deserializing JSON documents from Elasticsearch into objects.
| mapper { jsonMapper ->
        // Custom configuration of the mapper
    }

|===


== Examples of Usage

===Poll step

The `poll` step in the Elasticsearch plugin periodically retrieves data from Elasticsearch. It returns a list of `ElasticsearchDocument` objects, which can contain raw JSON or be deserialized into specific data models. 

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called.
The `poll` step within the Elasticsearch plugin uses a strategy of “delivered exactly once”.
The output of the `poll` step is an `ElasticsearchDocument` that contains maps of column to values.

Example::
[source,kotlin,linenumbers]
----
elasticsearch().poll {  <1>
    name = "my-poll-step"
    client { RestClient.builder(HttpHost.create("http://localhost:9200")).build() }  <2>
    query {       <3>
        """{
            "query":{
                "match_all":{}
            },
                "sort" : ["_score"]
            }""".trimIndent()
    }
    index("battery-state")   <4>
    pollDelay(Duration.ofSeconds(1))  <5>
}
----
 <1> Start the `poll` step.
 <2> Configure the REST client connection.
 <3> Configure the query.
 <4> Set the `elasticsearch` indices to use for the queries.
 <5> Specifies the delay between query executions.

Tips::
* The `poll` step is generally used in conjunction with a `join` to assert data or inject data into a workflow.
* The `query` parameter requires at least one sorting field to filter the newest results and not fetch the same records repeatedly.
* The output of the `poll` step is an `ElasticsearchDocument` that contains maps of column names to values. If `flatten` is called, the records are provided one by one to the next step; otherwise each poll batch remains complete.

Reference Documentation::
* Refer to
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params[Elasticsearch Query Parameters] for more information on query parameters.
* Refer to the https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after[Elasticsearch] documentation for further parameter and configuration information.

== Save step 
The `save` step within the Elasticsearch plugin persists a batch of documents into  https://www.elastic.co/[Elasticsearch].

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate a list of documents that are forwarded to https://www.elastic.co/[Elasticsearch].

Example::
[source,kotlin,linenumbers]
----

previousStep.elasticsearch().save {   <1>
    name = "my-save-step"
    client {    <2>
        RestClient.builder(HttpHost.create("http://localhost:9200"))
            .build() 
    }
    documents { _, input ->  <3>
        listOf(
            Document(
                index = "battery-state",
                id = input.deviceId,
                source = objectMapper.writeValueAsString(input)  
            )
        )
    }
}
----

<1> Start the `save` step.
<2> Configure the REST client connection.
<3> Define the strategy to create documents to save from the step context and input.

Reference Documentation::
Refer to the https://www.elastic.co/guide[Elasticsearch] documentation for further parameter information.

== Search step
The `search` step within the Elasticsearch plugin searches documents in the Elasticsearch database using a search query.

Ancestor::
Step

Functionality::
The `search` step’s input and step context are used to generate a query; the batch of results is then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
previousStep.elasticsearch().search {   <1>
    name = "my-search-step"
    client {    <2>
        RestClient.builder(HttpHost.create("http://localhost:9200")).build()
    }
    index { _, _ -> listOf("battery-state") }   <3>
    query { _, input ->     <4>
        """{
            "query": {
                "bool": {
                    "must": [
                        { "match": { "deviceId": "${input.input.deviceId}" }},
                        { "term": { "timestamp": ${input.input.timestamp.epochSecond} }}
                    ]
                }
            }
        }"""
    }  
}
----
<1> Start the `search` step.
<2> Configure the REST client connection.
<3> Set the `elasticsearch` indices to use for the queries, resolved from the step context and input.
<4> Configure the builder for the JSON query to perform a search, resolved from the step context and input.

Reference Documentation::
* Refer to the https://www.elastic.co/guide[Elasticsearch] documentation for further parameter and configuration information.
* For specifics on `queryParameters` refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-paramsElastic[Elasticsearch Query Parameters].
* For specifics on `search` parameters, refer to
 https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html[Elasticsearch Search Parameters].

== ElasticsearchSaveAndSearch scenario
[source,kotlin,linenumbers]
----
@Scenario("elasticsearch-save-and-search")
fun scenarioSaveAndSearch() {
    scenario { <1>
        minionsCount = 10
        profile {
            immediate()
        }
    }
        .start()
        .jackson() <2>  
        .csvToObject(mappingClass = BatteryState::class) { <3> 
            classpath(path = "battery-levels.csv") 
            header {     <4> 
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
                }
            unicast()  <5>
        }
        .map { it.value } <6> 
        .elasticsearch()
        .save {
            name = "save"
            client {  <7>
                RestClient.builder(HttpHost.create("http://localhost:9200"))
                    .build() 
            }
            documents { _, input ->
                listOf(
                    Document(
                        index = "battery-state",
                        id = input.deviceId,
                        source = objectMapper.writeValueAsString(input) <8>
                    )
                )
            }
        }
        .delay(Duration.ofSeconds(2)) <9>
        .elasticsearch()
        .search {
            name = "search"
            client {
                RestClient.builder(HttpHost.create("http://localhost:9200"))
                    .build()
            }
            index { _, _ -> listOf("battery-state*") } <10> 
            query { _, input ->   <11> 
                """{
                    "query": {
                        "bool": {
                            "must": [
                                { "match": { "deviceId": "${input.input.deviceId}" }},
                                { "term": { "timestamp": ${input.input.timestamp.epochSecond} }}
                            ]
                        }
                    }
                }"""
            } 
        }
        .deserialize(targetClass = BatteryState::class) <12> 
        .verify { result ->  <13>
            val savedBatteryState = result.first.input
            result.second.asClue {
                assertSoftly {
                    it.results shouldHaveSize 1
                    it.results.first().value.batteryLevel shouldBe savedBatteryState.batteryLevel
                }
            }
        }
    }
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Set the data transfer method to `unicast`.  
<6> Transform the output of the CSV reader entries to utils.BatteryState.
<7> Create the rest client to submit requests to elasticsearch.
<8> Parse the object to save to json.
<9> Add a 2-second delay to ensures the newly indexed data is fully refreshed and searchable before proceeding. 
<10> Specify the table to search for data to fetch.
<11> Create a query to get the `batterystate` for a specific id and specific timestamp.
<12> Define the method to transform the elastic search result to a specific object.
<13> Define the verification parameters.

== ElasticsearchSaveAndPoll scenario
[source,kotlin,linenumbers]
----
@Scenario("elasticsearch-save-and-poll")
fun scenarioSaveAndPoll() {
    scenario {  <1>
        minionsCount = 10
        profile {
            immediate()
        }
    }
        .start()
        .jackson() <2>
        .csvToObject(mappingClass = BatteryState::class) { <3>
            classpath(path = "battery-levels.csv")
            header {  <4>
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
            }
            unicast()
        }
        .map { it.value } <5> 
        .elasticsearch()
        .save {
            name = "save"
            client { 
                RestClient.builder(HttpHost.create("http://localhost:9200"))
                    .build() <6> 
            }
            documents { _, input ->
                listOf(
                    Document(
                        index = "battery-state",
                        id = input.deviceId,
                        source = objectMapper.writeValueAsString(input) <7> 
                    )
                )
            }
        }
        .map { it.input }
        .delay(duration = Duration.ofSeconds(2)) <8>
        .innerJoin()
        .using { correlationRecord -> correlationRecord.value.deviceId }
        .on {
            it.elasticsearch().poll {
                name = "poll"
                client +
                    { RestClient.builder(HttpHost.create("http://localhost:9200")).build() }
                query {
                    """{
                        "query":{
                            "match_all":{}
                        },
                        "sort" : ["_score"]
                        }""".trimIndent()
                }
                index("battery-state*") <9> 
                pollDelay(delay = Duration.ofSeconds(1)) <10> 
            }
                .deserialize(targetClass = BatteryState::class) <11> 
                .flatten() <12>
                .map { record ->
                    record.value
                }
        }
        .having { correlationRecord -> correlationRecord.value.deviceId }. <13>
        .filterNotNull()
        .verify { result ->  <14>
            result.asClue {
                assertSoftly {
                    it.first.batteryLevel shouldBeExactly it.second.batteryLevel
                }
            }
        }
}
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.
<6> Create the rest client to submit requests to elasticsearch.
<7> Parse the object to save to json.
<8> Add a 2-second delay to ensures the newly indexed data is fully refreshed before proceeding. 
<9> Specify the table to poll for data to fetch.
<10> Set the poll delay to 2 seconds to avoid saturating the server with requests.
<11> Define the method to transform the elastic search result to a specific object.
<12> Define the mapping for the incoming data stream. 
<13> Get the device id for the records.  
<14> Define the verification parameters. 

== Configuration of publication of events and meters to Elasticsearch

NOTE::
Configure `event` and `meter` publication settings in the factory configuration, separate from the scenario DSL.

Refer to xref:up-and-running/configuration/provide-configuration.adoc[Provide configuration] for information about specifying the configuration to QALIPSIS.

Events::
`events.export.elasticsearch`

Meters::
`meters.export.elasticsearch`


=== Event and meter parameters

[cols="2,2,1,1,6" options="header"]
|===

| *Parameter*
| *Applicable Step(s)*
| *Optional/*
   *Required* 
| *Default Value*
| *Description/Example DSL Statement*

|`enabled`
| Events, Meters
| Required
|`false`
| Boolean flag to activate/deactivate event/meter publishing to elasticsearch; *must* be set to `true`to enable publishing,

    enabled: true

|`min-level`
| Events
| Required 
| `INFO`
| Minimal event security level to be published; events below this level are ignored.

    min-level: INFO
 
| `urls` / `host`
| Events / Meters
| Required 
| http://localhost:9200
| List of URLs/host to the Elasticsearch instances.

    urls: http://localhost:9200 +
    host: ${meters.export.elasticsearch.urls}

| `step`
| Meters
| Optional
| PT10S
| The step size (reporting frequency). +
  +
   step: PT10S

| `index-prefix` / `index`
| Events/Meters
| Required
| qalipsis-events
| String prefix for the created indices containing the elasticearch events/meters.

    index-prefix: qalipsis-events  +
    index: qalipsis-meters

| `path-prefix` for `urls`
| Events
| Optional
| /
| String prefix used to demarcate url paths.

    path-prefix: http://

|`index-date-pattern`
| Events/Meters
| Required
| yyyy-MM-dd
| Date pattern appended to the index name to generate time-partitioned indices.

   For events: +
   index-date-pattern: yyyy-MM-dd
   
   For meters: +
   index-date-format: yyyy-MM-dd

|`auto-create-index`
|Meters
|Required
|true
|Boolean flag to enable/disable auto creation of the index.+

   auto-create-index: true

|`duration-as-nano` 
| Events
| Optional
| false
| Boolean flag to identifiy whether durations are serialized/output as an integer (true) or as a floating point decimal (false).

   duration-as-nano: true

| `refresh-interval` 
| Meters
| Required
| 10s
| String delay to refresh the indices in Elasticsearch.

   refresh-interval: 15s

| `store-source`
| Events
| Optional
| false
| Boolean flag to indicate whether the source of documents is stored with the values; set to true for yes and false for no.

    `store-source`: true

| `linger-period`
| Events
| Required
| 10s
| Maximum time to buffer events before forcing a flush, even if the batch size is not reached; positive duration.

    linger-period: 10s

| `batch-size`
| Events
| Required
| 2000
| Maximum number of events buffered between two publications of events to elasticsearch; positive integer.

    batch-size: 2000

| `publishers`
| Events, Meters
| Required
| 1 (no concurrency)
| Number of concurrent publication of events that can send batches to elasticsearch; positive integeer.

    publishers: 1

|`shards`
|Events
|Required
|1
|Number of shards to apply on the created indices for events; positive integer.

    shards: 1

|`replicas`
|Events, Meters
|Required
|0
|Number of replicas to apply on the created indices for events and meters. 

    replicas: 0

|`username`
|Events, Meters
|Optional
|N/A
|Name of the user for basic authentication when connecting to Elasticsearch.
 
    username: JohnS

|`password`
|Events
|Optional
|N/a
|Password of the user for basic authentication when connecting to Elasticsearch. 
    password: QALIPSIS 
    
|===

=== Example configuration file snippet (YAML)
Below are example configuration excerpts for event and meter publishing. Replace placeholders before use.
[source,yaml,linenumbers]
----
events: <1>
    export:
        elasticsearch: <2>
            enabled: true
            min-level: INFO
            urls: http://localhost:9200
            index-prefix: qalipsis-events
            index-date-pattern: yyyy-MM-dd
            duration-as-nano: false
            linger-period: 10s
            batch-size: 40000
            publishers: 1
            username: johndoe
            password: my-secret-password
            shards: 1
            replicas: 0

meters: <3>
    export:
        elasticsearch: <4>
            urls: http://localhost:9200 
            host: ${meters.export.elasticsearch.urls} 
            enabled: true 
            index-prefix: qalipsis-meters
            index-date-pattern: yyyy-MM-dd
            auto-create-index: true
            publishers: 1
            username: johndoe
            password: my-secret-password
            shards: 1
            replicas: 0
---- 
<1> Start the event configuration scenario.
<2> Configure event publishing to elasticsearch. 
<3> Start the meter configuration scenario.
<4> Configure meter publishing to elasticsearch.


Tips::
* By default, Elasticsearch does not require a `username` or `password` for authentication; however, it is recommended that the information be provided to ensure secure access to the Elasticsearch data.


Reference Documentation:: 
Refer to <</user-documentation/up-and-running/configuration/monitoring-test-campaigns,Monitoring test campaigns>> for a further explanation of the event and meter parameter values. 

// need to fix above link