= Elasticsearch plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The Elasticsearch plugin connects QALIPSIS to https://www.elastic.co/[Elasticsearch] using the elasticsearch REST client.

Elasticsearch allows QALIPSIS to poll, search, save, and analyze data from your tested system. 

This page explains configuration, core concepts, secure connection options, runnable examples and best practices.

Technology addressed::
Elasticsearch: https://www.elastic.co/[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-elasticsearch`

Namespace in scenario::
`elasticsearch()`

Client library::
JAVA API:  refer to
https://www.elastic.co/docs/reference/elasticsearch/clients/java/setup/connecting[Elasticsearch JAVA Client].

Supported steps::
* <<poll step,`poll`>>: polls the newest data periodically.
* <<save step,`save`>>: saves a batch records generated from the input and step context.
* <<search step,`search`>>: searches records and builds a query from the input and step context.

Examples of usage are provided later in this <<Examples of usage,section>>.

== Configuration

=== Example configuration file

Elasticsearch` configuration settings are configured in an elasticsearch.yaml file. 

[source,kotlin,linenumbers]
----
campaign:
  name: elasticsearch-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters

Available parameters are described in the table below.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `index`
a| Sets the elasticsearch indices to use for the queries. +
*Applicable Steps:* Poll, Search + 
*Optional/Required:* Optional +
*Data Type:* +
   Poll: `vararg String` +
   Search: Lambda that receives the step context and input to return `List<String>`
*Default Value:* `_all`

.Example (Poll)
[source,kotlin]
----
index("battery-state")
----

.Example (Search)
[source,kotlin]
----
index { stepContext, input -> listOf("${input.batteryState}") } 
----

| `client`
a| Configures the REST client to connect to https://www.elastic.co/[Elasticsearch] +
*Applicable Steps:* Poll, Search, Save + 
*Optional/Required:* Optional +
*Data Type:* Lambda that returns an instance of RestClient
*Default Value:* http://localhost:9200 +

.Example
[source,kotlin]
----
client { 
    RestClient.builder(HttpHost.create("http://localhost:9200")).build()
}
OR
client {
  RestClient.builder(HttpHost(hostname = "localhost", port = 9200,  scheme = "http")).build() 
}
----

| `query`
a| Configures the builder for the JSON query to perform the poll/search. +
*Applicable Steps:* Poll, Search + 
*Optional/Required:* Required +
*Data Type:* +
 Poll: Lambda that returns a String. +
 Search: Lambda that receives the step context and input to return a String. +
*Default Value:* N/A +

.Example (Poll)
[source,kotlin]
----
query { 
        """{
            "query":{
                "match_all":{}
            },
                "sort" : ["_score"]
            }"""
    }
----

.Example (Search)
[source,kotlin]
----
query { stepContext, input ->
        """{
            "query": {
                "bool": {
                    "must": [
                        { "match": { "deviceId": "${input.deviceId}" }},
                        { "term": { "timestamp": ${input.timestamp.epochSecond} }}
                    ]
                }
            }
        }"""
    }
----

| `queryParameters`
a|Adds parameters to the query. +
*Applicable Steps:* Poll, Search +  
*Optional/Required:* Optional +
*Data Type:* + 
 Poll: vararg Pair<String, String>  +
 Search: Lambda that receives the step context and input to return `Map<String, String>` +
*Default Value:* N/A + 

.Example (Poll)
[source,kotlin]
----
queryParameters("deviceId" to "deviceId1", "param-2" to "val-2")
----

.Example (Search) 
[source,kotlin]
----
queryParameters { stepContext, input → mapOf("deviceId" to "${input.deviceId}") }
----

| `pollDelay`
a| Specifies the delay between two successive polls.  +
*Applicable Steps:* Poll +
*Optional/Required:* Optional  +
*Data Type:* java.time.Duration
*Default Value:* null + 

.Example
[source,kotlin]
----
pollDelay(Duration.ofSeconds(1)) +
----

| `singletonConfiguration`
a|Configures how polled results are delivered to scenario minions. +
  Refer to xref:plugins/plugins.adoc#singletonconfiguration-parameters[SingletonConfiguration parameters] for details on strategies and examples of usage.
  
| `documents`
a| Builds the list of documents to save using the Elasticsearch Bulk API. +
*Applicable Step:* Save +
*Optional/Required:* Required +
*Data Type:*  Lambda that receives the step context and input to return `List<Document>` +
*Default Value:* N/A +

.Example
[source,kotlin] 
----
documents { stepContext, input ->
    listOf(
        Document(
            index = "battery-state",
            id = input.deviceId,
            source = objectMapper.writeValueAsString(input)
        )
    )
}
----

| `monitoring`
a| Configures QALIPSIS monitoring (meters/events) for the step. +
Refer to xref:plugins/plugins.adoc#monitoring-parameters[Monitoring parameters] for configuration details and examples of usage.

| `keepResponse`
a| When called, keeps the response from Elasticsearch after saving documents and forwards it to the next step. +
*Applicable Step:* Save +
*Optional/Required:* Optional +
*Data Type:* Function + 
*Default Value:* N/A +

.Example
[source,kotlin] 
----
keepResponse()
----

| `fetchAll`
a| Fetches all results from Elasticsearch, even if over the result-sized window. +
*Applicable Step:* Search +
*Optional/Required:* Optional +
*Data Type:* Function + 
*Default Value:* N/A + 

.Example
[source,kotlin] 
----
   fetchAll()
----

| `mapper`
a|Configures the JSON mapper to use for deserializing JSON documents from Elasticsearch into objects. +
*Applicable Step:* Search, Poll +
*Optional/Required:* Optional +
*Data Type:* Lambda that receives a JsonMapper to use in deserializing JSON records. + 
*Default Value:* N/A + 
 
.Example
[source,kotlin] 
----
mapper { jsonMapper ->
    // Custom configuration of the mapper
}
----
|===

== Examples of usage

=== Poll step

The `poll` step within the Elasticsearch plugin reads batches of documents periodically from Elasticsearch.
The output is a list of `ElasticsearchDocument` containing JSON data or deserialized to objects.

Ancestor::
Scenario

Functionality::
* The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. +
* The `poll` step within the Elasticsearch plugin uses a strategy of “delivered exactly once”. +
* The output of the `poll` step is an `ElasticsearchDocument` that contains maps of column to values.

Example::
[source,kotlin,linenumbers]
----
elasticsearch().poll {  <1>
    name = "my-poll-step"
    client { RestClient.builder(HttpHost.create("http://localhost:9200")).build() }  <2>
    query {       <3>
        """{
            "query":{
                "match_all":{}
            },
                "sort" : ["_score"]
            }""".trimIndent()
    }
    index("battery-state")   <4>
    pollDelay(Duration.ofSeconds(1))  <5>
}
----
 <1> Start the `poll` step.
 <2> Configure the REST client connection.
 <3> Configure the query.
 <4> Set the `elasticsearch` index to use for the queries.
 <5> Specify the delay between query executions.

//-
Tips::
* The `poll` step is generally used in conjunction with a `join` to assert data or inject data into a workflow.
* The `query` parameter requires at least one sorting field to filter the newest results and not fetch the same records repeatedly.
* The output of the `poll` step is an `ElasticsearchDocument` that contains maps of column names to values. If `flatten` is called, the records are provided one by one to the next step; otherwise each poll batch remains complete.

//-
Reference Documentation::
* Refer to
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params[Elasticsearch Query Parameters] for more information on query parameters.
* Refer to the https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after[Elasticsearch] documentation for further parameter and configuration information.

== Save step 
The `save` step within the Elasticsearch plugin persists a batch of documents into  https://www.elastic.co/[Elasticsearch].

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate a list of documents that are forwarded to https://www.elastic.co/[Elasticsearch].

Example::
[source,kotlin,linenumbers]
----

previousStep.elasticsearch().save {   <1>
    name = "my-save-step" <2>
    client {    <3>
        RestClient.builder(HttpHost.create("http://localhost:9200"))
            .build() 
    }
    documents { stepContext, input ->  <4>
        listOf(
            Document(
                index = "battery-state",
                id = input.deviceId,
                source = objectMapper.writeValueAsString(input)  
            )
        )
    }
}
----

<1> Start the `save` step. 
    Note: `previousStep` is a placeholder for any preceding step (e.g. `collect()` etc.)
<2> Give a name to the step.
<3> Configure the REST client connection.
<4> Define the strategy to create documents to save using the step context and input.

//-
Reference Documentation::
Refer to the https://www.elastic.co/guide[Elasticsearch] documentation for further parameter information.

== Search step
The `search` step within the Elasticsearch plugin searches documents in the Elasticsearch database using a search query.

Ancestor::
Step

Functionality::
The `search` step’s input and step context are used to generate a query; the batch of results is then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
previousStep.elasticsearch().search {   <1>
    name = "my-search-step"
    client {    <2>
        RestClient.builder(HttpHost.create("http://localhost:9200")).build()
    }
    index {  stepContext, input -> listOf("battery-state") }   <3>
    query { stepContext, input ->     <4>
        """{
            "query": {
                "bool": {
                    "must": [
                        { "match": { "deviceId": "${input.input.deviceId}" }},
                        { "term": { "timestamp": ${input.input.timestamp.epochSecond} }}
                    ]
                }
            }
        }"""
    }  
}
----
<1> Start the `search` step.
    Note: `previousStep` is a placeholder for any preceding step (e.g. `collect()` etc.)
<2> Configure the REST client connection.
<3> Set the `elasticsearch` indices to use for the queries, resolved from the step context and input.
<4> Configure the builder for the JSON query to perform a search, resolved from the step context and input.

//-
Reference Documentation::
* Refer to the https://www.elastic.co/guide[Elasticsearch] documentation for further parameter and configuration information.
* For specifics on `queryParameters` refer to https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-search#operation-search-query[Elasticsearch Query Parameters].
* For specifics on `search` parameters, refer to
 https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html[Elasticsearch Search Parameters].

== ElasticsearchSaveAndSearch scenario
[source,kotlin,linenumbers]
----
@Scenario("elasticsearch-save-and-search")
fun scenarioSaveAndSearch() {
    scenario { <1>
        minionsCount = 10
        profile {
            immediate()
        }
    }
        .start()
        .jackson() <2>  
        .csvToObject(mappingClass = BatteryState::class) { <3> 
            classpath(path = "battery-levels.csv") 
            header {     <4> 
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
                }
            unicast()  <5>
        }
        .map { it.value } <6> 
        .elasticsearch()
        .save {
            name = "save"
            client {  <7>
                RestClient.builder(HttpHost.create("http://localhost:9200"))
                    .build() 
            }
            documents { _, input ->
                listOf(
                    Document(
                        index = "battery-state",
                        id = input.deviceId,
                        source = objectMapper.writeValueAsString(input) <8>
                    )
                )
            }
        }
        .delay(Duration.ofSeconds(2)) <9>
        .elasticsearch()
        .search {
            name = "search"
            client {
                RestClient.builder(HttpHost.create("http://localhost:9200"))
                    .build()
            }
            index { _, _ -> listOf("battery-state*") } <10> 
            query { _, input ->   <11> 
                """{
                    "query": {
                        "bool": {
                            "must": [
                                { "match": { "deviceId": "${input.input.deviceId}" }},
                                { "term": { "timestamp": ${input.input.timestamp.epochSecond} }}
                            ]
                        }
                    }
                }"""
            } 
        }
        .deserialize(targetClass = BatteryState::class) <12> 
        .verify { result ->  <13>
            val savedBatteryState = result.first.input
            result.second.asClue {
                assertSoftly {
                    it.results shouldHaveSize 1
                    it.results.first().value.batteryLevel shouldBe savedBatteryState.batteryLevel
                }
            }
        }
    }
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Set the data transfer method to `unicast`.  
<6> Transform the output of the CSV reader entries to utils.BatteryState.
<7> Configure the rest client to submit requests to elasticsearch.
<8> Parse the object to save to json.
<9> Add a 2-second delay to ensure that the newly indexed data is fully refreshed and searchable before proceeding. 
<10> Specify the Elasticsearch index pattern to search.
<11> Build the query to retrieve the `battery-state` document for a specific device id and timestamp.
<12> Define the method to transform the Elasticsearch result to a specific object.
<13> Define the verification parameters.

== ElasticsearchSaveAndPoll scenario
[source,kotlin,linenumbers]
----
@Scenario("elasticsearch-save-and-poll")
fun scenarioSaveAndPoll() {
    scenario {  <1>
        minionsCount = 10
        profile {
            immediate()
        }
    }
        .start()
        .jackson() <2>
        .csvToObject(mappingClass = BatteryState::class) { <3>
            classpath(path = "battery-levels.csv")
            header {  <4>
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
            }
            unicast()
        }
        .map { it.value } <5> 
        .elasticsearch()
        .save {
            name = "save"
            client { 
                RestClient.builder(HttpHost.create("http://localhost:9200"))
                    .build() <6> 
            }
            documents { _, input ->
                listOf(
                    Document(
                        index = "battery-state",
                        id = input.deviceId,
                        source = objectMapper.writeValueAsString(input) <7> 
                    )
                )
            }
        }
        .map { it.input }
        .delay(duration = Duration.ofSeconds(2)) <8>
        .innerJoin()
        .using { correlationRecord -> correlationRecord.value.deviceId }
        .on {
            it.elasticsearch().poll {
                name = "poll"
                client +
                    { RestClient.builder(HttpHost.create("http://localhost:9200")).build() }
                query {
                    """{
                        "query":{
                            "match_all":{}
                        },
                        "sort" : ["_score"]
                        }""".trimIndent()
                }
                index("battery-state*") <9> 
                pollDelay(delay = Duration.ofSeconds(1)) <10> 
            }
                .deserialize(targetClass = BatteryState::class) <11> 
                .flatten() <12>
                .map { record ->
                    record.value
                }
        }
        .having { correlationRecord -> correlationRecord.value.deviceId }. <13>
        .filterNotNull()
        .verify { result ->  <14>
            result.asClue {
                assertSoftly {
                    it.first.batteryLevel shouldBeExactly it.second.batteryLevel
                }
            }
        }
}
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.
<6> Configure the rest client to submit requests to elasticsearch.
<7> Parse the object to save to json.
<8> Add a 2-second delay to ensure that the newly indexed data is fully refreshed before proceeding. 
<9> Specify the Elasticsearch index pattern to poll for data.
<10> Set the poll delay to 2 seconds to avoid saturating the server with requests.
<11> Flatten the incoming polled batches so documents are forwarded one by one.
<12> Define the mapping for the incoming data stream. 
<13> Correlate on `deviceId` for joining the saved record with the polled record. 
<14> Verify that the saved and polled battery levels match.

== Configuration of publication of events and meters to Elasticsearch

NOTE::
Configure `event` and `meter` publication settings in the factory configuration, separate from the scenario DSL.

Refer to xref:up-and-running/configuration/provide-configuration.adoc[Provide the configuration to QALIPSIS] for information about specifying the configuration to QALIPSIS.

Events::
`events.export.elasticsearch`

Meters::
`meters.export.elasticsearch`


=== Event and meter parameters

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

|`enabled` +
Boolean flag to activate/deactivate event/meter publishing to elasticsearch; *must* be set to `true`to enable publishing.
a| *Applicable Steps:* Events, Meters +
 *Optional/Required:* Required +
 *Data Type:* Boolean + 
 *Default Value:* false + 

.Example
[source,kotlin] 
----
enabled: true
----

|`min-level`
a|Minimal accepted level of events to publish; allowable values are `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`. +
* `TRACE` = most verbose, shows internal and fine‑grained details for deep troubleshooting. +
* `DEBUG` = diagnostic information useful to investigate issues. +
* `INFO` = routine operational messages and high‑level progress. +
* `WARN` = indications of potential problems that do not stop processing. +
* `ERROR` = confirmed problems that need attention. +
* `OFF` = disable event publishing.+

 *Applicable Step* Events +
 *Optional/Required:* Required +
 *Data Type:* ENUM + 
 *Default Value:* `INFO` + 

.Example
[source,kotlin] 
----
min-level: INFO
----

| `urls` 
a| List of URLs for the Elasticsearch instances. +
*Applicable Step* Events +
*Optional/Required:* Required +
*Data Type:* url(s) + 
*Default Value:* http://localhost:9200 + 

.Example
[source,kotlin] 
----
urls: http://localhost:9200 +
----

| `step`
a| The step size (reporting frequency) to use for QALIPSIS monitoring of meters. +
*Applicable Step* Meters +
*Optional/Required:* Required +
*Data Type:*  Duration +
*Default Value:* PT10S + 

.Example
[source,kotlin] 
----
step: PT10S
----

| `index-prefix`
a| Prefix for the created indices containing the elasticearch events or meters. +
*Applicable Step* Events, Meters +
*Optional/Required:* Required +
*Data Type:*  String +
*Default Value:* +
* Events: qalipsis-events +
* Meters: qalipsis-meters +

.Example (Events)
[source,kotlin] 
----
index-prefix: qalipsis-events  
----

.Example (Meters)
[source,kotlin] 
----
index-prefix: qalipsis-meters  
----

| `path-prefix` for `urls`
a| Prefix used to demarcate url paths. +
*Applicable Step* Events +
*Optional/Required:* Optional +
*Data Type:*  String +
*Default Value:* / +
 
.Example
[source,kotlin] 
----
path-prefix: /
----

|`index-date-pattern`
a| Date pattern appended to the index name to generate time-partitioned indices. +
*Applicable Steps:*  Events, Meters +
*Optional/Required:*  Required +
*Data Type:*  Date +
*Default Value:* yyyy-MM-dd +

.Example
[source,kotlin] 
----
index-date-pattern: yyyy-MM-dd
----
   
|`auto-create-index`
a| Enable/disable auto creation of the index. +
*Applicable Step:* Meters +
*Optional/Required:* Required +
*Data Type:* Boolean flag +
*Default Value:* true +

.Example
[source,kotlin] 
----
auto-create-index: true
----

|`duration-as-nano` 
a| Identifies whether durations are exported as nanoseconds(true); `false` converts to milliseconds. +
*Applicable Step:* Events +
*Optional/Required:* Optional +
*Data Type:* Boolean flag +
*Default Value:*  false +

.Example
[source,kotlin] 
----
duration-as-nano: true
----

| `refresh-interval` 
a| Delay to refresh the indices in Elasticsearch +
*Applicable Step:* Meters +
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* 10s +

.Example
[source,kotlin] 
----
refresh-interval: 15s
----

| `store-source` +
a| Indicates whether the `_source` field of documents is stored with the values; set to `true` for yes and `false` for no. +
*Applicable Step:* Events +
*Optional/Required:* Optional +
*Data Type:* Boolean flag + 
*Default Value:*  false +

.Example
[source,kotlin] 
----
store-source: true
----

| `linger-period` 
a| Maximum time to buffer events before forcing a flush, even if the batch size is not reached. +
*Applicable Step:* Events +
*Optional/Required:* Required +
*Data Type:* Positive duration string +
*Default Value:* 10s +

.Example
[source,kotlin] 
----
linger-period: 10s
----

| `batch-size`
a| Maximum number of events buffered between two publications of events to Elasticsearch before flushing a bulk request. +  
*Applicable Step:* Events + 
*Optional/Required:* Required +
*Data Type:* Positive integer +
*Default Value:* 40000 +

.Example
[source,kotlin] 
----
batch-size: 2000
----

| `publishers`
a| Number of concurrent publication of events that can send batches to elasticsearch. +
*Applicable Step:* Events +
*Optional/Required:* Required +
*Data Type:* Positive integer +
*Default Value:* 1 (no concurrency) +

.Example
[source,kotlin] 
----
publishers: 1
----

|`shards`
a| Number of shards to apply to the created indices. +
*Applicable Steps*:* Events, Meters +
*Optional/Required:* Required +
*Data Type:* Positive integer +
*Default Value:* 1 +

.Example
[source,kotlin] 
----
shards: 1
----

|`replicas` 
a| Number of replicas to apply to the created indices. +
*Applicable Steps*:* Events, Meters +   
*Optional/Required:* Required +
*Data Type:* Positive integer +
*Default Value:* 0 +

.Example
[source,kotlin] 
----
replicas: 3
----

|`username` 
a| Name of the user for basic authentication when connecting to Elasticsearch. +
   By default, Elasticsearch does not require a `username` for authentication. However; it is recommended that the information be provided to ensure secure access to the Elasticsearch data. +
*Applicable Steps*:* Events, Meters + 
*Optional/Required:* Optional +
*Data Type:* String +
*Default Value:* null +

.Example
[source,kotlin] 
----
username: JohnS
----

|`password` 
a|Password of the user for basic authentication when connecting to Elasticsearch. +
*Applicable Steps*:* Events, Meters + 
*Optional/Required:* Optional +
*Data Type:* String +
*Default Value:* null +

.Example
[source,kotlin] 
----
password: my-secret-password 
----

|===

=== Example configuration file snippet (YAML)
Below are example configuration excerpts for event and meter publishing. Replace placeholders before use.
[source,yaml,linenumbers]
----
events: <1>
    export:
        elasticsearch: <2>
            enabled: true
            min-level: INFO
            urls: http://localhost:9200
            index-prefix: qalipsis-events
            index-date-pattern: yyyy-MM-dd
            duration-as-nano: false
            linger-period: 10s
            batch-size: 40000
            publishers: 1
            username: johndoe
            password: my-secret-password
            shards: 1
            replicas: 0

meters: <3>
    export:
        elasticsearch: <4>
            urls: http://localhost:9200 
            host: ${meters.export.elasticsearch.urls} 
            enabled: true 
            index-prefix: qalipsis-meters
            index-date-pattern: yyyy-MM-dd
            auto-create-index: true
            publishers: 1
            username: johndoe
            password: my-secret-password
            shards: 1
            replicas: 0
---- 
<1> Start event configuration.
<2> Configure event publishing to Elasticsearch. 
<3> Start meter configuration.
<4> Configure meter publishing to Elasticsearch.

//-
Reference Documentation:: 
Refer to xref:up-and-running/configuration/monitoring-test-campaigns.adoc[Monitoring test campaigns] for a further explanation of the event and meter parameter values. 
