= Graphite plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview

The `https://github.com/graphite-project/graphite-web[Graphite]` plugin connects QALIPSIS to Graphite using the pickle or plaintext protocol.

Technology addressed::

Graphite: https://graphiteapp.org/

Dependency::
`io.qalipsis:plugin-graphite`

Namespace in scenario::
`graphite()`

Client library::
* https://netty.io/[Netty]
* https://ktor.io/[Ktor]

Supported steps::
* <<Poll step,`poll`>>: polls data from Graphite. 
* <<Save step,`save`>>: saves events and records to Graphite. 

Example of usage are provided later in this <<Example of usage,section>>.

== Configuration

=== Sample configuration file

Graphite configuration settings are configured in a graphite.yaml file. 

[source,kotlin,linenumbers]
----
campaign:
  name: graphite-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S
----

=== Configuration parameters

Available parameters are described in the table below.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `name`
a| Name of the step. +
 *Applicable Steps:* Poll   +
 *Optional/Required:* Required +
 *Data Type:* String +
 *Default Value:* N/A +

.Example
[source,kotlin,linenumbers]
----
name = "my-poll-step"
----

| `connect` 
a| Configures the connection to the https://github.com/graphite-project/graphite-web[Graphite] server. +
 *Applicable Steps:* Poll, Save +  
 *Optional/Required:* Required +
 *Data Type:* Lambda +
 *Default Value:* N/A +

.Example (Save)
[source,kotlin,linenumbers]
----
connect {
  server("localhost", 2003)
}
----
.Example (Poll)
[source,kotlin,linenumbers]
----
connect {
  server("http://localhost:8090/render")
}
----

| `connect.server`
a| Server for the connection. +
  *Applicable Steps:* Poll, Save +  
 *Optional/Required:* Required +
 *Data Type:* String +
 *Default Value:* N/A +

.Example (Save)
[source,kotlin,linenumbers]
----
server("localhost", 2003)
----

.Example (Poll)
[source,kotlin,linenumbers]
----
server("http://localhost:8090/render")
----

|`records`
a| Generates and configures a list of saved records. +
 *Applicable Steps:* Save    +
 *Optional/Required:* Required +
 *Data Type:* Lambda +
 *Default Value:* N/A +

.Example
[source,kotlin,linenumbers]
----
records { _, input ->
  listOf(
    GraphiteRecord(
      metricPath = "device.battery-state.${input.deviceId.lowercase()}",
      value = input.batteryLevel,
      timestamp = input.timestamp
    )
  )
}
----

|`GraphiteRecord`
a| Defines the data format of the saved records. +
 *Applicable Steps:* Save    +
 *Optional/Required:* Required +
 *Data Type:* Lambda data formatter +
 *Default Value:* N/A +

.Example
[source,kotlin,linenumbers]
----
GraphiteRecord(
      metricPath = "device.battery-state.${input.deviceId.lowercase()}",
      value = input.batteryLevel,
      timestamp = input.timestamp
)
----

|`metricPath`
a|The address for the saved data. +
 *Applicable Steps:* Save    +
 *Optional/Required:* Required +
 *Data Type:* String +
 *Default Value:* N/A +

.Example
[source,kotlin,linenumbers]
----
metricPath = "device.battery-state.${input.deviceId.lowercase()}"
----

|`value`
a| The value to record.  +
 *Applicable Steps:* Save    +
 *Optional/Required:* Required +
 *Data Type:* String +
 *Default Value:* N/A +

.Example
[source,kotlin,linenumbers]
----
value = input.batteryLevel
----

|`timestamp`
a| Captures the exact moment the value recorded.  +
 *Applicable Steps:* Save    +
 *Optional/Required:* Required +
 *Data Type:* timestamp +
 *Default Value:* N/A +

.Example
[source,kotlin,linenumbers]
----
timestamp = input.timestamp
----

| `monitoring`
a| Configures the monitoring of the step. +
 *Applicable Steps:* Poll, Save +
 *Optional/Required:* Optional +
 *Data Type:* Lambda within which monitoring parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
monitoring {
    meters = true
    events = true
}
----

| `monitoring.meters`
a| Enables or disables the monitoring by meters for the step.
*Applicable Steps:* Poll, Save +
 *Optional/Required:* Optional +
 *Data Type:* Boolean +
 *Default Value:* false +

.Example
[source,kotlin] 
----
monitoring {
    meters = true
}
----

| `monitoring.events`
a| Enables or disables the monitoring by events for the step.
 *Applicable Steps:* Poll, Save +
 *Optional/Required:* Optional +
 *Data Type:* Boolean +
 *Default Value:* false +

.Example
[source,kotlin] 
----
monitoring {
    events = true
}
----

| `monitoring.all`
a| Enables all monitoring options for the step.
 *Applicable Steps:* Poll, Save +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/ +

.Example
[source,kotlin] 
----
monitoring {
    all()
}
----

| `query`
a|Specifies a query to retrieve metrics from the https://github.com/graphite-project/graphite-web[Graphite] server. +
 *Applicable Steps:*  Poll +
 *Optional/Required:* Required +
 *Data Type:* Lambda +
 *Default Value:* N/A

.Example
[source,kotlin,linenumbers]
----
query {
  withTarget("device.battery-state.*")
    .from(GraphiteMetricsTime(-2, GraphiteMetricsTimeUnit.DAYS))
    .noNullPoints(true)
}
----

| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
  Specify one of the strategies directly (not wrapped in a lambda). +
  Available strategies: `sequential`, `broadcast`, `unicast`, `loop`. +

 * `broadcast`: sends every polled record to all minions. Records are delivered in order, with the oldest buffered record sent first. In this mode, the singleton behaves like a Pub/Sub broadcaster. 

 * `unicast`: sends each polled record to exactly one minion. The singleton acts as a FIFO distributor: Records are stored in a buffer until a minion consumes them. The buffer has a fixed size; when it becomes full, the oldest records are dropped to make space for new ones. 

 * `loop`: sends each polled record to all minions, but once the end of the buffer is reached, it loops back to the beginning. This creates a continuous cyclic stream of the buffered records. 

 * `sequential`: disables singleton execution and runs this step within the parent’s workflow. Data distribution is controlled entirely by the parent step. This mode is typically used when you want to process each record from a source from start to finish once, and then stop publishing until new data is available.
   
 Note::
 Each strategy EXCEPT `sequential` requires `bufferSize` (Int) and `idleTimeout` (Duration); see `singletonConfiguration.bufferSize` and `singletonConfiguration.idleTimeout` definitions below. +

*Applicable Step:* Poll +
*Optional/Required:* Optional +
*Data Type:* Function +
*Default Value:* unicast(bufferSize, idleTimeout)

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.bufferSize`
a| Size of the buffer used to store polled records before delivery to minions.+ +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Integer +
 *Default Value:* -1 +

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.idleTimeout`
a| Maximum time to wait before delivering polled records to minions, even if the buffer is not full. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration +
 *Default Value:* Duration.ZERO +

.Example
[source,kotlin] 
---- 
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `broadcast`
a| Specifies the broadcast parameters for a step. +
 *Applicable Step:* Poll
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
broadcast(3, Duration.ofMinutes(1))
----

| `unicast`
a| Specifies the unicast parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
unicast(1, Duration.ofMinutes(3))
----

| `loop`
a| Specifies the loop parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
loop(5, Duration.ofMinutes(2))
----

| `sequential`
a| Specifies the sequential parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
sequential()
----

| 
a|`delay`
 *Applicable Step:*    Save +
 *Optional/Required:*
 *Data Type:* enum
 *Default Value:* 10s

.Example
[source,kotlin,linenumbers]
----
.delay(Duration.ofSeconds(1))
----

| `pollDelay`
a|

 *Applicable Step:* Poll +
 *Optional/Required:*
 *Data Type:* enum
 *Default Value:* 10s

.Example
[source,kotlin,linenumbers]
----
pollDelay(Duration.ofSeconds(1))
----

|===

== Examples of usage

== Poll step
The poll step within the the Graphite plugin collects metrics from a Graphite server and broadcasts them to other components.

Ancestor::
Scenario or Step

Functionality::  
The ‘poll’ step is typically used to collect and distribute metrics for monitoring and visualization purposes.
 
Example::
[source,kotlin,linenumbers]
----
graphite().poll {
  name = "my-poll-step"

  connect { 
    server("http://localhost:8080")
  }

  query( 
    GraphiteQuery("device.battery-state.*")
      .from( 
        GraphiteMetricsTime(
          2,
          GraphiteMetricsTimeSignUnit.MINUS,
          GraphiteMetricsTimeUnit.DAYS
        )
      )
      .noNullPoints(true)
  )
  broadcast(123, Duration.ofSeconds(20))
  pollDelay(Duration.ofSeconds(1))
}
----


Reference documentation::
Refer to the https://github.com/graphite-project/graphite-web/tree/master/docs[Graphite] documentation for parameter and configuration information. 

== Save step
The `save` step within the Graphite plugin persists records into a Graphite database using the save query.

Ancestor::
Scenario or Step

Functionality::
The `save` step's input and step context are used to generate documents to save into Graphite.

Example::
[source,kotlin,linenumbers]
----
.graphite()
.save {

  connect {
    server("localhost", 2003)
  }

  records { _, input ->
    listOf(
      GraphiteRecord(
        metricPath = "device.battery-state.${input.deviceId.lowercase()}",
        value = input.batteryLevel,
        timestamp = input.timestamp
      )
    )
  }
  monitoring {
    events = false
    meters = true
  }
}
----

Reference documentation::
Refer to the https://github.com/graphite-project/graphite-web/tree/master/docs[Graphite] documentation for further parameter and configuration information. 

=== GraphiteSaveAndPoll scenario
[source,kotlin,linenumbers]
----
scenario {
  minionsCount = 20
  profile {
    immediate()
  }
}
  .start() 
  .jackson() <1>
  .csvToObject(mappingClass = BatteryState::class) {  <2>
    classpath(path = "battery-levels.csv")
    header { <3>
      column(name = "device_id")
      column(name = "timestamp")
      column(name = "battery_level").integer()
    }
    unicast()
  }
  .map { <4>
    val timeReportedToToday = LocalTime.from(it.value.timestamp.atZone(ZoneId.systemDefault()))
    val deviceTimestampReportedToToday = 
        yesterday.atTime(timeReportedToToday.hour, timeReportedToToday.minute, timeReportedToToday.second)

    it.value.copy(timestamp = deviceTimestampReportedToToday.toInstant(localZoneOffset))
  }
  .graphite() <5> 
  .save {

    connect {
      server("localhost", 2003)
    }

    records { _, input ->
      listOf(
        GraphiteRecord(
          metricPath = "device.battery-state.${input.deviceId.lowercase()}",
          value = input.batteryLevel,
          timestamp = input.timestamp
        )
      )
    }

    monitoring {
      events = false
      meters = true
    }

  }
  .delay(Duration.ofSeconds(1))
  .map { it.input }
  .innerJoin()
  .using { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .on {
    it.graphite().poll {
      name = "my-poll-step"

      connect {
        server("http://localhost:8090/render")
      }

      monitoring {
        events = false
        meters = true
      }

      query {
        withTarget("device.battery-state.*") <6>                             
          .from(GraphiteMetricsTime(-2, GraphiteMetricsTimeUnit.DAYS))
          .noNullPoints(true)
      }
      broadcast(123, Duration.ofSeconds(20))
      pollDelay(Duration.ofSeconds(1))
    }
      .flatten()
      .map { record ->
        val dataPoint = record.dataPoints.first()
        BatteryState(
          deviceId = record.target.substringAfter("device.battery-state.").uppercase(),
          batteryLevel = dataPoint.value.toInt(),
          timestamp = dataPoint.timestamp
        )
      }
  }
  .having { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .filterNotNull()
  .verify { result ->
    result.asClue {
      assertSoftly {
        it.first.batteryLevel shouldBeExactly it.second.batteryLevel
      }
    }
  }

----
<1> Start the jackson step to fetch data from the csv file. 
<2> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<3> Define the header of the csv file.
<4> Force the timestamp to a recent date; Graphite generates data points for all the missing granular periods; setting the timestamp to a recent date avoids having too many data points.
<5> Transform the output of the CSV reader entries to utils.BatteryState.
<6> Set the date range for the query; by default, Graphite provides only the latest 24 hours.

== Configuration of publication of events and meters to Graphite.

NOTE::
Configure `event` and `meter` publication settings in the factory configuration, separate from the scenario DSL.

Refer to xref:up-and-running/configuration/provide-configuration.adoc[Provide configuration] for information about specifying the configuration to QALIPSIS.

Events::
`events.export.graphite`

Meters::
`meters.export.graphite`

=== Event and meter parameters

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

|`enabled`
a|Activates/deactivates event publishing to Graphite.
 *Applicable Steps:* Events, Meters +
 *Optional/Required:* Required +
 *Data Type:* Boolean + 
 *Default Value:* false + 

.Example
[source,kotlin] 
----
enabled: `true`
----

|`min-level`
a|Minimal accepted level of events to publish; allowable values are `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`. +
* `TRACE` = most verbose, shows internal and fine‑grained details for deep troubleshooting. +
* `DEBUG` = diagnostic information useful to investigate issues. +
* `INFO` = routine operational messages and high‑level progress. +
* `WARN` = indications of potential problems that do not stop processing. +
* `ERROR` = confirmed problems that need attention. +
* `OFF` = disable event publishing.+

 *Applicable Steps* Events +
 *Optional/Required:* Required +
 *Data Type:* enum + 
 *Default Value:* `INFO` + 

.Example
[source,kotlin] 
----
min-level: INFO
----

| `host`
a| Host for the Graphite instances. +
 *Applicable Steps:* Events, Meters +
 *Optional/Required:* Required +
 *Data Type:* string +
 *Default Value:* localhost; cannot be blank + 

.Example
[source,kotlin] 
----
host: localhost
----

| `port`
a| Host for the Graphite instances. +
 *Applicable Steps:* Events, Meters +
 *Optional/Required:* Required +
 *Data Type:* Positive integer.  +
 *Default Value:* `2004` + 

.Example
[source,kotlin] 
----
port: `2004`
----

| `step`
a| The step size (reporting frequency) to us for monitoring meters.
 *Applicable Step* Meters +
 *Optional/Required:* Required +
 *Data Type:*  Duration +
 *Default Value:* PT10S + 

.Example
[source,kotlin] 
----
step: PT10S
----

| `linger-period`
a| Maximum period between two publications of events to Graphite,
 *Applicable Step* Meters +
 *Optional/Required:* Required +
 *Data Type:*  Positive duration +
 *Default Value:* 10S + 

.Example
[source,kotlin] 
----
linger-period: 10s
----

| `protocol`
a|GraphiteProtocol type; default is pickle; available choices are pickle or plaintext.
 *Applicable Step:* Events + 
 *Optional/Required:* Required +
 *Data Type:* enum +
 *Default Value:* 4000 +

.Example
[source,kotlin] 
----
batch-size: 2000
----

| `batch-size`
a| Maximum number of events buffered between two publications of events to Graphite. +
 *Applicable Step:* Events + 
 *Optional/Required:* Required +
 *Data Type:* Positive integer +
 *Default Value:* `2`

.Example
[source,kotlin] 
----
batch-size: `2`
----

| `publishers`
a| Number of concurrent publication of events that can send batches to Graphite. +
 *Applicable Step:* Events
 *Optional/Required:* Required +
 *Data Type:* Positive integer +
 *Default Value:* `2`  +

.Example
[source,kotlin] 
----
publishers: `2`
----
|===

=== Example configuration file snippet (YAML)
[source,kotlin,linenumbers]
----
events: <1>
  export:
    graphite: <2>
      enabled: true
      min-level: INFO
      host: localhost
      port: 2004
      protocol: pickle
      batch-size: 2
      linger-period: 10s
      publishers: 2

meters: <3>
  export:
    graphite: <4>
      host: localhost
      port: 2004
      enabled: true
      step: PT10S
----

<1> Start the event configuration scenario.
<2> Configure event publishing to Graphite. 
<3> Start the meter configuration scenario.
<4> Configure meter publishing to Graphite.