= InfluxDB plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview

The InfluxDB plugin connects QALIPSIS to https://www.influxdata.com/[InfluxDB].

Technologies addressed::
* InfluxDB: https://www.influxdata.com/[]
* Flux: https://docs.influxdata.com/flux/v0.x/[] 

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-influxdb`

Namespace in scenario::
`influxdb()`

Client library::
influxdb-client-kotlin: refer to the https://github.com/influxdata/influxdb-client-java/tree/master/client-kotlin[influxdb-client-kotlin].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Search step,`search`>>: searches records and builds a query from the input and step context.

Examples of usage are provided later in this <<Examples of usage,section>>.

== Configuration

=== Example configuration file
InfluxDB configuration settings are configured in a cassandra.yaml file.

[source,kotlin,linenumbers]
----
campaign:
  name: influxdb-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----


=== Configuration parameters
Available parameters are described in the table below.
[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `connect`  +
a| Defines the connection parameters to https://www.influxdata.com/[InfluxDB]. +
*Applicable Steps:* Poll, Search, Save +
*Optional/Required:* Required +
*Data Type:* Lambda within which connection parameters are defined. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
connect {
    server(
        url = "http://localhost:18086",
        bucket = "iot",
        org = "qalipsis",
        token = "INFLUX_TOKEN"
    ) 
}
----

| `connect.server`  +
a| Identifies the server parameters for the connection to https://www.influxdata.com/[InfluxDB]. +
*Applicable Steps:* Poll, Search, Save +
*Optional/Required:* Required +
*Data Type:* Named function argument +
*Default Value:* N/A +
 
.Example
[source,kotlin]
----
connect {
    server(
        url = "http://localhost:18086",
        bucket = "iot",
        org = "qalipsis",
        token = "INFLUX_TOKEN"
    )
}
----

| `connect.server.url`  
a| Identifies the url for the connection to https://www.influxdata.com/[InfluxDB]. +
*Applicable Steps:* Poll, Search, Save +
*Optional/Required:* Required +
*Data Type:* url +
*Default Value:* http://localhost:8086 +
 
.Example
[source,kotlin]
----
connect {
    server(
        url = "http://localhost:8086"
    )
}
----
 
| `connect.server.bucket`  
a| Name of the bucket to use; a bucket defines the the highest level of data organization in InfluxDB. +
*Applicable Steps:* Poll, Search, Save +
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* "" +
 
.Example
[source,kotlin]
----
connect {
    server(
        bucket = "iot"
    )
}
----

|`connect.server.org`  
a| The name of the organization (i.e., workspace) associated with the bucket. +
*Applicable Steps:* Poll, Search, Save +
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* N/A +
 
.Example
[source,kotlin]
----
connect {
    server(
    org = "qalipsis"
    )
}
----

|`connect.server.token`  
a| The user credentials (i.e., workspace) associated with the bucket. +
*Applicable Steps:* Poll, Search, Save +
*Optional/Required:* Required +
*Data Type:* string +
*Default Value:* N/A +
 
.Example
[source,kotlin]
----
connect {
    server(
        token = v-7g_W9X2R-K1Lp8mN5QjZxY4T6uVbW3aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789==
    ) 
}
----

| `query` 
a| Specifies a query respecting the requirements of https://www.influxdata.com/[InfluxDB]. +
*Applicable Steps:* Poll, Save, Search +
*Optional/Required:* Required +
*Data Type:* Lambda that returns a String. +
*Default Value:* N/A +

.Example (Poll)
[source,kotlin]
----
query( 
    """
    from(bucket:"${iot}")
        \|> range(start: -15m)
        \|> filter(
            fn: (r) => r._measurement == "battery_state"
        )
""".trimIndent()
)
----

.Example (Save)
----
query {  
    bucket = { _, _ -> "iot" }
    organization = { _, _ -> "qalipsis" }
    points = { _, input ->
        listOf(
            Point.measurement("battery_state")
                .addField("battery_level", input.batteryLevel)
                .addTag("device_id", input.deviceId)
                .addTag("timestamp", input.timestamp.epochSecond.toString())
        )
    }
}
----

.Example (Search)
----
query { _, input -> <
    """
        from(bucket: "${iot}")
            \|> range(start: -15m)
            \|> filter(
                fn: (r) => r._measurement == "${"battery_state"}" and
                r.${"device_id"} == "${input.deviceId}" and
                r.${"timestamp"} == "${input.timestamp.epochSecond}"
        )               
    """.trimIndent()
}
----

| `parameters`
a|Binds values to the clauses of the prepared query. +
*Applicable Steps:* Poll +
*Optional/Required:* Optional +
*Data Type:* + Lambda that returns a string. +
*Default Value:* `List<Any>` / `vararg Any` + 
 
.Example 
[source,kotlin]
----
parameters(listOf(1, "abc")) or parameters(1, "abc") 
----

| `pollDelay`
a| Specifies the delay between query executions. +
*Applicable Step:* Poll +
*Optional/Required:* Optional  +
*Data Type:* java.time.Duration +
*Default Value:* N/A + 

.Example
[source,kotlin]
----
pollDelay(Duration.ofSeconds(1)) 
----

| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
 Refer to xref:plugins/plugins.adoc#singletonconfiguration-parameters[SingletonConfiguration parameters] for details on strategies and examples of usage.
|===

== Examples of usage 

=== Poll step 
The `poll` step within the InfluxDB plugin polls the newest records from the database, with a delay between each execution of a select query.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. The `poll` step within the InfluxDB plugin uses a strategy of “delivered at least once”.

Example::
+
[source,kotlin,linenumbers]
----
influxdb().poll {
    connect { <1>
        server(
            url = "http://localhost:18086",
            bucket = "iot",
            org = "qalipsis"
        )
        basic(user = "DJones", password = "Oxford1987")
    }
    query( <2>
        """
        from(bucket:"${iot}")
            |> range(start: -15m)
            |> filter(
                fn: (r) => r._measurement == "battery_state" 
            )               
    """.trimIndent()
    )
    pollDelay(Duration.ofSeconds(1))
}
----
<1> Define the connection parameters to InfluxDB.
<2> Specify a query respecting the requirements of https://www.influxdata.com/[InfluxDB].

Tip::
Use the `poll` step with a join operator to verify the values that the tested system saves to the database.

Reference: Documentation::
Refer to the https://docs.influxdata.com/[InfluxDB] documentation for further parameter and configuration information.
 
=== Save step
The `save` step within the InfluxDB plugin persists a batch of records into the InfluxDB bucket using a specific `points` class.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate the bucket, the list of points with their measurement, and tags and fields, which are then combined and forwarded to the database.

Example::
+
[source,kotlin,linenumbers]
----
.save {
    connect { <1> 
        server(
            url =  "http://localhost:18086",
            bucket = "iot",
            org = "qalipsis"
        )
        basic(user = "DJones", password = "Oxford1987")
    }
    query {  <2>
        bucket = { StepContext, input -> "iot" }
        organization = { _, _ -> "qalipsis" }
        points = { _, input ->
            listOf(
                Point.measurement("battery_state")
                    .addField("battery_level", input.batteryLevel)
                    .addTag("device_id", input.deviceId)
                    .addTag("timestamp", input.timestamp.epochSecond.toString())
            )
        }
    }
}
----
<1> Define the connection parameters to InfluxDB.
<2> Specify a query respecting the requirements of https://www.influxdata.com/[InfluxDB].

//-
Tips::
* Use the `save` step after a `collect` step to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.
* The `save` step is extremely flexible: bucket, tags, measurement and fields might depend on the context and input value received from the previous step.

//-
Reference documentation::
Refer to the https://docs.influxdata.com/[InfluxDB] documentation for further parameter and configuration information.

=== Search step 
The `search` step within the InfluxDB plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The `search` step's input and step context are used to generate a query; the batch of results is then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
.influxdb()
.search {
    connect { <1>
        server(
            url = "http://localhost:18086",
            bucket = "iot",
            org = "qalipsis"
        )
        basic(user = "DJones", password = "Oxford1987")
    }
    query { StepContext, input -> <2>
        """
            from(bucket: "${iot}")
                |> range(start: -15m)
                |> filter(
                    fn: (r) => r._measurement == "${"battery_state"}" and
                    r.${"device_id"} == "${input.deviceId}" and
                    r.${"timestamp"} == "${input.timestamp.epochSecond}"
                )               
        """.trimIndent()
    }
}
----
<1> Define the connection parameters to InfluxDB.
<2> Specify a query respecting the requirements of https://www.influxdata.com/[InfluxDB].

//-
Tip::
Use the `search` step after a `collect` step to reduce the number of queries executed onto the database and to reduce the load the scenario generates on the test system.

Reference documentation::
Refer to the https://docs.influxdata.com/[InfluxDB] documentation for further parameter and configuration information.

=== InfluxdbSaveAndPoll scenario 
[source,kotlin,linenumbers]
----
@Scenario("influxdb-save-and-poll")
fun influxdbSearchSaveAndPoll() {
    scenario { <1>
        minionsCount = 20
        profile {
            immediate()
            }
        }
        .start()
        .jackson()  <2>
        .csvToObject(mappingClass = BatteryState::class) { <3>

            classpath(path = "battery-levels.csv")
               
            header { <4>  
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
                }
            unicast()
        }
        .map { it.value } <5> 
        .influxdb()
        .save { <6> 
            connect { <7>
                server(
                    url = "http://localhost:18086",
                    bucket = "iot",
                    org = "qalipsis"
                )
                basic(user = "qalipsis_user", password = "qalipsis_user_password")
            }
            query { <8>
                bucket = { _, _ -> "iot" }
                organization = { _, _ -> "qalipsis" }
                points = { _, input ->
                    listOf(
                        Point.measurement("pollable_battery_state")
                            .addField("battery_level", input.batteryLevel)
                            .addTag("device_id", input.deviceId)
                            .addTag("timestamp", input.timestamp.epochSecond.toString())
                    )
                }
            }
        }
        .map { it.input }  <9>
        .innerJoin()
        .using { correlationRecord ->
            correlationRecord.value.deviceId
        }
        .on {
            it.influxdb().poll { <10>
                connect {
                    server(
                        url = "http://localhost:18086",
                        bucket = "iot",
                        org = "qalipsis"
                    )

                    basic(user = "qalipsis_user", password = "qalipsis_user_password")
                }

                query(
                    """
                        from(bucket: "iot")
                        |> range(start: -15m)
                        |> filter(
                            fn: (r) => r._measurement == "pollable_battery_state" 
                        )               
                    """.trimIndent()
                )

                pollDelay(Duration.ofSeconds(1)) <9>

            }
                .flatten() <10>
                .map { fluxRecord -> <11>
                    BatteryState(
                        deviceId = fluxRecord.values["device_id"] as String,
                        timestamp = Instant.ofEpochSecond((fluxRecord.values["timestamp"] as String).toLong()),
                        batteryLevel = (fluxRecord.value as Number).toInt()
                    )
                }
        }
        .having { correlationRecord ->
            correlationRecord.value.deviceId
        }
        .filterNotNull()
        .verify { result ->
            result.asClue {
                assertSoftly {
                    it.first.batteryLevel shouldBeExactly it.second.batteryLevel
                }
            }
        }

}

----
// I need help here; I tried to follow the Elastisearch SaveAndPoll scenario but am having difficulty. 
// Please provide more input for the above code. 

<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file.
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.
<6> Start the save step.
<7> Define the parameters for connecting to InfluxDB. 
<8> Set the query parameters.
<9> Match the input from the previous step to to a database record????
<10> Set the poll delay to 2 seconds to avoid saturating the server with requests.
<11> Start the poll step.

=== InfluxdbSaveAndSearch scenario 

[source,kotlin,linenumbers]
----
@Scenario("influxdb-save-and-search")
fun influxdbSearchSaveAndPoll() {

    scenario {
        minionsCount = 20
        profile {
            immediate()
        }
    }
        .start()
        .jackson() <1> 
        .csvToObject(mappingClass = BatteryState::class) { <2>

            classpath(path = "battery-levels.csv")
           
            header { <3>  
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
            }
            unicast()
        }
        .map { it.value } <4> 
        .influxdb()
        .save {
            connect {
                server(
                    url = "http://localhost:18087",
                    bucket = "iot",
                    org = "qalipsis"
                )
                basic(user = "qalipsis_user", password = "qalipsis_user_password")
            }

            query {
                bucket = { _, _ -> "iot" }
                organization = { _, _ -> "qalipsis" }
                points = { _, input ->
                    listOf(
                        Point.measurement("searchable_battery_state")
                            .addField("battery_level", input.batteryLevel)
                            .addTag("device_id", input.deviceId)
                            .addTag("timestamp", input.timestamp.epochSecond.toString())
                    )
                }
            }
        }
        .map {
            it.input
        }
        .influxdb()
        .search {

            connect {
                server(
                    url = "http://localhost:18087",
                    bucket = "iot",
                    org = "qalipsis"
                )
                basic(user = "qalipsis_user", password = "qalipsis_user_password")
            }

            query { _, input ->
                """
                    from(bucket: "iot")
                        |> range(start: -15m)
                        |> filter(
                            fn: (r) => r._measurement == "searchable_battery_state" and
                                r.device_id == "${input.deviceId}" and
                                r.timestamp == "${input.timestamp.epochSecond}"
                        )               
                """.trimIndent()
            }

        }
        .map {
            it.input to it.results.map { fluxRecord ->
                BatteryState(
                    deviceId = fluxRecord.values["device_id"] as String,
                    batteryLevel = (fluxRecord.value as Number).toInt(),
                    timestamp = Instant.ofEpochSecond((fluxRecord.values["timestamp"] as String).toLong())
                )
            }
        }
        .verify { result ->
            result.asClue {
                assertSoftly {
                    it.second.size shouldBeExactly 1
                    it.first.batteryLevel shouldBeExactly it.second.first().batteryLevel
                }
            }
        }


    }
----
// Please provide more input for the above code. 
<1> Start the jackson step to fetch data from the csv file. 
<2> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<3> Define the header of the csv file.
<4> Transform the output of the CSV reader entries to utils.BatteryState.

== Configuration of publication of events and meters to InfluxDB

NOTE::
Configure `event` and `meter` publication settings in the factory configuration, separate from the scenario DSL.

Refer to xref:up-and-running/configuration/provide-configuration.adoc[Provide the configuration to QALIPSIS] for information about specifying the configuration to QALIPSIS.

Events::
`events.export.influxdb`

Meters::
`meters.export.influxdb`

=== Event and meter parameters

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

|`url`
a| Path for the publising of meters/events. +
*Applicable Steps:* Events, Meters +
*Optional/Required:* Required +
*Data Type:* url + 
*Default Value:* http://localhost:8086 + 

.Example
[source,kotlin] 
----
url: http://localhost:8086
----


|`enabled`
Boolean flag to activate/deactivate event/meter publishing to influxDB; *must* be set to `true`to enable publishing. +
a|*Applicable Steps:* Events, Meters +
*Optional/Required:* Required +
*Data Type:* Boolean + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
    enabled: true
----

|`min-level`
a|Minimal accepted level of events to publish; allowable values are `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`. +
* `TRACE` = most verbose, shows internal and fine‑grained details for deep troubleshooting. +
* `DEBUG` = diagnostic information useful to investigate issues. +
* `INFO` = routine operational messages and high‑level progress. +
* `WARN` = indications of potential problems that do not stop processing. +
* `ERROR` = confirmed problems that need attention. +
* `OFF` = disable event publishing.+

*Applicable Step* Events +
*Optional/Required:* Required +
*Data Type:* ENUM + 
*Default Value:* `INFO` + 

.Example
[source,kotlin] 
----
min-level: INFO
----

| `linger-period` 
a| Maximum time to buffer events before forcing a flush, even if the batch size is not reached. +
*Applicable Step:* Events +
*Optional/Required:* Required +
*Data Type:* Positive duration string +
*Default Value:* 10s +

.Example
[source,kotlin] 
----
linger-period: `10s`
----

| `batch-size`
a| Maximum number of events buffered between two publications of events to InfluxDB. +
*Applicable Step:* Events + 
*Optional/Required:* Required +
*Data Type:* Positive integer +
*Default Value:* 4000

.Example
[source,kotlin] 
----
batch-size: 2000
----

| `org`
a| Name of the organization to use for basic authentication when connecting to InfluxDB. +
*Applicable Step:* Events, Meters + 
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* `qalipsis`

.Example
[source,kotlin] 
----
org: `qalipsis`
----

| `bucket`
a| Password of the bucket to use for saving events and meters to InfluxDB.  +
 *Applicable Step:* Events, Meters + 
 *Optional/Required:* Required +
*Data Type:* String +
*Default Value:* +
 Events: `qalipsis-event` +
 Meters: `qalipsis-meter` +

.Example (Events)
[source,kotlin] 
----
bucket: qalipsis-event
----

.Example (Meters)
[source,kotlin] 
----
bucket: qalipsis-meter
----

| `step`
a| The step size (reporting frequency) to use for monitoring meters. +
*Applicable Step* Meters +
*Optional/Required:* Required +
*Data Type:*  Duration +
*Default Value:* PT10S + 

.Example
[source,kotlin] 
----
step: PT10S
----

|`token` 
a| The user credentials for basic authentication when connecting to InfluxDB. +
*Applicable Steps*:* Events, Meters + 
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* N/A +

.Example
[source,kotlin] 
----
token: v-7g_W9X2R-K1Lp8mN5QjZxY4T6uVbW3aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789==
----

|===

=== Example configuration file
[source,kotlin,linenumbers]
----
events:  <1>
    export:
        influxdb: <2>
            url: http://localhost:8086
            enabled: true
            min-level: INFO
            linger-period: 10s
            batch-size: 2000
            org: qalipsis
            bucket: qalipsis-event
            token: INFLUX_TOKEN

meters: <3>
    export:
        influxdb: <4>
            url: http://localhost:8086
            enabled: true
            step: PT10S
            org: qalipsis
            bucket: qalipsis-meter
            token:  INFLUX_TOKEN
----

<1> Start event configuration.
<2> Configure event publishing to influxdb. 
<3> Start meter configuration.
<4> Configure meter publishing to influxdb.

//-
Reference Documentation::
Refer to xref:up-and-running/configuration/monitoring-test-campaigns.adoc[Monitoring test campaigns] for a further explanation of the event and meter parameter values.


