= Jakarta EE Plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview

The Jakarta EE plugin connects QALIPSIS to a messaging platform that supports https://jakarta.ee/specifications/messaging/[JAKARTA EE Messaging].

Technology addressed::
https://jakarta.ee/specifications/messaging/[Jakarta EE Messaging] and the products compliant with it.

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-jakarta-ee-messaging`

Namespace in scenario::
` .jakarta()`

Client library::
Refer to https://jakarta.ee/[Jarkata EE].

Supported steps::
* <<Consume,`consume`>>: consumes data from a messaging platform supporting Jakarta EE.
* <<Produce,`produce`>>: pushes data to a messaging platform supporting Jakarta EE.

Example of usage are provided later in this <<Example of usage,section>>.

== Configuration

=== Example configuration file

Jakarta EE configuration settings are configured in a jakarta.yaml file. 
[source,kotlin,linenumbers]
----
campaign:
  name: jakarta-ee-messaging-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters

Available parameters are described in the table below.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `connect`  +
a| Defines the connection parameters for the `JakartaProducerRecord`(s). +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:* Lambda within which connection parameters are defined. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
connect {
  ActiveMQConnectionFactory(
    "tcp://localhost:61616",
      "qalipsis_user",
      "qalipsis_password"
    ).createQueueConnection()
  }
----

| `queues`
a| Specifies the queue(s) to consume. +
*Applicable Steps:* Consume +
*Optional/Required:* Required +
*Data Type:* Lambda within which connection parameters are defined. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
queues("battery_state")
----

| `QueueConnection`
a| Provides the connection to attach to the queue consumer, which is generally specific to the underlying product. +
*Applicable Steps:* Consume +
*Optional/Required:* Optional +
*Data Type:* Lambda within which connection parameters are defined. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
queueConnection {
    ActiveMQConnectionFactory(
      "tcp://localhost:61616",
      "qalipsis_user",
      "qalipsis_password"
    ).createQueueConnection()
  }
----

| `topics`
a| Specifies the topic(s) to consume. +
*Applicable Steps:* Consume +
*Optional/Required:* Optional +
*Data Type:* String. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
topics ("battery_state")
----


| `topicConnection`
a| provides the connection to attach to the topic consumer, which is generally specific to the underlying product. +
*Applicable Steps:* Consume +
*Optional/Required:* Optional +
*Data Type:* Lambda within which connection parameters are defined. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
topicConnection {
  ActiveMQConnectionFactory(
    "tcp://localhost:61616",
    "qalipsis_user",
    "qalipsis_password"
  ).createTopicConnection()
}
----

| `records`
a| Generates a list of records to send the messaging platform. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:* Lambda  +
*Default Value:* N/A +

.Example
[source,kotlin]
----
records { _, input ->
  listOf(
    JakartaProducerRecord(
      destination = Topic(name = "battery_state"),
      messageType = JakartaMessageType.BYTES,
      value = objectMapper.writeValueAsBytes(input)
    )
  )
}
----

| `destination`
a| Defines the destination for each `JakartaProducerRecord` as either queues (`QueueConnection`) or topics (`TopicConnection`). +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:* Function +
*Default Value:* N/A +

.Example
[source,kotlin]
----
destination = Topic(name = "battery_state")
----

| `messageType`
a| Indicates the `JakartaMessageType` as: `TEXT`, `AUTO`, `BYTES`, or `OBJECT`. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:* ENUM +
*Default Value:* N/A +

.Example
[source,kotlin]
----
messageType = JakartaMessageType.BYTES
----

|`value`
a| Defines the message to be displayed at the `destination`. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:* Function +
*Default Value:* N/A +

.Example
[source,kotlin]
----
value = objectMapper.writeValueAsBytes(input)
----

|`session`
a| Configures the session to attach to the message producer. +
*Applicable Steps:* Produce +
*Optional/Required:* Optional +
*Data Type:* Lambda within which session parameters are defined. +
*Default Value:* N/A +

.Example
[source,kotlin]
----
session {
  it.createSession(false, Session.AUTO_ACKNOWLEDGE)
}
----

|`producers`
a| The number of producers to use, in order to scale the data production upwards. +
*Applicable Steps:* Produce +
*Optional/Required:* Optional +
*Data Type:* Integer +
*Default Value:* 1 +

.Example
[source,kotlin]
----
producers = 1
----

| `deserialize`
a| Specifies the class to use to deserialize the body of the response. +
*Applicable Steps:* Consume +
*Optional/Required:* Required +
*Data Type:* function +
*Default Value:* N/A +

.Example
[source,kotlin]
----
 .deserialize(JakartaJsonDeserializer(targetClass = BatteryState::class))
----

| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
 Refer to xref:plugins/plugins.adoc#singletonconfiguration-parameters[SingletonConfiguration parameters] for details on strategies and examples of usage.

|===
== Example of usage

=== Consume step
The `consume` step within the Jakarta EE plugin consumes records from a Jakarta-EE-Messaging-compatible product.

Ancestor::
Scenario 

Functionality::
The `consume` step polls data from the designated connection, step context, and the data deserializer.

Example::
+
[source,kotlin,linenumbers]
----
it.jakarta().consume {. <1>
  queues("battery_state") <2>
  queueConnection { <3>
    ActiveMQConnectionFactory(
      "tcp://localhost:61616",
      "qalipsis_user",
      "qalipsis_password"
    ).createQueueConnection()
  }
}
  .deserialize(JakartaJsonDeserializer(targetClass = BatteryState::class))  <4>
  .map { result ->  <5>
    result.record.value
  }
----
<1> Start the Consume step.
<2> Specify the queue to consume.
<3> Configure the connection to the queue.
<4> Specify the class to use to deserialize the body of the response.
<5> Define how the result of the consume step is sent to the next step in a scenario.

//-
Tip::
The connection can be configured to consume either `queues` (`queueConnection`) or `topics` (`topicConnection`), but not both.

Reference documentation::
Refer to the  https://jakarta.ee/resources/#documentation[Jakarta EE] documentation for further parameter and configuration information.

=== Produce step
The `produce` step within the Jakarta EE plugin produces records in a Jakarta-EE-Messaging-compatible product.

Ancestor::
Step

Functionality::
The `produce` step within the Jakarta EE plugin produces records in a Jakarta-EE-Messaging-compatible product.

Example::
+
[source,kotlin,linenumbers]
----
.jakarta()
.produce { <1>

  connect { <2>
    ActiveMQConnectionFactory(
      "tcp://localhost:61616",
      "qalipsis_user",
      "qalipsis_password"
    ).createQueueConnection()
  }

  session { <3>
    it.createSession(false, Session.AUTO_ACKNOWLEDGE)
  }

  records { _, input -> <4>
    listOf(
      JakartaProducerRecord(
        destination = Queue("battery_state"),
        messageType = JakartaMessageType.BYTES,
        value = objectMapper.writeValueAsBytes(input)
      )
    )
  }
}
----
<1> Start the `produce` step.
<2> Provide the connection for the `JakartaProducerRecord`(s).
<3> Configure the session to attach to the message producer. 
<4> Generate a list of records to send the messaging platform.

//-
Tip::
If you are not sure about the `JakartaMessageType`, use `AUTO` to allow the system to infer the type and display the result. 

Reference documentation::
Refer to the  https://jakarta.ee/resources/#documentation[Jakarta EE] documentation for further parameter and configuration information.


=== JakartaProduceAndConsumeFromQueue scenario
[source,kotlin,linenumbers]
----
scenario { <1>
  minionsCount = 20
  profile {
    immediate()
  }
}
  .start()
  .jackson() <2> 
  .csvToObject(mappingClass = BatteryState::class) { <3>
    classpath(path = "battery-levels.csv")
    header { <4> 
      column(name = "deviceId")
      column(name = "timestamp")
      column(name = "batteryLevel").integer()
    }
    unicast()
  }
    .map { it.value } <5>
    .jakarta()
    .produce {

      connect {
        ActiveMQConnectionFactory(
          "tcp://localhost:61616",
          "qalipsis_user",
          "qalipsis_password"
        ).createQueueConnection()
      }

      session {
        it.createSession(false, Session.AUTO_ACKNOWLEDGE)
      }

      records { _, input ->
        listOf(
          JakartaProducerRecord(
            destination = Queue("battery_state"),
            messageType = JakartaMessageType.BYTES,
            value = objectMapper.writeValueAsBytes(input)
          )
        )
      }
    }
    .map {
      it.input
    }
    .innerJoin()
    .using { correlationRecord ->
      correlationRecord.value.deviceId
    }
    .on {
      it.jakarta().consume {
        queues("battery_state")
        queueConnection {
          ActiveMQConnectionFactory(
          "tcp://localhost:61616",
          "qalipsis_user",
          "qalipsis_password"
          ).createQueueConnection()
        }
      }
        .deserialize(JakartaJsonDeserializer(targetClass = BatteryState::class))
        .map { result ->
          result.record.value
        }
    }
    .having { correlationRecord ->
      correlationRecord.value.deviceId
    }
    .filterNotNull()
    .verify { result ->
      result.asClue {
        assertSoftly {
          it.first.batteryLevel shouldBeExactly it.second.batteryLevel
        }
      }
    }
----
<1> Define the scenario, set the name, number of minions and rampUp
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.

=== JakartaProduceAndConsumeFromTopic scenario
[source,kotlin,linenumbers]
----
scenario { <1> 
  minionsCount = 20
  profile {
    immediate()
  }
}
  .start()
  .jackson() <2> 
  .csvToObject(mappingClass = BatteryState::class) { <3>

    classpath(path = "battery-levels.csv")
    header {  <4>
      column(name = "deviceId")
      column(name = "timestamp")
      column(name = "batteryLevel").integer()
    }
    unicast()
  }
  .map { it.value } <5>
  .jakarta()
  .produce {

    connect {
      ActiveMQConnectionFactory(
        "tcp://localhost:61616",
        "qalipsis_user",
        "qalipsis_password"
        ).createTopicConnection()
    }

    session {
      it.createSession(false, Session.AUTO_ACKNOWLEDGE)
    }

    records { _, input ->
      listOf(
        JakartaProducerRecord(
          destination = Topic(name = "battery_state"),
          messageType = JakartaMessageType.BYTES,
          value = objectMapper.writeValueAsBytes(input)
        )
      )
    }
  }
  .map {
    it.input
  }
  .innerJoin()
  .using { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .on {
    it.jakarta().consume {
      topics("battery_state")
      topicConnection {
        ActiveMQConnectionFactory(
          "tcp://localhost:61616",
          "qalipsis_user",
          "qalipsis_password"
        ).createTopicConnection()
      }
    }
      .deserialize(JakartaJsonDeserializer(targetClass = BatteryState::class))
      .map { result ->
        result.record.value
      }
  }
  .having { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .filterNotNull()
  .verify { result ->
    result.asClue {
      assertSoftly {
        it.first.batteryLevel shouldBeExactly it.second.batteryLevel
      }
    }
  }
----
<1> Define the scenario, set the name, number of minions and rampUp
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.