= JMS plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The JMS plugin connects QALIPSIS to a messaging platform that supports https://www.oracle.com/java/technologies/java-message-service.html[JMS].

Technology addressed::
JMS: https://www.oracle.com/java/technologies/java-message-service.html[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-jms`

Namespace in scenario::
jms()
 
Client library::
JMS API: refer to 
https://docs.oracle.com/javaee/7/api/javax/jms/package-summary.html[Java Interface Summary].

Supported steps::
* <<Consume step,`consume`>>: consumes data from a messaging platform supporting JMS.
* <<Produce step,`produce`>>: pushes data to a messaging platform supporting JMS.

Examples of usage are provided <<Examples of usage,here>>.

== Configuration

=== Sample configuration file
[source,kotlin,linenumbers]
----
campaign:
  name: jms-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false

----
=== Configuration parameters
Available parameters are described in the table below.
[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `connect`  +
a| Specifies the connection type for the `JmsProducerRecord`(s) +
 *Applicable Steps:* Produce +
 *Optional/Required:* Required +
 *Data Type:* Lambda within which connection parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
connect {
    ActiveMQConnectionFactory("tcp://localhost:61616").createConnection()
}
----

| `consume`  +
a| Configures the the https://activemq.apache.org/[ActiveMQ] connection. +
 *Applicable Steps:* Consume +
 *Optional/Required:* Required +
 *Data Type:* Lambda within which connection parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
jms().consume {
    queues("battery_state")
    queueConnection { ActiveMQConnectionFactory("tcp://localhost:61616").createQueueConnection() }
}
----

| `queues`
a| Specifies the queue(s) for the connection. +
*Applicable Steps:* Consume +
 *Optional/Required:* Required +
 *Data Type:* Lambda within which connection parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
queues("battery_state")
----

| `QueueConnection`
a| Provides the java ActiveMQ connection for the specified queues. +
*Applicable Steps:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Lambda within which connection parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
queueConnection {
    ActiveMQConnectionFactory(
      "tcp://localhost:61616",
      "qalipsis_user",
      "qalipsis_password"
    ).createQueueConnection()
  }
----

| `topics`
a| Specifies the topic(s) to consume. +
*Applicable Steps:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* String. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
topics ("battery_state")
----

| `topicConnection`
a| Provides the connection to attach to the topic consumer, which is generally specific to the underlying product. +
*Applicable Steps:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Lambda within which connection parameters are defined. +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
topicConnection {
  ActiveMQConnectionFactory(
    "tcp://localhost:61616",
    "qalipsis_user",
    "qalipsis_password"
  ).createTopicConnection()
}
----

| `records`
a| Generates a list of records to send the messaging platform. +
*Applicable Steps:* Produce +
 *Optional/Required:* Required +
 *Data Type:* Lambda  +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
records { _, input ->
  listOf(
    JMSProducerRecord(
      destination = Topic(name = "battery_state"),
      messageType = JMSMessageType.BYTES,
      value = objectMapper.writeValueAsBytes(input)
    )
  )
}
----
| `destination`
a| Defines the destination for each `JMSProducerRecord` as either queues (`QueueConnection`) or topics (`TopicConnection`). +
*Applicable Steps:* Produce +
 *Optional/Required:* Required +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
destination = Topic(name = "battery_state")
----

| `messageType`
a| Indicates the `JMSMessageType` as: `TEXT`, `AUTO`, `BYTES`, or `OBJECT`. +
*Applicable Steps:* Produce +
 *Optional/Required:* Required +
 *Data Type:* ENUM +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
messageType = JMSMessageType.BYTES
----

|`value`
a| Defines the message to be displayed at the `destination`. +
*Applicable Steps:* Produce +
 *Optional/Required:* Required +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
value = objectMapper.writeValueAsBytes(input)
----


| `deserialize`
a| Specifies the class to use to deserialize the body of the response. +
*Applicable Steps:* Consume +
 *Optional/Required:* Required +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin]
----
 .deserialize(JakartaJsonDeserializer(targetClass = BatteryState::class))
----

| `singletonConfiguration`
a| Configures how consumed results are delivered to scenario minions. +
  Specify one of the strategies directly (not wrapped in a lambda). +
  Available strategies: `sequential`, `broadcast`, `unicast`, `loop`. +

 * `broadcast`: sends every consumed record to all minions. Records are delivered in order, with the oldest buffered record sent first. In this mode, the singleton behaves like a Pub/Sub broadcaster. 

 * `unicast`: sends each consumed record to exactly one minion. The singleton acts as a FIFO distributor: Records are stored in a buffer until a minion consumes them. The buffer has a fixed size; when it becomes full, the oldest records are dropped to make space for new ones. 

 * `loop`: sends each consumed record to all minions, but once the end of the buffer is reached, it loops back to the beginning. This creates a continuous cyclic stream of the buffered records. 

 * `sequential`: disables singleton execution and runs this step within the parent’s workflow. Data distribution is controlled entirely by the parent step. This mode is typically used when you want to process each record from a source from start to finish once, and then stop publishing until new data is available.
   
 Note::
 Each strategy EXCEPT `sequential` requires `bufferSize` (Int) and `idleTimeout` (Duration); see `singletonConfiguration.bufferSize` and `singletonConfiguration.idleTimeout` definitions below. +

*Applicable Step:* Consume +
*Optional/Required:* Optional +
*Data Type:* Function +
*Default Value:* N/A

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.bufferSize`
a| Size of the buffer used to store consumed records before delivery to minions.+ +
 *Applicable Step:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Integer +
 *Default Value:* -1 +

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.idleTimeout`
a| Maximum time to wait before delivering consumed records to minions, even if the buffer is not full. +
 *Applicable Step:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration +
 *Default Value:* Duration.ZERO +

.Example
[source,kotlin] 
---- 
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `broadcast`
a| Specifies the broadcast parameters for a step. +
 *Applicable Step:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
broadcast(3, Duration.ofMinutes(1))
----

| `unicast`
a| Specifies the unicast parameters for a step. +
 *Applicable Step:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
unicast(1, Duration.ofMinutes(3))
----

| `loop`
a| Specifies the loop parameters for a step. +
 *Applicable Step:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
loop(5, Duration.ofMinutes(2))
----

| `sequential`
a| Specifies the sequential parameters for a step. +
 *Applicable Step:* Consume +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
sequential()
----

|===


== Examples of Uage

=== Consume step 
The `consume` step within the JMS plugin consumes records from https://activemq.apache.org/[ActiveMQ].
 
Ancestor::
Scenario
 
Functionality::
The `consume` step polls data from the designated https://activemq.apache.org/[ActiveMQ] connection, step context, and the data deserializer.

Example::
+
[source,kotlin,linenumbers]
----
jms().consume { <1>
    queues("battery_state") <2>
    queueConnection { ActiveMQConnectionFactory("tcp://localhost:61616").createQueueConnection() } <3>
}
    .deserialize(JmsJsonDeserializer(targetClass = BatteryState::class)) <4>
    .map { result -> <5>
        result.record.value
    }
----
<1> Start the Consume step.
<2> Specify the queue to consume.
<3> Configure the connection to the queue.
<4> Specify the class to use to deserialize the body of the response.
<5> Define how the result of the consume step is sent to the next step in a scenario.

Tip::
The https://activemq.apache.org/[ActiveMQ] connection can be configured for either `queues` (`QeueConnection`) or `topics` (`TopicConnection`), but not both.

Reference documentation::
Refer to the  https://www.oracle.com/java/technologies/java-message-service.html[JMS] documentation for further parameter and configuration information.
 
=== Produce step
The `produce` step within the JMS plugin produces records in https://activemq.apache.org/[ActiveMQ] using https://www.oracle.com/java/technologies/java-message-service.html[JMS].
 
Ancestor::
Step
 
Functionality::
The `produce` step produces a batch of records into one or more https://www.oracle.com/java/technologies/java-message-service.html[JMS] `destinations`. The record values may be provided by previous steps.

Example::
+
[source,kotlin,linenumbers]
----
.jms()
.produce { <1>
    connect { <2>
        ActiveMQConnectionFactory("tcp://localhost:61616").createConnection()
    }
    records { _, input -> <3>
        listOf(
            JmsProducerRecord(
                destination = ActiveMQQueue().createDestination("battery_state"),
                messageType = JmsMessageType.BYTES,
                value = objectMapper.writeValueAsBytes(input)
            )
        )
    }
}
----
<1> Start the `produce` step.
<2> Provide the connection for the `JakartaProducerRecord`(s).
<3> Generate a list of records to send the messaging platform.

Tip::
If you are not sure about the `JmsMessageType`, use `AUTO` to allow the system to infer the type and display the result. 

Reference documentation::
Refer to the  https://www.oracle.com/java/technologies/java-message-service.html[JMS] documentation for further parameter and configuration information.

=== JmsProduceAndConsume scenario
[source,kotlin,linenumbers]
----
scenario {  <1>
    minionsCount = 20
    profile {
        immediate()
    }
}
    .start()
    .jackson() <2> 
    .csvToObject(mappingClass = BatteryState::class) { <3>

        classpath(path = "battery-levels.csv")
        header { <4>
            column(name = "deviceId")
            column(name = "timestamp")
            column(name = "batteryLevel").integer()
        }
        unicast()
    }
    .map { it.value } <5>
    .jms()
    .produce {
        connect {
            ActiveMQConnectionFactory("tcp://localhost:61616").createConnection()
        }

        records { _, input ->
            listOf(
                JmsProducerRecord(
                    destination = ActiveMQQueue().createDestination("battery_state"),
                    messageType = JmsMessageType.BYTES,
                    value = objectMapper.writeValueAsBytes(input)
                )
            )
        }
    }
    .map {
        it.input
    }
    .innerJoin()
    .using { correlationRecord ->
        correlationRecord.value.deviceId
    }
    .on {
        it.jms().consume {
            queues("battery_state")
            queueConnection { ActiveMQConnectionFactory("tcp://localhost:61616").createQueueConnection() }
        }
            .deserialize(JmsJsonDeserializer(targetClass = BatteryState::class))
            .map { result ->
                result.record.value
            }

    }
    .having { correlationRecord ->
        correlationRecord.value.deviceId
    }
    .filterNotNull()
    .verify { result ->
        result.asClue {
            assertSoftly {
                it.first.batteryLevel shouldBeExactly it.second.batteryLevel
            }
        }
    }
----
<1> Define the scenario, set the name, number of minions and rampUp
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.