= Apache Kafka plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The Apache Kafka plugin connects QALIPSIS to an https://kafka.apache.org/[Apache Kafka] cluster.
 
Technology addressed::
Kafka: https://kafka.apache.org/[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-kafka`

Namespace in scenario::
`kafka()`

Client library::
Kafka: refer to https://kafka.apache.org/[Apache Kafka]

Supported steps::
* <<Consume step,`consume`>>: consumes data from topics of an Apache Kafka cluster.
* <<Produce step,`produce`>>: pushes data to topics of the Apache Kafka cluster.

Examples of usage are provided later in this <<Examples of usage,section>>.

== Configuration

=== Example configuration file

Configuration settings are configured in a .yaml file. 

[source,kotlin,linenumbers]
----
campaign:
  name: kafka-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters
Available parameters are described in the table below.
[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `bootstrap`  
a| Configures the bootstrap hosts of the `Kafka` cluster. +
*Applicable Steps:* Consume, Produce +
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* ("localhost:9092") +

.Example
[source,kotlin]
----
 bootstrap("localhost:9092")
----

| `groupId`  
a| Defines the consumer group. +
*Applicable Steps:* Consume +
*Optional/Required:* Required +
*Data Type:*  +
*Default Value:* +

.Example
[source,kotlin]
----
groupId("kafka-example")
----

| `offsetReset`  
a| Defines the strategy to apply when the consumer starts consuming messages from the queue. +
  Valid `offsetReset` strategies are: +
  * `OffsetResetStrategy.EARLIEST`: starts consuming messages from the beginning of the queue. +
  * `OffsetResetStrategy.LATEST`: starts consuming messages when the  consumer starts, ignoring all previous messages in the queue. +
*Applicable Steps:* Consume +
*Optional/Required:* Required +
*Data Type:*  ENUM +
*Default Value:* OffsetResetStrategy.LATEST` +

.Example
[source,kotlin]
----
 offsetReset(OffsetResetStrategy.EARLIEST)
----

| `pollTimeout`  
a|Defines the consumer poll timeout to wait for records. +
*Applicable Steps:* Consume +
*Optional/Required:* Required +
*Data Type:*  Duration +
*Default Value:* 1s +

.Example
[source,kotlin]
----
pollTimeout(Duration.ofSeconds(1))
----

| `maxPollRecords`  
a| Defines the maximum number of records returned in a unique poll batch. +
*Applicable Steps:* Consume +
*Optional/Required:* Optional +
*Data Type:* Integer +
*Default Value:* 500 +

.Example
[source,kotlin]
----
 maxPollRecords = 500  
----

| `singletonConfiguration`
a| Configures how consumed results are delivered to scenario minions. +
Refer to xref:plugins/plugins.adoc#singletonconfiguration-parameters[SingletonConfiguration parameters] for details on strategies and examples of usage.

| `keySerializer`  
a| Describes how to serialize the record keys to send  to `kafka`. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:*  UTF-8 String +
*Default Value:* N/A  +

.Example
[source,kotlin]
----
keySerializer = Serdes.String().serializer(),
----

| `valueSerializer`  
a| Describes how to serialize the record values to send to `kafka`. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:*  UTF-8 String +
*Default Value:*  N/A +

.Example
[source,kotlin]
----
valueSerializer = Serdes.String().serializer()
----

| `clientName`  
a| Defines the name of the `kafka` client. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:*  String +
*Default Value:* N/A +

.Example
[source,kotlin]
----
clientName("producer")
----

| `records`  
a|Generates and configures a list of produced records. +
*Applicable Steps:* Produce +
*Optional/Required:* Required +
*Data Type:*  Lambda function +
*Default Value:* N/A +

.Example
[source,kotlin]
----
records { _, input ->
  listOf(
    KafkaProducerRecord(
      "battery_state",
      value = objectMapper.writeValueAsString(input),
      key = input.deviceId
    )
  )
}
----
|===

== Examples of usage

=== Consume step
The `consume` step within the Apache Kafka plugin polls data from topics of an Apache Kafka cluster and forwards the data to the next step, either in batches or individually. 

The `consume` step:

* is generally used in conjunction with a left join to assert data or inject data into a workflow.
* supports multithreading (concurrent consumers) using the `concurrency` property.

Ancestor::
Scenario
 
Functionality::
The `consume` step starts a polling loop for the designated `client`, using the provided subscription `topics` name, or `topicsPattern` and `groupId`. When new records appear, `consume` polls them and sends them to the next step(s). 

Example::
+
[source,kotlin,linenumbers]
----
kafka().consume {  
  bootstrap("localhost:9092")
  topics("battery_state")  
  groupId("kafka-example")
  offsetReset(OffsetResetStrategy.EARLIEST) 
  pollTimeout(Duration.ofSeconds(1))
}
----

Tip::
* Use the `consume` step with a left join to assert data or inject data into a workflow.

Reference documentation::
Refer to the https://kafka.apache.org/[Apache KAFKA] documentation for further parameter and configuration information. 
 
== Produce step
The `produce` step within the Apache Kafka plugin pushes data onto topics of the Kafka broker and forwards the data as input to the next step.

Ancestor::
Scenario
 
Functionality::
The `produce` step's input and step context are used to generate values to complete the step. The batch of results, or a single result, is then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
.kafka()
.produce(
  keySerializer = Serdes.String().serializer(),
  valueSerializer = Serdes.String().serializer()
) {
  bootstrap("localhost:9092")
  clientName("producer")
  records { StepContext, input ->
    listOf(
      KafkaProducerRecord(
        topic = "battery_state",
        value = objectMapper.writeValueAsString(input),
        key = input.deviceId
      )
    )
  }
  }
----

Reference documentation::
Refer to the https://kafka.apache.org/documentation/[Apache KAFKA] documentation for further parameter and configuration information. 

=== KafkaProduceAndConsume scenario
[source,kotlin,linenumbers]
----
scenario { <1>
  minionsCount = 20
  profile {
    immediate()
  }
}
  .start()
  .jackson() <2> 
  .csvToObject(mappingClass = BatteryState::class) { <3>

    classpath(path = "battery-levels.csv")
    header { <4>
      column(name = "deviceId")
      column(name = "timestamp")
      column(name = "batteryLevel").integer()
    }
    unicast()
  }
  .map { it.value }   
  .kafka()
  .produce( 
    keySerializer = Serdes.String().serializer(),
    valueSerializer = Serdes.String().serializer()
  ) {
    bootstrap("localhost:19092")
    clientName("producer")
    records { _, input ->
      listOf(
        KafkaProducerRecord(
          "battery_state",
          value = objectMapper.writeValueAsString(input),
          key = input.deviceId
        )
      )
    }
  }
  .map { it.input }
  .innerJoin()
  .using { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .on {
    it.kafka().consume {
      bootstrap("localhost:19092")
      topics("battery_state") <5>
      groupId("kafka-example")
      offsetReset(OffsetResetStrategy.EARLIEST) <6>
      pollTimeout(Duration.ofSeconds(1))
    }
      .flatten(Serdes.String().deserializer(), jsonSerde<BatteryState>().deserializer())
      .map { result ->
        result.record.value
      }
      .filterNotNull()
  }
  .having { correlationRecord ->
    correlationRecord.value.deviceId
  }
  
----
<1> Define the scenario, set the name, number of minions and rampUp
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Specify "battery_state" as the topic to consume.  
<6> Start consuming messages from the beginning of the queue.

== Configuration of publication of events and meters to Apache Kafka

NOTE::
Configure `event` and `meter` publication settings in the factory configuration, separate from the scenario DSL.

Refer to xref:up-and-running/configuration/provide-configuration.adoc[Provide the configuration to QALIPSIS] for information about specifying the configuration to QALIPSIS.

Events:: 
`events.export.kafka`

Meters::
`meters.export.kafka`

=== Event and meter parameters
[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

|`enabled`
a|Boolean flag to activate/deactivate event/meter publishing to Apache Kafka; *must* be set to `true`to enable publishing.
*Applicable Steps:* Events, Meters +
*Optional/Required:* Required +
*Data Type:* Boolean  + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
enabled: true
----

|`min-level`
a|Minimal accepted level of events to publish; allowable values are `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`. +
* `TRACE` = most verbose, shows internal and fine‑grained details for deep troubleshooting. +
* `DEBUG` = diagnostic information useful to investigate issues. +
* `INFO` = routine operational messages and high‑level progress. +
* `WARN` = indications of potential problems that do not stop processing. +
* `ERROR` = confirmed problems that need attention. +
* `OFF` = disable event publishing.+
+
*Applicable Steps* Events +
*Optional/Required:* Required +
*Data Type:* enum + 
*Default Value:* `INFO` + 

.Example
[source,kotlin] 
----
min-level: INFO
----

| `bootstrap` 
a| Host and port pair of the Kafka broker  +
*Applicable Steps* Events +
*Optional/Required:* Required +
*Data Type:* String + 
*Default Value:* localhost:9092 + 

.Example
[source,kotlin] 
----
  bootstrap: localhost:9092 
----

| `bootstrap.servers` 
a| Host and port pair of the Kafka broker +
*Applicable Steps* Meters +
*Optional/Required:* Required +
*Data Type:* String + 
*Default Value:* localhost:9092 + 

.Example
[source,kotlin] 
----
bootstrap.servers: localhost:9092
----

| `step`
a| The step size (reporting frequency) to use for monitoring meters. +
*Applicable Step* Meters +
*Optional/Required:* Required +
*Data Type:*  Duration +
*Default Value:* PT10S + 

.Example
[source,kotlin] 
----
step: PT10S
----

| `topic`
a| Name of the topic to write the meters and events to. +
*Applicable Step* Meters, Events +
*Optional/Required:* Required +
*Data Type:*  String +
*Default Value:*  +
* Events: qalipsis-events + 
* Meters: qalipsis-meters +

.Example (Events)
[source,kotlin] 
----
topic: qalipsis-events
----

.Example (Meters)
[source,kotlin] 
----
topic: qalipsis-meters
----

|`duration-as-nano` 
a| Activates/deactivates converting the duration to nanoseconds (`true`); `false` converts to milliseconds. +
*Applicable Step:* Events +
*Optional/Required:* Required +
*Data Type:* Boolean flag +
*Default Value:*  false

.Example
[source,kotlin] 
----
duration-as-nano: true
----

| `linger-period` 
a| Maximum time to buffer events before forcing a flush, even if the batch size is not reached. +
*Applicable Step:* Events +
*Optional/Required:* Required +
*Data Type:* Positive duration string +
*Default Value:* 10s +

.Example
[source,kotlin] 
----
linger-period: 10s
----

| `linger.ms` 
a| Maximum maximum period between two batches of events to Kafka. +
*Applicable Step:* Events +
*Optional/Required:* Required +
*Data Type:* Positive duration +
*Default Value:* 5000 +

.Example
[source,kotlin] 
----
linger.ms: 5000
----

| `batch-size`
a|Maximum number of events buffered between two publications of meters or events to Kafka +
*Applicable Step:* Events, Meters+ 
*Optional/Required:* Required +
*Data Type:* Positive integer +
*Default Value:* 2

.Example
[source,kotlin] 
----
batch-size: 2
----

|`format` 
a|Format of the exported data. +
*Applicable Steps*:* Events, Meters +  
*Optional/Required:* Optional +
*Data Type:* string +
*Default Value:* JSON 

.Example
[source,kotlin] 
----
format: JSON 
----

|`configuration` 
a|Key, value configuration parameters of type Properties, for the Kafka producer. +
*Applicable Steps*:* Events, Meters +  
*Optional/Required:* Optional +
*Data Type:* key,value string pair +
*Default Value:* N/A 

.Example
[source,kotlin] 
----
configuration:
  delivery.timeout.ms: 10000 
----
|===

=== Example configuration file
[source,kotlin,linenumbers]
----
events: <1>
  export:
    kafka: <2>
      enabled: true
      bootstrap`: localhost:9092
      topic: qalipsis-events
      duration-as-nano: false
      linger-period: 10s
      batch-size: 2
      configuration:
        delivery.timeout.ms: 10000

meters: <3>
  export:
    kafka: <4>
      enabled: true
      step: PT10S
      bootstrap.servers: localhost:9092
      topic: qalipsis-meters
      linger.ms: 5000
      batch-size: 800000 # In bytes.
      configuration:
        delivery.timeout.ms: 10000
----  

<1> Start event configuration.
<2> Configure event publishing to Kafka.
<3> Start meter configuration.
<4> Configure meter publishing to Kafka.

Reference Documentation::
Refer to xref:up-and-running/configuration/monitoring-test-campaigns.adoc[Monitoring test campaigns] for a further explanation of the event and meter parameter values.
