= Mail plugin [.badge.oss]## ##[.badge.commercial]## ##

== Overview
QALIPSIS supports email messaging, to notify users of the status of their campaigns after it runs. This is achieved by configuring and enabling the QALIPSIS publisher for mail.

Configuration namespace:: 
`report.export.mail`

== Congifuration parameters
[cols="1,4" options="header"]
|===
|*Parameter* 
|*Description*

|`enabled`
a|Activates/deactivates campaign report publishing to mail; must be set to true to enable notifications. +
*Optional/Required:* Required +
*Data Type:* Boolean flag + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
enabled: `true`
----

|`username`
a|Username to be used in authenticating network connection requests when password authentication is required (i,e, when the AuthenticationMode is set to USERNAME_PASSWORD). +
*Optional/Required:* Required +
*Data Type:* String + 
*Default Value:* N/A + 

.Example
[source,kotlin] 
----
username: qalipsis-user
----

|`password`
a|Password to be used in authenticating network connection requests when password authentication is required (i. e., when the AuthenticationMode is set to USERNAME_PASSWORD). +
*Optional/Required:* Required +
*Data Type:* Boolean + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
password: passpass
----

|`status`
a|Specifies which campaign report status(es) should trigger a notification. +
Allowed values are any set of `ReportExecutionStatus` values: `ALL`, `FAILED`, `SUCCESSFUL`, `WARNING`, `ABORTED`. +
* Specifying `ALL` triggers a notification for any campaign report status. +
* Specifying two or more status values triggers a notification when the campaign report status is the same as any of the selected status values. +
* Specifying just one status value triggers a notification only when the campaign report status is the same as the selected status value. +

*Optional/Required:* Required +
*Data Type:* ENUM + 
*Default Value:* ALL + 

.Example
[source,kotlin] 
----
status: 
  - SUCCESSFUL
  - FAILED
  - WARNING
----

|`authenticationMode`
a|Sets authentication options for SMTP server; allowed values: `USERNAME_PASSWORD`, `PLAIN`. + 
*Optional/Required:* Required +
*Data Type:* ENUM + 
*Default Value:* PlAIN + 

.Example
[source,kotlin] 
----
authenticationMode: USERNAME_PASSWORD `
----

|`from`
a|Email to indicate sender address. + 
*Optional/Required:* Required +
*Data Type:* email + 
*Default Value:* no-reply@@qalipsis.io + 

.Example
[source,kotlin] 
----
from: foo@bar.com
----

|`to`
a|List of valid email addresses that are recipients of the email. + 
*Optional/Required:* Required +
*Data Type:* email + 
*Default Value:* N/A + 

.Example
[source,kotlin] 
----
to: 
  - fooadmin1@bar.com
  - fooadmin2@bar.com
----

|`cc`
a|List of valid email addresses to be copied in the email. + 
*Optional/Required:* Optional +
*Data Type:* email + 
*Default Value:* empty list + 

.Example
[source,kotlin] 
----
cc: 
  - foosupport@bar.com
----

|`junit`
a|Activates/deactivates inclusion of a Junit report as a zipped attachment, if a report exists. +
*Optional/Required:* Required +
*Data Type:* boolean flag + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
junit: false
----

|`ssl`
a|Enables/disables the use of SSL to connect. +
*Optional/Required:* Required +
*Data Type:* boolean flag + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
ssl: true
----

|`starttls`
a|Enables/disables the use of the STARTTLS command (if supported by the server). +
*Optional/Required:* Required +
*Data Type:* boolean flag + 
*Default Value:* false + 

.Example
[source,kotlin] 
----
 starttls: true
----

|`host`
a|The host name of the mail server to connect to. +
 *Optional/Required:* Required +
 *Data Type:* String + 
 *Default Value:* localhost + 

.Example
[source,kotlin] 
----
 host: smtp.gmail.com
----

|`port`
a|The ho port number of the mail server to connect to. +
*Optional/Required:* Required +
*Data Type:* Integer + 
*Default Value:* 25 + 

.Example
[source,kotlin] 
----
 port: 587
----

|===

== Example configuration file

[source,kotlin,linenumbers]
----
report:
  export:
    mail:
      enabled: true
      username: qalipsis-user
      password: passpass
      status: <1>
        - SUCCESSFUL
        - FAILED
        - WARNING
      authenticationMode: USERNAME_PASSWORD <2> 
      from: foo@bar.com
      to: 
        - fooadmin1@bar.com
        - fooadmin2@bar.com
      junit: false  <3> 
      ssl: true
      starttls: true
      host: smtp.gmail.com
      port: 587
----
<1> Mail notifications are triggered only when the status of a campaign report is `FAILED`, `SUCCESSFUL`, or `WARNING`. All other campaign statuses are ignored.
<2> Allows authentication requests for a network connection.
<3> Junit report attachments would not be included in the email.