= MongoDB plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The MongoDB plugin connects QALIPSIS to https://mongodb.com/[MongoDb].

Technology addressed::
MongoDB: https://mongodb.com/[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-mongodb`

Namespace in scenario::
`mongodb()`

Client library::
MongoDB Reactive Streams Driver: refer to https://www.mongodb.com/docs/drivers/reactive-streams/[MongoDB Java Reactive Streams].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of documents generated from the input and step context.
* <<Search step,`search`>>: searches documents and builds a query from the input and step context.

Example scenarios are provided later in this <<Examples of Usage,section>>.  

== Configuration

=== Sample configuration file

MongoDB configuration settings are configured in a mongodb.yaml file. 
[source,kotlin,linenumbers]
----
campaign:
  name: mongodb-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters
Available parameters are described in the table below.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*


| `connect`
a| Configures the connection to https://mongodb.com/[MongoDb]. +
 *Applicable Steps:* Poll, Save, Search + 
 *Optional/Required:* Required +
 *Data Type:*  Lambda +
 *Default Value:*   +

.Example 
[source,kotlin]
----
connect {
    MongoClients.create("mongodb://James23:SantaFe1987@localhost:27017")
}
----

| `query`
a| Specifies a document respecting the requirements of the target database.  +
 *Applicable Steps:* Poll, Save + 
 *Optional/Required:* Required +
 *Data Type:*  Lambda +
 *Default Value:*   N/A +

.Example 
[source,kotlin]
----
query {
    database { _, _ ->
        "iot"
    }
    collection { _, _ ->
        "batteryState"
    }
    documents { _, input ->
        listOf(Document.parse(objectMapper.writeValueAsString(input)))
    }
}
----

| `search`
a| Defines the search parameters including,`database`, `collection` `query` and `sort`.  +
 *Applicable Steps:* Search, Poll + 
 *Optional/Required:* Required +
 *Data Type:*  Lambda +
 *Default Value:*   N/A +

.Example (Poll)
[source,kotlin]
----
search {
    database = "iot"
    collection = "batteryState"
    query = Document()
    sort = linkedMapOf("deviceId" to Sorting.ASC)
    tieBreaker = "deviceId"
}
----
.Example (Search)
[source,kotlin]
----
search {
    database { _, _ -> "iot" }
    collection { _, _ -> "batteryState" }
    query { _, input ->
        Document(
            mapOf(
                "deviceId" to input.deviceId,
                "timestamp" to input.timestamp.epochSecond
            )
        )
    }
}
----

| `tieBreaker`
a| Configures the tiebreaker column used to track the "last seen" value for polling. +
 *Applicable Steps:* Poll, Search + 
 *Optional/Required:* Optional +
 *Data Type:* Lambda within which tiebreaker parameters are defined. +
 *Default Value:*  N/A +

.Example 
[source,kotlin]
----
tieBreaker {         
    name = "timestamp"
    type = GenericType.INSTANT
}
----

| `tieBreaker.type`
a|Data type to help the datastax driver interpret a value. +
 *Applicable Step:* Poll +
 *Optional/Required:* Required +
 *Data Type:* GenericType (enum) +
 *Default Value:* null +

.Example
[source,kotlin] 
----
tieBreaker {
    type = GenericType.INSTANT
}
----


| `tieBreaker.name`
a|Name of the column used as a tiebreaker. +
 *Applicable Step:* Poll +
 *Optional/Required:* Required +
 *Data Type:* String  +
 *Default Value:* "" +

.Example
[source,kotlin] 
----
tieBreaker {
    name = "timestamp"
}
----
| `parameters`
a| Poll: Binds values to the clauses of the prepared query. +
 Search: Computes the list of values bound to the prepared query using the step context and input. +
 *Applicable Steps:* Poll, Search + 
 *Optional/Required:* Optional +
 *Data Type:* +
    Poll: `List<Any>` / `vararg Any` +
    Search: Lambda that takes step context and input and returns `List<Any>`. +
 *Default Value:* `emptyList()` +
    
.Example (Poll)
[source,kotlin] 
----
parameters(listOf(1, "abc")) or parameters(1, "abc") 
----
.Example (Search)
[source,kotlin] 
----
parameters { 
    stepContext, input -> listOf("ACME Inc.") 
} 
----

| `pollDelay`
a| Delay between two polling executions. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration 
 *Default Value:* Duration.ofSeconds(10) 

.Example
[source,kotlin] 
----
 pollDelay(Duration.ofSeconds(1)) 
----


| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
  Specify one of the strategies directly (not wrapped in a lambda). +
  Available strategies: `sequential`, `broadcast`, `unicast`, `loop`. +

`broadcast(bufferSize, idleTimeout)`:
 sends every polled record to all minions. Records are delivered in order, with the oldest buffered record sent first. In this mode, the singleton behaves like a Pub/Sub broadcaster. 

 `unicast(bufferSize, idleTimeout)`: 
  sends each polled record to exactly one minion. The singleton acts as a FIFO distributor: Records are stored in a buffer until a minion consumes them. The buffer has a fixed size; when it becomes full, the oldest records are dropped to make space for new ones. 

 `loop(bufferSize, idleTimeout)`:
  sends each polled record to all minions, but once the end of the buffer is reached, it loops back to the beginning. This creates a continuous cyclic stream of the buffered records. 

 `sequential()`: 
  disables singleton execution and runs this step within the parent’s workflow. Data distribution is controlled entirely by the parent step. This mode is typically used when you want to process each record from a source from start to finish once, and then stop publishing until new data is available.
   
 Each strategy EXCEPT `sequential` requires `bufferSize` (Int) and `idleTimeout` (Duration); see `singletonConfiguration.bufferSize` and `singletonConfiguration.idleTimeout` definitions below. +

 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* unicast(bufferSize, idleTimeout)

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.bufferSize`
a| Size of the buffer used to store polled records before delivery to minions.+ +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Integer +
 *Default Value:* -1 +

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.idleTimeout`
a| Maximum time to wait before delivering polled records to minions, even if the buffer is not full. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration +
 *Default Value:* Duration.ZERO +

.Example
[source,kotlin] 
---- 
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `broadcast`
a| Specifies the broadcast parameters for a step. +
 *Applicable Step:* Poll
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
broadcast(3, Duration.ofMinutes(1))
----

| `unicast`
a| Specifies the unicast parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
unicast(1, Duration.ofMinutes(3))
----

| `loop`
a| Specifies the loop parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
loop(5, Duration.ofMinutes(2))
----

| `sequential`
a| Specifies the sequential parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
sequential()
----
|===

== Examples of Usage

=== Poll step
The `poll` step within the MongoDB plugin polls the newest records from a database table, with a delay between each execution.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario;  it is then used throughout the scenario as called. The `poll` step within the MongoDB plugin uses a strategy of “delivered at least once”. 

Example::
+
[source,kotlin,linenumbers]
----
mongodb().poll {
    name = "poll"
    connect { <1>
        MongoClients.create("mongodb://James23:SantaFe1987@localhost:27017")
    }
    search { <2>
        database = "iot"
        collection = "batteryState"
        query = Document()
        sort = linkedMapOf("deviceId" to Sorting.ASC)
        tieBreaker = "deviceId"
    }
    pollDelay(Duration.ofSeconds(1)) <3>
}
----
 <1> Configure the connection to https://mongodb.com/[MongoDb].
 <2> Define the search parameters.
 <3> Specify the delay between search executions.

Tips::
* Use the `poll` step with a join operator if you need to verify the values saved by your tested system in the database.
* The `search` parameter requires at least one sorting field (`tiebreaker` in the example) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for `tiebreaker` is used to filter out the values already received from the database.

Reference Documentation::
Refer to the https://www.mongodb.com/docs/[Mongodb] documentation for further parameter and configuration information.

=== Save step
The `save` step within the MongoDB plugin persists a batch of documents into MongoDB.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate the table, the list of columns and their values, which are then combined and forwarded to the database.
Example::
+
[source,kotlin,linenumbers]
----
.mongodb()
.save {
    name = "save"
    connect { <1>
        MongoClients.create("mongodb://James23:SantaFe1987@localhost:27017")
    }
    query { <2>
        database { _, _ ->
            "iot"
        }
        collection { _, _ ->
            "batteryState"
        }
        documents { _, input ->
            listOf(Document.parse(objectMapper.writeValueAsString(input)))
        }
    }
}
----
<1> Configure the connection to https://mongodb.com/[MongoDb].
<2> Specifies query parameters respecting the requirements of the target database.


Tips::
* Use the `save` step after a `collect` step in order to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.
* The `save` step is extremely flexible; database, collection and documents may depend on the context and input value received from the previous step.

Reference Documentation::
Refer to the  https://www.mongodb.com/docs/[Mongodb] documentation for further parameter and configuration information.

=== Search step 
The `search` step within the MongoDB plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The `search` step’s input and step context are used to generate a document and the values to complete it; the batch of results is then forwarded to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
.search {
    name = "search"
    connect { <1>
        MongoClients.create("mongodb://James23:SantaFe1987@localhost:27017")
    }
    search { <2>
        database { _, _ -> "iot" }
        collection { _, _ -> "batteryState" }
        query { _, input ->
            Document(
                mapOf(
                    "deviceId" to input.deviceId,
                    "timestamp" to input.timestamp.epochSecond
                )
            )
        }
    }
}
----
<1> Configures the connection to https://mongodb.com/[MongoDb].
<2> Define the search parameters including `database`, `collection` and `query`. 

Tip::
Use the `search` step after a `collect()` step in order to reduce the number of queries executed onto the database and to reduce the load the scenario generates on the test system.

Reference Documentation::
Refer to the  https://www.mongodb.com/docs/[Mongodb] documentation for further parameter and configuration information.

=== MongoDbSaveAndSearch scenario 
[source,kotlin,linenumbers]
----
scenario { <1>
    minionsCount = 20
    profile {
        immediate()
    }
}
    .start()
    .jackson() <2> 
    .csvToObject(mappingClass = BatteryState::class) { <3>

        classpath(path = "battery-levels.csv") 
        header { <4>
            column(name = "deviceId")
            column(name = "timestamp")
            column(name = "batteryLevel").integer()
        }
        unicast()
    }
    .map { it.value } <5> // we transform the output of the CSV reader entries to utils.BatteryState
    .mongodb() <6> // we start the mongodb step to save data in mongodb database
    .save {

        connect { <7> setup connection of the database
            MongoClients.create("mongodb://admin:password@localhost:27017")
        }

        query {
            database { _, _ ->
                "iot"
            }

            collection { _, _ ->
                "batteryState"
            }

            documents { _, input ->
                listOf(Document.parse(objectMapper.writeValueAsString(input)))
            }
        }
    }
    .map { it.input }
    .mongodb()
    .search {
        name = "search"

        connect {
            MongoClients.create("mongodb://admin:password@localhost:27017")
        }

        search {
            database { _, _ -> "iot" }
            collection { _, _ -> "batteryState" }
            query { _, input ->
                Document(
                    mapOf(
                        "deviceId" to input.deviceId,
                        "timestamp" to input.timestamp.epochSecond
                    )
                )
            }
        }
    }
    .map {
        it.input to it.documents.first().let { document ->
            BatteryState(
                deviceId = document.getValue("deviceId") as String,
                batteryLevel = document.getValue("batteryLevel") as Int,
                timestamp = Instant.ofEpochSecond((document.getValue("timestamp") as Double).toLong())
            )
        }
    }
    .verify { result ->
        result.asClue {
            assertSoftly {
                it.first.batteryLevel shouldBeExactly it.second.batteryLevel
            }
        }
    }
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.

=== MongoDbSaveAndPoll scenario
[source,kotlin,linenumbers]
----
scenario { <1>
    minionsCount = 20
    profile {
        immediate()
    }
}.start()
    .jackson() 
    .csvToObject(mappingClass = BatteryState::class) { <3>
        name = "csv to json"

        classpath(path = "battery-levels.csv")
            header { <4>
                column(name = "deviceId")
                column(name = "timestamp")
                column(name = "batteryLevel").integer()
            }
            unicast()
    }.map { it.value } <5> 
    .mongodb() <6> 
    .save {
        name = "save"    
        connect { <7>
            MongoClients.create("mongodb://admin:password@localhost:27017")
        }

        query {
            database { _, _ ->
                "iot"
            }
            collection { _, _ ->
                "batteryState"
            }

            documents { _, input ->
                listOf(Document.parse(objectMapper.writeValueAsString(input)))
            }
        }
    }
    .map { it.input }
    .innerJoin()
    .using { correlationRecord -> correlationRecord.value.deviceId }
    .on {
        it.mongodb().poll {
            name = "poll"

            connect {
                MongoClients.create("mongodb://admin:password@localhost:27017")
            }

            search {
                database = "iot"
                collection = "batteryState"
                query = Document()
                sort = linkedMapOf("deviceId" to Sorting.ASC)
                tieBreaker = "deviceId"
            }

            pollDelay(Duration.ofSeconds(1)) <8> 

        }.flatten().map { record ->
            val batteryState = record.value
            BatteryState(
                deviceId = batteryState.getValue("deviceId") as String,
                batteryLevel = batteryState.getValue("batteryLevel") as Int,
                timestamp = Instant.ofEpochSecond((batteryState.getValue("timestamp") as Double).toLong())
            )
        }
    }
    .having { correlationRecord ->
        correlationRecord.value.deviceId
    }
    .filterNotNull()
    .verify { result ->
        result.asClue {
            assertSoftly {
                it.first.batteryLevel shouldBeExactly it.second.batteryLevel
            }
        }
    }
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.
<6> Start the mongodb step to save data in mongodb database.
<7> Setup the connection of the database.
<8> Poll the database after every on second.