= Netty plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview

The https://netty.io/[Netty] plugin supports https://datatracker.ietf.org/doc/html/rfc793[TCP], https://datatracker.ietf.org/doc/html/rfc768[UDP], https://httpwg.org/[HTTP] and https://mqtt.org/[MQTT] clients.

Technologies addressed::
* HTTP/1.1: https://httpwg.org/[]
* HTTP/2: https://httpwg.org/[]
* MQTT: https://mqtt.org/[]
* TCP (Transmission Control Protocol): https://datatracker.ietf.org/doc/html/rfc793[]
* UDP (User Datagram Protocol): https://datatracker.ietf.org/doc/html/rfc768[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-netty`

Namespace in scenario::
`netty()`

Client library::
Netty: refer to the https://netty.io/[Netty] project.

Supported steps::
* <<HTTP step,`HTTP`>>: executes an HTTP request using https://datatracker.ietf.org/doc/rfc2616[`HTTP 1.1`] or https://datatracker.ietf.org/doc/rfc7540[`HTTP 2.0`].
* <<HTTP WITH step,`HTTP WITH`>>: executes an HTTP request reusing the HTTP connection created by a precedent step.
* <<CLOSE HTTP step,`CLOSE HTTP`>>: closes an HTTP connection created by a precedent step.
* <<MQTT Publish step,`MQTT Publish`>>: sends data to an MQTT server.
* <<MQTT Subscribe step,`MQTT Subscribe`>>: consumes data from an MQTT server.
* <<TCP step,`TCP`>>: exchanges data with a TCP server.
* <<TCP WITH step,`TCP WITH`>>: exchanges data reusing the TCP connection created by a precedent step.
* <<CLOSE TCP step,`CLOSE TCP`>>: closes a TCP connection created by a precedent step.
* <<UDP step,`UDP`>>: exchanges data with a UDP endpoint.

Examples of usage are provided later in this <<Examples of usage,section>>. 

== Configuration

=== Example configuration file
Netty configuration settings are configured in a netty.yaml file. 

[source,kotlin,linenumbers]
----
campaign:
  name: mqtt-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

logging:
  console: true
  root: INFO

events:
  root: WARN

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters
Available parameters are described in the table below.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `connect`
a| Configures the connection to the remote endpoint +
*Applicable Steps:* HTTP, MQTT Publish, MQTT Subscribe, TCP, UDP + 
*Optional/Required:* Required +
*Data Type:* Lambda +
*Default Value:* `all` +

.Example 
[source,kotlin]
----
connect {
    url("https://my-website.com:8080/test")
    connectTimeout = Duration.ofSeconds(5)
    inflate()
    charset(Charsets.ISO_8859_1)
    maxContentLength(123)
    followRedirections(15)
    noDelay = false
    keepConnectionAlive = false
    tls {
    disableCertificateVerification = true
    }
    proxy {
        type = HttpProxyType.SOCKS5
        address("my-proxy", 9876)
    }
    followRedirections(5)
}
----

| `version`
a| Identifies the version of the HTTP protocol to use: `HTTP_1_1` or `HTTP_2_0`. +
*Applicable Steps:* HTTP +
*Optional/Required:* Optional +
*Data Type:* ENUM +
*Default Value:* `HTTP_1_1` +

.Example 
[source,kotlin]
----
connect {
    version: HTTP_1_1
}
----

| `url`
a| The root URL; the path of the request is appended to it. + 
*Applicable Steps:* HTTP + 
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* N/A +

.Example 
[source,kotlin]

----
connect {
    url("https://my-website.com:8080/test")
}
----

| `connectTimeout`
a| Limit duration to fully establish the connection.   + 
*Applicable Steps:* HTTP, TCP, UDP + 
*Optional/Required:* Optional +
*Data Type:* Duration of time +
*Default Value:* 10seconds +

.Example 
[source,kotlin]
----
connect {
    connectTimeout = Duration.ofSeconds(5)
}
----

| `readTimeout`
a| Limit duration to receive a response and read it totally after a request. + 
*Applicable Steps:* HTTP, TCP, UDP + 
*Optional/Required:* Optional +
*Data Type:* Duration of time +
*Default Value:* 10 seconds +

.Example 
[source,kotlin]
----
connect {
    readTimeout = Duration.ofSeconds(5)
  }
----

| `shutdownTimeout`
a| Limit duration to close a connection. + 
*Applicable Steps:* HTTP, TCP, UDP + 
*Optional/Required:* Optional +
*Data Type:* Duration of time +
*Default Value:* 10 seconds +

.Example 
[source,kotlin]
----
connect {
    shutdownTimeout = Duration.ofSeconds(5)
}
----

| `sendBufferSize`
a| The size of the buffer used to prepare the data to send. + 
*Applicable Steps:* HTTP, TCP, UDP + 
*Optional/Required:* Optional +
*Data Type:* Integer +
*Default Value:* 1024 bytes +

.Example 
[source,kotlin]
----
connect {
    sendBufferSize = 1024 
}  
----

| `receiveBufferSize`
a| The size of the buffer used to prepare the data to send. + 
*Applicable Steps:* HTTP, TCP, UDP + 
*Optional/Required:* Optional +
*Data Type:* Integer +
*Default Value:* 1024 bytes

.Example 
[source,kotlin]
----
connect {
    receiveBufferSize = 1024 
}  
----

| `nettyChannelOptions`
a|Overwrites the options of the Netty channel. + 
*Applicable Steps:* HTTP, TCP, UDP +
*Optional/Required:* Optional +
*Data Type:* Map<ChannelOption<*>, Any> + 
*Default Value:* emptyMap() ;uses Netty/OS defaults. +

.Example +
[source,kotlin]
----
netty {
    channelOptions = mapOf(
        ChannelOption.SO_KEEPALIVE to true,
        ChannelOption.TCP_NODELAY to true,
        ChannelOption.CONNECT_TIMEOUT_MILLIS to 5000,
        ChannelOption.SO_REUSEADDR to true
    )
}
----

| `noDelay`
a| Disables the Nagle Algorithm. + 
*Applicable Steps:* HTTP, TCP + 
*Optional/Required:* Optional +
*Data Type:* Lambda +
*Default Value:* true

.Example +
[source,kotlin]
----
connect {
    noDelay = false
}
----

| `keepConnectionAlive`
a| When set to true, the HTTP header connection is set to `Keep-Alive` and the client connection is kept open until `CLOSEHTTP`() is called. + 
*Applicable Steps:* HTTP + 
*Optional/Required:* Required +
*Data Type:* Lambda +
*Default Value:* false +

.Example 
[source,kotlin]
----
connect {
    keepConnectionAlive = false
}
----

| `tls`
a| Configuration for SSL/TLS   + 
*Applicable Steps:* HTTP, TCP + 
*Optional/Required:* Optional +
*Data Type:* Block +
*Default Value:* N/A +

.Example +
[source,kotlin]
----
connect {
    tls {
        disableCertificateVerification = true
        protocols(HttpProtocol.HTTP_1_1, HttpProtocol.HTTP_2)
        ciphers = listOf(
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_AES_128_GCM_SHA256"
        )
    }
}
----

| `disableCertificationVerification`
a| Enables (false) or disables (true) verification of the certificate on the server; for example, set to `true` for a self-signed certificate. + 
*Applicable Steps:* HTTP, TCP + 
*Optional/Required:* Optional +
*Data Type:* Boolean +
*Default Value:* false +

.Example 
[source,kotlin]
----
connect {
    tls {
        disableCertificateVerification = true
    }
}
----

| `protocols`
a| Defines the list of allowed HTTP versions for the connection.
 *Applicable Steps:* HTTP, TCP + 
 *Optional/Required:* Optional +
 *Data Type:* ENUM +
 *Default Value:* HttpProtocol.HTTP_1_1

.Example +
[source,kotlin]
----
connect {     
    tls {
        protocols(HttpProtocol.HTTP_1_1, HttpProtocol.HTTP_2) 
    }
}
----

| `ciphers`
|a Defines the list ofsupported cipher algorithms. defaults to the Netty default for the related HTTP version. +
*Applicable Steps:* HTTP, TCP + 
*Optional/Required:* Optional +
*Data Type:* ENUM +
*Default Value:* null +

.Example +
[source,kotlin]
----
connect {     
    tls {
        ciphers = listOf(
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_AES_128_GCM_SHA256"
        )    
    }
}
----

|`proxy`
a|Configuration to exchange HTTP data via a proxy.   + 
*Applicable Steps:* HTTP, TCP + 
*Optional/Required:* Optional +
*Data Type:* Block +
*Default Value:* null +

.Example 
[source,kotlin]
----
connect {
    proxy {
        type = HttpProxyType.SOCKS5
        address("my-proxy", 9876)
    }
 }
----

| `address`
a| The host and port of the proxy + 
*Applicable Steps:* HTTP, TCP, UDP +   
*Optional/Required:* Optional +
*Data Type:* String (Host) and Int (Port) +
*Default Value:* None +

.Example +
[source,kotlin]
----
address("my-proxy", 9876)
----

| `type`
a| Defines the type of the proxy to use. +
Available choices: HTTP:  `HTTP`, `SOCKS5` ; TCP: `SOCKS4`, `SOCKS5` +
*Applicable Steps:* HTTP, MQTT Publish, MQTT Subscribe, UDP + 
*Optional/Required:* Optional +
*Data Type:* HttpProxyType (ENUM) +
*Default Value:* None +

.Example +
[source,kotlin]
----
type = HttpProxyType.SOCKS5
----

|`authenticate`
a| Credentials (username and optional password) to authenticate to the proxy, if the proxy supports and requires it   + 
*Applicable Steps:* HTTP, MQTT Publish, MQTT Subscribe, UDP + 
*Optional/Required:* Optional +
*Data Type:* Lambda +
*Default Value:* N/A +

.Example (HTTP proxy type) +
[source,kotlin]
----
credentials {
    username = "office_user"
    password = "password123"
}
----

.Example (SOCKS5 proxy type)
[source,kotlin]
----
credentials {
    username = "tunnel_admin"
    password = "secure_socks_pass"
}
----

| `charset`
a| Character encoding of the HTTP requests. +
*Applicable Steps:* HTTP + 
*Optional/Required:* Optional +
*Data Type:* java.nio.charset.Charset +
*Default Value:* StandardCharsets.UTF_8 +

.Example +
[source,kotlin]
----
charset(Charsets.ISO_8859_1)
----

|`maxContentLength`
a| Sets the maximum allowed size (in bytes) for the HTTP response body. If the response exceeds this limit, the connection is closed to prevent memory exhaustion. +
*Applicable Steps:* HTTP +
*Optional/Required:*  Optional +
*Data Type:* Int +
*Default Value:* 1048576

.Example
[source,kotlin]
----
maxContentLength(10 * 1024 * 1024)
----

| `followRedirections`
a| Defines the maximum number of HTTP redirects (status codes 3xx) the client will automatically follow before giving up. This prevents infinite redirection loops +
*Applicable Steps:* HTTP +
*Optional/Required:* Optional+
*Data Type:* Int +
*Default Value:* 0 (Redirects are not followed.) +

.Example +
[source,kotlin]
----
followRedirections(5)
----

| `pool`
a| Configures the connection pooling strategy. Pooling reuses existing connections for multiple requests to avoid the overhead of repeated TCP handshakes and TLS negotiations. +
*Applicable Steps:*  HTTP, TCP +
*Optional/Required:* Optional +
*Data Type:* Configuration Block +
*Default Value:* N/A +

.Example +
[source,kotlin]
----
pool { 
    size = 143
    checkHealthBeforeUse = true
}
----

| `pool.size`
a| Maximum nuber of concurrent connections. Pooling reuses existing connections for multiple requests to avoid the overhead of repeated TCP handshakes and TLS negotiations. +
*Applicable Steps:*  HTTP, TCP +
*Optional/Required:* Optional +
*Data Type:* Block +
*Default Value:* Enabled with default settings (Size: 20 connections). +

.Example +
[source,kotlin]
----
pool { 
    size = 143
}
----

| `pool.checkHealthBeforeUse`
a| Verifies that the socket is still on before sending data open (true) before sending data. +
*Applicable Steps:* HTTP, TCP + 
*Optional/Required:* Optional +
*Data Type:*  Boolean +
*Default Value:* true +

.Example +
[source,kotlin]
----
pool { 
    checkHealthBeforeUse = true
}
----

| `inflate`
a| Enables or disables the automatic decompression of the HTTP response body. +
*Applicable Steps:* HTTP +
*Optional/Required:* Optional +
*Data Type:* Boolean +
*Default Value:* true +

.Example +
[source,kotlin]
----
inflate(true)
----

| `request`
a| A factory to create the request to exchange, using the step context and the input as arguments. +
The following types of reqiests can be created: `simple`, `form`, or `multipart`. +
*Applicable Steps:* HTTP, HTTP WITH, TCP, TCP WITH, UDP +
*Optional/Required:* Required +
*Data Type:* Lambda Block +
*Default Value:* None +

.Example  (`simple`) + 
[source,kotlin]
----
request { context, input ->
    simple(HttpMethod.POST, "/v1/users") {
        header("Content-Type", "application/json")
        body("{\"name\": \"Gemini\"}")
    }
}
----

.Example  (`form`) + 
[source,kotlin]
----
request { context, input -> 
    form(HttpMethod.POST, "/v1/login") { 
        param("username", "user_123") 
        param("grant_type", "password") 
        param("scope", "read write") 
    } 
}
----

.Example  (`multipart`) + 
[source,kotlin]
----
request { context, input ->
    multipart(HttpMethod.POST, "/v1/profile/upload") {
        text("description", "New profile picture")
        binary("avatar", input.fileBytes, "image/jpeg", "photo.jpg")
    }
}
----

| `deserialize`
a| Specifies the transformation logic used to convert the raw HTTP response bytes into a high-level object. +
*Applicable Steps:* HTTP, HTTP WITH, TCP  +
*Optional/Required:* Optional +
*Data Type:* Block +
*Default Value:* ByteBuf +

.Example +
[source,kotlin]
----
connect {
    deserialize(String::class)
}
----

| `closeHttp`
a| Specifies the  name of an `HTTP` step owning the `HTTP` connection to close. +
*Applicable Steps:* CLOSE HTTP  +
*Optional/Required:* Optional +
*Data Type:* String +
*Default Value:* N/A +

.Example +
[source,kotlin]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

| `clientName`
a| Identifies the client onto the MQTT server. +
*Applicable Steps:* MQTT Publish, MQTT Subscribe  +
*Optional/Required:* Required +
*Data Type:* String +
*Default Value:* N/A +

.Example +
[source,kotlin]
----
clientName("mqtt-client-1")
----

| `topicName`
a| Identifies the client onto the MQTT server where data is sent. +
*Applicable Steps:* MQTT Publish +
*Optional/Required:* Required  +
*Data Type:* String +
*Default Value:* N/A +

.Example +
[source,kotlin]
----
topicName("factory/floor1/machine5/telemetry")
----

| `topicFilter`
a| MQTT topics or patterns to consume. +
*Applicable Steps:* MQTT Subscribe  +
*Optional/Required:* Required  +
*Data Type:* String +
*Default Value:* N/A +

.Example +
[source,kotlin]
----
topicName("factory/floor1/machine5/telemetry")
----
|===

== Examples of usage

=== HTTP step
The `HTTP` step within the Netty plugin executes an HTTP request using https://datatracker.ietf.org/doc/rfc2616[`HTTP 1.1`] or https://datatracker.ietf.org/doc/rfc7540[`HTTP 2.0`].

Ancestor::
Scenario or Step

Functionality::
* The `HTTP` step establishes a connection with the server using either a pool of connections or an individual connection for each minion.
* If an individual connection is used, the connection is maintained until the latest execution for the minion is performed, including the ones from the related <<HTTP WITH step,`HTTP WITH`>> step, as in the example.
+
* When the step is kept open without limit, a <<CLOSE TCP step,`CLOSE TCP`>> step must be executed to properly close the connections and avoid saturation of the system.
+
Be aware that the number of open connections that can be concurrently maintained depends on the configuration of your operating system. If there are issues with maintaining open connections, try adapting the limits of the file descriptors.

Example::
+
[source,kotlin,linenumbers]
----
netty().http {
    connect {
        url("https://my-website.com:8080/test")
        connectTimeout = Duration.ofSeconds(5)
        inflate()
        charset(Charsets.ISO_8859_1)
        maxContentLength(123)
        followRedirections(15)
        noDelay = false
        keepConnectionAlive = false
        tls {
            disableCertificateVerification = true
        }
        proxy {
            type = HttpProxyType.SOCKS5
            address("my-proxy", 9876)
        }
        followRedirections(5)
    }
    pool {
        size = 143
        checkHealthBeforeUse = true
    }
    request { context, input -> simple(HttpMethod.HEAD, "/head") }
}.deserialize(String::class)

----

Reference Documentation::
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.

=== HTTP WITH step
The `HTTP WITH` step within the Netty plugin executes an HTTP request reusing the HTTP connection created by a precedent step.

Ancestor::
Step

Functionality::
* The `HTTP WITH` step is a direct or indirect follower of an `HTTP` step. `HTTP WITH` specifies the name of the step that owns the connection, and reuses a connection from that step as it was created (either from a pool or the connection attached to the minion).
* `HTTP WITH` cannot configure the connection differently than the `HTTP` step it relates to.

Example::
+
[source,kotlin,linenumbers]
----
netty().httpWith("name-of-a-previous-HTTP-step") {
    request { context, input -> simple(HttpMethod.HEAD, "/head") }
}.deserialize(String::class)
----


Reference Documentation:: 
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.

== CLOSE HTTP step
The `CLOSE HTTP` step within the Netty plugin closes the `HTTP` connection attached to the minion, and created by a direct or indirect ancestor step, when the tail of the minion workflow is received. 

It is always a best practice to use a `CLOSE HTTP`  step when reusing an `HTTP` connection across several steps without a pool of connections. 

Ancestor::
Step

Functionality::
The `CLOSE HTTP` step is a direct or indirect follower of an `HTTP` step which keeps the connection open.  `CLOSE HTTP` simply forwards the input it receives to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

Reference Documentation::
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.

=== MQTT Publish step 
The `MQTT Publish` step within the Netty plugin sends data to an MQTT server.

Ancestor::
Step
 
Functionality::
The MQTT Publish step provides a variety of options for controlling the quality and reliability of messages that are published to the server.

Example::
+
[source,kotlin,linenumbers]
----
.netty().mqttPublish {
    connect {
        host =  "localhost"
        port = 11883
    }
    clientName("mqtt-client-1")
    records { _, batteryState ->
        listOf(
            MqttPublishRecord(
                value = objectMapper.writeValueAsString(batteryState),
                topicName = "battery-state"
            )
        )
    }
}               
----

Reference Documentation::
Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.
  
=== MQTT Subscribe step 
The `MQTT Subscribe` step within the Netty plugin consumes data from an MQTT server.

Ancestor::
Step
Functionality::
The MQTT Subscribe step provides a variety of options for controlling the quality and reliability of the messages that are subscribed to from the server.

Example::
+
[source,kotlin,linenumbers]
----
it.netty().mqttSubscribe {
    connect {
        host = localhost
        port = 11883
    }
    clientName("mqtt-client-1")
    topicFilter(ServerConfiguration.TOPIC_NAME)
}
----


=== TCP step
The `TCP` step within the Netty plugin is a client for `TCP`.
 
Ancestor::
Scenario or Step

Functionality::
The TCP step establishes a connection with the server using either a pool of connections or an individual connection for each minion.
 
+
If an individual connection is used, the connection is maintained until the latest execution for the minion is performed, including the ones from the related <<TCP WITH, `TCP WITH`>> step, as in the example.
+
When the step is kept open without limit, a <<CLOSE TCP Step,`CLOSE TCP`>> step should be executed to properly close the connections and avoid a saturation of the system.
+
Be aware that the number of open connections that can be concurrently maintained depends on the configuration of your operating system. If there are issues with maintaining open connections, adapting the limits for file descriptors may help.


Example::
+
[source,kotlin,linenumbers]
----
netty().tcp {
    request { context, input -> input.encodeToByteArray() }
    connect {
        address("remote-server.acme.com", 9000)
        connectTimeout = Duration.ofMinutes(1)
        noDelay = false
        keepConnectionAlive = false
        tls {
            disableCertificateVerification = true
        }
        proxy {
            type = HttpProxyType.SOCKS5
            address("my-proxy", 9876)
        }
    }
    pool {
        size = 1000
        checkHealthBeforeUse = true
    }
}
----

Reference Documentation::
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.

=== TCP WITH step 
The `TCP WITH` step within the Netty plugin sends a TCP payload, reusing the connection created by a precedent step.

Ancestor::
Step

Functionality::
* The `TCP WITH` step is a direct or indirect follower of a `TCP`  step. `TCP WITH` specifies the name of the step that owns the connection, and reuses a connection from that step  as it was created (either from a pool or the connection attached to the minion).
* `TCP WITH` cannot configure the connection differently than the `TCP` step it relates to.
 
Example::
+
[source,kotlin,linenumbers]
----
netty().tcpWith("name-of-a-previous-HTTP-step") {
    request { context, input -> input.encodeToByteArray() }
}
----

Reference Documentation::
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.

=== CLOSE TCP step 
The `CLOSE TCP` step within the Netty plugin closes the TCP connection, attached to a minion and created by a direct or indirect ancestor step, when the tail of the minion workflow is received. 

It is best practice to use a `CLOSE TCP` step when reusing a `TCP` connection across several steps without a pool of connections.

Ancestor::
Step

Functionality::
The `CLOSE TCP` step is a direct or indirect follower of an `HTTP` step which keeps the connection open. `CLOSE TCP` simply forwards the input it receives to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
netty().closeHttp("name-of-a-previous-HTTP-step")
----

Reference Documentation::
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.

=== UDP step 
The `UDP` step within the Netty plugin is a client for UDP.

It is best practice to use the  `UDP` step when reusing a `TCP` connection across several steps without a pool of connections.

Ancestor:
Scenario or Step

Functionality::
The `UDP` step creates a UDP Datagram packet from the `request` and sends it to the remote endpoint and expects a response.

Example::
+
[source,kotlin,linenumbers]
----
netty().udp {
    request { context, input -> input.encodeToByteArray() }
    connect {
        address("remote-server.acme.com", 9000)
        connectTimeout = Duration.ofMinutes(1)
    }
}
----

Reference Documentation::
* Refer to the https://netty.io/wiki/index.html[Netty] documentation for further configuration and parameter information.