= R2DBC-jasync plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

== Overview
The R2DBC-jasync plugin connects QALIPSIS to https://mariadb.org/[MariaDB], https://www.mysql.com[MySQL] and https://www.postgresql.org/[PostgreSQL].

Technologies addressed::
* MariaDB: https://mariadb.org/[]

* MySQL: https://www.mysql.com[]

* PostgreSQL: https://www.postgresql.org/[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-r2dbc-jasync`

Namespace in scenario::
`r2dbcJasync()`

Client library::
Jasync-sql: refer to https://github.com/jasync-sql/jasync-sql[jasync-sql]
+
Jasync-sql is an asynchronous database driver for PostgreSQL and MySQL written in kotlin.

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Search step,`search`>>: searches records and builds a query from the input and step context.

Example of usage are provided later in this <<Examples of Usage,section>>.

== Configuration

=== Example configuration file

R2DBC-jasync configuration settings are configured in an r2dbc-jasync.yaml file. 

[source,kotlin,linenumbers]
----
campaign:
  name: r2dbc-jasync-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters

Available parameters are described in the table below.

[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `protocol`
a| Specifies the protocol of the target database.+
Available choices are: MariaDB, MySQL, * PostgreSQL +
*Applicable Steps:* Poll, Search, Save + 
*Optional/Required:* Required +
*Data Type:* Protocol.ENUM +
*Default Value:* N/A + 

.Example 
[source,kotlin]
----
protocol(Protocol.POSTGRESQL)
----

| `connection`
a| Specifies the connection parameters for the target database. +
*Applicable Steps:* Poll, Search, Save + 
*Optional/Required:* Required +
*Data Type:* Lambda +
*Default Value:* N/A + 
   
.Example 
[source,kotlin]
----
connection {
    database = "iot"
    port = 5432
    username = "DavidW"
    password = "Awesome_1978"
}
----

| `query`
a| Specifies a query respecting the requirements of the target database (https://mariadb.org/[MariaDB],  https://www.mysql.com[MySQL], https://www.postgresql.org/[PostgreSQL]).
. +
*Applicable Steps:* Poll, Search + 
*Optional/Required:* Required +
*Data Type:*
* Poll: String that defines the prepared statement or query to execute. +
* Search: Lambda that takes step context and input to return a string. +
*Default Value:* N/A + 
   
.Example (Poll)
[source,kotlin]
----
query("select * from battery_state order by \"timestamp\"")
----

.Example (Search)
[source,kotlin]
----
query { stepContext, input ->
    val request = "SELECT DISTINCT * from battery_state where timestamp = ? AND device_id = ?"
    request
}
----

| `parameters`
a| Poll: Binds values to the clauses of the prepared query. +
Search: Computes the list of values bound to the prepared query using the step context and input. +
*Applicable Steps:* Poll, Search + 
*Optional/Required:* Optional +
*Data Type:* +
* Poll: `List<Any>` / `vararg Any` +
* Search: Lambda that takes step context and input and returns `List<Any>`. +
*Default Value:* `emptyList()` +
 
.Example (Search) 
[source,kotlin]
----
parameters { _, input ->
    listOf(input.timestamp.epochSecond, input.deviceId)
}
----

| `pollDelay`
a| Specifies the delay between query executions. +
*Applicable Steps:* Poll +
*Optional/Required:* Optional  +
*Data Type:* java.time.Duration +
*Default Value:* N/A + 

.Example
[source,kotlin]
----
pollDelay(Duration.ofSeconds(1)) +
----

| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
   Refer to xref:plugins/plugins.adoc#singletonconfiguration-parameters[SingletonConfiguration parameters] for details on strategies and examples of usage.
|===

== Examples of Usage

=== Poll step 
The `poll` step within the R2DBC-jasync plugin polls the newest records from the database, respecting a delay between each execution of a select query.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. The `poll` step within the `r2b-jaysync` plugin uses a strategy of “delivered at least once”.

Example::
+
[source,kotlin,linenumbers]
----
r2dbcJasync().poll {
    protocol(Protocol.POSTGRESQL) <1>
    connection { <2>
        database = "iot"
        port = 5432
        username = "DavidW"
        password = "Awesome_1978"
    }
    query("select * from battery_state order by \"timestamp\"") <3>
    pollDelay(Duration.ofSeconds(1)) <4>
}
----
<1> Specify the protocol of the target database.
<2> Define the connection paraneters.
<3> Specify the query parameters.
<4> Set the poll delay.

//-
Tips::
* Use the `poll` step with a join operator when you need to verify the values saved by your tested system in the database.
* `query` requires at least one sorting field to filter the newest results and not fetch the same records repeatedly.

//-
Reference documentation::
Refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] for further parameter and configuration information.

=== Save step 
The `save` step within the R2DBC-jasync plugin persists a batch of records into an SQL table using a prepared statement.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate the table and the list of columns and their values, which are then combined and forwarded to the database.

Example::
+
[source,kotlin,linenumbers]
----
.r2dbcJasync()   
.save {
    protocol(Protocol.POSTGRESQL) <1>
    connection { <2>
        database = "iot"
        port = 5432
        username = "DavidW"
        password = "Awesome_1978"
    }
    tableName { StepContext, input -> <3>
        "battery_state"
    }
    columns { StepContext, input -> <4>
        listOf(
            "device_id",
            "timestamp",
            "battery_level"
        )
    }
    values { StepContext, input -> <5>
        listOf(
            JasyncSaveRecord(
                input.deviceId,
                input.timestamp.epochSecond,
                input.batteryLevel
            )
        )
    }
}
----
<1> Specify the protocol of the target database.
<2> Define the connection paraneters.
<3> Define the table name where values are saved.
<4> Define column names for the table.
<5> Specify the values to save to the table.

//-
Tips::
* Use the `save` step after a `collect()` step in order to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.
* The `save` step is extremely flexible; table, columns and values might depend on the context and input value received from the previous step.

//-
Reference documentation::
Refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] for further parameter and configuration information.

=== Search step 
The `search` step within the R2DBC-jasync plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The `search` step’s input and step context are used to generate a prepared statement and the values to complete it; the batch of results is then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
.r2dbcJasync()
.search {
    protocol(Protocol.MARIADB) <1>
    connection { <2>
        database = "iot"
        port = 3306
        username = "DavidW"
        password = "Awesome_1978"
    }
    query { _, _ -> <3>
        val request = "SELECT DISTINCT * from battery_state where timestamp = ? AND device_id = ?"
        request
    }
    parameters { _, input ->. <4>
        listOf(input.timestamp.epochSecond, input.deviceId)
    }
}
----
<1> Specify the protocol of the target database.
<2> Define the connection paraneters.
<3> Specify a query respecting the requirements of the target database.
<4> Specify the query parameters.

//-
Tip::
Use the `search` step after a `collect` step in order to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.

//-
Reference documentation::
Refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] for further parameter and configuration information.

=== R2dbcJayncSaveAndPoll scenario
[source,kotlin,linenumbers]
----
scenario { <1>
    minionsCount = 20
    profile {
        immediate()
    }
}
    .start()
    .jackson() <2>
    .csvToObject(mappingClass = BatteryState::class) { <3>

        classpath(path = "battery-levels.csv")
            header { <4> 
                column(name = "device_id")
                column(name = "timestamp")
                column(name = "battery_level").integer()
            }
            unicast()
    }
        .map { it.value }
        .r2dbcJasync() 
        .save { <5> 

            protocol(Protocol.POSTGRESQL)

            connection {
                database = "postgres"
                port = 15432
                username = "postgres"
                password = "root"
            }

            tableName { _, _ ->
                "battery_state"
            }

            columns { _, _ ->
                listOf(
                    "id",
                    "device_id",
                    "timestamp",
                    "battery_level"
                )
            }

            values { _, input ->
                listOf(
                    JasyncSaveRecord(
                        input.deviceId,
                        input.deviceId,
                        input.timestamp.epochSecond,
                        input.batteryLevel
                    )
                )
            }

            monitoring {
                events = false
                meters = true
            }

        }
        .map {
            it.input
        }
        .innerJoin()
        .using { correlationRecord ->
            correlationRecord.value.deviceId
        }
        .on {
            it.r2dbcJasync().poll {

                protocol(Protocol.POSTGRESQL)

                connection {
                    database = "postgres"
                    port = 15432
                    username = "postgres"
                    password = "root"
                }

                query("select * from battery_state order by \"timestamp\"")

                pollDelay(Duration.ofSeconds(1))
            }
                .flatten()
                .map { record ->
                    val batteryState = record.value
                    BatteryState(
                        deviceId = batteryState.getValue("device_id") as String,
                        batteryLevel = batteryState.getValue("battery_level") as Int,
                        timestamp = Instant.ofEpochSecond((batteryState.getValue("timestamp") as Int).toLong())
                    )
                }
        }
        .having { correlationRecord ->
            correlationRecord.value.deviceId
        }
        .filterNotNull()
        .verify { result ->
            result.asClue {
                assertSoftly {
                    it.first.batteryLevel shouldBeExactly it.second.batteryLevel
                }
            }
        }
----
<1> Define the scenario, set the number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object
<4> Define the header of the csv file.
<5> Start the save step.

=== R2dbcJayncSaveAndSearch scenario
[source,kotlin,linenumbers]
----
scenario { <1>
    minionsCount = 20
    profile {
        immediate()
    }
}
    .start() 
    .jackson() <2> 
    .csvToObject(mappingClass = BatteryState::class) { <3>

        classpath(path = "battery-levels.csv")
        header { <4>
            column(name = "device_id")
            column(name = "timestamp")
            column(name = "battery_level").integer()
        }
        unicast()
    }
    .map { it.value }
    .r2dbcJasync() 
    .save { <6>

        protocol(Protocol.MARIADB)

        connection {
            database = "iot"
            port = 13306
            username = "root"
            password = "root"
        }

        tableName { _, _ ->
            "battery_state"
        }

        columns { _, _ ->
            listOf(
                "id",
                "device_id",
                "timestamp",
                "battery_level"
            )
        }

        values { _, input ->
            listOf(
                JasyncSaveRecord(
                    input.deviceId,
                    input.deviceId,
                    input.timestamp.epochSecond,
                    input.batteryLevel
                )
            )
        }

        monitoring {
            events = false
            meters = true
        }

    }
    .map { it.input }
    .r2dbcJasync()
    .search { <7>
        protocol(Protocol.MARIADB)

        connection {
            database = "iot"
            port = 13306
            username = "root"
            password = "root"
        }

        query { _, _ ->
            val request = "SELECT DISTINCT * from battery_state where timestamp = ? AND device_id = ?"
            request
        }
        parameters { _, input ->
            listOf(input.timestamp.epochSecond, input.deviceId)
        }
    }
    .map { <5>
        it.input to it.records.map { record ->
            val batteryState = record.value
            BatteryState(
                    deviceId = batteryState.getValue("device_id") as String,
                    batteryLevel = batteryState.getValue("battery_level") as Int,
                    timestamp = Instant.ofEpochSecond((batteryState.getValue("timestamp") as Int).toLong())
            )
        }
    }
    .verify { result -> <8> 
        result.asClue {
            assertSoftly {
                    result.second.size shouldBeExactly 1
                    result.first.batteryLevel shouldBeExactly result.second.first().batteryLevel
            }
        }
    }

----
<1> Define the scenario, set the number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object
<4> Define the header of the csv file.
<5> Transform the output of the CSV reader entries to utils.BatteryState.
<6> Start the save step.
<7> Start the search step.
<8> Define the verification parameters.
