= Redis-lettuce plugin [.badge.oss]## ##[.badge.commercial]## ##[.badge.cloud]## ##

The Redis-lettuce plugin connects QALIPSIS to https://redis.io/[Redis].

Technology addressed::
Redis: https://redis.io/[]

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-redis-lettuce`

Namespace in scenario::
`redisLettuce()`

Client library::
Lettuce: refer to https://lettuce.io/[Lettuce].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Consume step,`consume`>>: consumes data from Redis streams.
* <<Produce step,`produce`>>: pushes messages to Redis streams.

Examples of usage are provided later in this <<Examples of usage,section>>. 

== Configuration
=== Example configuration file
[source,kotlin,linenumbers]
----
campaign:
  name: redis-${random.shortuuid}
  configuration:
    validation:
      max-execution-duration: PT40S

report:
  export:
    console-live:
      enabled: false
----

=== Configuration parameters
Available parameters are described in the table below.
[cols="1,4" options="header"]
|===
| *Parameter* 
| *Description*

| `connection`  
a| Specifies connection parameters. +
 *Applicable Steps:* Poll, Save, Consume +
 *Optional/Required:* Required +
 *Data Type:* Lambda +
 *Default Value:* ("localhost:5672") +

.Example
[source,kotlin]
----
connection {
  nodes = listOf("localhost:6379")
  database = 0
  redisConnectionType = RedisConnectionType.SINGLE
  authUser = "Celia45"
  authPassword = "Columbus1963"
}
----

| `redisConnectionType`  
a| Indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`. +
 *Applicable Steps:* Poll, Save, Consume +
 *Optional/Required:* Required +
 *Data Type:* RedisConnectionType.ENUM +
 *Default Value:* SINGLE +

.Example
[source,kotlin]
----
redisConnectionType = RedisConnectionType.SINGLE
----

| `pollDelay`  
a| Specifies the delay between query executions .+
 *Applicable Steps:* Poll, Consume +
 *Optional/Required:* Required +
 *Data Type:* Integer +
 *Default Value:* SINGLE +

.Example
[source,kotlin]
----
pollDelay(Duration.ofSeconds(1))
----

| `KeyOrPattern`  
a| Specifies the key or pattern that will be polled after each `pollDelay`. +
 *Applicable Steps:* Poll, Consume +
 *Optional/Required:* Required +
 *Data Type:* String +
 *Default Value:* N/A

.Example
[source,kotlin]
----
keyOrPattern("battery_state_save_and_poll")
----

| `records`  
a| Generates and configures a list of saved or produced records. +
 *Applicable Steps:* Save, Produce +
 *Optional/Required:* Required +
 *Data Type:* Lambda +
 *Default Value:* N/A

.Example
[source,kotlin]
----
records { _, input ->
    listOf(
      SetRecord("battery_state_save_and_poll",
        objectMapper.writeValueAsString(input)
      )
    )
  }
----

| `offset`  
a| sets the offset value for each topic and consumer group. +
 Available values are: `FROM_BEGINNING`, `LAST_CONSUMED` or `LATEST`. +
 *Applicable Steps:* Consume +
 *Optional/Required:* Required +
 *Data Type:* lambda +
 *Default Value:* N/A

.Example
[source,kotlin]
----
streamKey("battery_state_produce_and_consume")
offset(LettuceStreamsConsumerOffset.FROM_BEGINNING)
group("consumer")
----

| `singletonConfiguration`
a| Configures how polled results are delivered to scenario minions. +
  Specify one of the strategies directly (not wrapped in a lambda). +
  Available strategies: `sequential`, `broadcast`, `unicast`, `loop`. +

 * `broadcast`: sends every polled record to all minions. Records are delivered in order, with the oldest buffered record sent first. In this mode, the singleton behaves like a Pub/Sub broadcaster. 

 * `unicast`: sends each polled record to exactly one minion. The singleton acts as a FIFO distributor: Records are stored in a buffer until a minion consumes them. The buffer has a fixed size; when it becomes full, the oldest records are dropped to make space for new ones. 

 * `loop`: sends each polled record to all minions, but once the end of the buffer is reached, it loops back to the beginning. This creates a continuous cyclic stream of the buffered records. 

 * `sequential`: disables singleton execution and runs this step within the parent’s workflow. Data distribution is controlled entirely by the parent step. This mode is typically used when you want to process each record from a source from start to finish once, and then stop publishing until new data is available.
   
 Note::
 Each strategy EXCEPT `sequential` requires `bufferSize` (Int) and `idleTimeout` (Duration); see `singletonConfiguration.bufferSize` and `singletonConfiguration.idleTimeout` definitions below. +

*Applicable Step:* Poll +
*Optional/Required:* Optional +
*Data Type:* Function +
*Default Value:* unicast(bufferSize, idleTimeout)

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.bufferSize`
a| Size of the buffer used to store polled records before delivery to minions.+ +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Integer +
 *Default Value:* -1 +

.Example
[source,kotlin] 
----
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `singletonConfiguration.idleTimeout`
a| Maximum time to wait before delivering polled records to minions, even if the buffer is not full. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* java.time.Duration +
 *Default Value:* Duration.ZERO +

.Example
[source,kotlin] 
---- 
broadcast(bufferSize = 4, idleTimeout = Duration.ofMinutes(1))
----

| `broadcast`
a| Specifies the broadcast parameters for a step. +
 *Applicable Step:* Poll
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
broadcast(3, Duration.ofMinutes(1))
----

| `unicast`
a| Specifies the unicast parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
unicast(1, Duration.ofMinutes(3))
----

| `loop`
a| Specifies the loop parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
loop(5, Duration.ofMinutes(2))
----

| `sequential`
a| Specifies the sequential parameters for a step. +
 *Applicable Step:* Poll +
 *Optional/Required:* Optional +
 *Data Type:* Function +
 *Default Value:* N/A +

.Example
[source,kotlin] 
----
sequential()
----

|===

== Examples of usage

=== Poll step 
The `poll` step within the Redis-lettuce plugin polls the newest records from a Redis key, with a delay between each execution of polling.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called.
* The `KeyOrPattern` to be used in the poll is set to one of the following valid values: `scan`, `sscan`, `hscan`, `zscan`.
* The native Redis-lettuce command is called using the `KeyOrPattern` provided.

Example::
[source,kotlin,linenumbers]
----
it.redisLettuce()
  .pollSscan { <1> Start the poll step.
    connection { <2>  
      nodes = listOf("localhost:6379")
      database = 0
      redisConnectionType = RedisConnectionType.SINGLE
      authUser = "Celia45"
      authPassword = "Columbus1963"
    }
    keyOrPattern("battery_state_save_and_poll") <3>
    pollDelay(Duration.ofSeconds(1)) <4>
  }
----
<1> Start the poll step.
<2> Specify the connection parameters.
<3> Specify the pattern that will be polled after each `pollDelay`.
<4> Specify the delay between query executions.

Tips::
* Use the `poll` step with a join operator when you need to verify the values saved by your tested system in the database.
* In addition to SSCAN (`pollSscan` in the example), the `poll` step also supports the following Redis commands: HSCAN (`polllHscan`) SCAN (`pollScan`), and ZSCAN (`pollZscan`). 

Reference documentation::
* For more information on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

=== Save step 
The `save` step within the Redis-lettuce plugin persists a batch of records into Redis.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate a valid Redis command and the values to complete it; the batch of results is then forwarded to the next step(s). The records are saved individually.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
.save { <1>
  connection { <2>
    nodes = listOf("localhost:6379")
    database = 0
    redisConnectionType = RedisConnectionType.SINGLE
      authUser = "Celia45"
      authPassword = "Columbus1963"
  }

  records { _, input -> <3>
    listOf(
      SetRecord("battery_state_save_and_poll",
        objectMapper.writeValueAsString(input)
      )
    )
  }
}  
----
<1> Start the poll step.
<2> Specify the connection parameters.
<3> Generate and configure a list of saved records.


Tip::
* The `save` step supports the following Redis commands: SET, SADD, HSET, ZADD. The provided command may depend on the context and input value received from the previous step.
* If the `redisConnectionType` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more information on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

=== Consume step
The `consume` step within the Redis-lettuce plugin records data from Redis streams.

Ancestor::
Scenario 

Functionality::
The `consume` step creates a consumer group in a Redis stream with the provided `connection`, consumer `group` name, and `concurrency`. If `concurrency` is set to 1, records are transmitted sequentially to the next step.

Example::
+
[source,kotlin,linenumbers]
----
redisLettuce()
.streamsConsume { <1>
  connection {  <2>
    nodes = redis://localhost:6439
    database = 0
    redisConnectionType = RedisConnectionType.SINGLE
      authUser = "Celia45"
      authPassword = "Columbus1963"
  }
  streamKey("battery_state_produce_and_consume")  <3>
  offset(LettuceStreamsConsumerOffset.FROM_BEGINNING)
  group("consumer")
}
----
<1> Start the consume step.
<2> Specify the connection parameters.
<3> Set the offset value for the `consumer` group.

Tip::
If `redisConnectionType` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more information on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

=== Produce step
The `produce` step within the Redis-lettuce plugin produces records into the Redis streams.

Ancestor::
Step

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
.streamsProduce { <1>
  connection {  <2>
    nodes = listOf("localhost:6379")
    database = 0
    redisConnectionType = RedisConnectionType.SINGLE
      authUser = "Celia45"
      authPassword = "Columbus1963"
  }

  records { _, input -> <3>
    listOf(
      LettuceStreamsProduceRecord(
        key = "battery_state_produce_and_consume", value = mapOf(
        "device_id" to input.deviceId,
        "timestamp" to input.timestamp.epochSecond.toString(),
        "battery_level" to input.batteryLevel.toString()
        )
      )
    )
  }
}
----
<1> Start the produce step.
<2> Specify the connection parameters.
<3> Generate and configure a list of saved records.

Tip::
* If `redisConnectionType` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more information on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

=== RedisProduceAndConsume scenario

[source,kotlin,linenumbers]
----
 scenario { <1> 
  minionsCount = 20
  profile {
    immediate()
  }
}
  .start()
  .jackson()  <2> 
  .csvToObject(mappingClass = BatteryState::class) { <3>

    classpath(path = "battery-levels.csv")
      header { <4> 
        column(name = "device_id")
        column(name = "timestamp")
        column(name = "battery_level").integer()
      }
    unicast()
  }
  .map { it.value }
  .redisLettuce()
  .streamsProduce {
    connection {
      nodes = listOf("localhost:6379")
      database = 0
      redisConnectionType = RedisConnectionType.SINGLE
      authPassword = ""
      authUser = ""
    }

    records { _, input ->
      listOf(
        LettuceStreamsProduceRecord(
          key = "battery_state_produce_and_consume", value = mapOf(
            "device_id" to input.deviceId,
            "timestamp" to input.timestamp.epochSecond.toString(),
            "battery_level" to input.batteryLevel.toString()
          )
        )
      )
    }
  }
  .map {
    it.input
  }
  .innerJoin()
  .using { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .on {
    it.redisLettuce()
      .streamsConsume {
        connection {
          nodes = listOf("localhost:6379")
          database = 0
          redisConnectionType = RedisConnectionType.SINGLE
          authPassword = ""
          authUser = ""
        }

        streamKey(key = "battery_state_produce_and_consume")
        offset(LettuceStreamsConsumerOffset.FROM_BEGINNING)
        group("consumer")
      }
      .flatten()
      .map { result ->
        val batteryState = result.value
        BatteryState(
          deviceId = batteryState.getValue("device_id"),
          batteryLevel = batteryState.getValue("battery_level").toInt(),
          timestamp = Instant.ofEpochSecond(batteryState.getValue("timestamp").toLong())
        )
      }
  }
  .having { correlationRecord ->
    correlationRecord.value.deviceId
  }
  .filterNotNull()
  .verify { result -> <5>
    result.asClue {
      assertSoftly {
        it.first.batteryLevel shouldBeExactly it.second.batteryLevel
      }
    }
  }
----
<1> Define the scenario minion count and rampup.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Define the verification parameters.

=== RedisSaveAndPoll scenario

[source,kotlin,linenumbers]
----
scenario { <1>
  minionsCount = 20
  profile {
    immediate()
  }
}
  .start()
  .jackson() <2>
  .csvToObject(mappingClass = BatteryState::class) { <3>

    classpath(path = "battery-levels.csv")
      header { <4>
        column(name = "device_id")
        column(name = "timestamp")
        column(name = "battery_level").integer()
      }
    unicast()
  }
  .map {
    it.value
  }
  .redisLettuce()
  .save {
    connection {
      nodes = listOf("localhost:6379")
      database = 0
      redisConnectionType = RedisConnectionType.SINGLE
      authPassword = ""
      authUser = ""
    }

    records { _, input ->
      listOf(
        SetRecord(
          "battery_state_save_and_poll",
          objectMapper.writeValueAsString(input)
        )
      )
    }
  }
  .map {
    it.input
  }
  .innerJoin()
  .using { correlationRecord -> correlationRecord.value.deviceId }
  .on {
    it.redisLettuce()
      .pollSscan {
        connection {
          nodes = listOf("localhost:6379")
          database = 0
          redisConnectionType = RedisConnectionType.SINGLE
          authPassword = ""
          authUser = ""
        }

        keyOrPattern("battery_state_save_and_poll")

        pollDelay(Duration.ofSeconds(1))
      }
      .flatten()
      .map { result ->
        val batteryState = objectMapper.readValue(result.value, BatteryState::class.java)
        batteryState
      }
  }
  .having { correlationRecord -> correlationRecord.value.deviceId }
  .filterNotNull()
  .verify { result ->
    result.asClue {
      assertSoftly {
        it.first.batteryLevel shouldBeExactly it.second.batteryLevel
      }
    }
  }

----
<1> Define the scenario minion count and rampup.
<2> Start the jackson step to fetch data from the csv file. 
<3> Use the csvToObject method to map csv entries to list of utils.BatteryState object.
<4> Define the header of the csv file.
<5> Define the verification parameters.