
== cassandra plugin

=== Overview
The `cassandra` plugin connects QALIPSIS to https://cassandra.apache.org/_/index.html[APACHE Cassandra].

Technologies addressed::
* Cassandra: https://cassandra.apache.org/_/index.html[APACHE Cassandra]
* Cassandra Query Language: https://cassandra.apache.org/doc/latest/cassandra/cql/index.html[The Cassandra Query Language (CQL)]
* DataStax Driver: https://docs.datastax.com/[DataStax].

Dependency::
`io.qalipsis:plugin-cassandra`

Namespace in scenario::
`cassandra()`

Client library::
DataStax: refer to the https://docs.datastax.com/[DataStax].
+
Datastax is a modern, feature-rich and highly tunable Java client library for Apache Cassandra using Cassandra’s binary protocol and Cassandra Query Language.

Supported steps::
* <<poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves records generated from the input and step context.
* <<Search step,`search`>>: searches records and builds a query from the input and step context.

Example scenarios that use a combination of the supported steps are provided <<Cassandra scenario examples,here>>.

=== Poll step
The `poll` step within the `cassandra` plugin polls the newest records from the database table.

Ancestor::
Scenario or step

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. The `poll` step within the `cassandra` plugin uses a strategy of “delivered at least once."

Notable parameters::
* `connect` (required): configures the connection to https://cassandra.apache.org[APACHE Cassandra]
** `keyspace`(required): the outermost object that determines how data replicates on nodes.
** `datacenterProfile`(required): an execution profile that encapsulates a group of settings associated with individual queries.
* `query` (required): defines the prepared statement to execute when polling.
* `parameters` (optional): binds values to the clauses of the prepared query.
* `tieBreaker` (required): repeats the first column used for sorting and comparison (`<=` or `>=`, depending on the ascending or descending order).
* `pollDelay` (required): specifies the delay between query executions.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `poll` step with a left join operator to verify the values saved by your tested system in the database.
* `query` requires at least one sorting field (`tiebreaker` in the example) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for `tiebreaker` is used to filter out values already received from the database.

Reference documentation::
* Refer to the https://cassandra.apache.org/doc/latest[APACHE Cassandra] documentation further parameter and configuration information.

=== Save step
The `save` step within the `cassandra` plugin persists records into a cassandra database using the save query with Cassandra Query Language (CQL).

Ancestor::
 Step

Functionality::
 The `save` step's input and step context are used to generate documents to save into a table.

Notable parameters::
* `connect` (required): configures the connection to https://cassandra.apache.org[APACHE Cassandra].
** `keyspace`(required): the outermost object that determines how data replicates on nodes.
** `datacenterProfile`(required): an execution profile that encapsulates a group of settings associated with individual queries.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tips::
* Use the `save` after a `collect` step in order to reduce the number of queries executed onto the database and reduce the load your scenario generates on it.
* The `save` step is extremely flexible; table, rows, and columns depend on the context and input value received from the previous step.

Reference documentation:
* Refer to the https://cassandra.apache.org/doc/latest[APACHE Cassandra] documentation for further parameter and configuration information.

=== Search step
The `search` step within the `cassandra` plugin searches records in the database using a search query.

Ancestor::
step

Functionality::
The `search` step’s input and step context are used to complete the search; the list of results is then forwarded to the next step(s).

Notable parameters::
* `connect` (required): configures the connection to  https://cassandra.apache.org[APACHE Cassandra].
** `keyspace`(required): the outermost object that determines how data replicates on nodes.
** `datacenterProfile`(required): an execution profile that encapsulates a group of settings associated with individual queries.
** `query` (required): defines the prepared statement to execute when searching.
* `parameters`: (optional): binds values to the clauses of the prepared query.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tips::
* Use the `search` step after a `collect()` step to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.
* The `query` Parameter may contain ordering clauses.

Reference documentation::
* Refer to the https://cassandra.apache.org/doc/latest[APACHE Cassandra] documentation for further parameter and configuration information.

=== Cassandra scenario examples
The scenarios in this section demo how to save, poll and search data with the plugin for Apache Cassandra.

To start the scenarios:

* Start the container for Apache Cassandra from the <<docker-compose.yml,docker-compose.yml>>  with the command docker-compose up.
* Execute the Gradle task runCampaignForSaveAndPoll with the command gradle :cassandra:runCampaignForSaveAndPoll to see the save and poll scenario in action.
* Execute the Gradle task runCampaignForSaveAndSearch with the command gradle :cassandra:runCampaignForSaveAndSearch to see the save and search scenario in action.

docker-compose.yml::
+
[source,kotlin,linenumbers]
----
version: '3.9' \\docker-compose.yml for cassandra
services:
  cassandra:
    image: cassandra #https://hub.docker.com/_/cassandra
    container_name: cassandra-server
    restart: always
    environment:
      - CASSANDRA_SNITCH=GossipingPropertyFileSnitch
      - "JVM_OPTS=-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.initial_token=0"
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_DC=qalipsis
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
----

==== cassandra-save-and-search
 Save and Search desription here...
  Rework:
  Save and search : Records are saved into the database using the save step, then searched with a query from the same location and compared to the original saved record. 
 
[source,kotlin,linenumbers]
----
class CassandraSaveAndSearch {

    @Scenario
    fun scenarioSaveAndSearch() {  <1>
    
        scenario("") {
            minionsCount = NUMBER_MINION
            rampUp {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson() <2>
            .csvToObject(BatteryState::class) {

                classpath("battery-levels.csv")     <3>
                header {
                    column("deviceId")
                    column("timestamp")
                    column("batteryLevel").integer()
                }
                unicast()
            }
            .map { it.value } <4> 
            .cassandra() <5>
            .save {
                name = "save"

                
                connect {   <6>
                    servers = listOf("localhost:7777", "10.42.42.42:7778")
                    keyspace = "test_keyspace"
                    datacenterName = "test_datacenter"
                }

                table { _, _ ->    <7>
                    TABLE_NAME
                }

                columns { _, _ ->     <8>
                    listOf(
                        BatteryStateContract.COMPANY,
                        BatteryStateContract.DEVICE_ID,
                        BatteryStateContract.TIMESTAMP,
                        BatteryStateContract.BATTERY_LEVEL
                    )
                }

               
                rows { _, input ->     <9>
                    listOf(
                        CassandraSaveRow(
                            "'ACME Inc.'",
                            "'${input.deviceId}'",
                            "'${input.timestamp}'",
                            input.batteryLevel
                        )
                    )
                }
            }
            .search {
                name = "search"

                connect {
                    servers = listOf("localhost:7777", "10.42.42.42:7778")
                    keyspace = "test_keyspace"
                    datacenterName = "test_datacenter"
                }
                query { _, _ ->
                    "SELECT * FROM $TABLE_NAME WHERE ${BatteryStateContract.COMPANY} = ? AND ${BatteryStateContract.DEVICE_ID} = ? AND ${BatteryStateContract.TIMESTAMP} = ?"
                }
                parameters { _, input ->
                    listOf("ACME Inc.", input.input.deviceId, input.input.timestamp)
                }
            }
            .map {
                it.input.input to it.records.first().let { cassandraRecord ->
                    BatteryState(
                        deviceId = cassandraRecord.value[CqlIdentifier.fromCql(BatteryStateContract.DEVICE_ID)] as String,
                        timestamp = cassandraRecord.value[CqlIdentifier.fromCql(BatteryStateContract.TIMESTAMP)] as Instant,
                        batteryLevel = (cassandraRecord.value[CqlIdentifier.fromCql(BatteryStateContract.BATTERY_LEVEL)] as Number).toInt()
                    )
                }
            }
            .verify { result ->
                val savedBatteryState = result.first
                val foundedBatteryState = result.second
                foundedBatteryState.batteryLevel shouldBeExactly savedBatteryState.batteryLevel
            }
    }

}
----
<1> Define the scenario, set the name, number of minions and rampUp strategy.
<2> Start the `jackson` step to fetch data from the csv file, using the `csvToObject` method to map csv entries to list of `utils.BatteryState` object.
<3> Define the header of the csv file.
<4> Transform the output of the CSV reader entries to `utils.BatteryState`
<5> Start the `cassandra` step to save data in `cassandra` database.
<6> Setup the database connection. 
<7> Define the name of the database.
<8> Define the names of the columns of the table.
<9> Create the list of rows to save in the database/create the list of rows to save in database.

==== cassandra-save-and-poll 
Save and poll description ...
Rework: Records are saved into the database using the save step, then retrieved periodically from the same location and compared to the original saved record.

[source,kotlin,linenumbers]
----
    @Scenario
    fun scenarioSaveAndPoll() {

        scenario("cassandra-save-and-poll") {   <1>
            minionsCount = NUMBER_MINION
            rampUp {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson() <2>
            .csvToObject(BatteryState::class) {

                classpath("battery-levels.csv")
                header {  <3>
                    column("deviceId")
                    column("timestamp")
                    column("batteryLevel").integer()
                }
                unicast()
            }
            .map { it.value } <4>
            .cassandra()   <5>
            .save {

                
                connect {  <6>
                    servers = listOf("localhost:7777", "10.42.42.42:7778")
                    keyspace = "test_keyspace"
                    datacenterName = "test_datacenter"
                }

                table { _, _ ->   <7>
                    TABLE_NAME
                }

                
                columns { _, _ ->  <8>
                    listOf(
                        BatteryStateContract.COMPANY,
                        BatteryStateContract.DEVICE_ID,
                        BatteryStateContract.TIMESTAMP,
                        BatteryStateContract.BATTERY_LEVEL
                    )
                }

                rows { _, input ->  <9>
                    listOf(
                        CassandraSaveRow(
                            "'ACME Inc.'",
                            "'${input.deviceId}'",
                            "'${input.timestamp}'",
                            input.batteryLevel
                        )
                    )
                }
            }
            .map { it.input }
            .innerJoin(
                using = { correlationRecord -> correlationRecord.value.primaryKey },
                on = {
                    it.cassandra().poll {
                        connect {
                            servers = listOf("localhost:7777", "10.42.42.42:7778")
                            keyspace = "test_keyspace"
                            datacenterName = "test_datacenter"                           
                        }
                        query("SELECT ${BatteryStateContract.DEVICE_ID}, ${BatteryStateContract.TIMESTAMP}, ${BatteryStateContract.BATTERY_LEVEL} FROM $TABLE_NAME WHERE ${BatteryStateContract.COMPANY} = ? ORDER BY ${BatteryStateContract.TIMESTAMP}")
                        parameters("ACME Inc.")
                        tieBreaker {
                            name = BatteryStateContract.TIMESTAMP
                            type = GenericType.INSTANT
                        }
                        pollDelay(Duration.ofSeconds(1))
                    }
                        .flatten()
                        .map { record ->
                            BatteryState(
                                deviceId = record.value[CqlIdentifier.fromCql(BatteryStateContract.DEVICE_ID)] as String,
                                timestamp = record.value[CqlIdentifier.fromCql(BatteryStateContract.TIMESTAMP)] as Instant,
                                batteryLevel = (record.value[CqlIdentifier.fromCql(BatteryStateContract.BATTERY_LEVEL)] as Number).toInt()
                            )
                        }
                },
                having = { correlationRecord ->
                    correlationRecord.value.primaryKey
                }
            ).configure {
                timeout(5000L)
                report {
                    reportErrors = true
                }
            }
            .filterNotNull()
            .verify { result ->
                val savedBatteryState = result.first
                val foundedBatteryState = result.second!!
                foundedBatteryState.batteryLevel shouldBeExactly savedBatteryState.batteryLevel
            }
    }
----
<1> Define the scenario, set the name, number of minions and the rampUp strategy.
<2> Start the `jackson` step to fetch data from the csv file, using the `csvToObject` method to map csv entries to list of `utils.BatteryState` object.
<3> Define the header of the csv file.
<4> Transform the output of the CSV reader entries to `utils.BatteryState`.
<5> Start the `cassandra` step to save data in `cassandra` database.
<6> Setup the database connection. 
<7> Define the name of the database.
<8> Define the names of the columns of the table.
<9> Create the list of rows to save in the database.
