== elasticsearch plugin

=== Overview
The elasticsearch plugin connects QALIPSIS to https://www.elastic.co/[Elasticsearch].

Technology addressed::
Elasticsearch: https://www.elastic.co/[]

Dependency::
`io.qalipsis:plugin-elasticsearch`

Namespace in scenario::
`elasticsearch()`

Client library::
JAVA API:  refer to  
https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/8.1/connecting.html[Elasticsearch JAVA Client]. 


Supported steps::
* <<poll step,`poll`>>: polls the newest data periodically.
* <<save step,`save`>>: saves a batch records generated from the input and step context.
* <<search step,`search`>>: searches records and builds a query from the input and step context.

<<Elasticsearch examples>> using the supported steps are provided later in this document.

=== Poll step
The `poll` step within the `elasticsearch` plugin periodically polls data from Elasticsearch. The output is a list of `ElasticsearchDocument` containing JSON data or deserialized to objects. 

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. The `poll` step within the elasticsearch plugin uses a strategy of “delivered exactly once”. The output of the `poll` step is an `ElasticsearchDocument` that contains maps of column to values.

Notable parameters::
* `index`: sets the `elasticsearch` indices to use for the queries; defaults to `all`.
* `client`: configures the REST client to connect to https://www.elastic.co/[Elasticsearch].
* `query`: configures the builder for the JSON query to perform the first poll.
* `queryParameters`(optional): adds parameters to the query. 
* `mapper`: configures the JSON Mapper to deserialize the documents.
* `tieBreaker` (required): repeats the first column used for sorting and comparison (`<=` or `>=`, depending on the ascending or descending order).
* `pollDelay` (required): specifies the delay between query executions.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* The `poll` step is generally used in conjunction with a `join` to assert data or inject data into a workflow.
* The `query` parameter requires at least one sorting field (`tiebreaker` in the example) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for `tiebreaker` is used to filter out values already received from the database.
* The output of the `poll` step is an `ElasticsearchDocument` that contains maps of column names to values. If `flatten` is called, the records are provided one by one to the next step; otherwise each poll batch remains complete.

Reference Documentation::
* Refer to
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params[Elasticsearch Query Parameters] for more information on query parameters.
* Refer to the https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after[Elasticsearch] documentation for further parameter and configuration information.

=== Save step 
The `save` step within the `elasticsearch` plugin persists a batch of documents into  https://www.elastic.co/[Elasticsearch].

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate a list of documents that are forwarded to https://www.elastic.co/[Elasticsearch].

Notable Parameters::
* `documentsFactory`: defines the strategy to create documents to save from the input and step context.
* `client`: configures the REST client to connect to https://www.elastic.co/[Elasticsearch].
* `mapper`: configures the JSON Mapper to serialize the documents.
* `monitoring`(optional): configures the monitoring parameters for the step.

Reference Documentation::
Refer to the https://www.elastic.co/guide[Elasticsearch] documentation for further parameter information.

=== Search step
The `search` step within the `elasticsearch` plugin searches documents in the Elasticsearch database using a search query. 

Ancestor::
Step
 
Functionality::
The `search` step’s input and step context are used to generate a query; the batch of results is then forwarded to the next step(s).
 
Notable parameters::
* `client`: configures the REST client to connect to https://www.elastic.co/[Elasticsearch].
* `query`: configures the builder for the JSON query to perform a search. 
* `index`: sets the `elasticsearch` indices to use for the queries; defaults to `all`.
* `queryParameters`(optional): adds parameters to the query. 
* `mapper` configures the JSON Mapper to deserialize the documents.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `fetchAll`: specifies that all the documents have to be fetched, even over the result-sized window;  

Tip::
`fetchAll` must be combined with either a scroll activation or a sorting definition in the query.


Reference Documentation::
* Refer to the https://www.elastic.co/guide[Elasticsearch] documentation for further parameter information.
* For specifics on `queryParameters` refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-paramsElastic[Elasticsearch Query Parameters].
* For specifics on `search` parameters, refer to 
 https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html[Elasticsearch Search Parameters] 


=== Elasticsearch examples

==== elasticsearch-save-and-poll
The `elasticsearch-save-and-poll` scenario saves records into the database using the `save` step, periodically retrieves data from a specified location in the database using the `poll` step, and verifies that the retrieved data matches the original saved record.

[source,kotlin,linenumbers]
----
class ElasticSearchSaveAndPoll {

    private val objectMapper = ObjectMapper().also {
        it.registerModule(JavaTimeModule())
    }

    @Scenario("elasticsearch-save-and-poll")
    fun elasticSearchSaveAndPoll(){

        scenario {
            minionsCount = NUMBER_MINION
            profile {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson()       <1>
            .csvToObject(BatteryState::class) {

                classpath("battery-levels.csv")
                header {     <2>
                    column("deviceId")
                    column("timestamp")
                    column("batteryLevel").integer()
                }
                unicast()
            }
            .map { it.value }  <3> 
            .elasticsearch()
            .save {
                name = "save"
                client {
                    RestClient.builder(HttpHost.create("http://localhost:9200")).build() <4>
                }

                documents { _, input ->
                    listOf(Document(
                        index = BatteryStateContract.INDEX,
                        id = input.primaryKey,
                        source = objectMapper.writeValueAsString(input) <5>
                    ))
                }
            }
            .map { it.input }
            .delay(Duration.ofSeconds(2))     <6> 
            .innerJoinUncasted(
                using = {correlationRecord -> correlationRecord.value.primaryKey },
                on = {
                    it.elasticsearch().poll {
                        name = "poll"
                        client { RestClient.builder(HttpHost.create("http://localhost:9200")).build() }
                        query {
                            """{
                                "query":{
                                    "match_all":{}
                                },
                                "sort" : ["_score"]
                            }""".trimIndent()
                        }
                        index(BatteryStateContract.INDEX)  <7> 
                        pollDelay(Duration.ofSeconds(1))   <8> 
                    }
                        .deserialize(BatteryState::class)  <9> 
                        .flatten()
                        .map{record ->
                            record.value
                        }
                },
                having = {correlationRecord -> (correlationRecord.value as BatteryState).primaryKey}
            )
            .filterNotNull()
            .verify { result ->
                result.asClue {
                    assertSoftly {
                        it.first.batteryLevel shouldBeExactly (it.second as BatteryState).batteryLevel
                    }
                }
            }

    }

}
---- 
<1> Start the jackson step to fetch data from the csv file; use the csvToObject method to map csv entries to list of utils.BatteryState object
<2> Define the header of the csv file.
<3> Transform the output of the CSV reader entries to utils.BatteryState.
<4> Create the rest client that will help submit the request to elasticsearch.
<5> Parse to json the object we want to save.
<6> Input a delay of 2 seconds as elasticsearch's persistence of data is not immediate.
<7> Specify the table from where we want to fetch data.
<8> Pull data every 2 seconds to avoid saturating the server with requests.
<9> Transform your elastic search result to a specific object of your class.

==== elasticsearch-save-and-search
The `elasticsearch-save-and-search` scenario 
saves records into the database using the `save` step, then searches with a query from the same location and verifies that the retrieved data matches the original saved record.

[source,kotlin,linenumbers]
----
class ElasticSearchSaveAndSearch {

    private val objectMapper = ObjectMapper().also {
        it.registerModule(JavaTimeModule())
    }

    @Scenario("elasticsearch-save-and-search")
    fun scenarioSaveAndSearch() {
        scenario {
            minionsCount = NUMBER_MINION
            profile {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson() <1>
            .csvToObject(BatteryState::class) {

                classpath("battery-levels.csv") <2>
                header {
                    column("deviceId")
                    column("timestamp")
                    column("batteryLevel").integer()
                }
                unicast()
            }
            .map { it.value }      <3> 
            .elasticsearch()
            .save {
                name = "save"
                client {
                    RestClient.builder(HttpHost.create("http://localhost:9200"))
                        .build() <4>
                }
                documents { _, input ->
                    listOf(
                        Document(
                            index = "battery-state",
                            id = input.primaryKey,
                            source = objectMapper.writeValueAsString(input) <5> 
                        )
                    )
                }
            }
            .delay(Duration.ofSeconds(2)) <6>
            .elasticsearch()
            .search {
                name = "search"
                client {
                    RestClient.builder(HttpHost.create("http://localhost:9200")).build()
                }
                index { _, _ -> listOf(BatteryStateContract.INDEX) }  <7> 
                query { _, input ->
                    """{
                        "query": {
                            "bool": {
                                "must": [
                                    { "match": { "deviceId": "${input.input.deviceId}" }},
                                    { "term": { "timestamp": ${input.input.timestamp.epochSecond} }}
                                ]
                            }
                        }
                   }"""
                } <8> 
            }
            .deserialize(BatteryState::class) <9>
            .verify { result ->
                val savedBatteryState = result.first.input
                result.second.asClue {
                    assertSoftly {
                        it.results shouldHaveSize 1
                        it.results.first().value.batteryLevel shouldBe savedBatteryState.batteryLevel
                    }
                }
            }

    }

}
----
<1> Start the jackson step to fetch data from the csv file; use the csvToObject method to map csv entries to list of utils.BatteryState object.
<2> Define the header of the csv file.
<3> Transform the output of the CSV reader entries to utils.BatteryState.
<4> Create the rest client that will help submit the request to elasticsearch.
<5> Parse to json the object we want to save.
<6> Input a delay of 2 seconds as elasticsearch's persistence of data is not immediate.
<7> Specify the table from where we want to fetch data.
<8> Create the query that will help get the battery state of a specific id and specific timestamp.
<9> Transform your elastic search result to a specific object of your class.