= Graphite plugin

== Overview
The `https://github.com/graphite-project/graphite-web[Graphite]` plugin connects or supports...
 
Technology addressed::


Dependency::
`io.qalipsis:plugin-graphite`

Namespace in scenario::
`graphite()`

Client library::


Supported steps::
Step1



== Step1

Ancestor::
Scenario
 
Functionality::


Example::
+
[source,kotlin,linenumbers]
----



----

Notable parameters::


Reference documentation::
Refer to the https://github.com/graphite-project/graphite-web/tree/master/docs[Graphite] documentation for further parameter and configuration information. 

 
== Configuration of publication of events and meters to Graphite.
=== Events

Configuration namespace::
`events.export.graphite`

Parameters::
* `enabled`: boolean flag that activates/deactivates event publishing to Graphite; defaults to `false`; *must* be set to `true`.
* `min-level`: minimal accepted level of events; defaults to INFO; allowable values are `EventLevel`values: TRACE, DEBUG, INFO, WARN, ERROR, OFF. 
* `host`(required): defaults to localhost; cannot be blank.
* `port`(required): positive integer; defaults to 2004
* `protocol`: the GraphiteProtocol type; default is PICKLE; available choices are PICKLE PLAINTEXT.
* `batch-size`: maximum number of events buffered between two publications of events to Graphite; positive integer; defaults to `2`.
* `linger-period`: maximum period between two publications of events to Graphite; positive duration; defaults to `10s`.
* `publishers`: maximum number of concurrent publication of events to Graphite; positive integer; defaults to `2`.

=== Meters

Configuration namespace::
`meters.export.graphite`

Parameters::
* `enabled`: boolean flag that activates/deactivates meter publishing to Graphite; defaults to `false`; *must* be set to `true`.
* `host`(required): defaults to localhost; cannot be blank.
* `port`(required): positive integer; defaults to `2004`.
* `step`(optional): The step size (reporting frequency); defaults to `PT10S`.

=== Example
Example::
+
[source,kotlin,linenumbers]
----
events:
  export:
    graphite:
      enabled: true
      min-level: INFO
      host: localhost
      port: 2004
      protocol: pickle
      batch-size: 2
      linger-period: 10s
      publishers: 2


micronaut.metrics.export.graphite.enabled: false <1>

meters:
  export:
    graphite:
      host: localhost
      port: 2004
      enabled: false
      step: PT10S
----
<1> Disables the native micronaut registry.