== graphite plugin

=== Overview

The `https://github.com/graphite-project/graphite-web[Graphite]` plugin connects QALIPSIS to Graphite using the pickle or plaintext protocol.

Technology addressed::

Graphite: https://graphiteapp.org/

Dependency::
`io.qalipsis:plugin-graphite`

Namespace in scenario::
`graphite()`

Client library::
* https://netty.io/[Netty]
* https://ktor.io/[Ktor]

Supported steps::
* <<Poll step,`poll`>>: polls data from Graphite. 
* <<Save step,`save`>>: saves events and records Graphite. 

=== Poll step
The poll step within the the Graphite plugin polls the newest data periodically.

Ancestor::
Scenario or Step

Functionality::  //need input here

Example:: //need appropriate example 

Notable parameters:: // need list of parameters and their definitions


Reference documentation::
Refer to the https://github.com/graphite-project/graphite-web/tree/master/docs[Graphite] documentation for parameter and configuration information. 

=== Save step
The `save` step within the Graphite plugin persists records into a Graphite database using the save query.

Ancestor::
Scenario or Step

Functionality::
The `save` step's input and step context are used to generate documents to save into a table.

Example:: // need appropriate example

Notable parameters:: // need a list of parameters and their definitions.


Reference documentation::
Refer to the https://github.com/graphite-project/graphite-web/tree/master/docs[Graphite] documentation for further parameter and configuration information. 

=== Configuration of publication of events and meters to Graphite.

==== Configuration namespace
Events::
`events.export.graphite`

Meters::
`meters.export.graphite`

==== Example configuration file
[source,kotlin,linenumbers]
----
events:
  export:
    graphite:
      enabled: true
      min-level: INFO
      host: localhost
      port: 2004
      protocol: pickle
      batch-size: 2
      linger-period: 10s
      publishers: 2

meters:
  export:
    graphite:
      host: localhost
      port: 2004
      enabled: true
      step: PT10S
----

Event parameters::
* `enabled` (required): boolean flag that activates/deactivates event publishing to Graphite; defaults to `false`; *must* be set to `true`.
* `min-level` (required): minimal accepted level of events; defaults to INFO; allowed values are `EventLevel` values: `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, `OFF`. 
* `host` (required): defaults to `localhost`; cannot be blank.
* `port` (optional): positive integer; defaults to `2004`
* `protocol` (required): the GraphiteProtocol type; default is PICKLE; available choices are `PICKLE` or `PLAINTEXT`.
* `batch-size` (optional): maximum number of events buffered between two publications of events to Graphite; positive integer; defaults to `2`.
* `linger-period` (optional): maximum period between two publications of events to Graphite; positive duration; defaults to `10s`.
* `publishers` (optional): maximum number of concurrent publication of events to Graphite; positive integer; defaults to `2`.

Meter parameters::
* `enabled` (required): boolean flag that activates/deactivates meter publishing to Graphite; defaults to `false`; *must* be set to `true`.
* `host` (required): defaults to localhost; cannot be blank.
* `port` (optional): positive integer; defaults to `2004`.
* `step` (optional): The step size (reporting frequency); defaults to `PT10S`.