== influxdb plugin

=== Overview

The `influxdb` plugin connects QALIPSIS to https://www.influxdata.com/[InfluxDB].

Technologies addressed::
* InfluxDB: https://www.influxdata.com/[]
* Flux: https://docs.influxdata.com/flux/v0.x/[] 

Dependency::
`io.qalipsis.plugin:qalipsis-plugin-influxdb`

Namespace in scenario::
`influxdb()`

Client library::
influxdb-client-kotlin: refer to the https://github.com/influxdata/influxdb-client-java/tree/master/client-kotlin[influxdb-client-kotlin].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Search step,`search`>>: searches records and builds a query from the input and step context.

Example scenarios using a combination of the `influxdb` supported steps are provided on https://github.com/qalipsis/qalipsis-examples/tree/master/influxdb[GitHub].

=== Poll step 
The `poll` step within the `influxdb()` plugin polls the newest records from the database, with a delay between each execution of a select query.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. The `poll` step within the `influxdb` plugin uses a strategy of “delivered at least once”.

Example::
+
[source,kotlin,linenumbers]
----
influxdb().poll {
    connect {
        server(
            url = "http://localhost:18086",
            bucket = "iot",
            org = "qalipsis"
        )
        basic(user = "DomFisher", password = "Calgary1987")
    }
    query(
        """
        from(bucket:"${iot}")
            |> range(start: -15m)
            |> filter(
                fn: (r) => r._measurement == "battery_state" 
                )               
    """.trimIndent()
    )
    pollDelay(Duration.ofSeconds(1))
}
----

Notable parameters::
* `connect` (required): configures the connection to https://www.influxdata.com/[InfluxDB].
* `query` (required): specifies a query respecting the requirements of https://docs.influxdata.com/influxdb/v2.3/reference/api/[Flux v.2.0]. 
* `parameters` (optional): binds values to the clauses of the prepared query.
* `pollDelay` (required): specifies the delay between query executions.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tip::
Use the `poll` step with a join operator to verify the values that the tested system saves to the database.

Reference: Documentation::
Refer to the https://docs.influxdata.com/[InfluxDB] documentation for further parameter and configuration information.
 
=== Save step
The `save` step within the `influxdb()` plugin persists a batch of records into the `influxdb` bucket using a specific `points` class.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate the bucket, the list of points with their measurement, and tags and fields, which are then combined and forwarded to the database.

Example::
+
[source,kotlin,linenumbers]
----
.save {
    connect {
        server(
            url =  "http://localhost:18086",
            bucket = "iot",
            org = "qalipsis"
        )
        basic(user = "DomFisher", password = "Calgary1987")
    }
    query {
        bucket = { _, _ -> "iot" }
        organization = { _, _ -> "qalipsis" }
        points = { _, input ->
            listOf(
                Point.measurement("battery_state")
                    .addField("battery_level", input.batteryLevel)
                    .addTag("device_id", input.deviceId)
                    .addTag("timestamp", input.timestamp.epochSecond.toString())
            )
        }
    }
}
----
Notable parameters::
* `connect` (required): configures the connection to https://www.influxdata.com/[InfluxDB].
* `monitoring`(optional): configures the monitoring parameters for the step.

Tips::
* Use the `save` step after a `collect` step to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.
* The `save` step is extremely flexible: bucket, tags, measurement and fields might depend on the context and input value received from the previous step.

Reference documentation::
Refer to the https://docs.influxdata.com/[InfluxDB] documentation for further parameter and configuration information.

=== Search step 
The `search` step within the `influxdb` plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The `search` step's input and step context are used to generate a query; the batch of results is then forwarded to the next step(s).


Example::
[source,kotlin,linenumbers]
----
.influxdb()
.search {
    connect {
        server(
            url = "http://localhost:18086",
            bucket = "iot",
            org = "qalipsis"
        )
        basic(user = "DomFisher", password = "Calgary1987")
    }
    query { _, input ->
        """
            from(bucket: "${iot}")
                    |> range(start: -15m)
                    |> filter(
                        fn: (r) => r._measurement == "${"battery_state"}" and
                            r.${"device_id"} == "${input.deviceId}" and
                            r.${"timestamp"} == "${input.timestamp.epochSecond}"
                        )               
        """.trimIndent()
    }
}
----

Notable parameters::
* `search`: generates the search query from the step input and context.
* `connect` (required): configures the connection to https://www.influxdata.com/[InfluxDB]. 
* `monitoring`(optional): configures the monitoring parameters for the step.

Tip::
Use the `search` step after a `collect` step to reduce the number of queries executed onto the database and to reduce the load the scenario generates on the test system.

Reference documentation::
Refer to the https://docs.influxdata.com/[InfluxDB] documentation for further parameter and configuration information.
