== kafka Plugin

=== Overview
The `kafka` plugin connects QALIPSIS to an https://kafka.apache.org/[APACHE Kafka] cluster.
 
Technology Addressed::
Kafka: https://kafka.apache.org/[]

Dependency::
`io.qalipsis:plugin-kafka`

Namespace in Scenario::
`kafka()`

Client Library::
Kafka: refer to https://kafka.apache.org/[Apache Kafka]
+

Supported Steps::
* <<Consume Step,`consume`>>: consumes data from topics of an Apache Kafka cluster.
* <<Produce Step,`produce`>>: pushes data to topics of the Apache Kafka cluster.

=== Consume Step
The `consume` step within the `kafka` plugin polls data from topics of an Apache Kafka cluster and forwards the data to the next step, either in batches or individually.

This step is generally used in conjunction with a left join to assert data or inject data into a workflow.

The `consume` step supports multithreading (concurrent consumers) using the `concurrency` property.

Ancestor::
Scenario
 
Functionality::
The `consume` step starts a polling loop for the designated `client`, using the provided subscription `topics` name, or `topicsPattern` and `groupId`. When new records appear, `consume` polls them and sends them to the next step(s). 

Example::
+
[source,kotlin,linenumbers]
----
kafka().consume {
   name = "kafka-consumer"
   bootstrap(bootstrap)
   topics(testProducerTopic)
   groupId("kafka-left")
   pollTimeout(100)
   offsetReset(OffsetResetStrategy.EARLIEST)
}
----
 
Notable Parameters::
* `bootstrap`: configures the bootstrap hosts of the `Kafka` cluster; defaults to localhost:9092.
* `groupId`: defines the consumer group.
* `pollTimeout` defines the consumer poll timeout to wait for records; defaults to 1 second.
* `offsetReset` (required): defines the strategy to apply when the consumer starts consuming messages from the queue. 
* `maxPolledRecords`: defines the maximum number of records returned in a unique poll batch; defaults to 500.
* `pollDelay` (required): specifies the delay between query executions.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `consume` step with a left join to assert data or inject data into a workflow.
* Valid `offsetReset` strategies are:
** `OffsetResetStrategy.EARLIEST`: starts consuming messages from the beginning of the queue.
** `OffsetResetStrategy.LATEST`: starts consuming messages when the  consumer starts, ignoring all previous messages in the queue.
+
`OffsetResetStrategy.LATEST` is the default. 
* Refer to the https://kafka.apache.org/[APACHE KAFKA] documentation for further parameter and configuration information. 
 
=== Produce Step
The `produce` step within the `kafka` plugin pushes data onto topics of the Kafka broker and forwards the data as input to the next step.

Ancestor::
Scenario
 
Functionality::
The `produce` step's input and step context are used to generate values to complete the step. The batch of results, or a single result, is then forwarded to the next step(s).

Example::
+
[source,kotlin,linenumbers]
----
kafka().produce(
   Serdes.ByteArray().serializer(),
   Serdes.String().serializer()
) {
   name = "kafka-producer"
   bootstrap(bootstrap)
   clientName("producer")
   records { _, input ->
       listOf(
           KafkaProducerRecord(
               topic = producerTopic,
               value = "Produced ${input.record.value!!}"
           )
       )
   }
        monitoring {
            events = true
            meters = false
        }
}
----
 
Notable Parameters::
* `Serdes.ByteArray().serializer()`: describes how to serialize the record keys to send  to `kafka`.
* `Serdes.String().serializer()`: describes how to serialize the record values to send to `kafka`.
* `bootstrap` configures the bootstrap hosts of the Kafka cluster; defaults to `localhost:9092`.
* `clientName` defines the name of the `kafka` client
* `records` (required): generates and configures a list of produced records.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tip::
* Refer to the https://kafka.apache.org/documentation/[APACHE KAFKA] documentation for further parameter and configuration information. 