= Kafka plugin

== Overview
The Kafka plugin connects QALIPSIS to an https://kafka.apache.org/[APACHE Kafka] cluster.
 
Technology addressed::
Kafka: https://kafka.apache.org/[]

Dependency::
`io.qalipsis:plugin-kafka`

Namespace in scenario::
`kafka()`

Client library::
Kafka: refer to https://kafka.apache.org/[Apache Kafka]

Supported steps::
* <<Consume step,`consume`>>: consumes data from topics of an Apache Kafka cluster.
* <<Produce step,`produce`>>: pushes data to topics of the Apache Kafka cluster.
+
An example scenario that uses a combination of the supported steps is provided on https://github.com/qalipsis/qalipsis-examples/tree/master/kafka[GitHub].

== Consume step
The `consume` step within the Kafka plugin polls data from topics of an Apache Kafka cluster and forwards the data to the next step, either in batches or individually. The `consume` step:

* is generally used in conjunction with a left join to assert data or inject data into a workflow.
* supports multithreading (concurrent consumers) using the `concurrency` property.

Ancestor::
Scenario
 
Functionality::
The `consume` step starts a polling loop for the designated `client`, using the provided subscription `topics` name, or `topicsPattern` and `groupId`. When new records appear, `consume` polls them and sends them to the next step(s). 

Example::
+
[source,kotlin,linenumbers]
----
kafka().consume {  
    bootstrap("localhost:9092")
    topics("battery_state")  
    group-id("kafka-example")
    offset-reset(OffsetResetStrategy.EARLIEST) 
    poll-timeout(Duration.ofSeconds(1))
}
----

Notable parameters::
* `bootstrap`: configures the bootstrap hosts of the Kafka cluster; defaults to localhost:9092.
* `group-id`: defines the consumer group.
* `poll-timeout` defines the consumer poll timeout to wait for records; defaults to 1 second.
* `offset-reset` (required): defines the strategy to apply when the consumer starts consuming messages from the queue. 
* `poll-delay` (required): specifies the delay between query executions.
* `max-polled-records`(optional): defines the maximum number of records returned in a unique poll batch; defaults to 500.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `consume` step with a left join to assert data or inject data into a workflow.
* Valid `offset-reset` strategies are:
** `Offset-reset-strategy.EARLIEST`: starts consuming messages from the beginning of the queue.
** `Offset-reset-strategy.LATEST`: starts consuming messages when the  consumer starts, ignoring all previous messages in the queue.
+
`Offset-reset-strategy.LATEST` is the default. 

Reference documentation::
Refer to the https://kafka.apache.org/[Apache KAFKA] documentation for further parameter and configuration information. 
 
== Produce step

The `produce` step within the Kafka plugin pushes data onto topics of the Kafka broker and forwards the data as input to the next step.

Ancestor::
Scenario
 
Functionality::
The `produce` step's input and step context are used to generate values to complete the step. The batch of results, or a single result, is then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
            .kafka()
            .produce(
                key-serializer = Serdes.String().serializer(),
                value-serializer = Serdes.String().serializer()
            ) {
                bootstrap("localhost:9092")
                client-name("producer")
                records { _, input ->
                    list-of(
                        Kafka-producer-record(
                            server-configuration.TOPIC,
                            value = object-mapper.write-value-as-string(input),
                            key = input.primary-key
                        )
                    )
                }
            }
----

Notable parameters::
* `key-serializer`: describes how to serialize the record keys to send  to Kafka.
* `value-serializer`: describes how to serialize the record values to send to Kafka.
* `bootstrap` configures the bootstrap hosts of the Kafka cluster; defaults to `localhost:9092`.
* `client-name` defines the name of the Kafka client.
* `records` (required): generates and configures a list of produced records.

Reference documentation::
Refer to the https://kafka.apache.org/documentation/[Apache Kafka] documentation for further parameter and configuration information. 

== Configuration of publication of events and meters to Kafka
=== Events

Configuration namespace::
`events.export.kafka`

Parameters::
* `enabled`: boolean flag that activates/deactivates event publishing to Kafka; defaults to `false`; *must* be set to `true`.
* `min-level`: minimal accepted level of events; defaults to INFO; allowable values are `EventLevel`values: TRACE, DEBUG, INFO, WARN, ERROR, OFF. 
* `bootstrap`: bootstraps (string of host and port pair) of the Kafka broker; defaults to `localhost:9092`.
* `topic`: string name of the topic to write the events to; defaults to `qalipsis-events`.
* `duration-as-nano`: boolean flag that activates/deactivates converting the duration to nanoseconds; defaults to `false` (converts to milliseconds).
* `linger-period`: maximum period between two publications of events to Kafka; positive duration; defaults to `10s`.
* `batch-size`: maximum number of events buffered between two publications of events to Kafka; positive integer; defaults to `2`.
* `configuration`: key, value configuration parameters of type `Properties`, for the Kafka producer.

=== Meters
Configuration namespace::
`meters.export.kafka`

Parameters::
* `enabled`: boolean flag that activates/deactivates meter publishing to Kafka; defaults to `false`; *must* be set to `true`.
* `step`: The step size (reporting frequency); defaults to `PT10S`.
* `bootstrap.servers`: bootstraps (string of host and port pair) of the Kafka broker; defaults to `localhost:9092`.
* `topic`: string name of the topic to write events to; defaults to `qalipsis-meters`.
* `linger.ms`: maximum period between two batches of events; positive duration; defaults to `5000`.
* `batch-size`: maximum number of events buffered between two publications of events to Kafka; positive integer; defaults to `800000` (in bytes).
* `delivery.timeout.ms`: maximum integer value in milliseconds before time out.; defaults to `10000`.
* `configuration`: key, value configuration parameters of type `Properties`, for the Kafka producer.

=== Example
[source,kotlin,linenumbers]
----
meteventsers:
  export:
    kafka:
      enabled: false
      bootstrap`: localhost:9092
      topic: qalipsis-events
      duration-as-nano: false
      linger-period: 10s
      batch-size: 2
      configuration:
        delivery.timeout.ms: 10000

  export:
    kafka:
      enabled: false
      step: PT10S
      bootstrap.servers: localhost:9092
      topic: qalipsis-meters
      linger.ms: 5000
      batch-size: 800000 # In bytes.
      configuration:
        delivery.timeout.ms: 10000
----  