== kafka plugin

=== Overview
The `kafka` plugin connects QALIPSIS to an https://kafka.apache.org/[APACHE Kafka] cluster.
 
Technology addressed::
Kafka: https://kafka.apache.org/[]

Dependency::
`io.qalipsis:plugin-kafka`

Namespace in scenario::
`kafka()`

Client library::
Kafka: refer to https://kafka.apache.org/[Apache Kafka]
+

Supported steps::
* <<Consume step,`consume`>>: consumes data from topics of an Apache Kafka cluster.
* <<Produce step,`produce`>>: pushes data to topics of the Apache Kafka cluster.

An Example scenarios that use a combination of the supported steps is provided <<kafka-produce-and-consume scenario example,here>>.

=== Consume step
The `consume` step within the `kafka` plugin polls data from topics of an Apache Kafka cluster and forwards the data to the next step, either in batches or individually.

This step is generally used in conjunction with a left join to assert data or inject data into a workflow.

The `consume` step supports multithreading (concurrent consumers) using the `concurrency` property.

Ancestor::
Scenario
 
Functionality::
The `consume` step starts a polling loop for the designated `client`, using the provided subscription `topics` name, or `topicsPattern` and `groupId`. When new records appear, `consume` polls them and sends them to the next step(s). 
 
Notable parameters::
* `bootstrap`: configures the bootstrap hosts of the `Kafka` cluster; defaults to localhost:9092.
* `groupId`: defines the consumer group.
* `pollTimeout` defines the consumer poll timeout to wait for records; defaults to 1 second.
* `offsetReset` (required): defines the strategy to apply when the consumer starts consuming messages from the queue. 
* `maxPolledRecords`: defines the maximum number of records returned in a unique poll batch; defaults to 500.
* `pollDelay` (required): specifies the delay between query executions.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `consume` step with a left join to assert data or inject data into a workflow.
* Valid `offsetReset` strategies are:
** `OffsetResetStrategy.EARLIEST`: starts consuming messages from the beginning of the queue.
** `OffsetResetStrategy.LATEST`: starts consuming messages when the  consumer starts, ignoring all previous messages in the queue.
+
`OffsetResetStrategy.LATEST` is the default. 

Reference documentation::
* Refer to the https://kafka.apache.org/[APACHE KAFKA] documentation for further parameter and configuration information. 
 
=== Produce step
The `produce` step within the `kafka` plugin pushes data onto topics of the Kafka broker and forwards the data as input to the next step.

Ancestor::
Scenario
 
Functionality::
The `produce` step's input and step context are used to generate values to complete the step. The batch of results, or a single result, is then forwarded to the next step(s).

 
Notable parameters::
* `Serdes.ByteArray().serializer()`: describes how to serialize the record keys to send  to `kafka`.
* `Serdes.String().serializer()`: describes how to serialize the record values to send to `kafka`.
* `bootstrap` configures the bootstrap hosts of the Kafka cluster; defaults to `localhost:9092`.
* `clientName` defines the name of the `kafka` client
* `records` (required): generates and configures a list of produced records.
* `monitoring`(optional): configures the monitoring parameters for the step.

Reference documentation::
* Refer to the https://kafka.apache.org/documentation/[APACHE KAFKA] documentation for further parameter and configuration information. 

===Kafka scenario example
=== produce-and-consume
The example in this section deomonstrates how to produce and consume data using the APACHE `plugin`. 
Reowrk: 
The producer sends `BatteryState` data on a topic and the consumer read it periodically then compared to the original send data.

[source,kotlin,linenumbers]
----
class KafkaProduceAndConsume {

    private val objectMapper = ObjectMapper().also {
        it.registerModule(JavaTimeModule())
    }

    @Scenario("kafka-produce-and-consume")
    fun scenarioSaveAndPoll() {
        scenario {  <1>
            minionsCount = ServerConfiguration.NUMBER_MINION
            profile {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson()  <2>
            .csvToObject(BatteryState::class) {

                classpath("battery-levels.csv")
                // we define the header of the csv file
                header {
                    column("deviceId")
                    column("timestamp")
                    column("batteryLevel").integer()
                }
                unicast()
            }
            .map { it.value } <3>
            .kafka()
            .produce(
                keySerializer = Serdes.String().serializer(),
                valueSerializer = Serdes.String().serializer()
            ) {
                bootstrap(ServerConfiguration.SERVER_BOOTSTRAP)
                clientName("producer")
                records { _, input ->
                    listOf(
                        KafkaProducerRecord(
                            ServerConfiguration.TOPIC,
                            value = objectMapper.writeValueAsString(input),
                            key = input.primaryKey
                        )
                    )
                }
            }
            .map { it.input }
            .innerJoin(
                using = { correlationRecord ->
                    correlationRecord.value.primaryKey
                },
                on = {
                    it.kafka().consume {  <4>
                        bootstrap(ServerConfiguration.SERVER_BOOTSTRAP)
                        topics(ServerConfiguration.TOPIC)  
                        groupId("kafka-example")
                        offsetReset(OffsetResetStrategy.EARLIEST) 
                        pollTimeout(Duration.ofSeconds(1))
                    }
                        .flatten(Serdes.String().deserializer(), jsonSerde<BatteryState>().deserializer())
                        .map { result ->
                            result.record.value
                        }
                        .filterNotNull()
                },
                having = { correlationRecord ->
                    correlationRecord.value.primaryKey
                }
            )
    }

}
----
<1> Define the scenario, set the name, number of minions and rampUp.
<2> Start the jackson step to fetch data from the csv file; use the csvToObject method to map csv entries to list of utils.BatteryState object.
<3> Transform the output of the CSV reader entries to utils.BatteryState.
<4> Configure the `consume` step; define the `topics`, `groupId`, `offsetReset` strategy (EARLIEST starts consuming messages from the beginning of the queue), and `pollTimeout` duration.


To start the scenario:

1. Create a `docker-compose.yml` file in the project folder.
+
[source,kotlin,linenumbers]
----
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
----    
[start=2] 
. Start the container for Apache Kafka from the <<docker-compose.yml,`docker-compose.yml`>> with the command `docker-compose up`

. Execute the Gradle task `runCampaignForProduceAndConsume` with the command `gradle :kafka:runCampaignForProduceAndConsume` to see the produce and consume scenario in action.


