== TimescaleDB plugin

=== Overview
The TimescaleDB plugin connects QALIPSIS to https://docs.timescale.com/timescaledb/latest[TimescaleDB].

Technology addressed::
* PSQL: https://www.postgresql.org/
* TimescaleDB: https://www.timescale.com/

Dependency::
`io.qalipsis:plugin-timescaledb`
Namespace in scenario::
`timescaledb()`
Client library::
https://docs.timescale.com/keywords/Toolkit/

=== Configuration of publication of events and meters to TimescaleDB.

==== Configuration namespace

Events::
`events.export.timescaledb`

Meters::
`meters.export.timescaledb`

==== Example configuration file
[source,kotlin,linenumbers]
----
events:
  export:
    timescaledb:
      enabled: true
      min-level: INFO
      host: localhost
      port: 5432
      database: qalipsis
      schema: events
      linger-period: 10s
      batch-size: 20000
      publishers: 1
      username: qalipsis_user
      password: qalipsis-pwd

meters:
  export:
    timescaledb:
      enabled: true
      host: localhost
      port: 5432
      database: qalipsis
      schema: meters
      username: qalipsis_user
      password: qalipsis-pwd
      step: PT10S
----      
Event Parameters::
* `enabled` (required): boolean flag that activates/deactivates event publishing to TimescaleDB; defaults to `false`; *must* be set to `true`.
* `min-level` (required): minimum accepted level of events; defaults to INFO; allowable values are `EventLevel`values: TRACE, DEBUG, INFO, WARN, ERROR, OFF; cannot be null.
* `host`  (required): defaults to localhost; cannot be blank.
* `port` (required): positive integer; defaults to `5432`.
* `database` (required): string name of the database; defaults to `qalipsis`; cannot be blank.
* `schema` (required): string name of the schema; defaults to `events`; cannot be blank.
* `linger-period` (optional): maximum period between publication of events to TimescaleDB; positive duration, defaults to `10s`.
* `batch-size` (optional): maximum number of events buffered between two publications of events toTimescaleDB; positive integer; defaults to `2000`.
* `publishers` (optional): number of concurrent publication of events that can run; positive integer; defaults to `1` (no concurrency).
* `username` (optional): name of the user for basic authentication when connecting to TimescaleDB; defaults to `qalipsis_user`.
* `password` (optional): password of the user for basic authentication when connecting to TimescaleDB; defaults to `qalipsis_pwd`.

Meter Parameters::
* enabled` (required): boolean flag that activates/deactivates meter publishing to TimescaleDB; defaults to `false`; *must* be set to `true`.
* `host` (required): defaults to localhost; cannot be blank.
* `port` (required): positive integer; defaults to `5432`.
* `database` (required): string name of the database; defaults to `qalipsis`; cannot be blank.
* `schema` (required): string name of the schema; defaults to `events`; cannot be blank.
* `username` (optional): name of the user for basic authentication when connecting to TimescaleDB; defaults to `qalipsis_user`.
* `password` (optional): password of the user for basic authentication when connecting to TimescaleDB; defaults to `qalipsis_pwd`.
* `step` (optional): the step size (reporting frequency); defaults to `PT10S`.