== r2dbc-jasync plugin

=== Overview
The `r2dbc-jasync` plugin connects QALIPSIS to https://mariadb.org/[MariaDB], https://www.mysql.com[MySQL] and https://www.postgresql.org/[PostgreSQL].

Technologies addressed::
* MariaDB: https://mariadb.org/[]

* MySQL: https://www.mysql.com[]

* PostgreSQL: https://www.postgresql.org/[]

Dependency::
`io.qalipsis:plugin-r2dbc-jasync`

Namespace in scenario::
`r2dbcJasync()`

Client library::
Jasync-sql: refer to https://github.com/jasync-sql/jasync-sql[jasync-sql]
+
Jasync-sql is an asynchronous database driver for PostgreSQL and MySQL written in kotlin.

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Search step,`search`>>: searches records and builds a query from the input and step context.

Example scenarios using a combination of `r2dbc-jasync` supported steps are provided <<r2dbc-jasync scenario examples,here>>.

=== Poll step 
The `poll` step within the `r2bc-jasync` plugin polls the newest records from the database, respecting a delay between each execution of a select query.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called. The `poll` step within the `r2b-jaysync` plugin uses a strategy of “delivered at least once”.

Notable parameters::
* `connection` (required): specifies the connection parameters. 
* `query` (required): specifies a query respecting the requirements of the target database (https://mariadb.org/[MariaDB],  https://www.mysql.com[MySQL], https://www.postgresql.org/[PostgreSQL],).
* `parameters` (optional): binds values to the clauses of the prepared query.
* `pollDelay` (required): specifies the delay between query executions.
`tieBreaker` (required): repeats the first column used for sorting and comparison ( `<=` or `>=`, depending on the ascending or descending order).
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `poll` step with a join operator when you need to verify the values saved by your tested system in the database.
* `query` requires at least one sorting field (known as `tiebreaker` in the example) to filter the newest results and not fetch the same records repeatedly.
* The latest known value for the `tiebreaker` is used to filter out the values already received directly from the database.

Reference documentation::
Refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] for further parameter and configuration information.

=== Save step 
The `save` step within the `r2bc-jasync` plugin persists a batch of records into an SQL table using a prepared statement.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate the table and the list of columns and their values, which are then combined and forwarded to the database.

Notable parameters::
* `connection` (required): specifies the connection parameters. 
* `monitoring`(optional): configures the monitoring parameters for the step.

Tips::
* Use the `save` step after a `collect()` step in order to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.
* The `save` step is extremely flexible; table, columns and values might depend on the context and input value received from the previous step.

Reference documentation::
Refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] for further parameter and configuration information.

=== Search step 
The `search` step within the `r2bc-jasync` plugin searches records in the database using a search query.

Ancestor::
Step

Functionality::
The `search` step’s input and step context are used to generate a prepared statement and the values to complete it; the batch of results is then forwarded to the next step(s).

Notable parameters::
* `connection` (required): specifies the connection parameters.
* `query`: generates a prepared statement from the step's context and input.
* `parameters` (optional): binds values to the clauses of the prepared query.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tip::
Use the `search` step after a `collect` step in order to reduce the number of queries executed onto the database and to reduce the load your scenario generates on the test system.

Reference documentation::
Refer to https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections[Configuring and Managing Connections] for further parameter and configuration information.

=== r2dbc-jasync scenario examples

==== r2dbc-jasync-save-and-poll
The example `r2dbc-jasync-save-and-poll` scenario saves records into the database using the `save` step, periodically retrieves data from a specified location in the database using the `poll` step, and verifies that the retrieved data matches the original saved record.
[source,kotlin]
----
class R2dbcJasyncSaveAndPoll {
   
    private val objectMapper = ObjectMapper().also {
        it.registerModule(JavaTimeModule())
    }
    private val databaseConfiguration = PostgresDatabaseConfiguration()
    @Scenario("r2dbc-jasync-save-and-poll")
    fun r2dbcJasyncSaveAndPoll() {
        scenario {
            minionsCount = ScenarioConfiguration.NUMBER_MINION
            profile {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson() <1> 
            .csvToObject(BatteryState::class) {
                classpath("battery-levels.csv")

                header { <2>
                    column("device_id")
                    column("timestamp")
                    column("battery_level").integer()
                }
                unicast()
            }
            .map { it.value }
            .r2dbcJasync()   <3> 
            .save {
                protocol(Protocol.POSTGRESQL)
                connection {
                    database = databaseConfiguration.databaseName
                    port = databaseConfiguration.port
                    username = databaseConfiguration.userName
                    password = databaseConfiguration.password
                }
                tableName { _, _ ->
                    databaseConfiguration.tableName
                }
                columns { _, _ ->
                    listOf(
                        BatteryStateContract.ID,
                        BatteryStateContract.DEVICE_ID,
                        BatteryStateContract.TIMESTAMP,
                        BatteryStateContract.BATTERY_LEVEL
                    )
                }
                values { _, input ->
                    listOf(
                        JasyncSaveRecord(
                            input.primaryKey(),
                            input.deviceId,
                            input.timestamp.epochSecond,
                            input.batteryLevel
                        )
                    )
                }
                monitoring {
                    events = false
                    meters = true
                }
            }
            .map {
                it.input
            }
            .innerJoin(
                using = { correlationRecord ->
                    correlationRecord.value.primaryKey()
                },
                on = {
                    it.r2dbcJasync().poll {
                        protocol(Protocol.POSTGRESQL)
                        connection {
                            database = databaseConfiguration.databaseName
                            port = databaseConfiguration.port
                            username = databaseConfiguration.userName
                            password = databaseConfiguration.password
                        }
                        query("select * from ${databaseConfiguration.tableName} order by \"${BatteryStateContract.TIMESTAMP}\"")
                        pollDelay(Duration.ofSeconds(1))
                    }
                        .flatten()
                        .map { record ->
                            objectMapper.convertValue(record.value, BatteryState::class.java)
                        }
                },
                having = { correlationRecord ->
                    correlationRecord.value.primaryKey()
                }
            )
            .filterNotNull()
            .verify { result ->
                result.asClue {
                    assertSoftly {
                        it.first.batteryLevel shouldBeExactly it.second.batteryLevel
                    }
                }
            }
    }
}
----
<1> Start the `jackson` `csvToObject` step to fetch data from the csv file and map the csv entries to a list of `utils.BatteryState` objects.
<2> Define the header of the csv file.
<3> Transform the output of the CSV reader entries to `utils.BatteryState`.

==== r2dbc-jasync-save-and-search
The example  `r2dbc-jasync-save-and-search` scenario saves records into the database using the `save` step, queries a specific location in the database using the search step, and verifies that the retrieved data matches the original saved record.

[source,kotlin]
----
class R2dbcJasyncSaveAndSearch {
    
    private val objectMapper = ObjectMapper().also {
        it.registerModule(JavaTimeModule())
    }
    private val databaseConfiguration = MariaDBDatabaseConfiguration()
    @Scenario("r2dbc-jasync-save-and-search")
    fun r2dbcJasyncSaveAndPoll() {
        scenario {
            minionsCount = ScenarioConfiguration.NUMBER_MINION
            profile {
                regular(periodMs = 1000, minionsCountProLaunch = minionsCount)
            }
        }
            .start()
            .jackson() <1>
            .csvToObject(BatteryState::class) {
                classpath("battery-levels.csv")
                header {  <2>
                    column("device_id")
                    column("timestamp")
                    column("battery_level").integer()
                }
                unicast()
            }
            .map { it.value }
            .r2dbcJasync()  <3> 
            .save {
                protocol(Protocol.MARIADB)
                connection {
                    database = databaseConfiguration.databaseName
                    port = databaseConfiguration.port
                    username = databaseConfiguration.userName
                    password = databaseConfiguration.password
                }
                tableName { _, _ ->
                    databaseConfiguration.tableName
                }
                columns { _, _ ->
                    listOf(
                        BatteryStateContract.ID,
                        BatteryStateContract.DEVICE_ID,
                        BatteryStateContract.TIMESTAMP,
                        BatteryStateContract.BATTERY_LEVEL
                    )
                }
                values { _, input ->
                    listOf(
                        JasyncSaveRecord(
                            input.primaryKey(),
                            input.deviceId,
                            input.timestamp.epochSecond,
                            input.batteryLevel
                        )
                    )
                }
                monitoring {
                    events = false
                    meters = true
                }
            }
            .map { it.input }
            .r2dbcJasync()
            .search {
                protocol(Protocol.MARIADB)
                connection {
                    database = databaseConfiguration.databaseName
                    port = databaseConfiguration.port
                    username = databaseConfiguration.userName
                    password = databaseConfiguration.password
                }
                query { _, _ ->
                    val request = "SELECT DISTINCT * from ${databaseConfiguration.tableName} where ${BatteryStateContract.TIMESTAMP} = ? AND ${BatteryStateContract.DEVICE_ID} = ?"
                    request
                }
                parameters { _, input ->
                    listOf(input.timestamp.epochSecond, input.deviceId)
                }
            }
            .map {
                it.input to it.records.map { record ->
                    objectMapper.convertValue(
                        record.value,
                        BatteryState::class.java
                    )
                }
            }
            .verify { result ->
                result.asClue {
                    assertSoftly {
                        result.second.size shouldBeExactly 1
                        result.first.batteryLevel shouldBeExactly result.second.first().batteryLevel
                    }
                }
            }
    }
}

----
<1> Start the `jackson` `csvToObject` step to fetch data from the csv file and map the csv entries to a list of `utils.BatteryState` objects.
<2> Define the header of the csv file.
<3> Transform the output of the CSV reader entries to `utils.BatteryState`.