= RabbitMQ plugin

== Overview
The RabbitMQ plugin connects QALIPSIS to the https://www.rabbitmq.com/[RabbitMQ] broker.

Technology addressed::
 RabbitMQ: https://www.rabbitmq.com/[]

Dependency::
 `io.qalipsis:plugin-rabbitmq`
 
Namespace in scenario::
 `rabbitmq()`

Client library::
RabbitMQ: refer to https://www.rabbitmq.com/[rabbitMQ]

Supported steps::
* <<Consume step,`consume`>>: polls data from the RabbitMQ broker.
* <<Produce step,`produce`>>: pushes data to the RabbitMQ broker.
+
An example scenario that uses a combination of the supported steps is provided on https://github.com/qalipsis/qalipsis-examples/tree/master/rabbitmq[GitHub].

== Consume step
The `consume` step within the RabbitMQ plugin consumes data from queues of the RabbitMQ broker and forwards the data to the next step.

This step is generally used in conjunction with `join` to assert data or inject data into a workflow.

This step supports multithreading concurrent consumers using  the `concurrency()` property.  When the concurrency is set to more than 1, the sequence of the records transmitted to the next step in no longer guaranteed.
 
To learn more, visit the https://www.rabbitmq.com/#getstarted[RabbitMQ] website.

Ancestor::
Scenario
 
Functionality::
The `consume` step starts a polling loop for consumption of the designated queue.  As new records appear, `consume` polls them and sends them to the next step.

Example::
+
[source,kotlin,linenumbers]
----
rabbitmq().
  consume {
    queue("user")
    connection {
      host = "localhost"
      port = 5672
      password = "Ceila1995"
      username = "PaulSmith"
    }
    concurrency(2)
    prefetchCount (11)
}
----
Notable parameters::
* `queue`: defines the name of the queue to consume.
* `connection`: configures the connection to the RabbitMQ broker; defaults to `localhost:5672`
* `concurrency:` defines the number of concurrent channels producing messages to RabbitMQ; defaults to 1.
* `prefetchCount`: defines the prefetch count value; defaults to 10. 
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tip::
Use the `consume` step with `join` to assert data or inject data into a workflow.

Reference documentation::
* Learn more about `prefetchCount` by reading the  https://www.rabbitmq.com/consumer-prefetch.html[RabbitMQ Prefetch] documentation.
* To configure the `consume` step, consult the https://www.rabbitmq.com/documentation.html[rabbitMQ] documentation.

== Produce step 
The `produce` step within the RabbitMQ plugin provides messages to the RabbitMQ broker using a query; the messages are then forwarded as input to the next step.

Ancestor::
Scenario
 
Functionality::
The `produce` step's input and step context are used to generate the values to complete the step; results are then forwarded to the next step(s).

Example::
[source,kotlin,linenumbers]
----
.rabbitmq()
.produce {
    connection {
      host = "localhost"
      port = 5672
      password = "Ceila1995"
      username = "PaulSmith"

    }
    records { _, input ->
        listOf(
            RabbitMqProducerRecord(
                exchange = "battery_state",
                routingKey = "battery_state",
                props = null,
                value = objectMapper.writeValueAsBytes(input)
            )
        )
    }
}
----

Notable parameters::
* `concurrency`(optional): defines the number of concurrent channels producing messages to RabbitMQ; defaults to `1`.
* `connection`: configures the connection to the RabbitMQ broker; defaults to `localhost:5672`.
* `records`: configures and generates a list of produced records.

Reference documentation:: 
* For more information on configuring the connection to RabbitMQ, refer to  https://www.rabbitmq.com/api-guide.html#connecting[Connecting to RabbitMQ].
* For more information on configuring the `produce` step, refer to the https://www.rabbitmq.com/documentation.html[RabbitMQ] documentation.