= Redis-lettuce plugin

The Redis-lettuce plugin connects QALIPSIS to https://redis.io/[Redis].

Technology addressed::
Redis: https://redis.io/[]

Dependency::
`io.qalipsis:plugin-redis-lettuce`

Namespace in scenario::
`redisLettuce()`

Client library::
Lettuce: refer to https://lettuce.io/[Lettuce].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Consume step,`consume`>>: consumes data from Redis streams.
* <<Produce step,`produce`>>: pushes messages to Redis streams.

Example scenarios using a combination of the supported steps are provided on https://github.com/qalipsis/qalipsis-examples/tree/master/redis[Github].

== Poll step 
The `poll` step within the Redis-lettuce plugin polls the newest records from a Redis key, with a delay between each execution of polling.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called.
* The `Key-or-pattern` to be used in the poll is set to one of the following valid values: `scan`, `sscan`, `hscan`, `zscan`.
* The native Redis-lettuce command is called using the `Key-or-pattern` provided.

Example::
+
[source,kotlin,linenumbers]
----
it.redisLettuce()
  .pollSsscan {
    connection {
      nodes = redis://localhost:6439
      database = 0
      redis-connection-type = Redis-connection-type.SINGLE
      auth-password = "    authPassword = "Brother1999"
      auth-user = "JohnJacobson"
    }
    key-or-pattern(sscan)
    poll-delay(Duration.of-seconds(1))
}
----
Notable parameters::
* `Connection`(required): specifies the connection parameters.
* `redis-connection-type` (required): indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
* `key-or-pattern` (required): specifies the key or pattern that will be polled after each `poll-delay`.
* `poll-delay` (required): specifies the delay between query executions.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `poll` step with a join operator when you need to verify the values saved by your tested system in the database.
* In addition to SSCAN (`pollSscan` in the example), the `poll` step also supports the following Redis commands: HSCAN (`polllHscan`) SCAN (`pollScan`), and ZSCAN (`pollZscan`). 

Reference documentation::
* For more information on the `SENTINEL` `redis-connection-type`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.


== Save step 
The `save` step within the Redis-lettuce plugin persists a batch of records into Redis.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate a valid Redis command and the values to complete it; the batch of results is then forwarded to the next step(s). The records are saved individually.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
.save {
  connection {
    nodes = redis://localhost:6439
    database = 0
    redis-connection-type = RedisConnectionType.SINGLE
    auth-password = "Brother1999"
    auth-user = "JohnJacobson"
    }

  records { _, input ->
    list-of(
      set-record("battery_state_save_and_poll",
        object-mapper.writeValueAsString(input)
      )
    )
  }
}  
----

Notable parameters::
* `Connection`(required): specifies the connection parameters.
* `redis-connection-type` (required): indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
* `records` (required): generates and configures a list of saved records.


Tip::
* The `save` step supports the following Redis commands: SET, SADD, HSET, ZADD. The provided command may depend on the context and input value received from the previous step.
* If the `redis-connection-type` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more information on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

== Consume step
The `consume` step within the Redis-lettuce plugin records data from Redis streams.

Ancestor::
Scenario 

Functionality::
The `consume` step creates a consumer group in a Redis stream with the provided `connection`, consumer `group` name, and `concurrency`. If `concurrency` is set to 1, records are transmitted sequentially to the next step.

Example::
+
[source,kotlin,linenumbers]
----
redisLettuce()
  .streams-consume {
        connection {
            nodes = redis://localhost:6439
            database = 0
            redis-connection-type = RedisConnectionType.SINGLE
            auth-password = "Brother1999"
            auth-user = "JohnJacobson"
        }
        stream-key("battery_state_produce_and_consume")
        offset("FROM_BEGINNING")
        group("consumer")
  }
----

Notable parameters::
* `connection`(required): configures the connection to Qalipsis.
* `redis-connection-type` (required): indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`. The default is `SINGLE`.
* `offset`(required): sets the offset value to `FROM_BEGINNING`, `LAST_CONSUMED` or `LATEST` for each topic and consumer group.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tip::
If `redis-connection-type` is set to `SENTINEL`, the parameter `master-id` is necessary. 

Reference documentation::
* For more information on the `SENTINEL` `redis-connection-type`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

== Produce step
The `produce` step within the Redis-lettuce plugin produces records into the Redis streams.

Ancestor::
Step

Functionality::
The `produce` step produces a batch of records into one or more Redis stream topics. The record values may be provided by previous step(s).

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
.streams-produce {
  connection {
    nodes = redis://localhost:6439
    database = 0
    redis-connection-type = RedisConnectionType.SINGLE
    auth-password = "Brother1999"
    auth-user = "JohnJacobson"
  }

  records { _, input ->
    lis-of(
     LettuceStreamsProduceRecord(
        key = "battery_state_produce_and_consume", value = map-of(
            "device_id" to input.device-id,
            "timestamp" to input.timestamp.epoch-second.to-string(),
            "battery_level" to input.battery-level.to-string()
          )
      )
   )
  }
}
----
Notable parameters::
* `redis-connection-type` (required): sets the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
* `records` (required): generates and configures a list of produced records.

Tip::
* If `redis-connection-type` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more information on the `SENTINEL` `redis-connection-type`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.