== redis-lettuce plugin

The redis-lettuce plugin connects QALIPSIS to https://redis.io/[Redis].

Technology addressed::
Redis: https://redis.io/[]

Dependency::
`io.qalipsis:plugin-redis-lettuce`

Namespace in scenario::
`redisLettuce()`

Client library::
Lettuce: refer to https://lettuce.io/[Lettuce].

Supported steps::
* <<Poll step,`poll`>>: polls the newest data periodically.
* <<Save step,`save`>>: saves a batch of records generated from the input and step context.
* <<Consume step,`consume`>>: consumes data from `redis` streams.
* <<Produce step,`produce`>>: pushes messages to `redis` streams.

Example scenarios using a combination of `redis` supported steps are provided on https://github.com/qalipsis/qalipsis-examples/tree/master/redis[Github].

=== Poll step 
The `poll` step within the `redis-lettuce` plugin polls the newest records from a `redis` key, with a delay between each execution of polling.

Ancestor::
Scenario

Functionality::
The `poll` step is created only once in a scenario; it is then used throughout the scenario as called.
* The `KeyOrPattern` to be used in the poll is set to one of the following valid values: `scan`, `sscan`, `hscan`, `zscan`.
* The native `redis-lettuce` command is called using the `KeyOrPattern` provided.

Example::
+
[source,kotlin,linenumbers]
----
it.redisLettuce()
  .pollSscan {
    connection {
      nodes = redis://localhost:6439
      database = 0
      redisConnectionType = RedisConnectionType.SINGLE
      authPassword = "redisuserpwd"
      authUser = "redisusername"
    }
    keyOrPattern(sscan)
    pollDelay(Duration.ofSeconds(1))
}
----
Notable parameters::
* `Connection`(required): specifies the connection parameters.
* `redisConnectionType` (required): indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
* `KeyOrPattern` (required): specifies the key or pattern that will be polled after each `pollDelay`.
* `pollDelay` (required): specifies the delay between query executions.
* `monitoring`(optional): configures the monitoring parameters for the step.
* `broadcast` (optional): specifies the broadcast parameters for the step.

Tips::
* Use the `poll` step with a join operator when you need to verify the values saved by your tested system in the database.
* In addition to SSCAN (`pollSscan` in the example), the `poll` step also supports the following `redis` commands: HSCAN (`polllHscan`) SCAN (`pollScan`), and ZSCAN (`pollZscan`). 

Reference documentation::
* For more informationon on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.


=== Save step 
The `save` step within the `redis-lettuce` plugin persists a batch of records into `redis`.

Ancestor::
Step

Functionality::
The `save` step's input and step context are used to generate a valid `redis` command and the values to complete it; the batch of results is then forwarded to the next step(s). The records are saved individually.

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
.save {
  connection {
    nodes = redis://localhost:6439
    database = 0
    redisConnectionType = RedisConnectionType.SINGLE
    authPassword = "redisuserpwd"
    authUser = "redisusername"
    }

  records { _, input ->
    listOf(
      SetRecord("battery_state_save_and_poll",
        objectMapper.writeValueAsString(input)
      )
    )
   }
  monitoring {
    events = true
    meters = true
  }
}  
----

Notable parameters::
* `Connection`(required): specifies the connection parameters.
* `redisConnectionType` (required): indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
* `records` (required): generates and configures a list of saved records.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tip::
* The `save` step supports the following `redis` commands: SET, SADD, HSET, ZADD. The provided command may depend on the context and input value received from the previous step.
* If the `redisConnectionType` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more informationon on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

=== Consume step
The `consume` step within the `redis-lettuce` plugin records data from `redis` streams.

Ancestor::
Scenario 

Functionality::
The `consume` step creates a consumer group in a `redis` stream with the provided `connection`, consumer `group` name, and `concurrency`. If `concurrency` is set to 1, records are transmitted sequentially to the next step.

Example::
+
[source,kotlin,linenumbers]
----
redisLettuce()
  .streamsConsume {
        connection {
            nodes = redis://localhost:6439
            database = 0
            redisConnectionType = RedisConnectionType.SINGLE
            authPassword = "redisuserpwd"
            authUser = "redisusername"
        }
        streamKey("battery_state_produce_and_consume")
        offset("FROM_BEGINNING")
        group("consumer")
  }
----

Notable parameters::
* `connection`(required): configures the connection to Qalipsis.
* `redisConnectionType` (required): indicates the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`. The default is `SINGLE`.
* `offset`(required): sets the offset value to `FROM_BEGINNING`, `LAST_CONSUMED` or `LATEST` for each topic and consumer group.
* `broadcast` (optional): specifies the broadcast parameters for the step.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tip::
If `redisConnectionType` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more informationon on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.

=== Produce step
The `produce` step within the `redis-lettuce` plugin produces records into the Redis streams.

Ancestor::
Step

Functionality::
The `produce` step produces a batch of records into one or more `redis` stream topics. The record values may be provided by previous step(s).

Example::
+
[source,kotlin,linenumbers]
----
.redisLettuce()
.streamsProduce {
  connection {
    nodes = redis://localhost:6439
    database = 0
    redisConnectionType = RedisConnectionType.SINGLE
    authPassword = "redisuserpwd"
    authUser = "redisusername"
  }

  records { _, input ->
    listOf(
     LettuceStreamsProduceRecord(
        key = "battery_state_produce_and_consume", value = mapOf(
            "device_id" to input.deviceId,
            "timestamp" to input.timestamp.epochSecond.toString(),
            "battery_level" to input.batteryLevel.toString()
          )
      )
   )
  }
  monitoring {
    events = true
    meters = true
  }
}
----
Notable parameters::
* `redisConnectionType` (required): sets the connection type as `SINGLE`, `CLUSTER` or `SENTINEL`.
* `records` (required): generates and configures a list of produced records.
* `monitoring`(optional): configures the monitoring parameters for the step.

Tip::
* If `redisConnectionType` is set to `SENTINEL`, the parameter `masterId` is necessary. 

Reference documentation::
* For more informationon on the `SENTINEL` `redisConnectionType`, refer to: https://lettuce.io/core/release/reference/#sentinel.redis-discovery-using-redis-sentinel[Redis discovery using Redis Sentinel]. 
* Refer to the  https://redis.io/docs/[Redis] documentation for further parameter and configuration information.