= Standalone

== Overview
Standalone installations of QALIPSIS are designed for low to normal load operations that require data tracking. They allow you to tweak the deployment configuration to track the history of executions. 

A standalone installation:

* Executes all QALIPSIS components as in a transient installation.
* Provides durability in data and history tracking.
* Provides REST endpoints to interact with QALIPSIS.

QALIPSIS stores the master data and the time-series data generated by the scenario (events, meters) in separate databases. The master data requires transactional consistency and the time-series data requires high throughput and strong calculation capabilities. Separate databases allow for the different requirements.  

For sake of simplicity, this guide will use http://postgresql.org[PostgreSQL] for both groups of data.  

If you want to configure a different database for the time-series data, refer to the applicable plugin section for details (`elasticsearch`, `influxDB`, `timescaleDB`, and `graphite` are currently supported).
 
This section will guide you through the configuration of a <<Transient>> installation to a persistent standalone installation.

While this installation requires the installation of a PostgreSQL database, we will not go into those details here as they are provided in the official http://postgresql.org[PostgreSQL] documentation.

== Prepare the installation
Execute the following steps as for a <<Transient>> installation:

. In your QALIPSIS project, execute the task `package-standalone` to create a ZIP file: `build/install/qalipsis-your-project-name.zip`.

. Add the ZIP archive to your installation folder of choice and extract the compressed files: `unzip qalipsis-your-project-name.zip`. 

== Prepare the database
[start]
. Install your PostgreSQL database
. Create a user with the name `qalipsis`. 
. Create a database with the name `qalipsis`. 
. Connect to the database `qalipsis` with your admin user (generally `postgres`).
. Execute the following:
+
[example,kotlin, linenumbers]
----
CREATE SCHEMA qalipsis_liquibase IF NOT EXISTS;
ALTER SCHEMA qalipsis_liquibase OWNER TO qalipsis;
CREATE SCHEMA qalipsis IF NOT EXISTS;
ALTER SCHEMA qalipsis OWNER TO qalipsis;

CREATE SCHEMA events AUTHORIZATION qalipsis;
GRANT ALL ON SCHEMA events TO qalipsis;

CREATE SCHEMA meters AUTHORIZATION qalipsis;
GRANT ALL ON SCHEMA meters TO qalipsis;
---- 

== Configure the database for the master data
[start]
. Navigate to your installation folder where the `qalipsis.sh` and `qalipsis.bat` files are located.
. Create a `qalipsis.yml` file to configure access to the database for the master data:
+
[source,kotlin, linenumbers]
----
datasources:
  default:
    url: jdbc:postgresql://your-database-host:5432/qalipsis <1>
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    maximumPoolSize: 4      <2>
    minimumIdle: 2
----
<1> Replace the `host`, `port`, `username`, and `password` values with the appropriate values for you configuration.
<2> The `maximumPoolSize` and `minimumIdle` are the REST endpoints and depend on your number of users. Increase the value of `maximumPoolSize` if you observe errors or a high latency when using the REST endpoints.

== Configure the database for the events and meters
The connection to PostgreSQL for events and meters is provided by the timescaledb plugin, which is embedded by default in all the head, transient and standalone installations you will build with the QALIPSIS Gradle plugin.

In the file qalipsis.yml add the following details:

[source,kotlin,linenumbers]
----
events: 
  export.timescaledb:  <1>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters

  provider.timescaledb: <2>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters
    
meters:
  export.timescaledb: <3>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters

  provider.timescaledb: <4>
    enabled: true
    host: your-database-host
    port: 5432
    database: qalipsis
    username: qalipsis
    password: the_password_of_your_qalipsis_user
    schema: meters
----
<1> Export the events to PostgreSQL.
<2> Render the events from PostgreSQL.
<3> Export the meters to PostgreSQL.
<4> Render the meters from PostgreSQL.

== Start QALIPSIS

[start]
. Navigate to the QALIPSIS folder on your system:

* Linux, Unix or Mac systems:`/your/installation/folder/qalipsis-your-project-name`

* Windows systems:`C:\your\installation\folder\qalipsis-your-project-name on Windows`

. Start QALIPSIS:

* On Linux, Unix or Mac systems: 
. Run `chmod +x -R`
. Run `./qalipsis.sh --autostart`

* On Windows systems:
+
Run `qalipsis.bat --autostart`

QALIPSIS will start and provide REST endpoints on port 8080.

Note: Open source QALIPSIS OSS does not support native security. For a native secured installation, we encourage you to https://qalipsis.io/#contact[contact] the QALIPSIS team to request a license for QALIPSIS Commercial edition. 
