

= Transient
== Overview
Transient installations of QALIPSIS are designed for operations that do not need to keep a history of data. The most often used cases for transient installations include:

* Continuous integration/continuous deployment (CI/CD) workflows where only the success or failure of the execution determines if the data passes through the quality gates.
* End-to-end testing that does not require a history of data.

A transient installation is not a long-live process.

* QALIPSIS starts a campaign execution on demand and stops immediately after the campaign's completion. 
* To keep external logs of the campaign execution, export the results as a file or to a third-party platform.

If any of your use cases includes data that you want to retain in QALIPSIS for comparison, regression testing, or other use, you should use QALIPSIS in a non-persistent standalone installation.  

== Configuring a transient installation for project deployment
 
The QALIPSIS Gradle Plugin provides tasks to create an installable archive from your project. It proposes a unique task to create a ZIP archive and a TAR.GZ archive. The installation is similar whether using a ZIP archive or a TAR.GZ archive; installation using a ZIP archive is described in this section.

In your QALIPSIS project, execute the task `package-standalone` which will assemble your project and create a ZIP file: `build/install/qalipsis-your-project-name.zip`.

The ZIP archive contains your scenario, classes, and all required dependencies to execute your QALIPSIS project.

* Add the ZIP archive to your installation folder of choice and extract the compressed files: `unzip qalipsis-your-project-name.zip`. 

* Navigate to the QALIPSIS folder on your system:

 ** Linux, Unix or Mac systems:`/your/installation/folder/qalipsis-your-project-name` 
 ** Windows systems:`C:\your\installation\folder\qalipsis-your-project-name' 

* Start QALIPSIS:
** On Linux, Unix or Mac systems: 

. Run `chmod +x -R`
. Run `./qalipsis.sh --autostart`

** On Windows systems: run `qalipsis.bat --autostart`

An additional argument is not required, as the transient, non-persistent execution, is the default.

* QALIPSIS starts, executes the scenario(s) in the project, and quits.

* The results of the project are displayed on the console but are not saved to QALIPSIS.

* To save the results, export them results to a file(s) using an exporter such as JUnit.

If you want to tweak the configuration, create and include in your project a `qalipsis.yml` or `config/qalipsis.yml` file that contains the parts of the configuration that you want to overwrite.

Note that the `config/qalipsis.yml` file has precedence over the `qalipsis.yml` if both are present in the configuration.

If any of your use cases includes data that you want to retain in QALIPSIS for comparison, regression testing, or other use, you should use QALIPSIS in a non-persistent standalone installation.
